### ISSUE TITLE
bottomTabNavigator和StackNavigator嵌套跳转问题

### ISSUE THREAD

**Issue by venom1999** [reactnativecn/react-native-website#100]
我的路由栈关系如下图：
![)L~CK2STFT 35FA0FN~J(DL](https://user-images.githubusercontent.com/49115023/78101816-3f1c9c00-741b-11ea-995e-f050276bce59.png)
我需要实现的需求是从PensonalInfo跳转到Login界面
想请各位指教

**Comment by sunnylqm** [comment]
https://github.com/reactnativecn/react-native-website/issues/92

**Comment by venom1999** [comment]
> #92

感谢指点，已解决问题
