### ISSUE TITLE
原生嵌套RN，如何集成 react-navigation?

### ISSUE THREAD

**Issue by xyZangGit** [reactnativecn/react-native-website#101]
我原生嵌套RN，然后集成react-navigation3X  4X版本都有一个link的操作，但是原生集成RN，是没有继承reactActivity类的，然后 RN添加 如下配置
  "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.7.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-navigation": "^4.3.6"

会把我原生里面的
![image](https://user-images.githubusercontent.com/19574114/78110514-a93e3c80-742d-11ea-80eb-12c7fe95622f.png)
这个版本从60.5变成20.0导致，方法找不到报错；
![image](https://user-images.githubusercontent.com/19574114/78110577-c410b100-742d-11ea-8621-1dba4b9049d3.png)
此处也指定版本了，

**Comment by sunnylqm** [comment]
如果你不按标准流程走，那你就得自己研究这些第三方是如何链接编译并加到packagelist中了

**Comment by xyZangGit** [comment]
> 如果你不按标准流程走，那你就得自己研究这些第三方是如何链接编译并加到packagelist中了

我是按照 原生嵌套RN的官方流程走的；目前已经找到问题所在了
