### ISSUE TITLE
Mac端真机调试报错

### ISSUE THREAD

**Issue by kely2019** [reactnativecn/react-native-website#109]
按照官网的教程连接真机调试报错，在ios文件夹内pod install也不行。

CompileC /Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/Objects-normal/arm64/AwesomeProject_vers.o /Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/DerivedSources/AwesomeProject_vers.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'AwesomeProject' from project 'AwesomeProject')
    cd /Users/ykk/AwesomeProject/ios
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target arm64-apple-ios9.0 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fmodules -gmodules -fmodules-cache-path=/Users/ykk/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/ykk/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DDEBUG=1 -DCOCOAPODS=1 -DFB_SONARKIT_ENABLED=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -index-store-path /Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Index/DataStore -iquote /Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/AwesomeProject-generated-files.hmap -I/Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/AwesomeProject-own-target-headers.hmap -I/Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/AwesomeProject-all-target-headers.hmap -iquote /Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/AwesomeProject-project-headers.hmap -I/Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Products/Debug-iphoneos/include -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/CocoaAsyncSocket -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/CocoaLibEvent -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/DoubleConversion -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/FBLazyVector -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/FBReactNativeSpec -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/Flipper -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/Flipper-DoubleConversion -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/Flipper-Folly -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/Flipper-Glog -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/Flipper-PeerTalk -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/Flipper-RSocket -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/FlipperKit -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/OpenSSL-Universal -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/RCTRequired -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/RCTTypeSafety -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/React-Core -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/React-RCTText -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/React-cxxreact -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/React-jsi -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/React-jsiexecutor -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/React-jsinspector -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/ReactCommon -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/Yoga -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/YogaKit -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/glog -I/Users/ykk/AwesomeProject/ios/Pods/Headers/Private/React-Core -I/Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/DerivedSources-normal/arm64 -I/Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/DerivedSources/arm64 -I/Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/DerivedSources -F/Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Products/Debug-iphoneos -fmodule-map-file=/Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Products/Debug-iphoneos/YogaKit/YogaKit.modulemap -fmodule-map-file=/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/FlipperKit/FlipperKit.modulemap -fmodule-map-file=/Users/ykk/AwesomeProject/ios/Pods/Headers/Public/yoga/Yoga.modulemap -MMD -MT dependencies -MF /Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/Objects-normal/arm64/AwesomeProject_vers.d --serialize-diagnostics /Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/Objects-normal/arm64/AwesomeProject_vers.dia -c /Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/DerivedSources/AwesomeProject_vers.c -o /Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/Objects-normal/arm64/AwesomeProject_vers.o

fatal error: module map file '/Users/ykk/Library/Developer/Xcode/DerivedData/AwesomeProject-czhnrdedsnmsxpcstdgrpapbjuwt/Build/Products/Debug-iphoneos/YogaKit/YogaKit.modulemap' not found
1 error generated.

**Comment by sunnylqm** [comment]
确认打开的是.xcworkspace文件吗

**Comment by kely2019** [comment]
> 确认打开的是.xcworkspace文件吗

用Xcode打开.xcodeproj文件

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/78681077-dbb0d380-791e-11ea-9689-d2c7372e0d3a.png)
