### ISSUE TITLE
启动时遇到 unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by github123333** [reactnativecn/react-native-website#112]
F:\App\AwesomeProject>react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 960 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Installing the app...
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'AwesomeProject'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.5.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.5.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'AwesomeProject'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.5.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.5.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.2/gradle-3.5.2.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s

    at makeError (F:\App\AwesomeProject\node_modules\execa\index.js:174:9)
    at F:\App\AwesomeProject\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (F:\App\AwesomeProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (F:\App\AwesomeProject\node_modules\@react-native-community\cli\build\index.js:186:9)

**Comment by sunnylqm** [comment]
翻墙问题

**Comment by PL-SQL** [comment]
请问解决了吗

**Comment by woshidashuaibi-lsj** [comment]
同问题求解

**Comment by github123333** [comment]
> 同问题求解

并未找到问题所在，重装系统解决了

**Comment by PL-SQL** [comment]
> > 同问题改善
> 
> 根本找不到问题所在，重装系统解决了

你那个不能装成功的是不是win10的系统

**Comment by github123333** [comment]
> > > 同问题改善
> > 
> > 
> > 根本找不到问题所在，重装系统解决了
> 
> 你那个不能装成功的是不是win10的系统

**Comment by github123333** [comment]
> > > 同问题改善
> > 
> > 
> > 根本找不到问题所在，重装系统解决了
> 
> 你那个不能装成功的是不是win10的系统

是的

**Comment by PL-SQL** [comment]
我的电脑也是win 10也是一样不能构建，我猜想会不会是win 10用户文件夹的问题(用户文件夹去全是数字) @sunnylqm 
![image](https://user-images.githubusercontent.com/37580744/82276821-eac48000-99b8-11ea-9711-c6153e493e31.png)

**Comment by sunnylqm** [comment]
跟系统没有关系，数字也是完全合法的字符。这个报错是说服务器的证书有问题。然而google的证书怎么会有问题呢，这就没有解释的必要了吧。
