### ISSUE TITLE
iOS打包总是卡在最后不动

### ISSUE THREAD

**Issue by KQAR** [reactnativecn/react-native-website#115]
iOS打包总是卡在最后一点就不动了，是不是缺少什么东西，项目Libraries目录下为空是正常的吗，用的是0.62版本的rn。
<img width="542" alt="Snipaste_2020-04-14_19-09-16" src="https://user-images.githubusercontent.com/31615748/79219980-c93a1b00-7e85-11ea-9f46-277f251bf7a5.png">
<img width="1400" alt="Snipaste_2020-04-14_19-26-33" src="https://user-images.githubusercontent.com/31615748/79220042-e373f900-7e85-11ea-84c8-974648e4bffa.png">

**Comment by Kennytian** [comment]
@KQAR 你要把打包的详细打开了看输出信息，才好定位问题。三角形里面那个一行，你都点点，我忘了，是哪个了。

**Comment by KQAR** [comment]
@Kennytian 这里的问题看不太懂，你能帮忙看下吗，感谢！
<img width="1400" alt="Snipaste_2020-04-15_10-32-59" src="https://user-images.githubusercontent.com/31615748/79292943-fb3e9200-7f04-11ea-826c-e25a9009acb0.png">

**Comment by sunnylqm** [comment]
看起来是在更新homebrew卡住了

**Comment by KQAR** [comment]
那我先主动更新homebrew可以吗，还是说它在它在打包的时候一定会下载东西 @sunnylqm

**Comment by sunnylqm** [comment]
当然可以先更新啊

**Comment by KQAR** [comment]
是homebrew的问题，打包成功了，谢谢老哥们🙏

**Comment by gl02521** [comment]
我这边总是执行到打包就卡死不动了，请问有人遇到过吗？就一直显示下面这些。
node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev true --reset-cache --bundle-output Library/Developer/Xcode/DerivedData/xxxx-fszkqrflstctmgdauhnzoebmmyua/Build/Products/Debug-iphoneos/main.jsbundle --assets-dest Library/Developer/Xcode/DerivedData/xxxx-fszkqrflstctmgdauhnzoebmmyua/Build/Products/Debug-iphoneos/xxxx.app
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated
