### ISSUE TITLE
请教一个安卓打包的问题

### ISSUE THREAD

**Issue by hu-qi** [reactnativecn/react-native-website#116]
最近被一个奇葩的问题困扰。
我本地有个项目，运行 `react-native run-android` 打包出来的 `.apk` 文件是60多M；
然后我将该项目进行分发，如上传至svn，再拉取下来，一样的代码，执行`npm install`
再执行`react-naitve run-android`，结果打包出来的`.apk`文件只有40多M了。经排查，
项目中引用的安卓原生代码模块功能有些缺失。项目集成了一个百度语音输入，通过
`Native Module`引入桥接，诡异的是`javascript`中能输出该模块的方法、属性，但功能
就是不正常，而且打包出来的安装包体积变小。疑似`android\app\src\main\jniLibs`目录
下一些自己添加的文件没有正常打包。如图一中`jniLibs`为集成百度语音输入的一些依赖
文件，打包出来的`.apk`文件大小差额差不多就是这个文件夹的大小。
![图一](https://user-images.githubusercontent.com/17986122/79530123-03cbcf80-80a1-11ea-9cf2-03ce56ef6c5b.png)
不懂安卓原生，查了一些文档，最终也没解决这个问题，不知道您有什么指导思路可以
提供一下吗？

**Comment by sunnylqm** [comment]
https://developer.android.com/studio/projects/gradle-external-native-builds#jniLibs

**Comment by hu-qi** [comment]
> https://developer.android.com/studio/projects/gradle-external-native-builds#jniLibs

说出来您可能不信，最终的原因是 `svn`提交代码的时候，居然忽略了`.so`文件。
估计全宇宙也就我能踩到这个坑😂
![image](https://user-images.githubusercontent.com/17986122/79544193-34bbfc80-80c1-11ea-9474-a857a412192f.png)

**Comment by sunnylqm** [comment]
这年代了为什么不用git呢
