### ISSUE TITLE
有没有好用的 检测用户截屏的插件？（RN > 0.60）

### ISSUE THREAD

**Issue by jinshuokang** [reactnativecn/react-native-website#117]

**Comment by leonsimple** [comment]
https://github.com/gre/react-native-view-shot.git
这个蛮好用的

**Comment by jinshuokang** [comment]
> https://github.com/gre/react-native-view-shot.git
> 这个蛮好用的

这个插件并没有 **监测**用户截屏的 方法。

**Comment by a112121788** [comment]
自己写吧，不难
