### ISSUE TITLE
搭建开发环境 页面优化提议

### ISSUE THREAD

**Issue by wanYin2g** [reactnativecn/react-native-website#121]
目前在从0开始运行一个已有的RN项目，按照目前的指引操作发现运行react-native run-android会提示react-native 命令找不到。仔细查看了文档并没有相关说明只有“如果你之前全局安装过旧的react-native-cli命令行工具，请使用npm uninstall -g react-native-cli卸载掉它以避免一些冲突。”希望可以加入添加react-native-cli的指导。

**Comment by sunnylqm** [comment]
react-native-cli已经过期了，现在不应该这样用了

**Comment by sunnylqm** [comment]
也就是react-native命令前必须使用yarn或者npx，这个文档已经明确说明了吧？

**Comment by sunnylqm** [comment]
> 使用 React Native 内建的命令行工具来创建一个名为"AwesomeProject"的新项目。这个命令行工具不需要安装，可以直接用 node 自带的npx命令来使用

**Comment by wanYin2g** [comment]
我想知道从一台新的电脑里，不执行新建RN项目的语句“npx react-native init AwesomeProject”，只在公司的RN项目中运行"yarn android#或yarn react-native run-android" 是否可以跑得起来？

**Comment by sunnylqm** [comment]
最低需要0.59以上版本  
https://github.com/react-native-community/cli#compatibility
低于0.59的应该需要使用老的cli
