### ISSUE TITLE
RN0.61.5使用SwipeableFlatList报错，使用FlatList正常。

### ISSUE THREAD

**Issue by GXlaishengcai** [reactnativecn/react-native-website#122]
使用SwipeableFlatList报错，使用FlatList正常。
1.Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ManageAccount`.
2.已经导入组件 SwipeableFlatList
3.RN0.61.5

**Comment by sunnylqm** [comment]
此组件已移除
