### ISSUE TITLE
初始化项目时出错了

### ISSUE THREAD

**Issue by StevenWang88** [reactnativecn/react-native-website#129]
按照官网进行初始化项目报错，请帮我解决问题，谢谢！
步骤： 
sudo gem install cocoapods -v 1.8.4
cd app/ios
pod install
![屏幕快照 2020-04-26 上午10 27 53](https://user-images.githubusercontent.com/34699137/80295830-a45c7680-87a8-11ea-98b5-5b3f5598b50c.png)
这是我的配置参数：
![屏幕快照 2020-04-26 上午10 29 38](https://user-images.githubusercontent.com/34699137/80295868-02895980-87a9-11ea-809f-05d6aca57f8b.png)

**Comment by sunnylqm** [comment]
翻墙

**Comment by StevenWang88** [comment]
VPN用过了，没鸟用

**Comment by sunnylqm** [comment]
那就换



---原始邮件---
发件人: "React-Wallet"<notifications@github.com&gt;
发送时间: 2020年4月26日(周日) 中午11:04
收件人: "reactnativecn/react-native-website"<react-native-website@noreply.github.com&gt;;
抄送: "Sunny Luo"<sunnylqm@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [reactnativecn/react-native-website] 初始化项目时出错了 (#129)




 
VPN用过了，没鸟用

**Comment by StevenWang88** [comment]
直接说你用的那个VPN，少让我走弯路。。。

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/80301540-56ab3280-87d7-11ea-94cc-ec745b3861ac.png)

**Comment by StevenWang88** [comment]
我买的VPN工具，翻墙去链接，发现还是不管用，
![屏幕快照 2020-04-26 下午4 06 49](https://user-images.githubusercontent.com/34699137/80301669-fa94de00-87d7-11ea-90eb-6dc384a6158a.png)
这就是传说中的小飞机，解决不了问题

**Comment by sunnylqm** [comment]
这个叫ss  不叫vpn
一个非常常见的使用上的误解就是，ss默认其实并不代理其他工具，起码应该先尝试`全局模式`

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/80302046-4e082b80-87da-11ea-88b3-e4e78a7214d6.png)

**Comment by sunnylqm** [comment]
还是先读下新手必读吧   https://github.com/reactnativecn/react-native-website/issues/77

**Comment by zhangmingJ** [comment]
楼主解决了吗，我也遇到了这个问题，
