### ISSUE TITLE
react native如何使用Fetch下载图片

### ISSUE THREAD

**Issue by liwenlongepipechina** [reactnativecn/react-native-website#130]
后端使用xsrf-token验证，使用RNFetblob下载图片后，将xsrf-token保存到global，下个接口取出来使用iOS报403错误，Android正常。求助一下这个问题该如何解决

**Comment by sunnylqm** [comment]
贴代码吧，还有各种版本信息

**Comment by liwenlongepipechina** [comment]
"rn-fetch-blob": "0.10.13"
  "react-native": "0.57.1",
![image](https://user-images.githubusercontent.com/48268460/80571015-70928280-8a2e-11ea-9076-89415d822a92.png)
![image](https://user-images.githubusercontent.com/48268460/80571046-7ee09e80-8a2e-11ea-90fc-a01aff3427fe.png)
这个接口Android，ios返回正常，但下一个接口iOS报403
![image](https://user-images.githubusercontent.com/48268460/80571804-ca477c80-8a2f-11ea-840b-926d97512b5c.png)

**Comment by liwenlongepipechina** [comment]
"react-native": "0.57.1",
    "rn-fetch-blob": "0.10.13"
下载图片接口
`
static async downloadPicture(id){

        let {DocumentDir} = RNFetchBlob.fs.dirs;
        let cachePath = `${DocumentDir}/RNFetchBlob_tmp/${id}`;
        let url = `${config.chaosstoneIpAndPort}${config.applicationContext}api/download/${id}`;

        //let url = `http://192.168.70.20:8181/api/download/${id}`
        let result = "";
        await RNFetchBlob.config({
            fileCache: true,
            path: cachePath,
            timeout: 30000,
            trusty : true
        }).fetch('GET',url,{
            'Content-Type': 'application/x-www-form-urlencoded',
            'access_token': global.token,
            'X-XSRF-TOKEN':global.X_XSRF_TOKEN,
            'Authorization':'Bearer  '+global.token,
            responseType: 'arraybuffer'
        }).then((res)=>{
            debugger

            console.log("res:",res);
                result =  res;
            }
        ).catch((error)=>{
            console.log("SErver downloadPicture:",error)
            }

        );
        this.getNewToken(result,'2');


        return result;
    }
`

将图片转化成64base

`downloadPictures=async(filePath,id)=>{
        let photo = this.state.photos;
        try{
            let res= await Server.downloadPicture(filePath);
            console.log("图片信息:"+JSON.stringify(res));

            let status = res.info().status;
            if(status===200) {

                let base64Str = await res.base64()
                photo.push(
                    {
                        id:id,
                        url: 'data:image/png;base64,'+base64Str
                    }
                )
                console.log("下载图片 base64Str：", JSON.stringify(photo));
            }


            this.setState({
                photos:photo
            });

        }catch (e) {
            Toast.hide();
            if (e.message === config.invalidateToken) {
                // token失效错误


                handleLoginFirst(()=>{}, () => {},this.props.navigation);
            } else {
                // 普通错误
                showError("",e)
            }
        }

    }`

下载图片Android，iOS正常，但是下一个接口android正常，iOS报403错误
![image](https://user-images.githubusercontent.com/48268460/80572366-bc462b80-8a30-11ea-97a1-95f18c5591ee.png)

**Comment by sunnylqm** [comment]
服务器端说token不对啊

**Comment by liwenlongepipechina** [comment]
服务器是说token不对，但是我打印headers里的token是正确的，如果不对的话android这边也应该是错误的，现在是Android正常，iOS报403。之前上传图片使用rn-fetch-blob，Android正常，iOS报同样的错误，后来iOS改用fetch上传图片就正常了，所以现在想试试使用fetch下载图片不用fetchblob，但fetch只拿到response后面不会了
这个是获取的response
![image](https://user-images.githubusercontent.com/48268460/80573609-d6810900-8a32-11ea-9f5d-a8d3c6d20930.png)

**Comment by sunnylqm** [comment]
服务器端说token不对，那么你应该在服务器端设断点或者抓日志调试，谁报错就要首先确定谁的报错靠不靠谱啊（如果假报错，那不就是服务器的bug吗）
如果服务器端确实拿到的token不对，那么问题在客户端，如果客户端android对，ios不对，那么问题在ios端（这个缩小范围排查的逻辑能理解吧？）rn虽然是跨平台框架，但也没有谁能保证android端的逻辑就和ios端的逻辑完全一致且都正确啊？
排查到问题在ios端之后，那么剩下的就是对ios端fetch-blob（请注意，fetch和fetch-blob并不是一个东西）相关的原生代码的调试咯
