### ISSUE TITLE
初始化项目中下载之后并没有.xcworkspace文件，只有. xcodeproj文件。然后通过xcode也启动不了

### ISSUE THREAD

**Issue by zhangmingJ** [reactnativecn/react-native-website#134]
<img width="604" alt="截屏2020-05-04 下午5 18 57" src="https://user-images.githubusercontent.com/13863590/80952118-bcc53480-8e2b-11ea-8787-b7e97347b9dd.png">
<img width="1088" alt="截屏2020-05-04 下午5 18 37" src="https://user-images.githubusercontent.com/13863590/80952127-bfc02500-8e2b-11ea-9735-888e9bef3397.png">

**Comment by sunnylqm** [comment]
这是因为你的cocoapods没有安装完成

**Comment by zhangmingJ** [comment]
> 这是因为你的cocoapods没有安装完成

刚刚gem -v 显示3.0.3

**Comment by sunnylqm** [comment]
gem是gem，cocoapods是cocoapods啊，而且即便你装上了cocoapods，还要完成pod install啊

**Comment by zhangmingJ** [comment]
> gem是gem，cocoapods是cocoapods啊，而且即便你装上了cocoapods，还要完成pod install啊

我是通过sudo gem install cocoapods来下载的，是否还需要做别的操作

**Comment by sunnylqm** [comment]
init的过程中会自动执行pod install（前提是已经装好了cocoapods），这一步会自动生成.xcworkspace，如果这一步由于网络原因不能完成，那么你需要自己弄好翻墙工具，然后去ios目录下手动执行pod install命令

**Comment by zhangmingJ** [comment]
> init的过程中会自动执行pod install（前提是已经装好了cocoapods），这一步会自动生成.xcworkspace，如果这一步由于网络原因不能完成，那么你需要自己弄好翻墙工具，然后去ios目录下手动执行pod install命令

了解了，请问有推荐
翻墙的吗。。我用的蓝灯，最近用不了了

**Comment by sunnylqm** [comment]
https://user-images.githubusercontent.com/615282/80301540-56ab3280-87d7-11ea-94cc-ec745b3861ac.png

**Comment by sunnylqm** [comment]
![](https://user-images.githubusercontent.com/615282/80301540-56ab3280-87d7-11ea-94cc-ec745b3861ac.png)

**Comment by sunnylqm** [comment]
还是先读下新手必读吧 https://github.com/reactnativecn/react-native-website/issues/77

**Comment by zhangmingJ** [comment]
> 还是先读下新手必读吧 #77

好的，多谢
