### ISSUE TITLE
初始化项目红屏(能访问localhost:8081但不能访问bundle，卸载watchman后正常）

### ISSUE THREAD

**Issue by eastrain** [reactnativecn/react-native-website#135]
作为一个初学者，红屏问题搞了半天始终不解，请教各位大佬

按照最新的[react native 中文网](https://reactnative.cn/docs/next/getting-started)搭建环境，该装的工具都装上了，初始化项目也完成了，iOS的pod 安装也通过国内镜像安装上了。就是在运行起来的时候，报了红屏错误。

**_Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate
- WiFi is enabled and connected to the same network as the Node Server

URL: http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main_**

根据这个错误，查看服务确实是启动的，网络环境也是同一个环境，AppDelegate.m网上查找问题说在这个文件下需要配置自己的IP地址，不过好像新版本的，代码有改动，已经没有一个叫jsCodeLocation的了。IP也尝试了手动去设置，也没有效果。

求教下各位大佬，是哪里有问题么，还是我需要配置什么东西

**Comment by sunnylqm** [comment]
1. 请把命令行也截图贴出来
2. 注意app安装成功后要断开全局模式的翻墙工具，不然可能连不上本地的packager
3. 不需要更改任何代码

**Comment by eastrain** [comment]
这个是第一步初始化项目
![start](https://user-images.githubusercontent.com/6072550/81078900-64705e80-8f21-11ea-8e47-07be5c6537b3.png)
这是项目初始化完成结尾
![end](https://user-images.githubusercontent.com/6072550/81084026-ee232a80-8f27-11ea-9a76-6dfb62c49422.png)

这是在ios路径下通过镜像去pod install 
![pod_start](https://user-images.githubusercontent.com/6072550/81087578-7b687e00-8f2c-11ea-949b-5f49fe136418.png)


这是pod install 完成后的结尾
![pod_end](https://user-images.githubusercontent.com/6072550/81084434-6e499000-8f28-11ea-8a61-b363bf132c9d.png)

这是服务启动
![react_start](https://user-images.githubusercontent.com/6072550/81085454-d0ef5b80-8f29-11ea-9248-feca7b2693e2.png)

这是启动模拟器后的展示效果
<img width="1165" alt="phone_start" src="https://user-images.githubusercontent.com/6072550/81087804-b8347500-8f2c-11ea-9f1e-0d3033202e93.png">
![phone_end](https://user-images.githubusercontent.com/6072550/81087853-c5e9fa80-8f2c-11ea-8479-19f364c47a8f.png)

 ip地址也改过但是好像也没啥效果
![image](https://user-images.githubusercontent.com/6072550/81078366-b9f83b80-8f20-11ea-9668-95245cdc7111.png)

暂时也没有翻墙，项目也没有做任何修改
大致就是这么个过程，还请 @sunnylqm 指点

**Comment by sunnylqm** [comment]
现在看起来问题是不能访问 localhost:8081，但是packager看起来又在正常运行
1. 先用桌面端浏览器访问localhost:8081，能访问说明localhost正常解析，packager正常运行，如果不能，说明有什么软件或者设置干扰了localhost的解析和连接（比如代理软件，抓包软件，防火墙等等）
2. 同理再用模拟器的浏览器访问localhost:8081

**Comment by eastrain** [comment]
浏览器可以打开
![image](https://user-images.githubusercontent.com/6072550/81135323-4559e700-8f8a-11ea-89e2-ca3bfbd6ce71.png)
模拟器也可以打开
![image](https://user-images.githubusercontent.com/6072550/81135331-4b4fc800-8f8a-11ea-8f2f-619277806cf9.png)

@sunnylqm 这是不是也说明正常的

**Comment by sunnylqm** [comment]
访问完整地址呢 http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false

**Comment by eastrain** [comment]
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false 这个地址打不开
@sunnylqm 这会是什么情况

**Comment by sunnylqm** [comment]
截图，两边都截图

**Comment by eastrain** [comment]
这是模拟器拼接的地址和没有拼接的地址
![image](https://user-images.githubusercontent.com/6072550/81138243-03ce3980-8f94-11ea-96d1-edde5329eb2c.png)
这是浏览器拼接的地址和没有拼接的地址
![image](https://user-images.githubusercontent.com/6072550/81138498-dcc43780-8f94-11ea-956e-65439d01039d.png)
@ @sunnylqm

**Comment by sunnylqm** [comment]
我说packager（命令行端）的截图

**Comment by eastrain** [comment]
截图，两边都截图------不好意思哈，没理解是什么信息的截图，还得麻烦描述下 大佬@sunnylqm

**Comment by sunnylqm** [comment]
命令行啊（那个正在运行的命令行，也就是正在8081端口运行的一个服务，负责打包js文件，我们叫他packager，官方现在的名字叫metro）

**Comment by eastrain** [comment]
是说的这个 react-native start?
![image](https://user-images.githubusercontent.com/6072550/81149309-8ebd2d00-8fb0-11ea-92a9-b5bceb7ca342.png)
@sunnylqm

**Comment by sunnylqm** [comment]
是的

**Comment by eastrain** [comment]
不过这个好像也一直运行，没看出什么问题。 @sunnylqm 大佬该如何解？还需要做什么

**Comment by sunnylqm** [comment]
截图啊

**Comment by sunnylqm** [comment]
访问不同地址时，packager端截图

**Comment by eastrain** [comment]
这个服务运行起来就一直保持这样，你的意思是执行请求，命令行会打印？
@sunnylqm 
![image](https://user-images.githubusercontent.com/6072550/81165932-6db30700-8fc5-11ea-83d6-38168700b284.png)

**Comment by sunnylqm** [comment]
是的，会打印的。加我qq吧34731408

**Comment by TheFirstSunday** [comment]
tongyang de wenti

**Comment by TheFirstSunday** [comment]
我也遇到了同样的问题

**Comment by jmy10241024** [comment]
> 1. 请把命令行也截图贴出来
> 2. 注意app安装成功后要断开全局模式的翻墙工具，不然可能连不上本地的packager
> 3. 不需要更改任何代码

你是真有耐心啊...

**Comment by zhangwei900808** [comment]
同问，请问问题解决没有

**Comment by sunnylqm** [comment]
这个问题是watchman有问题（具体原因不明），卸载watchman后正常

**Comment by 719500396** [comment]
> watchman
还真是watchman的问题,最近在被这个要搞崩溃了!!!!谢谢

**Comment by deeryoona** [comment]
> 浏览器可以打开 ![image](https://user-images.githubusercontent.com/6072550/81135323-4559e700-8f8a-11ea-89e2-ca3bfbd6ce71.png) 模拟器也可以打开 ![image](https://user-images.githubusercontent.com/6072550/81135331-4b4fc800-8f8a-11ea-8f2f-619277806cf9.png)
> 
> @sunnylqm 这是不是也说明正常的

大佬交流一下嘛，我看你也是搞区块链，加我qq764665007
