### ISSUE TITLE
初始化好的项目不能跑到真机上

### ISSUE THREAD

**Issue by sunmze** [reactnativecn/react-native-website#137]
请PS E:\RNtest4\Demo2> yarn android
yarn run v1.22.4
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 960 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (E:\RNtest4\Demo2\node_modules\execa\index.js:174:9)
    at E:\RNtest4\Demo2\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (E:\RNtest4\Demo2\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (E:\RNtest4\Demo2\node_modules\@react-native-community\cli\build\index.js:186:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sunnylqm** [comment]
检查下环境变量是否正确设置了

**Comment by sunmze** [comment]
>

> 检查下环境变量是否正确设置了

谢谢啊  我做andorid的 我以为我自己打android环境变量都配置完了呢   ,我又检查一边缺了两个，配置完搞定   。灰常感谢

**Comment by wushiwen123456** [comment]
您好，请问是怎么解决的，我也是遇到这个问题

**Comment by sunmze** [comment]
> 您好，请问是怎么解决的，我也是遇到这个问题
我当时是因为我的android环境配置错了导致的 你看看你的jdk环境和android 环境配置的对不对  ，按照他这边的搭建环境就可以

**Comment by sunmze** [comment]
您好，请问是怎么解决的，我也是遇到这个问题--->


我当时是因为我的android环境配置错了导致的 你看看你的jdk环境和android 环境配置的对不对 ，按照他这边的搭建环境就可以
