### ISSUE TITLE
library not found for -lCocoaAsyncSocket

### ISSUE THREAD

**Issue by ma569322307** [reactnativecn/react-native-website#138]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 如果是安装过程中的问题，请再三确认你有使用稳定的翻墙工具，且翻墙工具对命令行有生效（如开启全局模式等等）
- 请说明具体操作步骤和现象（例如执行什么命令，或者点击哪里，出现了什么异常现象或错误信息）
- 请尽量配上相关报错截图
   - 如果设备上有红屏报错请直接截图
   - 如果命令行有报错请直接截图
   - 警告(warning)一般不用管
   - 如果设备上看不到报错，请先尝试[调试模式](https://reactnative.cn/docs/debugging)。
   - 如果是发行版本无法调试，对于安卓设备请使用[adb logcat命令](https://developer.android.google.cn/studio/command-line/logcat)来捕获日志并粘贴到这里。iOS设备查看日志的[一些方法](https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a)。
- 请尽量配上相关代码截图

## 请描述完整的环境/版本信息
- 请在命令行的项目目录中运行`react-native info`命令，并将其输出结果粘贴到这里。
- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

**Comment by Where2Go** [comment]
![WeChate6f7156ff016ea143989e9191ee14db8](https://user-images.githubusercontent.com/15249318/84876602-f9867b80-b0b9-11ea-9b1a-c98b7093f5cc.png)
![WeChat12e8b94ddbae4353a49028784216168f](https://user-images.githubusercontent.com/15249318/84876623-fee3c600-b0b9-11ea-918d-65e5f6bc846e.png)
RN版本0.62.2报错 library not found for -lCocoaAsyncSocket

**Comment by sunnylqm** [comment]
确定pod install有完成吗
打开的是.xcworkspace文件吗

**Comment by lhorizon** [comment]
> ![WeChate6f7156ff016ea143989e9191ee14db8](https://user-images.githubusercontent.com/15249318/84876602-f9867b80-b0b9-11ea-9b1a-c98b7093f5cc.png)
> ![WeChat12e8b94ddbae4353a49028784216168f](https://user-images.githubusercontent.com/15249318/84876623-fee3c600-b0b9-11ea-918d-65e5f6bc846e.png)
> RN版本0.62.2报错 library not found for -lCocoaAsyncSocket


请问解决了吗？我也遇到这问题了，几天没搞定

**Comment by sunnylqm** [comment]
xcode 中的 build sysyem 改为 new build system



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 16, 2021 15:28 PM
To: ***@***.***&gt;;
Cc: "Sunny ***@***.******@***.***&gt;;
Subject: Re: [reactnativecn/react-native-website] library not found for -lCocoaAsyncSocket (#138)




  

 
 RN版本0.62.2报错 library not found for -lCocoaAsyncSocket
  
请问解决了吗？我也遇到这问题了，几天没搞定

**Comment by lhorizon** [comment]
> xcode 中的 build sysyem 改为 new build system
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Aug 16, 2021 15:28 PM To: ***@***.***&gt;; Cc: "Sunny ***@***.******@***.***&gt;; Subject: Re: [reactnativecn/react-native-website] library not found for -lCocoaAsyncSocket (#138) RN版本0.62.2报错 library not found for -lCocoaAsyncSocket 请问解决了吗？我也遇到这问题了，几天没搞定 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

解决了，谢谢

**Comment by minxiangyu** [comment]
![171630562577_ pic_hd](https://user-images.githubusercontent.com/31460872/131790913-1390d2a4-1138-4eb5-8285-021e39d28ba7.jpg)
![151630562494_ pic_hd](https://user-images.githubusercontent.com/31460872/131790931-1de65f01-3f15-4791-8357-28bacb678441.jpg)
![161630562548_ pic_hd](https://user-images.githubusercontent.com/31460872/131790941-d110ef8d-5683-40bc-9ab1-7039779c273a.jpg)
RN版本0.63.3报错 library not found for -lCocoaAsyncSocket
试过楼上的解决方案，无法解决



已解决，build phases-link binary with libraries中添加libCocoaAsyncSocket.a文件

**Comment by sunnylqm** [comment]
截图看不到你的build system是什么

**Comment by minxiangyu** [comment]
> 截图看不到你的build system是什么

xcode 中的 build sysyem 为 new build system，习惯性新建项目就改为new build system

**Comment by minxiangyu** [comment]
xcode 中的 build sysyem 为 new build system，习惯性新建项目就改为new build system




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sunny ***@***.***&gt;; 
发送时间: 2021年9月3日(星期五) 晚上6:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reactnativecn/react-native-website] library not found for -lCocoaAsyncSocket (#138)






建立系统

—
你收到这个是因为你评论了。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by minxiangyu** [comment]
> 截图看不到你的build system是什么

项目名.xcodeproj - project.pbxproj 中 LIBRARY_SEARCH_PATHS 的引号也得去掉，共两处，""/$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)/""改成"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"
