### ISSUE TITLE
运行 yarn react-native run-ios  报错

### ISSUE THREAD

**Issue by CherishLily** [reactnativecn/react-native-website#141]
运行 yarn react-native run-ios   时，出现如下错误：
The following build commands failed:
        ProcessPCH /Users/yuli/Documents/TBear-Project/TBears/ios/build/TBears/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/283540149031437557/PrefixHeader.pch.gch /Users/zhaodanning/project/TBears/ios/TBears/PrefixHeader.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/81495632-3fdf0280-92e4-11ea-947b-bd7ed1fd9519.png)
