### ISSUE TITLE
UIwebView禁用，IOS提交appstore，报错New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability

### ISSUE THREAD

**Issue by anbingyang** [reactnativecn/react-native-website#143]
邮件返回：

 
--
 
Dear Developer,We identified one or more issues with a recent delivery for your app, "Digi" 1.0.7 (1.0.7). Please correct the following issues, then upload again.ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).Best regards,The App Store Team

**Comment by sunnylqm** [comment]
不知道你怎么禁用的，要完全移除相关代码才可以

**Comment by aidola** [comment]
怎么解决的，给说个方案呗，昨天被苹果商店给拒了也是报的90809，苹果尼玛这是要疯啊，坑爹玩意

**Comment by anbingyang** [comment]
> 怎么解决的，给说个方案呗，昨天被苹果商店给拒了也是报的90809，苹果尼玛这是要疯啊，坑爹玩意

https://www.jianshu.com/p/44dcb3e6d246
刚写的文章，希望能对你有所帮助

**Comment by aidola** [comment]
> > 怎么解决的，给说个方案呗，昨天被苹果商店给拒了也是报的90809，苹果尼玛这是要疯啊，坑爹玩意
> 
> https://www.jianshu.com/p/44dcb3e6d246
> 刚写的文章，希望能对你有所帮助

是的，我今天琢磨了一下午，应该就是你简书里面说的原因，react-native-wechat的作者支持的ios sdk版本为1.7.2，而微信官方的sdk在1.8+版本的时候才修正了UIWebview的问题，切换成了WKWebview。react-native-wechat已经没人维护了，没人管这个问题。我也不太会改人家的代码，而且后期还怕会出现其他问题，我决定抛弃他，我看了友盟的官方api是跟随微信官方api更新了这个功能，所以用友盟的方法去集成微信了。

也感谢您的回答，不过我还是要调用微信分享和支付，所以改途径啦
