### ISSUE TITLE
iOS 打包后 运行报错

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#147]
**打包后运行报错**
`Unhandled JS Exception: TypeError: console.assert is not a function. (In 'console.assert(null!=o,"'this' is expected an Event object, but got",n)', 'console.assert' is undefined)`

**打包方式**
![0B7B4312-50BA-4997-A016-FC25443E5F29](https://user-images.githubusercontent.com/25916259/81807814-576ef300-9551-11ea-93e2-4b5b2db7d628.png)

**环境**
"react": "16.9.0",
"react-native": "0.61.5"

**其他**
发现index.ios.jsbundle 中有这段代码
![DB1B91F2-DD2B-4348-B7EB-64C3CE72DB0D](https://user-images.githubusercontent.com/25916259/81808472-57bbbe00-9552-11ea-91c2-c778526125a0.png)

**Comment by sunnylqm** [comment]
这种一般都是由于自己覆盖了console，但却漏掉了一些方法比如这里的assert

**Comment by GWCodeN** [comment]
> 这种一般都是由于自己覆盖了console，但却漏掉了一些方法比如这里的assert

这要如何解决 ，直接运行代码都没有这个报错

**Comment by sunnylqm** [comment]
就是不要覆盖console啊

**Comment by GWCodeN** [comment]
> 就是不要覆盖console啊

谢谢 找到了 不知道什么时候代码中有这样一段东西
```
if (!__DEV__) {
	global.console = {
		info: () => { },
		log: () => { },
		warn: () => { },
		debug: () => { },
		error: () => { }
	};
}
```

**Comment by sunnylqm** [comment]
很老版本的文档里，我写的，很久了都一直有人在抄。。。

**Comment by GWCodeN** [comment]
> 很老版本的文档里，我写的，很久了都一直有人在抄。。。

。。。。。。大佬  请收下我的膝盖
