### ISSUE TITLE
关于项目的思路问题

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#149]
**需求**
在A页面获取用户信息 B页面调用用户信息 （A,B 无任何交互，用户信息不需要本地存储）
**思路**
<img width="210" alt="image" src="https://user-images.githubusercontent.com/25916259/82040486-3c2eef80-96d9-11ea-9f29-12962d71e7e7.png">
**问题**
这样写会有问题么？正常的思路是怎样的？

**Comment by sunnylqm** [comment]
正常的思路就是用redux/mobx做组件无关的数据流

**Comment by GWCodeN** [comment]
> 正常的思路就是用redux/mobx做组件无关的数据流

如果不用redux/mobx 用上述同样能获取修改用户信息，不知是否可行

**Comment by sunnylqm** [comment]
是可以，但是问题一个接一个来了，
1、数据变化要如何使相关的组件刷新呢
2、应用中肯定不止一个用户数据，还有很多其他数据呢，你一个个单独处理吗
3、如何约束数据读写？如果任意地方随意读写那么和全局变量有何区别？如何保证逻辑明确利于维护？

如果你解决了上面三个问题，恭喜你你又实现了一个redux/mobx

**Comment by GWCodeN** [comment]
> 是可以，但是问题一个接一个来了，
> 1、数据变化要如何使相关的组件刷新呢
> 2、应用中肯定不止一个用户数据，还有很多其他数据呢，你一个个单独处理吗
> 3、如何约束数据读写？如果任意地方随意读写那么和全局变量有何区别？如何保证逻辑明确利于维护？
> 
> 如果你解决了上面三个问题，恭喜你你又实现了一个redux/mobx

谢谢指点 。还有一点不明白 ，对于 import A from 'B'  内存上是个什么样的过程？（浅拷贝？）
