### ISSUE TITLE
yarn android运行项目报错

### ISSUE THREAD

**Issue by Lester0301** [reactnativecn/react-native-website#150]
初始化的项目在android studio中能够在模拟器中运行，但是yarn android就报错，build.gradle配置如下：
`buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        
        // google()
        // jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        //  maven { 
        //     url "http://maven.aliyun.com/nexus/content/groups/public/" 
        // }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        
        // google()
        // jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
`

错误如下，
$ yarn android
yarn run v1.22.4
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 960 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'AwesomeProject'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.3.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.5.3.
         > Could not get resource 'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'. Received status code 400 from server: Bad Request
      > Could not resolve com.android.tools.build:gradle:3.5.3.
         > Could not get resource 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'AwesomeProject'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.3.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.5.3.
         > Could not get resource 'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'. Received status code 400 from server: Bad Request
      > Could not resolve com.android.tools.build:gradle:3.5.3.
         > Could not get resource 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (D:\workspace\Learn\RNLearn\AwesomeProject\node_modules\execa\index.js:174:9)
    at D:\workspace\Learn\RNLearn\AwesomeProject\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (D:\workspace\Learn\RNLearn\AwesomeProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (D:\workspace\Learn\RNLearn\AwesomeProject\node_modules\@react-native-community\cli\build\index.js:186:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sunnylqm** [comment]
Could not GET 'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'. Received status code 400 from server: Bad Request

下载gradle依赖报错400，要么是阿里云服务器挂了（不太可能），要么是你用了某种代理，代理报错了

**Comment by Zhou-Bill** [comment]
我也一样，请问解决了吗

**Comment by sunnylqm** [comment]
加上debug参数可以看到具体报错的代理设置

```shell
cd android && ./gradlew installDebug --debug
```
