### ISSUE TITLE
RN运行android报错，求大佬解答一下

### ISSUE THREAD

**Issue by zsadrtyu** [reactnativecn/react-native-website#155]
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s

**Comment by sunnylqm** [comment]
好像是jdk版本不对？

**Comment by zsadrtyu** [comment]
> 好像是jdk版本不对？

我也不知道...我在官网下的最新的14.0.1....

**Comment by sunnylqm** [comment]
不能仔细看一下文档吗？
![image](https://user-images.githubusercontent.com/615282/82518502-1d55b080-9b52-11ea-9ec4-15117f63b7aa.png)
