### ISSUE TITLE
react-native运行起来报错

### ISSUE THREAD

**Issue by zhangwei900808** [reactnativecn/react-native-website#156]
![image](https://user-images.githubusercontent.com/4385154/82519601-a1a93300-9b54-11ea-9548-a18ee2e24f9a.png)
![image](https://user-images.githubusercontent.com/4385154/82519621-ac63c800-9b54-11ea-85f6-50af4d6ee4bf.png)

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/82523255-395f4f00-9b5e-11ea-9b40-a508b49464b1.png)
浏览器里访问这个地址看下
命令行端也同时截图看下

**Comment by zhangwei900808** [comment]
@sunnylqm  访问不了，一直在转

**Comment by zhangwei900808** [comment]
![image](https://user-images.githubusercontent.com/4385154/82525951-4469ad80-9b65-11ea-8f4d-f95a11c9cae3.png)

**Comment by zhangwei900808** [comment]
![image](https://user-images.githubusercontent.com/4385154/82526007-66fbc680-9b65-11ea-8abd-333861e0c0f6.png)

**Comment by sunnylqm** [comment]
卸载watchman试下

**Comment by zhangwei900808** [comment]
@sunnylqm 确实卸载就好了，这是为什么？
![image](https://user-images.githubusercontent.com/4385154/82527108-30737b00-9b68-11ea-9867-d903c66008df.png)

**Comment by sunnylqm** [comment]
不清楚

**Comment by zhangwei900808** [comment]
好吧，多谢了
