### ISSUE TITLE
Mac Xcode 10.1 执行 react-native run-ios 报错  版本是react-native-cli: 2.0.1 react-native: 0.55.4

### ISSUE THREAD

**Issue by Huwei1993** [reactnativecn/react-native-website#157]
Installing build/Build/Products/Debug-iphonesimulator/TestRNProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/82526797-7419b500-9b67-11ea-8ed6-69ddbc1d60d1.png)
