### ISSUE TITLE
运行react-native run-android报错Failed to parse React Native CLI... ?

### ISSUE THREAD

**Issue by wilsonchen85** [reactnativecn/react-native-website#158]
请问下，我搭建好RN环境，在项目里运行react-native run-android报错：
FAILURE: Build failed with an exception.
* Where:
Script 'D:\myproject\node_modules\@react-native-community\cli-platform-android
\native_modules.gradle' line: 200

What went wrong:
A problem occurred evaluating script.

Failed to parse React Native CLI configuration. Expected running 'npx.cmd --qu
iet --no-install react-native config' command from 'D:\myproject' directory to
output valid JSON, but it didn't. This may be caused by npx resolving to a lega
cy global react-native binary. Please make sure to uninstall any global 'react-n
ative' binaries: 'npm uninstall -g react-native react-native-cli' and try again
这种报错如何解决？

**Comment by sunnylqm** [comment]
感觉是老的react-native-cli没有卸载干净

**Comment by wilsonchen85** [comment]
> 感觉是老的react-native-cli没有卸载干净

我执行了提示中的命令：npm uninstall -g react-native react-native-cli
再重新安装：yarn add react-native react-native-cli

然后就提示：'react-native' 不是内部或外部命令，也不是可运行的程序或批处理文件。
执行npm的命令也报
Error: Cannot find module 'D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.
js'

请问是不是这样执行的？

**Comment by sunnylqm** [comment]
卸载后就不用再安装了啊，请仔细对着文档来啊

**Comment by wilsonchen85** [comment]
> 卸载后就不用再安装了啊，请仔细对着文档来啊

卸载后，直接执行react-native run-android就会提示如下：
'react-native' 不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by sunnylqm** [comment]
请仔细看文档

**Comment by wilsonchen85** [comment]
> 请仔细看文档

指导一下呗

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/82755029-94fe3680-9e03-11ea-8d89-5448c2394506.png)
我实在不太懂，我截个图和你自己看有啥区别？

**Comment by wilsonchen85** [comment]
懂的大神们能指点一下吗？跪谢！

**Comment by sunnylqm** [comment]
我划红线的看不到吗？

**Comment by wilsonchen85** [comment]
> 我划红线的看不到吗？

看不到，图片挂了。

**Comment by sunnylqm** [comment]
我发个网盘链接你能看到吧

https://pan.baidu.com/s/14Dqq9P3HoHkGN72-FV6YmA 
提取码:0aqj

**Comment by wilsonchen85** [comment]
每日一顶

**Comment by sunnylqm** [comment]
所以网盘链接也看不到吗
