### ISSUE TITLE
求大佬指导！win10遇到的问题

### ISSUE THREAD

**Issue by XieZongChen** [reactnativecn/react-native-website#159]
react-native : 无法将“react-native”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ react-native run-android
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (react-native:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

麻烦各位大佬指导一下，辛苦了！

**Comment by sunnylqm** [comment]
![](https://user-images.githubusercontent.com/615282/82755029-94fe3680-9e03-11ea-8d89-5448c2394506.png)

如果你看不见截图，这里有百度网盘链接
https://pan.baidu.com/s/14Dqq9P3HoHkGN72-FV6YmA 
提取码:0aqj

**Comment by XieZongChen** [comment]
> ![](https://user-images.githubusercontent.com/615282/82755029-94fe3680-9e03-11ea-8d89-5448c2394506.png)
> 
> 如果你看不见截图，这里有百度网盘链接
> https://pan.baidu.com/s/14Dqq9P3HoHkGN72-FV6YmA
> 提取码:0aqj

谢谢大佬，是我太粗心了
