### ISSUE TITLE
android应用市场发布需要targetSdkVersion必须大于等于26，但修改之后，app扫码功能出现黑屏

### ISSUE THREAD

**Issue by RENKEKERONG** [reactnativecn/react-native-website#161]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 如果是安装过程中的问题，请再三确认你有使用稳定的翻墙工具，且翻墙工具对命令行有生效（如开启全局模式等等）
- 请说明具体操作步骤和现象（例如执行什么命令，或者点击哪里，出现了什么异常现象或错误信息）
- 请尽量配上相关报错截图
   - 如果设备上有红屏报错请直接截图
   - 如果命令行有报错请直接截图
   - 警告(warning)一般不用管
   - 如果设备上看不到报错，请先尝试[调试模式](https://reactnative.cn/docs/debugging)。
   - 如果是发行版本无法调试，对于安卓设备请使用[adb logcat命令](https://developer.android.google.cn/studio/command-line/logcat)来捕获日志并粘贴到这里。iOS设备查看日志的[一些方法](https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a)。
- 请尽量配上相关代码截图

## 请描述完整的环境/版本信息
- 请在命令行的项目目录中运行`react-native info`命令，并将其输出结果粘贴到这里。
- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

**Comment by RENKEKERONG** [comment]
android应用市场发布需要targetSdkVersion必须大于等于26，但修改之后，app扫码功能出现黑屏 

![image](https://user-images.githubusercontent.com/48847039/82975663-ba5f9000-a00f-11ea-8338-105a7d5bd067.png)



android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    defaultConfig {
        applicationId "com.pexetech"
        minSdkVersion 16
       ###  **

- ### **1. targetSdkVersion 26**

**
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

**Comment by RENKEKERONG** [comment]
![image](https://user-images.githubusercontent.com/48847039/82975789-03afdf80-a010-11ea-9f77-398bfb706e15.png)

**Comment by sunnylqm** [comment]
感觉你的版本有点老？你可能首先要考虑升级rn，包括这个扫码组件的版本
这些问题也应该去这个扫码组件的issue里去搜索

**Comment by yz1311** [comment]
需要主动获取权限

**Comment by hongbobo614** [comment]
这是没有获取扫码相关的权限
