### ISSUE TITLE
react-native0.60 以后如何修改默认的启动的8081端口？

### ISSUE THREAD

**Issue by wuxiii** [reactnativecn/react-native-website#163]
请按以下格式提供问题的相关信息。

## 问题的具体描述
`react-native run-android --port 8081`可以修改用命令安装到模拟器的meter端口，如果在android stdio中调试，如何在Android stdio中点run按钮更换启动端口？

在之前的版本中可以修改/node_modules/react-native/local-cli/server/server.js中的配置的8081，但是0.60以后cli好像给社区维护了

**Comment by sunnylqm** [comment]
一样的
