### ISSUE TITLE
react-native 

### ISSUE THREAD

**Issue by liuwu4** [reactnativecn/react-native-website#164]
## android 无法热更新
- 执行react-native run-android后能够正常运行在真机或模拟器上但是不能自动编辑和热更新
<img width="1440" alt="屏幕快照 2020-05-29 17 23 34" src="https://user-images.githubusercontent.com/34388697/83244042-64d2e100-a1d1-11ea-864b-ad7b080ba92b.png">

## 完整的环境/版本信息
<img width="1298" alt="屏幕快照 2020-05-29 17 16 54" src="https://user-images.githubusercontent.com/34388697/83243784-f7bf4b80-a1d0-11ea-9279-e0a83c4a14f2.png">

## 预期结果
-  android 真机和模拟器模式下应该能自动编译和热更新

**Comment by sunnylqm** [comment]
截图上看不到什么问题啊
