### ISSUE TITLE
Task 'installChannel01Debug' not found in project ':app'.

### ISSUE THREAD

**Issue by LoveEocding** [reactnativecn/react-native-website#167]
请按以下格式提供问题的相关信息。

## 问题的具体描述
FAILURE: Build failed with an exception.

* What went wrong:
Task 'installChannel01Debug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installChannel01Debug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installChannel01Debug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (C:\work\MyFirstRnApp\node_modules\execa\index.js:174:9)
    at C:\work\MyFirstRnApp\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (C:\work\MyFirstRnApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\work\MyFirstRnApp\node_modules\@react-native-community\cli\build\index.js:186:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## 请描述完整的环境/版本信息
默认完整初始化版本

## 预期结果
就初始化一个项目 没有跑起来

**Comment by sunnylqm** [comment]
初始化的项目为什么会蹦出来一个Channel01？

**Comment by LoveEocding** [comment]
> 初始化的项目为什么会蹦出来一个Channel01？

错了这里我是按照网上加了渠道 但是没有用 初始报错intallDebug not found in :app

**Comment by sunnylqm** [comment]
那是因为环境变量没配置

**Comment by LoveEocding** [comment]
> 那是因为环境变量没配置

我刚才重新搭建了环境 这种可能是什么原因抛的错 请问* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > java/util/Collections$2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by sunnylqm** [comment]
你有修改什么gradle的配置吗

**Comment by LoveEocding** [comment]
> 你有修改什么gradle的配置吗
你好没有，目前又是初始化的一个项目。我估计还是环境的问题 我重新搭建一个完整的试试。从头

**Comment by LoveEocding** [comment]
> 你有修改什么gradle的配置吗
我重新完整的搭建了环境 已经可以了 应该是环境配置有问题 感谢。
