### ISSUE TITLE
初始化项目出现Npm错误

### ISSUE THREAD

**Issue by haxifang-aircos** [reactnativecn/react-native-website#168]
执行 npx react-native init AwesomeProject

抛错
![截屏2020-06-02下午12 53 51](https://user-images.githubusercontent.com/61681123/83481381-335b5d80-a4d0-11ea-9b13-5647e44676ce.png)

我的 npm 版本为 6.14.4

**Comment by sunnylqm** [comment]
有替换淘宝源吗
