### ISSUE TITLE
真机调试报错，求大佬！

### ISSUE THREAD

**Issue by lincong206** [reactnativecn/react-native-website#169]
环境是一步一步按照教程安装，初始化项目，然后真机调试。
是不是还有地方需要设置啥的？
在文件目录下面也没找到这些.sh文件
是需要手动创建还是直接有下载的？
需要更改文件的参数嘛？
多谢大佬。
PhaseScriptExecution Start\ Packager /Users/XXX/Library/Developer/Xcode/DerivedData/AwesomeProject-bilvwqshjglisuatbqtvtydkxbep/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/Script-FD10A7F022414F080027D42C.sh
    cd /Users/XXX/AwesomeProject/ios
    /bin/sh -c /Users/XXX/Library/Developer/Xcode/DerivedData/AwesomeProject-bilvwqshjglisuatbqtvtydkxbep/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/Script-FD10A7F022414F080027D42C.sh

/Users/XXX/Library/Developer/Xcode/DerivedData/AwesomeProject-bilvwqshjglisuatbqtvtydkxbep/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphoneos/AwesomeProject.build/Script-FD10A7F022414F080027D42C.sh: line 3: /Users/XXX/AwesomeProject/ios/../node_modules/react-native/scripts/.packager.env: No such file or directory
Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

**Comment by sunnylqm** [comment]
上面的日志都是正常的

**Comment by lincong206** [comment]
但是连了真机没想到，说是没有设备。
模拟器也是，
求教，小白，demo工程没起来。

**Comment by lincong206** [comment]
> 上面的日志都是正常的
之前那是在xcode工程运行的结果。
找了一下资料，pod install。显示有的库下载失败。源是淘宝的。
现在命令运行iOS会出现如下报错。
lincongdeMacBook-Air:AwesomeProject XXX$ react-native run-ios
error Could not find "Podfile.lock" at /Users/XXX/Downloads/AwesomeProject/ios/Podfile.lock. Did you run "pod install" in iOS directory?
info Found Xcode project "AwesomeProject.xcodeproj"
info Building (using "xcodebuild -project AwesomeProject.xcodeproj -configuration Debug -scheme AwesomeProject -destination id=4E699C71-E98C-4241-90C9-1E472A41AB88")
(node:73335) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
...............
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening AwesomeProject.xcodeproj. Run CLI with --verbose flag for more details.

是因为pod install有些库没下载的原因嘛？要翻墙？

**Comment by sunnylqm** [comment]
你能成功运行pod install吗，不完成这一步是不能运行的
