### ISSUE TITLE
初始化工程后run命令报错invariant violation module rcteventemitter is not a registered callable module

### ISSUE THREAD

**Issue by iCodeAnt** [reactnativecn/react-native-website#170]
## 初始化工程后run命令报错 红屏报错
nvariant violation module rcteventemitter is not a registered callable module

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-03 at 10 53 09](https://user-images.githubusercontent.com/13937612/83590575-a88a6980-a588-11ea-9976-2816bc4fe66e.png)

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-03 at 10 52 52](https://user-images.githubusercontent.com/13937612/83590601-b63fef00-a588-11ea-9fc0-359a5619b4bf.png)

## 请描述完整的环境/版本信息
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 21.15 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 3.8.0 - /Users/moon/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

**Comment by sunnylqm** [comment]
看起来是你安装了一些原生依赖（reanimated, gesture-handler）之后没有编译

**Comment by iCodeAnt** [comment]
> 看起来是你安装了一些原生依赖（reanimated, gesture-handler）之后没有编译

谢谢回复，我就是直接按教程初始话的
1.
npx react-native init AwesomeProject
2
yarn ios

就这样了、
请问有人碰到一样的问题吗

**Comment by iCodeAnt** [comment]
终端关掉，重新运行命令就可以了！谢谢各位大佬！
