### ISSUE TITLE
为什么我的初始化项目会 Task :app:javaPreCompileDebug FAILED

### ISSUE THREAD

**Issue by linyanlong** [reactnativecn/react-native-website#171]
我把项目部署到模拟机上报了这个错误 我之前在电脑上开发了安卓（用java）我也没搞懂这是环境哪里出错了
> Task :app:javaPreCompileDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.                                     <============-> 94% EXECUTING [4m 42s]
Use '--warning-mode all' to show the individual deprecation warnings.cebook.flipper:flipper:0.33.1) with JetifyTransform > flipper-0.33.1.aar > 5. > IDLE
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
12 actionable tasks: 2 executed, 10 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:javaPreCompileDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not download flipper-0.33.1.aar (com.facebook.flipper:flipper:0.33.1)
      > Could not get resource 'https://jcenter.bintray.com/com/facebook/flipper/flipper/0.33.1/flipper-0.33.1.aar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/8f406682cfa1e948aa0a1ad4bc9326c256d4f33f063c4842882d5402b00ec28a?response-content-disposition=attachment%3Bfilename%3D%22flipper-0.33.1.aar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvOGY0MDY2ODJjZmExZTk0OGFhMGExYWQ0YmM5MzI2YzI1NmQ0ZjMzZjA2M2M0ODQyODgyZDU0MDJiMDBlYzI4YT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmZsaXBwZXItMC4zMy4xLmFhciUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU5MTE3NDYzOH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=hMl2fiv5nPlEOaKOzFRYffzEVD0L3WNutAtKwVLdowUi542NsUSo5WDVkCF9HH-QvMbcv5UiCOoGpy58G4l0ggASThpOtVRuZtLIOVKsJ0OYXvm0H~-w7W27BLUYT~oPUmEK8MMpEblnp5VqScvD3UzW1lMQEY2r0MOXI1Gs5qr66BBdPVMBNRRiFlXZhe09mgEonbqg-VBIq2d~2tmCU-kHIAo-jxpDOY2WGJVcZFdCt59tu-VSn7sSpM-6MyVARctvaVC1iDxayz0CZeHrrjpPo5KfHOEaw3kSyrVPQdqh44Lk~vGO0YxGlJAytsZPVjALqUHJCaNGry3UeI6W6A__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > Received close_notify during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 22s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:javaPreCompileDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not download flipper-0.33.1.aar (com.facebook.flipper:flipper:0.33.1)
      > Could not get resource 'https://jcenter.bintray.com/com/facebook/flipper/flipper/0.33.1/flipper-0.33.1.aar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/8f406682cfa1e948aa0a1ad4bc9326c256d4f33f063c4842882d5402b00ec28a?response-content-disposition=attachment%3Bfilename%3D%22flipper-0.33.1.aar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvOGY0MDY2ODJjZmExZTk0OGFhMGExYWQ0YmM5MzI2YzI1NmQ0ZjMzZjA2M2M0ODQyODgyZDU0MDJiMDBlYzI4YT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmZsaXBwZXItMC4zMy4xLmFhciUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU5MTE3NDYzOH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=hMl2fiv5nPlEOaKOzFRYffzEVD0L3WNutAtKwVLdowUi542NsUSo5WDVkCF9HH-QvMbcv5UiCOoGpy58G4l0ggASThpOtVRuZtLIOVKsJ0OYXvm0H~-w7W27BLUYT~oPUmEK8MMpEblnp5VqScvD3UzW1lMQEY2r0MOXI1Gs5qr66BBdPVMBNRRiFlXZhe09mgEonbqg-VBIq2d~2tmCU-kHIAo-jxpDOY2WGJVcZFdCt59tu-VSn7sSpM-6MyVARctvaVC1iDxayz0CZeHrrjpPo5KfHOEaw3kSyrVPQdqh44Lk~vGO0YxGlJAytsZPVjALqUHJCaNGry3UeI6W6A__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > Received close_notify during handshake

**Comment by sunnylqm** [comment]
这么明显的一个下载失败
![image](https://user-images.githubusercontent.com/615282/83618013-75fa6400-a5bc-11ea-858d-525085301263.png)
