### ISSUE TITLE
 react native调试模式下  真机(Android API 29)点击 没反应或非常的慢

### ISSUE THREAD

**Issue by hongbobo614** [reactnativecn/react-native-website#172]
react native项目在 Chorme 下debug 真机调试 ，
   1.点击没有反应，需要多点几次，但是非常慢；
   2.页面也不能跳转，需要手动触摸，才能正常跳转。
   3.使用React-Native Debugger调试工具调试，操作真机完全没反应

 "react": "16.11.0",
 "react-native": "0.62.2"

手机小米9  系统安卓10

**Comment by sunnylqm** [comment]
检查下电脑和手机时钟是否一致

**Comment by amusiq** [comment]
我也有同样问题

**Comment by bingaicao** [comment]
我也是同样问题，网上搜了半天没有什么答案，我怀疑是debug.js劫持了页面事件，只有滑动可以，有人有解决方案吗

**Comment by sunnylqm** [comment]
此现象最常见的情况就是电脑和调试设备的时钟不一致（差几秒都有影响）
此外有些第三方也会极大的拖慢调试性能，比如realm

**Comment by hongbobo614** [comment]
我的 mac系统 可以用这命令解决问题： sudo sntp -sS time.apple.com    已经解决了。

**Comment by hongbobo614** [comment]
> 我也是同样问题，网上搜了半天没有什么答案，我怀疑是debug.js劫持了页面事件，只有滑动可以，有人有解决方案吗

我的mac系统可以用这命令解决问题：sudo sntp -sS time.apple.com  已经解决了。

**Comment by hongbobo614** [comment]
> 我也是同样问题，网上搜了半天没有什么答案，我怀疑是debug.js劫持了页面事件，只有滑动可以，有人有解决方案吗

我的mac系统可以用这命令解决问题：sudo sntp -sS time.apple.com已经解决了。

**Comment by amusiq** [comment]
如果是windows系统怎么解决呢

**Comment by hongbobo614** [comment]
> 如果是windows系统怎么解决呢

windows系统没有验证过，我是按照 上面大兄弟 提的 ”检查下电脑和手机时钟是否一致“ 这个方向去查询解决的。你可以尝试下

**Comment by bingoShawn** [comment]
> 此现象最常见的情况就是电脑和调试设备的时钟不一致（差几秒都有影响） 此外有些第三方也会极大的拖慢调试性能，比如realm

又是你大神！谢谢了！
