### ISSUE TITLE
rn0.62用chrome+夜游神模拟器调试时，文本框不能输入内容

### ISSUE THREAD

**Issue by jztele** [reactnativecn/react-native-website#173]
## 问题的具体描述
rn0.62用chrome+夜游神模拟器调试时，文本框不能输入内容，react navigation导航也没反应。在非调试模式下，一切都正常。请问如何解决？

##package.json的内容
{
  "name": "demo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.5.1",
    "@react-navigation/native": "^5.5.0",
    "@react-navigation/stack": "^5.4.1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.2",
    "react-native-screens": "^2.8.0",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by sunnylqm** [comment]
注意下模拟器时钟和系统是否一致

**Comment by jztele** [comment]
> 注意下模拟器时钟和系统是否一致

你好，模拟器时钟和系统是一致的。而且，如果用expo的话，在调试模式下就也都是正常的。好奇怪啊
