### ISSUE TITLE
rn项目运行报错

### ISSUE THREAD

**Issue by wushiwen123456** [reactnativecn/react-native-website#176]
请按以下格式提供问题的相关信息。

## rn 项目运行报错
这里是保存的信息：：

PS D:\android-project\rn-app> npm run start

> myReactProject@0.0.1 start D:\android-project\rn-app
> node node_modules/react-native/local-cli/cli.js start

Scanning 699 folders for symlinks in D:\android-project\rn-app\node_modules (27ms)

Invalid regular expression: /(node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!
npm ERR! Failed at the myReactProject@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-06-06T10_04_50_162Z-debug.log
PS D:\android-project\rn-app>

## 请描述完整的环境/版本信息
-node 版本： v12.16.2
-npm 版本：6.14.4

**Comment by sunnylqm** [comment]
metro之前的版本在windows上对node12有一些兼容性问题，0.57之后修复
携带metro 0.57的是react native0.62以上版本
所以，解决方案是
1、使用最新的react native版本
2、或者退回到node10

**Comment by wushiwen123456** [comment]
感谢感谢！！
