### ISSUE TITLE
react-native link [packageName] is deprecated 

### ISSUE THREAD

**Issue by yuanbolin** [reactnativecn/react-native-website#179]
link已经弃用,比较流行的三方包link应该如何解决

**Comment by sunnylqm** [comment]
0.60以上自动link，不需要任何命令（当然需要手动配置的地方仍然需要手动配置，以文档为准），实在不能自动link的，应当去第三方的issue里发帖询问正确做法
0.60以下仍然使用link命令

**Comment by yuanbolin** [comment]
收到,打扰了

**Comment by yuanbolin** [comment]
还有个疑问,我发现0.62.2很多第三方的字体文件图标解析不出来请问这怎么解决

**Comment by sunnylqm** [comment]
无非是你或者第三方没有正确配置和编译

**Comment by yuanbolin** [comment]
那可能是我的问题,我查看了android/app/src/main下发现没有assets文件夹所以才不显示,这种情况您有什么建议吗

**Comment by sunnylqm** [comment]
建议就是仔细看文档，按文档正确配置

**Comment by 452MJ** [comment]
> 那可能是我的问题,我查看了android/app/src/main下发现没有assets文件夹所以才不显示,这种情况您有什么建议吗

自己建一个
