### ISSUE TITLE
关于rn配合自定义ImageView加载本地资源图片问题

### ISSUE THREAD

**Issue by smsuperman** [reactnativecn/react-native-website#180]
## 问题的具体描述
Android原生ImageView加载的本地图片都是Drawable或者Bitmap类型，我想在rn那里propTypes中传入本地资源来加载，但是propTypes不支持这些类型，大佬们有合适的方法吗，求助

**Comment by sunnylqm** [comment]
propTypes已经是被放弃的做法了，没啥必要再研究了吧
