### ISSUE TITLE
TouchableOpacity点击无效

### ISSUE THREAD

**Issue by sunmengm** [reactnativecn/react-native-website#185]
{
            !this.state.showList ? <View
              style={{
                position: 'absolute',
                left: '5%',
                top: (this.state.showIndex + 1) * 42 + 10,
                width: width * 0.4,
                borderRadius: 2,
                borderTopColor: '#F2F2F2',
                borderTopWidth: 1
              }} >
       
              <ScrollView   style={styles.flatlist}>
                {
                  searchList.map((item, index) => {
                    return (<TouchableOpacity
                      gestureState={true}
                      style={styles.itemList}
                      key={index}
                      onPress={() => {
                        console.log('点击列表')
                      }}>
                      <Text style={styles.itemTitle}>{item.name}</Text>
                    </TouchableOpacity>)
                  })
                }

              </ScrollView>
              {/* <FlatList
                style={styles.flatlist}
                renderItem={this.renderItem}
                data={searchList}
                keyExtractor={(item, index) => index.toString()}
              >
              </FlatList> */}
如代码所示，我添加一个悬浮框，然后进行绝对定位，发现绝对定位中的TouchableOpacity无法触发事件，求教大神帮忙解决一下

**Comment by lilicoder** [comment]
同遇到，M

**Comment by lilicoder** [comment]
第一个回答
https://stackoverflow.com/questions/60698200/react-native-touchableopacity-not-working-with-position-absolute
