### ISSUE TITLE
ios真机运行报错，大佬求助

### ISSUE THREAD

**Issue by wangyao333** [reactnativecn/react-native-website#186]
Check dependencies

Code Signing Error: Signing for "weilink-tvOS" requires a development team. Select a development team in the project editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'tvOS 12.1'

**Comment by sunnylqm** [comment]
ios真机运行需要配置所有四个target（主项目，主项目test，主项目tvos，主项目tvos-test）的签名
参考 https://reactnative.cn/docs/running-on-device

但实际上很多target你基本用不上，所以不如直接把那些target（test, tvos, tvos-test）删掉省得麻烦

**Comment by wangyao333** [comment]
谢谢大佬，那如何删除呢

**Comment by sunnylqm** [comment]
点减号删除啊
