### ISSUE TITLE
求助----RN ios 安装依赖包后运行项目报错

### ISSUE THREAD

**Issue by yanyufanchen** [reactnativecn/react-native-website#187]
ld: warning: directory not found for option '-L/Users/wangpeng/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator'
ld: library not found for -lRCTBluetoothSerial
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sunnylqm** [comment]
有个蓝牙相关的第三方配置不正确（怎么配置得看他们的文档，去他们的issue里提问）
