### ISSUE TITLE
大佬求助 iOS运行报错

### ISSUE THREAD

**Issue by wangyao333** [reactnativecn/react-native-website#188]
Undefined symbols for architecture arm64:
  "_RCTSharedApplication", referenced from:
      -[weilinkTests testRendersWelcomeScreen] in weilinkTests.o
  "_RCTDefaultLogFunction", referenced from:
      -[weilinkTests testRendersWelcomeScreen] in weilinkTests.o
  "_RCTSetLogFunction", referenced from:
      -[weilinkTests testRendersWelcomeScreen] in weilinkTests.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by leaf2006** [comment]
这种情况我没遇到过😂

**Comment by shadow-boy** [comment]
把这`weilinkTests.o`文件所在的原生工程删了
