### ISSUE TITLE
运行成功但是报Unable to resolve module `./index` from ``

### ISSUE THREAD

**Issue by pphxiong** [reactnativecn/react-native-website#193]
## 问题的具体描述
- 在一个终端执行react-native start
- 另外一个终端执行react-native run-android
结果是：BUILD SUCCESSFUL in 56s
但是， react-native start的终端报错了：
Error: Unable to resolve module `./index` from ``:

None of these files exist:
  * index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * index\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (D:\web\taobao\umiRNExample-master\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (D:\web\taobao\umiRNExample-master\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\web\taobao\umiRNExample-master\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at D:\web\taobao\umiRNExample-master\node_modules\metro\src\lib\transformHelpers.js:267:42
    at Server.<anonymous> (D:\web\taobao\umiRNExample-master\node_modules\metro\src\Server.js:841:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\web\taobao\umiRNExample-master\node_modules\metro\src\Server.js:99:24)
    at _next (D:\web\taobao\umiRNExample-master\node_modules\metro\src\Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

## 完整的环境/版本信息
- 执行react-native info信息如下：
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 403.37 MB / 6.94 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: D:\web\taobao\umiRNExample-master>"node"  "C:\Users\dehua.xiong\AppData\Roaming\npm\\node_modules\npm\bin\npm-cli.js" -v
6.13.4 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 10, 20, 22, 23, 26, 27, 28
      Build Tools: 20.0.0, 22.0.1, 23.0.1, 26.0.1, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-28 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: [0x7FFF6FD74F50] ANOMALY: meaningless REX prefix used[0x7FFF6FD74F90] ANOMALY: meaningless REX prefix used[0x7FFF6FD751A0] ANOMALY: meaningless REX prefix used[0x7FFF6
FD73440] ANOMALY: meaningless REX prefix used[0x7FFF570540E0] ANOMALY: meaningless REX prefix used[0x7FFF6FD72130] ANOMALY: meaningless REX prefix used[0x7FFF57053E70] ANOMALY: meaningles
s REX prefix used[0x7FFF6F510750] ANOMALY: meaningless REX prefix used[0x7FFF50D729B0] ANOMALY: meaningless REX prefix used[0x7FFF50D72DC0] ANOMALY: meaningless REX prefix used
  Languages:
    Java: Not Found
    Python: 2.7.16 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## 预期结果
- 都运行成功了，怎么最后报了Unable to resolve module `./index` from ``这个错误，
打开http://localhost:8081/index.android.bundle?platform=android 也是显示这个错误

**Comment by sunnylqm** [comment]
你把index.js删掉了？
这个是固定的入口文件，不可删除，不可移动位置，不可修改文件名

**Comment by pphxiong** [comment]
> 你把index.js删掉了？
> 这个是固定的入口文件，不可删除，不可移动位置，不可修改文件名

终于好了，确实是缺少了index.js
原来我用的这个框架是用yarn watch临时生成的index.js
要先执行yarn watch，再启动和运行。。

感谢 @sunnylqm
