### ISSUE TITLE
this.props.navigation.navigate('register')路由跳转的时候报： Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by pnzyl** [reactnativecn/react-native-website#194]
底部tabtar跳转的时候页面可以正常显示，执行this.props.navigation.navigate('register')页面却报错，代码语法没有问题，底部导航可以实现跳转，但页面之间却无法实现跳转，反而报Error: Text strings must be rendered within a <Text> component.
2020-06-28 18:06:47.978 4680-11267/com.xblzreact E/ReactNativeJS: Error: Text strings must be rendered within a <Text> component.
    
    This error is located at:
        in NavigationContainer (at renderApplication.js:45)
        in RCTView (at AppContainer.js:109)
        in RCTView (at AppContainer.js:135)
        in AppContainer (at renderApplication.js:39)

**Comment by sunnylqm** [comment]
这个报错是因为有字符串没有用Text组件包起来，既然是navigate('register')报错，那么多半是出现在register页面
这个错误很难排查，因为没有明确的报错位置，所以一般通过删除法来定位（删到不报错为止）

如果不是换行，空格等容易忽视的字符串，那么一种更常见的错误是用到了布尔表达式
![image](https://user-images.githubusercontent.com/615282/85949080-34749300-b987-11ea-834f-523d139a72b2.png)
