### ISSUE TITLE
Text设置numberOfLines为2，界面相同样式前提下只展示1行内容。。。

### ISSUE THREAD

**Issue by fanzhengbiao** [reactnativecn/react-native-website#195]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 采用原生组件：Text，配置属性numberOfLines为2，在部分真机上面遍历出来的**部分数据只展示一行**
## 真机问题图
![image](https://user-images.githubusercontent.com/15938682/86126607-2ce0f580-bb11-11ea-85ae-8d06a793baae.png)

- styles
![image](https://user-images.githubusercontent.com/15938682/86125982-23a35900-bb10-11ea-8786-e040057c3e02.png)

## 请描述完整的环境/版本信息
- 环境：在真机iphone7，iphone6等真机。

## 预期结果
- 都正常能展示两行。

## 浏览器查看元素
![image](https://user-images.githubusercontent.com/15938682/86126689-569a1c80-bb11-11ea-99fc-6f262c4f0f22.png)

**Comment by sunnylqm** [comment]
参考下 https://github.com/facebook/react-native/issues/21410#issuecomment-480744517

**Comment by fanzhengbiao** [comment]
> 参考下 [facebook/react-native#21410 (comment)](https://github.com/facebook/react-native/issues/21410#issuecomment-480744517)
