### ISSUE TITLE
求助大佬 `React/RCTBridgeModule.h` file not found问题（关于iOS安装react-native-bluetooth-serial蓝牙）

### ISSUE THREAD

**Issue by yanyufanchen** [reactnativecn/react-native-website#196]
"react-native": "0.62.2",
安装react-native-bluetooth-serial后 pod install 提示找不到文件 ，并且Xcode编译报错：`React/RCTBridgeModule.h` file not found
这个该怎么解决

**Comment by sunnylqm** [comment]
这你得去问包作者
