### ISSUE TITLE
按照官网启动app失败，急

### ISSUE THREAD

**Issue by kisssama** [reactnativecn/react-native-website#197]
android studio里启动OK。
vscode里启动就报错
java version "1.8.0_181"
"react": "16.11.0",
"react-native": "0.62.2"
node版本 v10.15.0
![1593880559(1)](https://user-images.githubusercontent.com/19910976/86517002-eadcea00-be57-11ea-9ca3-f258fbb805af.png)

**Comment by sunnylqm** [comment]
你应该还另外有个高于1.8版本的jdk

**Comment by kisssama** [comment]
> 你应该还另外有个高于1.8版本的jdk

你说的没错，我装了个14的版本。
问题解决了，我把电脑恢复系统设置。重新配置环境就好了
