### ISSUE TITLE
yarn andriod报错

### ISSUE THREAD

**Issue by denghuafen** [reactnativecn/react-native-website#201]
请按以下格式提供问题的相关信息。

## 问题的具体描述
![image](https://user-images.githubusercontent.com/55309737/86767625-d4fd3e00-c07e-11ea-816b-b93d2effc14d.png)

**Comment by loveToMy** [comment]
我跟你情况一样，换成npm就好了

**Comment by sunnylqm** [comment]
标准的代理配置有问题啊(http 400报错)

**Comment by denghuafen** [comment]
> 我跟你情况一样，换成npm就好了

你是说通过npm android启动吗

**Comment by sunnylqm** [comment]
gradle都没下载下来   编译都还没开始  启动啥

**Comment by loveToMy** [comment]
![image](https://user-images.githubusercontent.com/49303865/87110136-e3bf3d00-c298-11ea-9b65-fc4b37075958.png)
npm run android  也可能是我替换了maven镜像的原因

**Comment by denghuafen** [comment]
> gradle都没下载下来 编译都还没开始 启动啥

![image](https://user-images.githubusercontent.com/55309737/87110520-d060a180-c299-11ea-8478-deaa0a7fe133.png)
通过本地获取gradle之后，还是会报错。。

**Comment by denghuafen** [comment]
> gradle都没下载下来 编译都还没开始 启动啥



> ![image](https://user-images.githubusercontent.com/49303865/87110136-e3bf3d00-c298-11ea-9b65-fc4b37075958.png)
> npm run android 也可能是我替换了maven镜像的原因

使用npm run android 之后，还是会报http 400的错误。。。

**Comment by sunnylqm** [comment]
第一个下载的是gradle-wrapper   下载完gradle wrapper之后  应该替换阿里云的maven源，之后不需要代理就可以进行

**Comment by denghuafen** [comment]
> 第一个下载的是gradle-wrapper 下载完gradle wrapper之后 应该替换阿里云的maven源，之后不需要代理就可以进行

![image](https://user-images.githubusercontent.com/55309737/87111372-ca6bc000-c29b-11ea-8e01-fb2daa3f292a.png)
已哭。。maven源替换后，还是不行。。

**Comment by sunnylqm** [comment]
看到那个400报错没  `你！的！代！理！设！置！有！问！题！`

**Comment by denghuafen** [comment]
> 看到那个400报错没 `你！的！代！理！设！置！有！问！题！`

em....是指需要科学上网工具，去设置代理吗

**Comment by sunnylqm** [comment]
不是需要什么  是你`已经`设置过代理了，而这个代理或者设置本身是有问题的

**Comment by denghuafen** [comment]
> 不是需要什么 是你`已经`设置过代理了，而这个代理或者设置本身是有问题的
em....我好像没设置过啥代理呀。。。有什么方法可以查看吗

**Comment by sunnylqm** [comment]
设置代理的方式很多，那你就得好好回忆下了

**Comment by loveToMy** [comment]
> > 不是需要什么 是你`已经`设置过代理了，而这个代理或者设置本身是有问题的
> > em....我好像没设置过啥代理呀。。。有什么方法可以查看吗

可能是一开始编译gradle写进去了 然后再换maven源还是执行的之前的

**Comment by sunnylqm** [comment]
maven源已经变成阿里云的了啊  截图不是很清楚吗

**Comment by denghuafen** [comment]
太难受了，我都不知道我干了啥。。。

**Comment by denghuafen** [comment]
时隔多日，我终于知道我在哪写错了，我将C:\Users\dengx\.gradle的gradle.properties删除掉就可以了。。。。cry。。

**Comment by loveToMy** [comment]
> 时隔多日，我终于知道我在哪写错了，我将C:\Users\dengx.gradle的gradle.properties删除掉就可以了。。。。cry。。

强强强 这次踩坑下次就没有了
