### ISSUE TITLE
RNapp为什么使用UI Automator Viewer获取resource_id为空？该怎么解决？

### ISSUE THREAD

**Issue by lucky5678** [reactnativecn/react-native-website#202]
开发出的RNapp,想要使用appium自动化测试需要获取元素id,
结果使用 UI Automator Viewer获取resource_id为空？
该怎么解决？
谢谢有心人的回答~

**Comment by sunnylqm** [comment]
看起来不好解决  https://github.com/facebook/react-native/pull/18527

**Comment by lucky5678** [comment]
> 看起来不好解决 [facebook/react-native#18527](https://github.com/facebook/react-native/pull/18527)

谢谢~
