### ISSUE TITLE
Why PanResponder is not working on android? What needs to be done for it to work on android devices?(panResponder 在安卓上不生效)

### ISSUE THREAD

**Issue by lepus-esn** [reactnativecn/react-native-website#207]
## 问题的具体描述
-  我已经在苹果手机和模拟器上试过了，同一份代码在苹果上运行良好，但是安卓上不生效
-  没有报错
-  调试发现： 安卓上console.warn('start')并没有走到
    onStartShouldSetPanResponderCapture: (_e: any, _gestureState: any) => {
                console.warn('start');
                return true;
     },

## 代码如下： 
constructor(props: IProps) {
        super(props);
        this._onPanResponderGrant = this._onPanResponderGrant.bind(this);
        this._onPanResponderEnd = this._onPanResponderEnd.bind(this);
        this._onPanResponderMove = this._onPanResponderMove.bind(this);
        this.watcher = PanResponder.create({
            // 建立监视器
            onStartShouldSetPanResponderCapture: (_e: any, _gestureState: any) => {
                console.warn('start');
                return true;
            },
            onStartShouldSetPanResponder: (_e: any, _gestureState: any) => {
                console.warn('start1');
                return true;
            },
            onPanResponderGrant: this._onPanResponderGrant, // 按下
            onPanResponderMove: this._onPanResponderMove, // 移动
            onPanResponderEnd: this._onPanResponderEnd, // 结束
        });
    }

  render() {
return (
   <View> <View style={styles.rightNavigatorContainer}{...this.watcher.panHandlers}></View></View>
)
}

**Comment by explorefit** [comment]
我刚好相反，在android上正常使用，在ios上不能
