### ISSUE TITLE
RN 在android手机上调试运行正常，打包成发布包apk后，安装成功，点击运行闪退。求指教？

### ISSUE THREAD

**Issue by GXlaishengcai** [reactnativecn/react-native-website#208]
RN项目， 在android手机上调试运行正常，打包成发布包apk后，安装成功，点击运行闪退。求指教？
1.$ cd android
  $ ./gradlew assembleRelease
  打包成功。

2.$ npx react-native run-android --variant=release 运行安装也成功，但是点击图标运行就闪退。求解。。。？

**Comment by sunnylqm** [comment]
任意运行时的异常都会导致闪退，请输出adb logcat的日志才好分析问题

**Comment by vobear** [comment]
app使用过程中闪退99%都是程序异常导致的，可usb连接真机操作尝试复现。

**Comment by hongbobo614** [comment]
Js代码没有打包进去

**Comment by pisyell** [comment]
同样  0.67最新版 调试各种稳定 打包出来 就直接闪退
