### ISSUE TITLE
RN清除缓存的方式

### ISSUE THREAD

**Issue by chuhemiao** [reactnativecn/react-native-website#209]
## 目前使用react-native-http-cache 包
- 安装后，ios版（有[添加.a文件](http://facebook.github.io/react-native/docs/linking-libraries-ios.html)）一直报 `clearCache of undefined `错误，在`react-native-http-cache` 包下面也看到很多类似提问的问题，其中有一个说明`https://github.com/reactnativecn/react-native-http-cache/issues/36` 这个说明一些修改的办法，有试过 但是还是一直报`clearCache of undefined `

+ 请问可还有其他方式清除缓存？

**Comment by yz1311** [comment]
可以试下 https://github.com/yz1311/react-native-http-cache ，支持最新的RN版本

**Comment by xiao-shu-sheng** [comment]
我按照https://github.com/yz1311/react-native-http-cache 这个修改之后，iOS运行正常，Android报错：Could not initialize class com.google.common.collect.Ordering$ArbitraryOrderingHolder，请问，这个该怎么修改 @yz1311

**Comment by free-leaves** [comment]
这是我使用的版本
"@ant-design/react-native": "^4.0.5",
"@yz1311/react-native-http-cache": "^0.3.1",

**Comment by xiao-shu-sheng** [comment]
这是我使用的版本
"react": "16.13.1",
"react-native": "0.63.2",
"@yz1311/react-native-http-cache": "^0.3.1",

**Comment by yz1311** [comment]
你清空下缓存，用`assemblew installRelease`打包试下

我跟你用的RN是一样的版本，没问题的

**Comment by xiao-shu-sheng** [comment]
好的，谢谢，我现在打包试一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reactnativecn/react-native-website"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 下午5:29
收件人:&nbsp;"reactnativecn/react-native-website"<react-native-website@noreply.github.com&gt;;
抄送:&nbsp;"鬼谷子"<2418356743@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [reactnativecn/react-native-website] RN清除缓存的方式 (#209)





 
你清空下缓存，用assemblew installRelease打包试下
 
我跟你用的RN是一样的版本，没问题的

**Comment by free-leaves** [comment]
还是不行，我清空缓存之后还是失败了，这里是我的android配置，您看一下是不是我的配置有问题
MainApplication.java
import cn.reactnative.httpcache.HttpCachePackage;

protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          packages.add(new HttpCachePackage());
          return packages;
        }
android/app/build.gradle
dependencies {
   ...
   implementation project(':RCTHttpCache')
}

android/settings.gradle
include ':RCTHttpCache'
project(':RCTHttpCache').projectDir = new File(rootProject.projectDir, '../node_modules/@yz1311/react-native-http-cache/android')

**Comment by free-leaves** [comment]
我这里编译无法通过，一直报：Could not initialize class com.google.common.collect.Ordering$ArbitraryOrderingHolder @yz1311

**Comment by xiao-shu-sheng** [comment]
包的问题，下载的时候包没有下载完全，我重新清除缓存就好了。谢谢啦 @yz1311

**Comment by xiao-shu-sheng** [comment]
你好，我这边在打包时遇到一个问题，@yz1311/react-native-http-cache 一直无法link，这是它报的错误
![image](https://user-images.githubusercontent.com/23214175/95699751-ef474900-0c77-11eb-9a5d-60927bf9da4a.png)
下面是我重新修改的的配置：
MainApplication.java
import cn.reactnative.httpcache.HttpCachePackage;

build.gradle
dependencies {
   ...
  implementation project(':RCTHttpCache')   
}
settings.gradle

include ':RCTHttpCache'
project(':RCTHttpCache').projectDir = new File(rootProject.projectDir, '../node_modules/@yz1311/react-native-http-cache/android')
 缓存什么的都清理过了，在虚拟机上没有问题，连手机测试也没有问题了，但是在打包的时候一直无法link,希望您有空的话能抽空看一下，先谢过了
@yz1311

**Comment by yz1311** [comment]
你把报错文字发下吧，我这边看不到github传的图片，或者你用其他的图片源

**Comment by xiao-shu-sheng** [comment]
下面是报错的文件
Task :RCTHttpCache:verifyReleaseResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':RCTHttpCache:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/zq/.gradle/caches/transforms-2/files-2.1/a4acec3d7b0b9a5466832fdd5542584b/appcompat-1.0.2/res/values-v26/values-v26.xml:5:5-8:13: AAPT: error: resource android:attr/colorError not found.

**Comment by xiao-shu-sheng** [comment]
我不确定是不是里面的字体文件无法下载下来

**Comment by yz1311** [comment]
你试下0.3.2版本

**Comment by xiao-shu-sheng** [comment]
好的

**Comment by xiao-shu-sheng** [comment]
可以了，谢谢啦
