### ISSUE TITLE
get started文档 缺少yarn start步骤

### ISSUE THREAD

**Issue by CroMarmot** [reactnativecn/react-native-website#210]
## 搭建开发环境 文档缺少步骤 导致启动失败
- 报错 `unable to load script make sure you're either running a metro server...` 如图 [stackoverflow链接](https://stackoverflow.com/questions/55441230/unable-to-load-script-make-sure-you-are-either-running-a-metro-server-or-that-yo)
- "搭建环境中" 应该包含步骤`yarn start`或`npx react-native start` 见[英文文档](https://reactnative.dev/docs/environment-setup)的`step 1`, 但是[中文文档](https://reactnative.cn/docs/getting-started)漏掉了。
- 重现方法：按照中文文档描述的三个步骤操作即可重现

```
npx react-native init AwesomeProject
cd AwesomeProject
yarn android
```

## 完整的环境/版本信息
- 请在命令行的项目目录中运行`react-native info`命令，并将其输出结果粘贴到这里。

```
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 5.06 GB / 15.55 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 24, 26, 27, 28, 29
      Build Tools: 22.0.1, 23.0.3, 26.0.0, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
  npmGlobalPackages:
    *react-native*: Not Found
```
- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

无，默认上面三条命令即可

## 预期结果

- 请描述你觉得代码正常运行的情况应该是什么样子。

正常运行

**Comment by sunnylqm** [comment]
英文文档目前也不完整（之前是漏了yarn start这条常用命令的说明，现在倒是把更重要的android/ios命令漏了，step2哪里去了？看起来是markdown格式问题），这里等官方梳理好了我再补上。
yarn android/yarn ios会自动调用yarn start，所以正常情况下不会碰到这个问题

**Comment by CroMarmot** [comment]
我这边看上去是

`yarn start` = `npx react-native start`(package.json里) = `npm start`(英文文档step1)

`yarn android` = `npx react-native run-android`(package.json里 / 英文文档step2)

我这边不执行`yarn start`的话，终端输出`info Starting JS server...` 但是似乎并没有启动成功？（至少我`ps -aux | grep node`是没看到任何运行着的服务的 ），输出如下，这种情况在android上看会报错

![Screenshot from 2020-07-17 19-38-57](https://user-images.githubusercontent.com/24691835/87782556-51ed9c00-c865-11ea-9277-261e5a315cdd.png)

下面是执行了`yarn start`以后再执行`yarn android`的截图，这种情况是正常运行的。

![Screenshot from 2020-07-17 19-38-28](https://user-images.githubusercontent.com/24691835/87782559-531ec900-c865-11ea-8b6b-509fde07fd0a.png)

**Comment by CroMarmot** [comment]
我有怀疑过是不是 没全局装 `react-native`,就尝试了`yarn global add react-native-cli`。

但只用`yarn android`依然没有看到启动的node 服务

**Comment by sunnylqm** [comment]
`info Starting JS server...`就是尝试启动metro， 见 https://github.com/react-native-community/cli/blob/master/packages/platform-android/src/commands/runAndroid/index.ts#L104-L117
你这个确实是没有启动成功，但也没有看到报错，建议有空的话去这里汇报下  https://github.com/react-native-community/cli/issues
不应该全局安装react-native-cli，那个已经废弃了

**Comment by CroMarmot** [comment]
感谢

我去提了个issue,  https://github.com/react-native-community/cli/issues/1223

之前没翻源码，看起来是识别我的终端为`xterm-256color`，但是并不能直接掉起。

我用的是ubuntu 18.04.4 LTS 默认的terminal,应该是`gnome-terminal`（但硬编码改变量也没调用成功 似乎它也并不支持`-e`参数..），不知道其它系统会不会有类似的问题，而且目前它的终端输出中也没错误提示。感觉步骤中加个`yarn start`还是会保险一些。

**Comment by CroMarmot** [comment]
看起来官方团队有在跟踪, https://github.com/react-native-community/cli/issues/1223 , 似乎是跟terminal参数格式有关的问题, 但我本地环境和系统都升级了, 也没有使用RN很久了, 没有重现的环境, 先关闭Issue了.
