### ISSUE TITLE
Failed to load bundle(http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false) with error:(Could not connect to development server.

### ISSUE THREAD

**Issue by mayanliyanan** [reactnativecn/react-native-website#212]
ios mac 电脑按照官网步骤搭建完环境，从git克隆下项目，运行模拟器连接节点服务，服务器会退出，报错如下图 
![93029ED8-1078-43F2-ABED-B36C29143A04](https://user-images.githubusercontent.com/10249603/87873532-d7538680-c9f4-11ea-9667-b57f57d7b84f.png)

**Comment by sunnylqm** [comment]
贴一下package.json

**Comment by mayanliyanan** [comment]
> 贴一下package.json

![A2548010-731C-43E4-B87C-AFDCD9A8FA76](https://user-images.githubusercontent.com/10249603/87893057-4ec6fb80-ca71-11ea-96ae-aa2bffa22bd3.png)

**Comment by mayanliyanan** [comment]
这个就是package.json代码，用浏览器连接也会出现这个错误

**Comment by sunnylqm** [comment]
你这个环境有点奇怪，是从expo弹出的吗
你试着删掉lock文件和node_modules重新install
