### ISSUE TITLE
如何 import from 只有模块名，不带有路径

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#214]
**例如：**
// test.js
```
export default function () {
  console.log('foo');
}
```
该js 在项目多个地方被使用 不想要import * as from './test'; 如何才能 import * as from 'test'？

**Comment by sunnylqm** [comment]
这叫做使用绝对路径，最标准的做法是把它发布到npm。如果不想发布，不同的打包系统又有不同的做法。对于react native来说最简单的做法是
比如你有个目录test，在test目录下创建package.json，然后其中只放name字段
```
// package.json
{ "name": "test" }
```

然后在其他地方就可以直接引用test模块，例如
```
import test from 'test'; // 引用test/index.js
import testA from 'test/testA'; // 引用test/testA.js
```

**Comment by GWCodeN** [comment]
> 这叫做使用绝对路径，最标准的做法是把它发布到npm。如果不想发布，不同的打包系统又有不同的做法。对于react native来说最简单的做法是
> 比如你有个目录test，在test目录下创建package.json，然后其中只放name字段
> 
> ```
> // package.json
> { "name": "test" }
> ```
> 
> 然后在其他地方就可以直接引用test模块，例如
> 
> ```
> import test from 'test'; // 引用test/index.js
> import testA from 'test/testA'; // 引用test/testA.js
> ```

谢谢大佬 懂了

**Comment by GWCodeN** [comment]
> 这叫做使用绝对路径，最标准的做法是把它发布到npm。如果不想发布，不同的打包系统又有不同的做法。对于react native来说最简单的做法是 比如你有个目录test，在test目录下创建package.json，然后其中只放name字段
> 
> ```
> // package.json
> { "name": "test" }
> ```
> 
> 然后在其他地方就可以直接引用test模块，例如
> 
> ```
> import test from 'test'; // 引用test/index.js
> import testA from 'test/testA'; // 引用test/testA.js
> ```

在.tex 中无法识别 有办法解决么
<img width="659" alt="image" src="https://user-images.githubusercontent.com/25916259/167528536-f2d117a5-e32c-40a7-a0dc-93930a6b810f.png">
