### ISSUE TITLE
编译IOS时出现'React/RCTImageView.h' file not found的错误

### ISSUE THREAD

**Issue by terius** [reactnativecn/react-native-website#218]
大佬们我在VMware上建立的MacOs平台上用xcode编译React Native项目时用Product->Archive菜单编译时老是显示“'React/RCTImageView.h' file not found”，搜谷歌也搜不到什么解决方案，求大佬们帮帮忙啊，，万谢了~~~，以下是截图：
![image](https://user-images.githubusercontent.com/7608809/88471374-4f610580-cf3b-11ea-8698-483683245ebb.png)

**Comment by 25878734272** [comment]
没错我也是这样的  新手

**Comment by sunnylqm** [comment]
https://github.com/software-mansion/react-native-screens/issues/415
