### ISSUE TITLE
布局问题

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#219]
**代码**
![47942E28-4BD8-4E31-B7F9-9867925BCA45](https://user-images.githubusercontent.com/25916259/88657436-7fa7d000-d104-11ea-88b6-9a0be87d6579.png)
**效果**
<img width="263" alt="5FA87D4F-5261-4201-93F8-9E72FEE68535" src="https://user-images.githubusercontent.com/25916259/88657490-98b08100-d104-11ea-9954-90eaf8bcef5e.png">
**问题**
1、为什么V1宽度会自动布满界面，而高度是自适应？
2、有没有办法让V1宽度也自适应？

**Comment by sunnylqm** [comment]
无样式的View好像默认有 { alignItems: 'stretch' }

**Comment by GWCodeN** [comment]
> 无样式的View好像默认有 { alignItems: 'stretch' }

谢谢大佬 V1加上{alignSelf: 'flex-start'} 可以了
