### ISSUE TITLE
项目添加装饰器后，报Can't find variable: require

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#220]
**package.json**
<img width="342" alt="image" src="https://user-images.githubusercontent.com/25916259/88872983-22b83100-d24e-11ea-9114-6ef5c10048d1.png">
**babel.config.js**
<img width="512" alt="image" src="https://user-images.githubusercontent.com/25916259/88873038-4f6c4880-d24e-11ea-87da-34b2065fb568.png">

**Comment by sunnylqm** [comment]
reset cache试下
```
yarn react-native start --reset-cache
```

**Comment by GWCodeN** [comment]
> reset cache试下
> 
> ```
> yarn react-native start --reset-cache
> ```

还是报Can't find variable: require 昨天装完一切正常 今早就不行了

**Comment by GWCodeN** [comment]
### 其他
同时会有提示：
`WARNING: Logging before InitGoogleLogging() is written to STDERR`
`Attempting to call JS function on a bad application bundle: RCTLog.logIfNoNativeHook()`
另外发现，开启另外react-native0.63.2 的项目运行成功然后 再跑这个项目 正常了 然后重启电脑又报错了
### 解决方案
不装了 卸载然后 yarn react-native start --reset-cache
安装装饰器本来就为了 Mobx  用babel-preset-mobx来代替了
