### ISSUE TITLE
Installing required CocoaPods dependencies

### ISSUE THREAD

**Issue by lovesL** [reactnativecn/react-native-website#222]
请按以下格式提供问题的相关信息。
请问 有没有什么比较好的方法在安装CocoaPods 不会直接失败
![image](https://user-images.githubusercontent.com/27960630/89252977-e457b300-d64d-11ea-9e23-d914231c2b1c.png)
我已经科学上网了  开启了全局 还是这样 
## 问题的具体描述
- 如果是安装过程中的问题，请再三确认你有使用稳定的翻墙工具，且翻墙工具对命令行有生效（如开启全局模式等等）
- 请说明具体操作步骤和现象（例如执行什么命令，或者点击哪里，出现了什么异常现象或错误信息）
- 请尽量配上相关报错截图
   - 如果设备上有红屏报错请直接截图
   - 如果命令行有报错请直接截图
   - 警告(warning)一般不用管
   - 如果设备上看不到报错，请先尝试[调试模式](https://reactnative.cn/docs/debugging)。
   - 如果是发行版本无法调试，对于安卓设备请使用[adb logcat命令](https://developer.android.google.cn/studio/command-line/logcat)来捕获日志并粘贴到这里。iOS设备查看日志的[一些方法](https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a)。
- 请尽量配上相关代码截图

## 请描述完整的环境/版本信息
- 请在命令行的项目目录中运行`react-native info`命令，并将其输出结果粘贴到这里。
- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

**Comment by sunnylqm** [comment]
你手动执行pod install看下有什么报错

**Comment by lovesL** [comment]
@sunnylqm  
![image](https://user-images.githubusercontent.com/27960630/89253532-7a400d80-d64f-11ea-8adf-21b71bced142.png)
![image](https://user-images.githubusercontent.com/27960630/89253546-8330df00-d64f-11ea-9139-9fe5051ca7fa.png)
![image](https://user-images.githubusercontent.com/27960630/89253555-8af08380-d64f-11ea-8daa-67114822a6f5.png)

**Comment by lovesL** [comment]
@sunnylqm  似乎没有报错 但是pod  install  执行完 输出这些就没 了

**Comment by sunnylqm** [comment]
试下
sudo xcode-select --switch /Applications/Xcode.app

**Comment by lovesL** [comment]
执行了 但是没什么反应

**Comment by lovesL** [comment]
![image](https://user-images.githubusercontent.com/27960630/89254003-b58f0c00-d650-11ea-9577-0d1a96530f7d.png)

**Comment by sunnylqm** [comment]
没反应是对的啊，执行完了再回头重试

**Comment by lovesL** [comment]
重试什么 重新init  项目？

**Comment by sunnylqm** [comment]
你上面不是在pod install吗？重新pod install啊



---Original---

**Comment by lovesL** [comment]
如果这pod  install 执行成功了?项目就构建完成了么    是不是还有重新 init 一下啊

**Comment by sunnylqm** [comment]
pod install就是安装pod依赖，依赖安装完了才可以开始构建（xcode运行，或者运行yarn ios命令）

重新init就是另外一个新的项目了啊

**Comment by lovesL** [comment]
但是 安装到  CocoaPods这步就失败了 项目似乎没有构建完成吧 RN 的一些其他依赖还没装上

**Comment by sunnylqm** [comment]
所以让你重新执行pod install啊

**Comment by GWCodeN** [comment]
是不是CocoaPods 版本低了
