### ISSUE TITLE
刚接手的iOS项目接入的RN，项目运行一直打印以下log Socket SO_ERROR [61: Connection refused]

### ISSUE THREAD

**Issue by a758209678** [reactnativecn/react-native-website#223]
![image](https://user-images.githubusercontent.com/17403010/89265308-dbbfa680-d666-11ea-9b18-e5bc8a98d3f8.png)

**Comment by sunnylqm** [comment]
这个bug是rn0.61版本修复的
如果不能升级rn，可以尝试用yarn resolutions升级react-devtools-core到3.6.2
