### ISSUE TITLE
关于内存释放的问题

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#224]
在一个页面中使用fetch请求，数据还未返回的时候。就退出了页面 ，等有数据返回时就会报下面的警告
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`
这怎么解决？

**Comment by sunnylqm** [comment]
没有什么实际影响，可以忽略

**Comment by GWCodeN** [comment]
> 没有什么实际影响，可以忽略

好的，谢谢大佬。怎么晚还能看到大佬的身影👍
