### ISSUE TITLE
请问开发Android TV, 使用TextInput, 是否可以根据遥控器上的方向键，如上下左右来聚焦。

### ISSUE THREAD

**Issue by Shuo-Mr** [reactnativecn/react-native-website#225]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 你好，现在需要在 **安卓TV** 开发APP，使用TextInPut输入一串值
- TV端是无法触屏的，也就是无法根据点击来进行聚焦。所以想询问是否可以**根据遥控器的上下左右按键以及确认来聚焦**
-- 我观察到，遥控器的上下左右是对应电脑键盘的上下左右，而如Button组件是可以通过键盘的上下左右来聚焦，而TextInput无法获得聚焦点
-- 官网文档里也没具体的说法，现在我采取的是进入即聚焦，但是也是一次性而已，显然不符合实际情况。

## 请描述完整的环境/版本信息
- react-native 版本0.63.2
- 运行环境，android TV
- 未实际真机测试

## 预期结果
- 可以通过遥控器的上下按钮来聚焦TextInput。

感谢解答！

**Comment by sunnylqm** [comment]
这个坑似乎还没人填，看到有人提到个workaround，你看看能用不
https://github.com/facebook/react-native/pull/16500#issuecomment-629285638

**Comment by Shuo-Mr** [comment]
多谢，替代方案可以实现，使用touchable元素来传递聚焦。尽管这个坑这么久没人修。
