### ISSUE TITLE
关于 throw 的问题

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#226]
### 情况
在调用图1中test2方法时报错 ，明明已经使用了trycatch，但是还是会如图2的提示和A1处的catch log打印。 定位错误，发现有手动throw的代码如图3。
**图1：**
<img width="455" alt="image" src="https://user-images.githubusercontent.com/25916259/89497947-e6f20e00-d7ef-11ea-8a6d-8bb9299fb6e1.png">
**图2：**
<img width="318" alt="image" src="https://user-images.githubusercontent.com/25916259/89498153-48b27800-d7f0-11ea-9a10-95b4ca7d38d8.png">
**图3：**
<img width="609" alt="image" src="https://user-images.githubusercontent.com/25916259/89498215-6b449100-d7f0-11ea-8f2c-664be3518e33.png">
### 问
1、以上情况什么怎么回事？按我的理解不应该会有图2的提示  
2、如果不trycatch 直接throw error  程序好像也不会崩溃 这是什么情况？

**Comment by sunnylqm** [comment]
1、你需要找些async/await和promise的文章系统学习下，这里我没法给你细讲
2、开发模式下会被LogBox全局catch，release版就会崩溃了

**Comment by guoyw** [comment]
> 1、你需要找些async/await和promise的文章系统学习下，这里我没法给你细讲
> 2、开发模式下会被LogBox全局catch，release版就会崩溃了
大概先trycatch， 后throw ，所以要在图3处trycatch才没问题 ,这样理解应该没错吧 。
图3的代码来之 @microsoft/signalr   ，任何JavaScript的代码，放到React-Native是会存在兼容性问题？

**Comment by GWCodeN** [comment]
> 1、你需要找些async/await和promise的文章系统学习下，这里我没法给你细讲
> 2、开发模式下会被LogBox全局catch，release版就会崩溃了

大概先trycatch， 后throw ，所以要在图3处trycatch才没问题 ,这样理解应该没错吧 。
图3的代码来之 @microsoft/signalr ，任何JavaScript的代码，放到React-Native是会存在兼容性问题？

**Comment by sunnylqm** [comment]
1、有问题，你没有区分同步和异步
2、https://reactnative.cn/docs/javascript-environment

**Comment by GWCodeN** [comment]
> 1、有问题，你没有区分同步和异步
> 2、https://reactnative.cn/docs/javascript-environment

```
new Promise((resolve, reject) => {
      setTimeout(() => {
        try {
          var error = new Error('error');
          reject(error)
          throw error
        } catch (error) {
          console.log(error)
        }
      }, 1000);
    })
      .then(() => { })
      .catch(error => console.log(error))
```
简化一下大概这样 ， 试了没问题啊

**Comment by GWCodeN** [comment]
https://segmentfault.com/q/1010000011279913
