### ISSUE TITLE
defaultSource 在 Android 的 debug, release 版本上本属性不会生效

### ISSUE THREAD

**Issue by jiyunkeji** [reactnativecn/react-native-website#228]
defaultSource 在 Android 的 debug, release 版本上本属性不会生效.文档说在“在 Android 的 debug 版本上本属性不会生效（但在 release 版本中会生效）”是不是有歧义啊？
[http://www.react-native.cn/docs/image#defaultsource](url)（0.62.2版本的组件页面打不开，就用这个啦）
## 问题的具体描述
在 Android 的  debug, release 版本上本属性不会生效。
Image图片加载失败onError都不回调呢？

## 请描述完整的环境/版本信息
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2

**Comment by sunnylqm** [comment]
没明白是什么问题？

**Comment by jiyunkeji** [comment]
> 没明白是什么问题？
图片没加载出来，我设置defaultSource 在android debug, release 版本上都不显示。
<img width="336" alt="image" src="https://user-images.githubusercontent.com/50569560/89612867-74e2fd00-d8b3-11ea-843d-c02d9b6633e3.png">

然后我想不显示的话，onError会报错吧？Image图片加载失败onError都不回调呢？

**Comment by sunnylqm** [comment]
defaultSource官方原版文档是这么写的，我没有验证过。如果不符合预期的话，建议去官方的repo提个issue报告
onError我自己用是可以正常触发的

**Comment by jiyunkeji** [comment]
> defaultSource官方原版文档是这么写的，我没有验证过。如果不符合预期的话，建议去官方的repo提个issue报告
> onError我自己用是可以正常触发的

<img width="462" alt="image" src="https://user-images.githubusercontent.com/50569560/89613557-174fb000-d8b5-11ea-99db-fcba83de210f.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/50569560/89613568-1f0f5480-d8b5-11ea-8616-115900ce8c32.png">
刷了好多回了，不调呢？android怎么网络加载失败怎么设置默认图片呢？

**Comment by sunnylqm** [comment]
没有调就说明没有error啊
