### ISSUE TITLE
Websocket Handshake failed

### ISSUE THREAD

**Issue by vobear** [reactnativecn/react-native-website#229]
请按以下格式提供问题的相关信息。

## 问题的具体描述
在安卓7.0握手失败，安卓7.1.1、 安卓8.0、 安卓9.0和安卓10都能正常连接,同一套websocket服务在
微信小程序正常(主要是安卓7.0也正常) ,现在怀疑是android 7.0对TSL1.2不支持（wss证书版本是1.2），请问下可能原因有哪些? websocket是php+ swoole搭建的。

## 实际运行结果截图

![59080d88bf717a7672bc4d316e3c641](https://user-images.githubusercontent.com/45116869/89616566-30f3f600-d8bb-11ea-87c3-1c8a5a1657e7.png)

**Comment by sunnylqm** [comment]
https://stackoverflow.com/a/42047877

**Comment by vobear** [comment]
> https://stackoverflow.com/a/42047877

感谢，我尝试下。
