### ISSUE TITLE
Android ReactInstanceManager单例问题

### ISSUE THREAD

**Issue by MuchenXmy** [reactnativecn/react-native-website#230]
一个ReactInstanceManager实例对应多个页面， 如果某个页面的bundle加载或JS运行发生异常，这种情况ReactInstanceManager中的CatalystInstance实例被destroy掉。源码如下：
private void onNativeException(Exception e) {
    mNativeModuleCallExceptionHandler.handleException(e);
    mReactQueueConfiguration
        .getUIQueueThread()
        .runOnQueue(
            new Runnable() {
              @Override
              public void run() {
                destroy();
              }
            });
  }
那对已经渲染的页面也会有影响，比如ReactRootView刷新时UIManger检查CatalystInstance状态，如果destroy会抛出异常。请教一下该怎么去处理这个问题

**Comment by sunnylqm** [comment]
全局捕获异常即可，error boundary或者ExceptionHandler都可以
https://reactjs.org/docs/error-boundaries.html
https://github.com/a7ul/react-native-exception-handler

**Comment by MuchenXmy** [comment]
> 全局捕获异常即可，error boundary或者ExceptionHandler都可以
> https://reactjs.org/docs/error-boundaries.html
> https://github.com/a7ul/react-native-exception-handler

我通过这种方式设置的全局异常捕获：

  public ReactInstanceManagerBuilder setNativeModuleCallExceptionHandler(
      NativeModuleCallExceptionHandler handler) {
    mNativeModuleCallExceptionHandler = handler;
    return this;
  }

但是当捕获到全局异常时，只能退出重启app吗？ 有没有方式，可以恢复ReactInstanceManager 的状态，能够继续正常使用RN项目。在发生异常后，我尝试recreateReactContextInBackground  重新创建ReactContext，但是会抛出异常。

**Comment by sunnylqm** [comment]
recreateReactContextInBackground可以用的，不知道你碰到什么异常

不过用我上面提到的两个方式都可以防止instancemanager崩溃  没有必要在原生端去处理和重启啊

**Comment by sunnylqm** [comment]
我建议用https://github.com/a7ul/react-native-exception-handler  就省得自己处理了

**Comment by MuchenXmy** [comment]
> recreateReactContextInBackground可以用的，不知道你碰到什么异常
> 
> 不过用我上面提到的两个方式都可以防止instancemanager崩溃 没有必要在原生端去处理和重启啊

recreateReactContextInBackground会重新runJSBundle，同时会遍历重新绑定ReactRootView，绑定时bundle还没有加载完或只加载了公共包 就会报异常。所以不能用，就无解了。
 我们这个项目主要是做的动态模块化，刚接入，所以会在原生端做一些兜底逻辑。 可能我要换个思路，考虑在RN代码里面处理了
