### ISSUE TITLE
关于类拓展问题

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#231]
### 描述
例如
```
Array.prototype.remove = function (val) {
    var index = this.indexOf(val);
    if (index > -1) { this.splice(index, 1); }
}
```
项目中有多个地方用到 不想每个js中都写一遍 怎么封装以达到：

```
//a.js
var test = [1,2,3]
test.remove(2)
```
在React Native 中有没有处理这种情况的方式？

**Comment by sunnylqm** [comment]
react native就是js  当然也可以用这样的方式（虽然不推荐）

**Comment by GWCodeN** [comment]
> react native就是js 当然也可以用这样的方式（虽然不推荐）

a.js 、 b.js 都要用到这个方法 我能不能 把这个方法
```
Array.prototype.remove = function (val) {
    var index = this.indexOf(val);
    if (index > -1) { this.splice(index, 1); }
}
```
写到 c.js 中 
在 a、b中导入c 。 a、b 中就可以直接
```
var test = [1,2,3]
test.remove(2)
```

**Comment by GWCodeN** [comment]
> react native就是js 当然也可以用这样的方式（虽然不推荐）

我现在查到 都是在哪个文件中用就在哪个文件写  这样就重复了

**Comment by sunnylqm** [comment]
你修改prototype是全局的，不需要引入

**Comment by GWCodeN** [comment]
> 你修改prototype是全局的，不需要引入

这里产生新的疑问：
```
//a.js
var test = [1,2,3]
test.remove(2)
console.log(test);
```

```
//b.js
Array.prototype.remove = function (val) {
    var index = this.indexOf(val);
    if (index > -1) { this.splice(index, 1); }
}
```
a push b    , 按我的理解对象b是后生成的Array 还有没有 remove() 方法 。 但是代码没有问题正常，结果正确。难道是import 的时候就将Array 与remove 关联上了？

**Comment by sunnylqm** [comment]
没错  import就直接执行  执行就直接修改了所有array的原型
正由于有着这样的副作用，所以不建议做类似这样的全局操作，会导致其他人无法知道副作用在哪里引入

**Comment by GWCodeN** [comment]
> 没错 import就直接执行 执行就直接修改了所有array的原型
> 正由于有着这样的副作用，所以不建议做类似这样的全局操作，会导致其他人无法知道副作用在哪里引入

明白了 谢谢大佬
