### ISSUE TITLE
yarn android报错

### ISSUE THREAD

**Issue by fanrax** [reactnativecn/react-native-website#232]
![image](https://user-images.githubusercontent.com/39158061/90210778-8717ea80-de21-11ea-9bbe-11056a006618.png)
![image](https://user-images.githubusercontent.com/39158061/90210828-b0d11180-de21-11ea-9d77-7430d75ebf10.png)
![image](https://user-images.githubusercontent.com/39158061/90210857-bfb7c400-de21-11ea-860c-7d112e010f29.png)
执行的这个java报错是为什么

**Comment by sunnylqm** [comment]
很明显  翻墙问题啊
![image](https://user-images.githubusercontent.com/615282/90211500-6f416600-de23-11ea-941f-3ade23bfcbb2.png)

**Comment by fanrax** [comment]
具体要怎么解决呢？  我现在打开翻墙软件设置代理或者不打开翻墙软件关闭代理  然后yarn andriod 都是报上面的错误

**Comment by sunnylqm** [comment]
不行就换咯

**Comment by fanrax** [comment]
解决了   主要是我的本地代理没配置到sdk上面  然后导致sdk下载文件出错  执行不了
![image](https://user-images.githubusercontent.com/39158061/90312750-9427fd00-df39-11ea-8a29-c7bf22d07980.png)

![image](https://user-images.githubusercontent.com/39158061/90312771-bfaae780-df39-11ea-8ecc-be9157ba7723.png)
然后点击check connection  如果是success 那就没问题了  前提是你所有的环境都配置好了

**Comment by fanrax** [comment]
不好意思现在才关这个issue
