### ISSUE TITLE
Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

### ISSUE THREAD

**Issue by YfreeFly** [reactnativecn/react-native-website#234]
### Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
新创建的RN项目运行没有问题，我只要在入口文件index.js或者App.js中修改代码之后，重新运行就会报错。
之后我再重新创建一个RN项目就没有问题了。
尝试过一次创建多个RN项目，然后修改一个项目的入口文件之后，出现上面的错误之后；
我再次运行第二个项目就出现相同的项目，第二个项目没有任何改动。

### 库的版本都是最新的，最近创建的RN项目
<img width="378" alt="截屏2020-08-19 上午9 38 40" src="https://user-images.githubusercontent.com/23369494/90607789-4ad6f680-e234-11ea-9c61-7e0c680b256b.png">

**Comment by sunnylqm** [comment]
packager窗口在运行吗  截个图

**Comment by YfreeFly** [comment]
<img width="949" alt="截屏2020-08-19 下午4 56 56" src="https://user-images.githubusercontent.com/23369494/90614264-04d26080-e23d-11ea-9c58-6cd07ea77423.png">
有运行的

**Comment by sunnylqm** [comment]
有开什么全局代理吗

**Comment by YfreeFly** [comment]
开的有网络代理，但是应该不影响。在相同网络环境下是可以运行成功的，之后就不行了。
还会报下面这个错误，按照网上的办法，清除yarn和npm的缓存，重新安装依赖包，也不行。
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening skill_assessment.xcworkspace. Run CLI with --verbose flag for more details.

**Comment by sunnylqm** [comment]
1. 网络代理是有可能影响的
2. 这个报错没有具体信息，需要用xcode来运行查看具体错误

**Comment by YfreeFly** [comment]
找到问题了，我使用热点就可以了，是网络代理的问题，谢谢

**Comment by sunnylqm** [comment]
环境配置好之后就可以把代理关掉了，编译运行时并不需要外网
