### ISSUE TITLE
andriod打包后图片无法显示，测试正常显示

### ISSUE THREAD

**Issue by Bull778** [reactnativecn/react-native-website#235]

**Comment by sunnylqm** [comment]
远程图片的话Android9以上默认要求https，否则需要申明android:usesCleartextTraffic="true"

**Comment by Bull778** [comment]
本地项目里的图片，`<Image source={require('./assets/green.png')} style={{ width: 60, height: 60 }} />`

**Comment by Bull778** [comment]
真机测试，一开始无法显示，修改样式就显示

**Comment by sunnylqm** [comment]
rn版本多少

**Comment by Bull778** [comment]
"react": "16.13.1",
"react-native": "0.63.2",

**Comment by Bull778** [comment]
图片是在高德地图基础上的一个标记点

**Comment by sunnylqm** [comment]
那是高德地图的问题
https://github.com/qiuxiang/react-native-amap3d/issues/411

**Comment by Bull778** [comment]
好的，谢谢啦
