### ISSUE TITLE
iOS真机运行app后闪退

### ISSUE THREAD

**Issue by LTYZHYH** [reactnativecn/react-native-website#239]
刚开始接触react-native，拉取了一个之前的rn项目，能够安装在真机上，但一运行就会闪退。以下是控制台报错：
![B62C3BAE-2279-40F6-A1DA-367FF12E23B5](https://user-images.githubusercontent.com/44766993/91001007-2ea0d400-e5fd-11ea-8f1b-98b1d40a30ed.png)

环境/版本信息如下：
![image](https://user-images.githubusercontent.com/44766993/91001245-bedf1900-e5fd-11ea-8cc4-ff72bfbd00bf.png)

![image](https://user-images.githubusercontent.com/44766993/91001269-d4ecd980-e5fd-11ea-8e5e-ccd2da74ff9d.png)

想问问大家怎么解决这个问题？谢谢各位了🙏

**Comment by sunnylqm** [comment]
你这有具体的js报错啊
![image](https://user-images.githubusercontent.com/615282/91001909-ad970c00-e5ff-11ea-81d1-b9e23e372c38.png)
什么地方调用了Platform.constants.reactNativeVersion
但Platform或constants为空（对应的原生模块有问题）

**Comment by LTYZHYH** [comment]
> 你这有具体的js报错啊 什么地方调用了Platform.constants.reactNativeVersion 但Platform或constants为空（对应的原生模块有问题）
> ![图片](https://user-images.githubusercontent.com/615282/91001909-ad970c00-e5ff-11ea-81d1-b9e23e372c38.png)

RCTPlatform.m文件中调用的reactNativeVersion
![image](https://user-images.githubusercontent.com/44766993/91012143-31f58900-e618-11ea-977a-e4cb9611133f.png)
RCTVersion.m文件中调用的RCTGetReactNativeVersion
![image](https://user-images.githubusercontent.com/44766993/91012366-90bb0280-e618-11ea-8bd3-7b9a0a9facc2.png)

**Comment by sunnylqm** [comment]
0.59.2里并没有Platform.constants.reactNativeVersion这种用法，而是单独的PlatformConstants 
https://github.com/facebook/react-native/blob/v0.59.2/Libraries/Core/ReactNativeVersionCheck.js#L29
，不知道你从哪看来的
