### ISSUE TITLE
建议在run-android成功后再尝试使用 Android Studio 启动。怎么在studio里面启动啊

### ISSUE THREAD

**Issue by 2575829997** [reactnativecn/react-native-website#241]

**Comment by sunnylqm** [comment]
用android studio打开android目录（注意是android目录，不是项目目录）
等他gradle sync完成（几分钟到十几分钟不等，右下角有进度提示），如果sdk、模拟器什么的都配置好了，运行按钮会自动亮起，点击后即开始编译、启动模拟器，安装运行

**Comment by dingmh** [comment]
请问打开Android目录后，AS 直接报CreateProcess error=2, 系统找不到指定的文件。 gradle并没有进行。这个有遇到的嘛
