### ISSUE TITLE
运行后，手机红屏报错unexpected token ‘？’unexpected token ‘？’no stack

### ISSUE THREAD

**Issue by my-code-store** [reactnativecn/react-native-website#242]
react-native，创建项目完成之后可以运行！手机连上电脑，安装app之后报错，但是控制台未打印任何错误！
报错图片---
![image](https://user-images.githubusercontent.com/58247445/91857286-4e3d9980-ec9a-11ea-8c45-4c766ab9b05f.png)
控制台图片---

![image](https://user-images.githubusercontent.com/58247445/91857412-762cfd00-ec9a-11ea-8dd4-4a4412f637a6.png)

**Comment by ligengithub** [comment]
我也遇到这个问题，重新安装了node 重新建项目，都有这个问题

**Comment by ligengithub** [comment]
请问楼主解决了嘛？

**Comment by my-code-store-rice** [comment]
没有,有没有大佬出来提供一个解决方案?

**Comment by sunnylqm** [comment]
贴一下基本的环境信息（npx react-native info)
以及是否使用什么babel插件

**Comment by baiyingbin** [comment]
有没有解决方案，已经重新安装了好几遍，错误很莫名其妙
