### ISSUE TITLE
FlatList绝对定位后，覆盖在scrollView上面，无法触发滚动

### ISSUE THREAD

**Issue by Shuo-Mr** [reactnativecn/react-native-website#244]
## 问题的具体描述
- FlatList绝对定位后，覆盖在scrollView上面，无法触发滚动
- FlatList没有与scrollView嵌套。
- 我了解到FlatList绝对不能放在scrollView里面，所以我将其抽出来，同时将FlatList绝对定位后与TextInput组合来生成下拉搜索框
- 当FlatList绝对定位后，覆盖到scrollView上面，滚动事件就被scrollView拦截了，只触发scrollView的滚动事件。
- 在我调试中，在没有覆盖到scrollView视图的边缘，是可以将FlatList进行滚动的，但是只是边缘。
- 我觉得这可能可以根据样式来解决，或者是增加FlatList权重之类的，但是我不清楚具体如何实现。
- 如图所示
![image](https://user-images.githubusercontent.com/50469430/92062800-22bacc00-edcc-11ea-9514-631a0b1da4f6.png)

## 请描述完整的环境/版本信息
    "react": "16.13.1",
    "react-native": "0.63.2", 

## 预期结果
- 实现下拉搜索框，且FlatList绝对定位，不撑开实际内容。

谢谢。

**Comment by sunnylqm** [comment]
可以尝试在列表弹出后把scrollview给disable掉？

**Comment by sunnylqm** [comment]
不过这种交互问题很多的，一般这种搜索列表还是建议跳到一个单独的页面进行

**Comment by Shuo-Mr** [comment]
嗯，主要是类似于管理端的页面，且是平板的横屏应用，所以单独一个页面会有些奇怪，不过也可以当做一种方案

**Comment by Shuo-Mr** [comment]
我了解到了此问题的原因了，是由于绝对定位后，子容器不会超过父容器的zindex值，所以FlatList始终在scrollView之下，因为scrollView是与FlatList的祖先同级。
![image](https://user-images.githubusercontent.com/50469430/92071361-1725d000-ede1-11ea-9e93-cf2d459f553e.png)
上图可以看出，scrollView里的图片都能盖住FlatList。
应该是这个原因。

**Comment by wanxue0804** [comment]
@Shuo-Mr 
请问下如何解决层级问题的 我现在也有个需求 
一个表格 左侧固定 右侧滚动 每行点击后会展开操作按钮 我的操作按钮覆盖在scrollview上无法操作

**Comment by Shuo-Mr** [comment]
> @ Shuo-Mr
> 请问下如何解决层级问题的我现在也有个需求
> 一个表格正面固定滚动滚动每行单击后会展开操作按钮我的操作按钮覆盖在滚动视图上无法操作

嘿，有代码片段么，我后面取消了原本的设计方式，因为我觉得那的确很反人类（代码），我之前了解过这样的问题，你看你的操作按钮的父级的宽高是否拥有以及z-index是否高于scrollview，重要原因应该是父级的原因而导致操作按钮无法触发。

![image](https://user-images.githubusercontent.com/50469430/101116625-784b8280-3620-11eb-9f56-e63945ee8cf2.png)

**Comment by Shuo-Mr** [comment]
> @Shuo-Mr
> 请问下如何解决层级问题的 我现在也有个需求
> 一个表格 左侧固定 右侧滚动 每行点击后会展开操作按钮 我的操作按钮覆盖在scrollview上无法操作

嘿，有代码片段么，我后面取消了原本的设计方式，因为我觉得那的确很反人类（代码），我之前了解过这样的问题，你看你的操作按钮的父级的宽高是否拥有以及z-index是否高于scrollview，重要原因应该是父级的原因而导致操作按钮无法触发。
![program](https://user-images.githubusercontent.com/50469430/101116717-9e712280-3620-11eb-8165-1b9ca874ba12.png)

**Comment by Shuo-Mr** [comment]
@wanxue0804 如上图，这样也会导致无法触发

**Comment by wanxue0804** [comment]
> @wanxue0804 如上图，这样也会导致无法触发

是的 我的代码就是跟上述图片展示一样的
[代码片段](https://snack.expo.io/wk77RBBWS)

这种需求应该比较常见 可是我现在就是无法点击，不知如何是好，以下是需求场景
![图片](https://user-images.githubusercontent.com/35684234/101118006-34a64800-3623-11eb-9a9f-d6ebd7cedf46.png)

**Comment by Shuo-Mr** [comment]
@wanxue0804 
如代码片段那样子，的确无法触发right中区域的按钮，原因在于你的left只占左边屏幕，你的按钮区域溢出了。这个是底层的问题，之前在哪看到一篇文，好像是react-native官网有人写的一个分支, 说有解决这个问题，具体地址我也找不到了，不过据我看的介绍，虽然修复了，但是可能会出想一些不可预料的错误，如点击贯穿，具体我没试过，无法论证。
![image](https://user-images.githubusercontent.com/50469430/101120995-f82a1a80-3629-11eb-957b-c0ae0281ae37.png)

这样那种结构我也无法解决。重点就在于，子容器超出父容器所属于宽高。


至于你这种情况，我观看场景，应该是买卖和行情这两个按钮是吧。但是貌似没有所诉的按钮区域属于left的情况。难不成不是一行股票代码属于一列吗？
如果换种思路，点击每个列表中的一项，然后显示买卖行情的话，直接在其item下方撑开其区域不就可以？

**Comment by Shuo-Mr** [comment]
如代码片段那样子，的确无法触发right中区域的按钮，原因在于你的left只占左边屏幕，你的按钮区域溢出了。这个是底层的问题，之前在哪看到一篇文，好像是react-native官网有人写的一个分支, 说有解决这个问题，具体地址我也找不到了，不过据我看的介绍，虽然修复了，但是可能会出想一些不可预料的错误，如点击贯穿，具体我没试过，无法论证。
![2](https://user-images.githubusercontent.com/50469430/101121767-e8133a80-362b-11eb-8ad1-35c688c6dd04.png)


这样那种结构我也无法解决。重点就在于，子容器超出父容器所属于宽高。

至于你这种情况，我观看场景，应该是买卖和行情这两个按钮是吧。但是貌似没有所诉的按钮区域属于left的情况。难不成不是一行股票代码属于一列吗？
如果换种思路，点击每个列表中的一项，然后显示买卖行情的话，直接在其item下方撑开其区域不就可以？

**Comment by Shuo-Mr** [comment]
@wanxue0804

**Comment by wanxue0804** [comment]
> @wanxue0804

我的需求是左右滚动的时候第一列固定 上下滚动的时候头部固定，因此同一只股票的数据（行数据）第一列 和 右侧滚动的是分开的要不然我无法固定第一列， 左右滚动的时候按钮是不会随之滚动的 所以我放在了第一列里面，我有尝试过将按钮放在右侧横跨到左侧，但是scrollview 应该有个overflow：hidden 无法横跨至左边。

当前的写法在ios上很正常，只是android会有上述讨论的异常，很苦恼
