### ISSUE TITLE
短视频拍摄剪辑上传播放大家采用的什么方案，类似抖音短视频，

### ISSUE THREAD

**Issue by ganshiqingyuan** [reactnativecn/react-native-website#245]
如题

**Comment by yz1311** [comment]
这个在原生也算难题，有第三方的付费sdk，可以封装下或者这个页面直接跳转到原生页面

**Comment by ganshiqingyuan** [comment]
> 这个在原生也算难题，有第三方的付费sdk，可以封装下或者这个页面直接跳转到原生页面

有免费sdk吗....

**Comment by ganshiqingyuan** [comment]
@yz1311

**Comment by yz1311** [comment]
那你直接在github上面找下吧或者看那种付费的是否有免费额度

**Comment by afeng159** [comment]
也想问下有什么方案

**Comment by ganshiqingyuan** [comment]
> 也想问下有什么方案

直接react-native-video 和 react-antive-camera 估计也能搞，，但是效果就没那么强大了

**Comment by ganshiqingyuan** [comment]
> 也想问下有什么方案

各个云平台的sdk也很贵，集成到rn中还不知道行不行，只能先camera组件搞起了
