### ISSUE TITLE
mac配置环境一直卡在最后一步。

### ISSUE THREAD

**Issue by lululuting** [reactnativecn/react-native-website#246]
![image](https://user-images.githubusercontent.com/26959652/92429570-ed93ec80-f1c4-11ea-883b-4decf3e4f769.png)
各位大佬这是为啥呀，这一步等了好久。梯子开了的

**Comment by sunnylqm** [comment]
看不出有什么问题，xcode能运行吗

**Comment by lululuting** [comment]
> 看不出有什么问题，xcode能运行吗

原来是梯子不够稳定，我重新按流程再来一次就可以了。。。
