### ISSUE TITLE
ScrollView 嵌套 FlatList 问题

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#248]
### 版本
"react-native": "0.63.2"
### 代码
```
 menuView = () => {
        var array = [1, 2]
        return <View style={{ flexDirection: 'row'}}>
            {array.map((item, index) => {
                return <TouchableOpacity key={index}  style={{ flex: 1, alignItems: 'center' }} >
                    <Text style={{ fontSize: 17, color:  '#737380' }}>{item}</Text>
                </TouchableOpacity>
            })}
        </View>
 }

 render() {
        return <View style={{ flex: 1, backgroundColor: '#fff' }}>
            {this.menuView()}
            <ScrollView  style={{ flex: 1 }}  horizontal>
                    <FlatList
                        style={{ width: DWidth/2, backgroundColor: '#fff' }}
                        data={[1]}
                        renderItem={()=><View style={{ height: 10, backgroundColor: 'red' }}></View>}
                        keyExtractor={(item, index) => index.toString()}
                    />
                    <View style={{ width: DWidth/2, backgroundColor: 'green' }}></View>
                </ScrollView>
        </View >
    }

```
### 问题
以上代码运行后FlatList无法滚动 ；当去掉menuView()中<Text>的fontSize或者添加height之后正常，请问这是怎么回事？

**Comment by yz1311** [comment]
可以滚动的前提是内容大于控件的高度，不要ScrollView套ScrollView(FlatList也是ScrollView)

**Comment by GWCodeN** [comment]
> 可以滚动的前提是内容大于控件的高度，不要ScrollView套ScrollView(FlatList也是ScrollView)

有两个问题。
1、我删除menuView() 中 text 的fontSize 属性就能正常滑动（或者给定height都可以滑动） ，不知道是bug，还是ScrollView添加ScrollView导致的。
2、我要实现左右滑动，左边右边都有个列表的样式（类似斗鱼首页这种）。这在React-Nation中要如何实现？

**Comment by yz1311** [comment]
我看不明白你下面为啥要嵌套ScrollView，上面的menuView是一个固定住的东西，跟下面的ScrollView无关

**Comment by GWCodeN** [comment]
> 我看不明白你下面为啥要嵌套ScrollView，上面的menuView是一个固定住的东西，跟下面的ScrollView无关

![Untitled](https://user-images.githubusercontent.com/25916259/93555496-b1247580-f9a8-11ea-95fc-c30ce877c57f.gif)
大概是这样

**Comment by yz1311** [comment]
https://github.com/ptomasroos/react-native-scrollable-tab-view

**Comment by GWCodeN** [comment]
> https://github.com/ptomasroos/react-native-scrollable-tab-view

好的 谢谢
