### ISSUE TITLE
不进行pod install该如何运行项目

### ISSUE THREAD

**Issue by suwu150** [reactnativecn/react-native-website#253]
不进行pod install该如何运行项目
## 问题的具体描述
离线情况下,希望能够进行运行ios,不用执行pod install,能够通过将pod中内容处理成静态库文件这种方案

## 请描述完整的环境/版本信息
  Binaries:
    Node: 10.20.0 - ~/.nvm/versions/node/v10.20.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.20.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 24, 26, 27, 28, 29
      Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_171 - /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.

## 预期结果
能提供不执行pod install命令执行项目的方案

**Comment by sunnylqm** [comment]
并没有看到有人做这种尝试
但是pod install只用执行一次，后续就可以离线运行了啊

**Comment by suwu150** [comment]
> 并没有看到有人做这种尝试
> 但是pod install只用执行一次，后续就可以离线运行了啊

首次也是没法执行的环境,希望能够通过库文件的方式进行处理

**Comment by sunnylqm** [comment]
那你的项目从何而来呢？

**Comment by suwu150** [comment]
> 那你的项目从何而来呢？
通过有网络的机器运行起来,然后复制到不能执行pod install的机器上,然后在不能执行pod install的机器上进行打包

**Comment by sunnylqm** [comment]
可以带上pod目录复制过来啊，就不需要执行pod install了

**Comment by suwu150** [comment]
> 可以带上pod目录复制过来啊，就不需要执行pod install了

这样尝试过,在转存的过程是mac->windows->mac中会出现Header/private下面的头文件替身格式错乱,变成了相对路径的格式,然后就出现无法识别的问题

**Comment by suwu150** [comment]
> 可以带上pod目录复制过来啊，就不需要执行pod install了

这样尝试过,在转存的过程是mac->windows->mac中会出现Header/private下面的头文件替身格式错乱,变成了相对路径的格式,然后就出现无法识别的问题

**Comment by sunnylqm** [comment]
不清楚你是怎么个转存，也不明白为什么会两次跨平台，建议git分发或者zip打包
