### ISSUE TITLE
发送事件到 JavaScript   react-native没有到

### ISSUE THREAD

**Issue by weizhishu1901** [reactnativecn/react-native-website#257]
![image](https://user-images.githubusercontent.com/39817571/94659869-81298a80-0337-11eb-9072-6844ebb90b8c.png)
![image](https://user-images.githubusercontent.com/39817571/94659958-a0c0b300-0337-11eb-98c5-6f8235e6e441.png)

**Comment by weizhishu1901** [comment]
《----------------------------------------react-native代码部分-------------------------------------》
componentDidMount() {
        DeviceEventEmitter.addListener('test', (e) => {
            Toast.success('扫描成功');
            this.onScanningResult(e)
        });
        this.props.navigation.addListener('focus', () => {
            const {position}=this.state;
            const {vehicleInfo, organizationInfo, deliveryInfo} = this.props.route.params;
            this.verification([
                {field:'position',value:position},
                {field:'vehicle',value:vehicleInfo&&vehicleInfo.id},
                {field:'organization',value:organizationInfo&&organizationInfo.id},
                {field:'deliveryStatus',value:deliveryInfo&&deliveryInfo.id},
            ]);
        });
    }
    onScanningResult = (e)=> {
        this.setState({
            scanningResult: "更新数据成功",
        });
    };


《--------------------------------------原生代码-----------------------------------》
@Override
    public void onReceive(Context context, Intent intent) {
        if (intent.getAction().equals(scan_action)) {
            data = intent.getStringExtra("data");
            WritableMap writableMap = Arguments.createMap();
            writableMap.putString("code", data);
            sendTransEvent(reactApplicationContext, "test", writableMap);
        } else {
            Toast.makeText(context.getApplicationContext(), intent.getAction()+"", Toast.LENGTH_SHORT).show();
        }
    }

    public void sendTransEvent(ReactContext reactContext, String eventName, @Nullable WritableMap params) {
        Toast.makeText(reactContext.getApplicationContext(), "进入", Toast.LENGTH_SHORT).show();
        if (reactContext == null) {
            Toast.makeText(reactContext.getApplicationContext(), "reactContext等于null", Toast.LENGTH_SHORT).show();
        } else {
            reactContext
                    .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                    .emit(eventName, params);
        }
    }

**Comment by sunnylqm** [comment]
1、检查eventName对得上吗
2、[文档](https://reactnative.cn/docs/native-modules-android#%E5%8F%91%E9%80%81%E4%BA%8B%E4%BB%B6%E5%88%B0-javascript)里用的是 `NativeEventEmitter`，并不是`DeviceEventEmitter`

**Comment by weizhishu1901** [comment]
> 1、检查eventName对得上吗
> 2、[文档](https://reactnative.cn/docs/native-modules-android#%E5%8F%91%E9%80%81%E4%BA%8B%E4%BB%B6%E5%88%B0-javascript)里用的是 `NativeEventEmitter`，并不是`DeviceEventEmitter`

eventName没有问题，NativeEventEmitter和DeviceEventEmitter都试过了

**Comment by sunnylqm** [comment]
贴用NativeEventEmitter的代码

**Comment by weizhishu1901** [comment]
> 贴用NativeEventEmitter的代码

难道两者用法不一样吗？

**Comment by sunnylqm** [comment]
你看文档啊
