### ISSUE TITLE
 Command failed: adb shell am start -n com.test/com.test.MainActivity

### ISSUE THREAD

**Issue by Flyooofly** [reactnativecn/react-native-website#260]
大佬们帮看看，我是在webstorm上创建的rn项目    各种版本都跟官网的配置一样
![image](https://user-images.githubusercontent.com/31236750/95175175-af9ede00-07ed-11eb-986b-f6210eaa5631.png)
![image](https://user-images.githubusercontent.com/31236750/95175209-bb8aa000-07ed-11eb-8a7f-fdf97bfdbd02.png)

**Comment by sunnylqm** [comment]
1、你的app已经已经编译完成并且安装完成了，完全可以自己点击继续运行
2、adb命令找不到，说明环境变量的配置仍然有问题
3、无论如何项目名称不应该包含空格，哪怕这次执行成功，也很难保证以后不出问题

**Comment by Flyooofly** [comment]
> 1、你的app已经已经编译完成并且安装完成了，完全可以自己点击继续运行
> 2、adb命令找不到，说明环境变量的配置仍然有问题
> 3、无论如何项目名称不应该包含空格，哪怕这次执行成功，也很难保证以后不出问题

谢谢大佬。刚刚我重新安装了一下HAMX然后又重启了AndroidStudio就好了。adb那个也不报错了，，，毕竟之前其实已经在环境变量那里配置好了。
