### ISSUE TITLE
问下有用npx react-native upgrade更新版本的么，我这个报错怎么解决，有其他的更新方式么？

### ISSUE THREAD

**Issue by lh9403** [reactnativecn/react-native-website#262]
npx react-native upgrade
info No version passed. Fetching latest...
info Fetching diff between v0.63.2 and v0.63.3...
error request to https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.63.2..0.63.3.diff failed, reason: connect ECONNREFUSED 0.0.0.0:443
error Failed to fetch diff for react-native@0.63.3. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#diff-table-full-table-here

**Comment by sunnylqm** [comment]
翻墙问题

**Comment by sunnylqm** [comment]
再就是手动照着升级
https://react-native-community.github.io/upgrade-helper/?from=0.63.2&to=0.63.3
