### ISSUE TITLE
如何解决  FlatList 和 TouchableOpacity 上下左右滑动时的冲突

### ISSUE THREAD

**Issue by zinete** [reactnativecn/react-native-website#263]
例如我有一个 tabs 预期左右滑动但是触发了点击事件进入了详情页面。

**Comment by shendiid** [comment]
左右滑动的时候禁止点击

**Comment by Han3Jim** [comment]
> 例如我有一个 tabs 预期左右滑动但是触发了点击事件进入了详情页面。

TouchableOpacity 组件上 有 onPressIn onPressOut事件，通过判断起落手势到底是滑动了一段距离还是一个点上的点击。

**Comment by Han3Jim** [comment]
<TouchableOpacity
            key={curOrder.orderNumber}
            onPressIn={(e) => {
                preventOnPress = false;
                pressPos.current = {
                    x: e.nativeEvent.pageX,
                    y: e.nativeEvent.pageY,
                }
            }}
            onPressOut={(e) => {
                const [x, y] = [e.nativeEvent.pageX, e.nativeEvent.pageY];
                if (
                    Math.abs(pressPos.current.x - x) > PREVENTDISTANCE ||
                    Math.abs(pressPos.current.y - y) > PREVENTDISTANCE
                ) {
                    preventOnPress = true;
                }
            }}
            onPress={() => {
                !preventOnPress && dealJump()
            }}
            style={[styles.touchWrap, { marginBottom: marginBot }]}
        >
