### ISSUE TITLE
react native 移动端app紧急项目有偿请求外援

### ISSUE THREAD

**Issue by samuel-jwis** [reactnativecn/react-native-website#264]
## 项目需求
- 开发一款类似于企业微信、飞书、钉钉的企业级app
- 具备IM能力
- 实现在线会议
   - 添加参会者
   - 语音沟通
   - 查看web端用户的屏幕共享
   - 共享手机摄像头

## 合作模式
- 地点在深圳科技园
- 最好能full time 1-2周
- 如果是part-time，可离线指导搭建基础框架和培训
- 按人天或者项目整包计费
- 联系方式： 罗晓敏 13823129702

**Comment by ChenqiaoYizhan** [comment]
我现在就在附近: 东方科技大厦。
但是你的这个需求，移动方面的技术无非就是摄像头和麦克风的Stream。
这个APP的核心是后端: 

```
1. 音视频的RTS的服务器
2. 屏幕共享的TCP Socket服务器
```

**Comment by samuel-jwis** [comment]
音视频服务我们采用的是租赁腾讯云的音视频



罗晓敏 Samuel Luo

杰为软件系统（深圳）有限公司
T：0755-8696 1998 | M：138 2312 9702
E：samuelluo@jwis.cn | W：www.jwis.cn
A：深圳市南山区粤海街道科园路1002号A8音乐大厦24层
官方微信公众号：
 
发件人： 陈桥驿站
发送时间： 2020-10-12 18:13
收件人： reactnativecn/react-native-website
抄送： samuel-jwis; Author
主题： Re: [reactnativecn/react-native-website] react native 移动端app紧急项目有偿请求外援 (#264)
我现在就在附近: 东方科技大厦。
但是你的这个需求，移动方面的技术无非就是摄像头和麦克风的Stream。
这个APP的核心是后端:
1. 音视频的RTS的服务器
2. 屏幕共享的TCP Socket服务器

**Comment by ChenqiaoYizhan** [comment]
> 音视频服务我们采用的是租赁腾讯云的音视频 罗晓敏 Samuel Luo 杰为软件系统（深圳）有限公司 T：0755-8696 1998 | M：138 2312 9702 E：samuelluo@jwis.cn | W：[www.jwis.cn](http://www.jwis.cn) A：深圳市南山区粤海街道科园路1002号A8音乐大厦24层 官方微信公众号： 发件人： 陈桥驿站 发送时间： 2020-10-12 18:13 收件人： reactnativecn/react-native-website 抄送： samuel-jwis; Author 主题： Re: [reactnativecn/react-native-website] react native 移动端app紧急项目有偿请求外援 (#264) 我现在就在附近: 东方科技大厦。 但是你的这个需求，移动方面的技术无非就是摄像头和麦克风的Stream。 这个APP的核心是后端: 1. 音视频的RTS的服务器 2. 屏幕共享的TCP Socket服务器 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

``` javascript
1.如果不用自己搭RTS服务器，感觉还是省很多力气，我看了看RN也有相关的Module了已经。
2.屏幕共享你可以用SWING的Robot，然后自己搭一个TCP Server，剩余的就是CRUD的操作了。
```
