### ISSUE TITLE
初始化的项目运行报错：___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by shabbyaaa** [reactnativecn/react-native-website#270]
请按以下格式提供问题的相关信息。

## macOS：10.14.6  xcode: 11.3 RN: 0.63 在官网初始化的项目跑不成功，在xcode中报错___darwin_check_fd_set_overflow
- 请在命令行的项目目录中运行`react-native info`命令，并将其输出结果粘贴到这里。
yarn react-native info截图如下：
![image](https://user-images.githubusercontent.com/48679300/96332279-7ee46180-1095-11eb-9a2f-7908538e15e2.png)

命令行运行报错显示
![image](https://user-images.githubusercontent.com/48679300/96332169-5197b380-1095-11eb-987b-a4b1c6fe3e75.png)

xcode运行报错结果如下：
![image](https://user-images.githubusercontent.com/48679300/96332289-915e9b00-1095-11eb-9078-6212f7beb2a3.png)

**Comment by sunnylqm** [comment]
看起来是xcode的bug，我搜了一圈也还没看到明确的说法和解决方案，哪怕是最新版本也有人碰到这个问题

**Comment by sunnylqm** [comment]
有人说升到11.6可以解决，11.6应该不用升级系统吧

**Comment by daichangxin** [comment]
podfile 中注释：
use_flipper!
执行pod install  即可。不用升级。
