### ISSUE TITLE
rn0.62版本能否支持继续使用link的方式手动link依赖

### ISSUE THREAD

**Issue by suwu150** [reactnativecn/react-native-website#271]
rn0.62版本能否支持继续使用link的方式手动link依赖

**Comment by sunnylqm** [comment]
可以但是没有必要，也不推荐，可能导致重复链接

**Comment by suwu150** [comment]
@sunnylqm 请问如何操作,我这边需要进行直接依赖到项目中,不需要通过pod进行管理,目前我尝试删掉pods文件夹时,运行时提示Header无法找到,请问使用link方式该如何操作,非常感谢.

**Comment by sunnylqm** [comment]
剥离pod的话不太现实，官方现在完全围绕pod来做，他们自己都未必知道怎么剥离了，也没见到有谁尝试过

**Comment by suwu150** [comment]
这就有点难受了,看了官方,有人也有类似问题:[https://github.com/facebook/react-native/issues/30196](https://github.com/facebook/react-native/issues/30196)

**Comment by sunnylqm** [comment]
他们围绕pod重构了大量代码，现在回头应该是不可能了

**Comment by suwu150** [comment]
放弃这种方案了吗
