### ISSUE TITLE
有大佬知道这是什么问题吗

### ISSUE THREAD

**Issue by wangyao333** [reactnativecn/react-native-website#272]
* What went wrong:
Execution failed for task ':react-native-ble-manager:javaPreCompileDebug'.
> Could not resolve all files for configuration ':react-native-ble-manager:debugCompileClasspath'.
   > Failed to transform artifact 'support-v4.aar (com.android.support:support-v4:23.0.1)' to match attributes {artifactType=android-classes, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: C:\Users\24638\.gradle\caches\modules-2\files-2.1\com.android.support\support-v4\23.0.1\9e8da0e4ecf9f63258c7fbd273889252cba2d0c3\support-v4-23.0.1.aar.
         > duplicate entry: META-INF/MANIFEST.MF

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by sunnylqm** [comment]
看起来版本非常老

**Comment by finghtingjie** [comment]
提供地错误信息太少了，不过从报错信息来看可能你需要把support-v4改成support-v7
