### ISSUE TITLE
RN0.63不翻墙运行报错怎么解决?

### ISSUE THREAD

**Issue by a1145422343** [reactnativecn/react-native-website#273]
![图片说明](https://img-ask.csdn.net/upload/202010/21/1603243313_251114.jpg)

按照官网推荐修改jcenter()和google()也不行,

翻墙后完美运行   不翻墙报错

![图片说明](https://img-ask.csdn.net/upload/202010/21/1603243340_433289.jpg)

**Comment by sunnylqm** [comment]
你上面的截图报错没有看出跟翻墙有什么关系
