### ISSUE TITLE
初始化的项目报错 No bundle URL  preset

### ISSUE THREAD

**Issue by Glenfiddish** [reactnativecn/react-native-website#274]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 项目初始化
- 修改8081端口为8004（yarn ios 添加 --port=8004), 为metro添加server.port: 8004
- 运行命令: yarn ios 报错，No bundle url preset

![image](https://user-images.githubusercontent.com/22559022/96666925-a172c500-138a-11eb-834d-25408e3d7ea8.png)

- 检查metro服务
![image](https://user-images.githubusercontent.com/22559022/96667033-d54dea80-138a-11eb-85c5-af18fd251e60.png)

- 代理检查，localhost:8004能直接访问
![image](https://user-images.githubusercontent.com/22559022/96667302-67ee8980-138b-11eb-8d3f-78ec966ec9e4.png)

## 请描述完整的环境/版本信息
- package.json
```
"scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios --port=8004",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.3"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
```

- metro.config.js
```
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  server: {
    port: 8004,
  },
};
```
- project.pbxproj 修改 METRO端口
- ![image](https://user-images.githubusercontent.com/22559022/96667613-f7943800-138b-11eb-82be-90a36bcfa519.png)

## 预期结果
- 由于8081被占用无法被kill，需要项目初始化后修改端口能跑起来

**Comment by Glenfiddish** [comment]
@sunnylqm 大佬帮忙看一下？

**Comment by sunnylqm** [comment]
之前好像也是碰到这个问题，发现官方的几个说法也不是太靠谱，不记得后来怎么解决甚至解决了没。。。现在似乎开发者菜单和android一样直接能改端口？

**Comment by Glenfiddish** [comment]
> 之前好像也是碰到这个问题，发现官方的几个说法也不是太靠谱，不记得后来怎么解决甚至解决了没。。。现在似乎开发者菜单和android一样直接能改端口？

尝试参考: https://github.com/reactnativecn/react-native-website/issues/135，卸载重装也是没有解决
而且比较奇怪的就是他有些时候可以但是现在就不行了， = =

**Comment by lihuiwen** [comment]
我创建项目的时候也遇到这个问题了，我的解决方案是：
1、到ios目录执行pod install
2、将项目中的node_modules删掉，重新npm i
之后执行react-native run-ios就可以启动成功了

**Comment by simon9211** [comment]
watchman的问题，重新安装就好了，`brew reinstall watchman`
