### ISSUE TITLE
reactNative环境搭建(windows)

### ISSUE THREAD

**Issue by Reeko103** [reactnativecn/react-native-website#278]
请按以下格式提供问题的相关信息。

## reactNative环境搭建(windows) yarn android 报错
- 
![image](https://user-images.githubusercontent.com/29188175/96703902-fbdd4700-13c5-11eb-85c7-e6532064f79d.png)

**Comment by sunnylqm** [comment]
![gradle (1).png](https://user-images.githubusercontent.com/615282/96704665-eddbf600-13c6-11eb-92f8-e6bdc52a684e.png)

**Comment by Reeko103** [comment]
大佬，我没太明白，尴尬

**Comment by sunnylqm** [comment]
就照图片上说的做啊

**Comment by 13875861363** [comment]
已解决

**Comment by Reeko103** [comment]
嗯呢，跑起来了，我把这个文件下了下来，把本地那个压缩包给替换了，没改url

**Comment by yddhero** [comment]
已解决 谢谢大佬

**Comment by zYu-wow** [comment]
大佬，我这样改了之后还是不行啊

**Comment by sunnylqm** [comment]
我发现很多人看不懂这个图片，也有很多人参考其他文章搞不懂路径
不用那么麻烦，你用迅雷之类的下载工具下载gradle的zip包，找到`android/gradle/wrapper`这个目录，直接把这个包放到目录里，它和`gradle-wrapper.properties`不就在同一层目录吗，那么相对路径就直接是`gradle-x.x-all.zip`，不用考虑什么协议头什么盘符什么正斜杠反斜杠什么随机文件名啊
