### ISSUE TITLE
yarn android报错

### ISSUE THREAD

**Issue by 13875861363** [reactnativecn/react-native-website#280]
1.参考官方文档搭建了一套开发环境，demo app能正常运气起来。
2.现在手上有一个现有 react native工程，直接用yarn android 运行报错 Command "android" not found：如下图

![react_报错](https://user-images.githubusercontent.com/59083909/96873750-eb9d9880-14a7-11eb-8ff2-202a5665ae3a.png)

**Comment by sunnylqm** [comment]
1、老版本没有yarn android命令，你可以参照新版本工程的package.json里的scripts复制一份android和ios命令
2、不建议用git bash来跑rn命令，可能会有一些错误
