### ISSUE TITLE
多层TouchableHighlight嵌套如何阻止冒泡

### ISSUE THREAD

**Issue by xf1987** [reactnativecn/react-native-website#281]
## 问题的具体描述
                        <TouchableWithoutFeedback onPress={()=>{}}>
                        <View style={filter_model_styles.test_view_style}>
                        <TouchableHighlight onPress={()=>{}}></TouchableHighlight>
                        </View>
                        </TouchableWithoutFeedback>
## 请描述完整的环境/版本信息
iOS/Android react native 0.63

## 预期结果
如何阻止内层的TouchableHighlight冒泡

**Comment by sunnylqm** [comment]
https://reactnative.cn/docs/view.html#pointerevents

**Comment by xf1987** [comment]
@sunnylqm 试了，iOS端可以，Android端不行
