### ISSUE TITLE
运行rn的npm run android报错

### ISSUE THREAD

**Issue by zyt1234** [reactnativecn/react-native-website#284]
'C:\Users\用户名' is not recognized as an internal or external command,
operable program or batch file.
error Failed to launch emulator. Reason: Could not start emulator within 30 seconds..
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

> Task :app:stripDebugDebugSymbols UP-TO-DATE
Compatible side by side NDK version was not found.

> Task :app:installDebug FAILED
Skipping device 'emulator-5554' (emulator-5554): Device is OFFLINE.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
256 actionable tasks: 2 executed, 254 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No online devices found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.        

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ServicesHubMobile@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ServicesHubMobile@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Yanan Zhang\AppData\Roaming\npm-cache\_logs\2020-10-26T06_59_15_721Z-debug.log

package.json
  "dependencies": {
    "@fluentui/react-native": "^0.15.80",
    "@microsoft/microsoft-graph-client": "^2.0.0",
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.9.1",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "@reduxjs/toolkit": "^1.4.0",
    "@types/react-native-snap-carousel": "^3.8.2",
    "@uifabricshared/themed-stylesheet": "^0.3.67",
    "@uifabricshared/theming-react-native": "^0.7.71",
    "eslint-config-prettier": "^6.11.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jest": "^23.20.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "formik": "^2.2.0",
    "i18next": "^19.7.0",
    "moment": "^2.28.0",
    "prettier": "^2.1.0",
    "react": "16.13.1",
    "react-dom": "^16.13.1",
    "react-i18next": "^11.7.0",
    "react-native": "0.63.2",
    "react-native-app-auth": "^6.0.0",
    "react-native-config": "^1.3.3",
    "react-native-elements": "^2.3.1",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-localize": "^1.4.1",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^3.1.7",
    "react-native-screens": "^2.10.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-testing-library": "^6.0.0",
    "react-native-vector-icons": "^7.0.0",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-injectors": "^1.3.0",
    "redux-logger": "3.0.6",
    "redux-saga": "^1.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.9",
    "@types/react": "^16.9.46",
    "@types/react-native": "^0.63.8",
    "@types/react-redux": "^7.1.9",
    "@types/react-test-renderer": "^16.9.3",
    "@types/redux-logger": "3.0.8",
    "@typescript-eslint/eslint-plugin": "^3.9.1",
    "@typescript-eslint/parser": "^3.9.1",
    "babel-jest": "^26.3.0",
    "babel-plugin-dynamic-import-node": "^2.3.3",
    "eslint": "^7.7.0",
    "eslint-plugin-react": "^7.20.6",
    "eslint-plugin-react-hooks": "^4.1.0",
    "eslint-plugin-react-native": "^3.9.0",
    "husky": "^4.2.5",
    "jest": "^26.4.0",
    "metro-react-native-babel-preset": "^0.62.0",
    "pretty-quick": "^3.0.0",
    "react-test-renderer": "16.13.1",
    "redux-devtools": "^3.6.0",
    "typescript": "^3.9.7"
  },

代码无法运行

**Comment by sunnylqm** [comment]
编译已经完成了，但是和设备通讯有问题，你是用的模拟器还是真机？

**Comment by wwl135184** [comment]
我用的模拟器，也出现这个问题啦，该怎么解决？
