### ISSUE TITLE
react-native运行项目错误

### ISSUE THREAD

**Issue by lili199601** [reactnativecn/react-native-website#285]
项目搭建好实用Android studio模拟器启动，
npx react-native run-android提示错误Could not resolve com.android.tools.build:gradle:3.5.3
Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
使用adb devices是能查出来连接的虚拟机的
![image](https://user-images.githubusercontent.com/73465886/97151811-fe1b1900-17aa-11eb-8ed6-eb62045aa853.png)

![image](https://user-images.githubusercontent.com/73465886/97151557-9e247280-17aa-11eb-8fb3-294bf2552999.png)

**Comment by sunnylqm** [comment]
maven源连接困难，按rn中文网的文档替换阿里云的源

**Comment by lili199601** [comment]
> maven源连接困难，按rn中文网的文档替换阿里云的源
感觉还是没用
![image](https://user-images.githubusercontent.com/73465886/97283263-9502d680-187a-11eb-93de-555ac7df1b6c.png)

**Comment by lili199601** [comment]
而且我也查了是有虚拟机启动成功的
![image](https://user-images.githubusercontent.com/73465886/97284950-9df4a780-187c-11eb-915b-e0feceffac43.png)

**Comment by lili199601** [comment]
> maven源连接困难，按rn中文网的文档替换阿里云的源

在Android studio中运行又提示这个错误ERROR: Cause: unable to find valid certification path to requested target
![image](https://user-images.githubusercontent.com/73465886/97285503-4145bc80-187d-11eb-80a8-24636ecd6112.png)
