### ISSUE TITLE
yarn android报错

### ISSUE THREAD

**Issue by zYu-wow** [reactnativecn/react-native-website#286]
reactNative环境搭建(windows) yarn android 报错
![tianruo_2020-10-26-637393318576536229](https://user-images.githubusercontent.com/68732704/97158923-13954080-17b5-11eb-96e7-873ca41204b4.png)
尝试了大佬的方法
![tianruo_2020-10-26-637393318797059775](https://user-images.githubusercontent.com/68732704/97158975-23ad2000-17b5-11eb-89cd-2dba9c2b338f.png)
但是改过之后没有效果，不知道是不是放的位置错了啊
![tianruo_2020-10-26-637393319182508129](https://user-images.githubusercontent.com/68732704/97159056-43dcdf00-17b5-11eb-9568-8d99205f749a.png)

**Comment by sunnylqm** [comment]
你这个报错和gradle无关啊，build tools没装
