### ISSUE TITLE
react native运行报错

### ISSUE THREAD

**Issue by Only-vip** [reactnativecn/react-native-website#287]
react native创建项目后yarn android一直有报错
第一张图是我的报错，第二张和第三张是尝试的大佬的解决办法但是没有效，不知道是不是放的路径错了
求大佬解决
![1](https://user-images.githubusercontent.com/68732704/97159808-5b689780-17b6-11eb-9be9-e2fe24679e45.png)
![2](https://user-images.githubusercontent.com/68732704/97159811-5c99c480-17b6-11eb-8695-d13ef8bf408a.png)
![3](https://user-images.githubusercontent.com/68732704/97159813-5d325b00-17b6-11eb-9b6e-67634cd114fc.png)

**Comment by sunnylqm** [comment]
不要发重复的问题，你的问题我刚刚在另一个issue里已经回答了，你现在的报错跟gradle无关啊，折腾gradle有什么用呢
