### ISSUE TITLE
大家有好的方法能收集rn 页面卡死，白屏原因和显示具体堆栈信息吗

### ISSUE THREAD

**Issue by bayinhe110** [reactnativecn/react-native-website#289]
我们现在用的是Sentry来统计日志的，但是有些页面因为代码逻辑问题卡死收集不到日志，大家有什么好方法吗，或者是否可以通过原生层面捕获rn 的异常

**Comment by finghtingjie** [comment]
> 我们现在用的是Sentry来统计日志的，但是有些页面因为代码逻辑问题卡死收集不到日志，大家有什么好方法吗，或者是否可以通过原生层面捕获rn 的异常

可以使用adb logcat命令来捕获安卓的错误
