### ISSUE TITLE
有大佬知道为什么安卓打包出的apk一直是上一版本的内容

### ISSUE THREAD

**Issue by wangyao333** [reactnativecn/react-native-website#290]
有大佬知道为什么安卓打包出的apk一直是上一版本的内容
{
  "name": "LGCloudLink",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "bundle-android": "react-native bundle --entry-file index.js  --platform android --dev false --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res"
  },
  "dependencies": {
    "crypto-js": "^3.1.9-1",
    "events": "^3.2.0",
    "iconv-lite": "^0.4.24",
    "native-base": "^2.13.14",
    "native-echarts": "^0.4.0",
    "prop-types": "^15.7.2",
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.2",
    "react-native-alert-input": "^1.0.5",
    "react-native-ble-manager": "^6.5.1",
    "react-native-bluetooth-serial": "^1.0.0-rc1",
    "react-native-camera": "^1.0.2",
    "react-native-device-info": "^0.21.2",
    "react-native-dialogbox": "^0.6.9",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-fs": "^2.13.3",
    "react-native-image-crop-picker": "^0.24.0",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-modalbox": "^1.6.0",
    "react-native-orientation-locker": "^1.2.0",
    "react-native-picker": "^4.3.7",
    "react-native-refresh-list-view": "^1.0.8",
    "react-native-refreshable-flatlist": "^0.1.1",
    "react-native-root-toast": "^3.0.1",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-segmented-control-tab": "^3.3.1",
    "react-native-sound": "^0.10.9",
    "react-native-storage": "^0.2.2",
    "react-native-sunmi-inner-printer": "^0.1.6",
    "react-native-table-component": "^1.1.8",
    "react-native-ultimate-listview": "^3.3.0",
    "react-native-webview-bridge": "^0.33.0",
    "react-navigation": "^1.5.7"
  },
  "devDependencies": {
    "babel-jest": "23.0.0-alpha.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.2",
    "react-test-renderer": "16.3.0-alpha.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "optionalDependencies": {}
}

**Comment by sunnylqm** [comment]
不要手动生成bundle（不要执行bundle命令），删掉assets目录重新打包

**Comment by wangyao333** [comment]
还是一样没作用

**Comment by sunnylqm** [comment]
检查下别处有没有.bundle文件，检查下入口文件是否正确引用了你自己的代码

**Comment by wangyao333** [comment]
app/src/main/assets/index.android.bundle这个目录有这个文件

**Comment by wangyao333** [comment]
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit App.js
        </Text>
        <Text style={styles.instructions}>
          {instructions}
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
app.js文件

**Comment by sunnylqm** [comment]
所以不是让你删掉assets目录吗？

**Comment by wangyao333** [comment]
删了没作用，而且assets目录在打包命令后还是空的

**Comment by sunnylqm** [comment]
你刚刚不是说有bundle文件？到底是有文件还是空的？另外有清空build目录吗？

**Comment by wangyao333** [comment]
刚刚我又把这两个目录全清空再打包时报错了

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:0.19.+.
     Required by:
         project :app > project :react-native-webview-bridge
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/35.161.162.245, jcenter.bintray.com/54.187.47.108, jcenter.bintray.com/52.88.32.158, jcenter.bintray.com/52.43.200.1] failed: No route to host (connect failed)
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://maven.google.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://maven.google.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://maven.google.com/com/facebook/react/react-native/maven-metadata.xml'.
                  > Connect to maven.google.com:443 [maven.google.com/203.208.40.66] failed: No route to host (connect failed)
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml'.
                  > Connect to jitpack.io:443 [jitpack.io/104.26.9.99, jitpack.io/104.26.8.99, jitpack.io/172.67.72.129, jitpack.io/2606:4700:20:0:0:0:ac43:4881, jitpack.io/2606:4700:20:0:0:0:681a:863, jitpack.io/2606:4700:20:0:0:0:681a:963] failed: No route to host (connect failed)
   > Could not resolve com.facebook.react:react-native:0.12.+.
     Required by:
         project :app > project :react-native-sound
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/35.161.162.245, jcenter.bintray.com/54.187.47.108, jcenter.bintray.com/52.88.32.158, jcenter.bintray.com/52.43.200.1] failed: No route to host (connect failed)
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://maven.google.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://maven.google.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://maven.google.com/com/facebook/react/react-native/maven-metadata.xml'.
                  > Connect to maven.google.com:443 [maven.google.com/203.208.40.66] failed: No route to host (connect failed)
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml'.
                  > Connect to jitpack.io:443 [jitpack.io/104.26.9.99, jitpack.io/104.26.8.99, jitpack.io/172.67.72.129, jitpack.io/2606:4700:20:0:0:0:ac43:4881, jitpack.io/2606:4700:20:0:0:0:681a:863, jitpack.io/2606:4700:20:0:0:0:681a:963] failed: No route to host (connect failed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 52s

**Comment by sunnylqm** [comment]
确定没有改gradle配置文件？



---Original---

**Comment by wangyao333** [comment]
gradle配置文件改com.android.tools.build:gradle:2.2.3为'com.android.tools.build:gradle:3.5.4'，我打包成功但assets目录是空的而且apk包安装闪退

**Comment by sunnylqm** [comment]
0.57之前的rn好像最高支持到3.1.x的gradle版本



---Original---

**Comment by mcj122755** [comment]
1. 有缓存文件没删除   进到/src/main/assets下删除旧的index.android.bundle和index.android.bundle.meta文件,
2. 你的RN没有编译通过，系统默认使用上次缓存
就这个两个

**Comment by panZongLin** [comment]
我每次打包都会更新/android/app/build.gradle 里的versionCode和versionName

**Comment by KevinHao1314** [comment]
直接clean project，然后再次yarn android，然后再打包

**Comment by Onedayago** [comment]
手动运行打 bundle 的命令
