### ISSUE TITLE
请求大佬们指导 React-Native 怎么调用别的app里的方法

### ISSUE THREAD

**Issue by Reeko103** [reactnativecn/react-native-website#294]
请按以下格式提供问题的相关信息。

**Comment by sunnylqm** [comment]
基本上只能通过linking调用

**Comment by Reeko103** [comment]
调用安卓SDK

**Comment by sunnylqm** [comment]
sdk就按原生模块的文档来自己封装

**Comment by Reeko103** [comment]
> sdk就按原生模块的文档来自己封装

想请问下如果是和别的app交互  比如请求这样一个接口com.reeko.box.BoxController.OnIntEventTriggerListener   我想告诉他开门的状态  这样的操作是通过linking 吗？

**Comment by sunnylqm** [comment]
1、和其他的app交互 -> linking
2、调用sdk -> 原生模块桥接封装

**Comment by sunnylqm** [comment]
至于什么是app什么是sdk应该不需要解释吧？

**Comment by Reeko103** [comment]
谢谢你呀大佬！上次也是你回复我的，感谢

**Comment by Reeko103** [comment]
> 1、和其他的app交互 -> linking
> 2、调用sdk -> 原生模块桥接封装

大佬，原生模块桥接封装 我应该要把对方的jar放到自己项目里面吗？

**Comment by sunnylqm** [comment]
不然要放到我的项目里面吗？

**Comment by Reeko103** [comment]
> 不然要放到我的项目里面吗？

大佬，能加个微信吗？aidd0811
