### ISSUE TITLE
请问一下，reactNative 使用jar

### ISSUE THREAD

**Issue by Reeko103** [reactnativecn/react-native-website#295]
在这里打扰大家不好意思了，先在这里给大家道个歉，本人纯属小白，请大家多多担待，也是弄了好久没弄明白，毫无头绪，在这里真诚的希望得到大佬帮助，具体情况是这样的，我在reactNative里写好了页面，这个时候我需要向另一个项目的APP发起接口请求，如果是通过网络请求可能会出现不稳定导致功能不能使用的情况，想着把对面的APP弄成在本地的jar，放到lids目录下，进行接口请求，我不知道这样对不对，如果是这样，怎么在reactNative里面去请求到本地jar里的接口呢！请求好心大佬的帮助，谢谢

**Comment by sunnylqm** [comment]
放到`android/app/libs`目录下即可

**Comment by sunnylqm** [comment]
app是app，sdk是sdk，没办法把app“弄成”jar的

**Comment by Reeko103** [comment]
> app是app，sdk是sdk，没办法把app“弄成”jar的

请问放在目录下后，怎么样可以请求到本地jar里的接口，是需要配置什么吗？

**Comment by Reeko103** [comment]
> > app是app，sdk是sdk，没办法把app“弄成”jar的
> 
> 请问放在目录下后，怎么样可以请求到本地jar里的接口，是需要配置什么吗？

放到lids里的jar是sdk吗？

**Comment by sunnylqm** [comment]
lib就直接在代码里import啊（具体import什么怎么用，那是文档的事情了）

**Comment by Reeko103** [comment]
> lib就直接在代码里import啊（具体import什么怎么用，那是文档的事情了）

谢谢，请问那个jar是sdk吗

**Comment by sunnylqm** [comment]
在代码中引用别人提供的代码，就是sdk

**Comment by Reeko103** [comment]
> 在代码中引用别人提供的代码，就是sdk

辛苦了，谢谢

**Comment by Reeko103** [comment]
> > 在代码中引用别人提供的代码，就是sdk
> 
> 辛苦了，谢谢

对了，请问这里调用sdk还需要按原生文档自己封装吗？

**Comment by sunnylqm** [comment]
如果你要在js代码中调用就需要封装

**Comment by Reeko103** [comment]
> 如果你要在js代码中调用就需要封装
哦！是不是在Java文件里调用就不需要封装，想在JS里面调用就需要
