### ISSUE TITLE
不小心执行了bundle命令，项目无法刷新了

### ISSUE THREAD

**Issue by hiBruce** [reactnativecn/react-native-website#296]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 开发中不小心执行了bundle命令，现在项目完全无法刷新了，求助！
  - bundle命令：eact-native bundle --entry-file index.js --platform android --dev false --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res/
 
 -目前情况截图：
 
![image](https://user-images.githubusercontent.com/39815835/98113991-7be3d080-1edf-11eb-87d0-fc5ff7b222bf.png)

## 请描述完整的环境/版本信息
![image](https://user-images.githubusercontent.com/39815835/98114238-ea289300-1edf-11eb-959b-02431d0aed1b.png)

## 预期结果
- 可以正常刷新。

**Comment by sunnylqm** [comment]
删掉这个文件即可 android/app/src/main/assets/index.android.bundle

**Comment by hiBruce** [comment]
> 删掉这个文件即可 android/app/src/main/assets/index.android.bundle

删掉过了，没有用。还是跟上面截图一样。
node_modules删除过，重装也没用；
AS里clean，然后重新build也没用
.idea删除也试过了

**Comment by sunnylqm** [comment]
已经安装的app也要先删掉

**Comment by hiBruce** [comment]
> 已经安装的app也要先删掉

删过了，虚拟机都删掉了。。。
没有index.android的时候，app启动不了，会报错

**Comment by sunnylqm** [comment]
报什么错截图

**Comment by hiBruce** [comment]
> 报什么错截图

找到问题了。是因为我昨天解决AS里的错误时，误把BuildConfig引用成了facebook的了。。。。
还是要感谢您的热心相助
