### ISSUE TITLE
IOS调用react native出现问题

### ISSUE THREAD

**Issue by xuezhy** [reactnativecn/react-native-website#297]
Bridge is not set. This is probably because you've explicitly synthesized the bridge in ReactInteraction, even though it's inherited from RCTEventEmitter.'
  
RN版本:0.57.8

**Comment by sunnylqm** [comment]
贴代码

**Comment by xuezhy** [comment]
this is my code :

.h

```
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
#import <React/RCTBridge.h>
@interface ReactInteraction : RCTEventEmitter

(void)refreshEventReminderReceived;
(void)notifyWeiXinPayFinish:(NSString*) out_trade_no;
(void)notifyModeChange;
//- (void)refresh1;
+(id)allocWithZone:(NSZone *)zone ;
@EnD
```

.m

```
// ReactInteraction.m
// Neurmt
//
// Created by xzy on 2020/3/30.
// Copyright © 2020 xue. All rights reserved.
//

#import "ReactInteraction.h"

@implementation ReactInteraction

RCT_EXPORT_MODULE();

//.m文件
+(id)allocWithZone:(NSZone *)zone {
static ReactInteraction *sharedInstance = nil;
static dispatch_once_t onceToken;
dispatch_once(&onceToken, ^{
sharedInstance = [super allocWithZone:zone];
});
return sharedInstance;
}

(NSArray<NSString *> *)supportedEvents
{
return @[@"EventReminder",@"EventWeiXinPayFinish",@"currentMode"];
}

(void)refreshEventReminderReceived
{
//NSString *eventName = notification.userInfo[@"name"];
NSLog(@"----R----");
NSString *eventName = @"name";

[self sendEventWithName:@"EventReminder" body:@{@"name": eventName}];
}

(void)notifyWeiXinPayFinish:(NSString*) out_trade_no
{
NSLog(@"----notifyWeiXinPayFinish----");
[self sendEventWithName:@"EventWeiXinPayFinish" body:@{@"out_trade_no": out_trade_no}];
}

(void)notifyModeChange
{
NSLog(@"----notifyModeChange----");
// NSLog(mode);

// NSDictionary *dic = @{@"mode":mode};
// [self sendEventWithName:@"currentMode" body:dic];
[self sendEventWithName:@"currentMode" body:@{@"name": @"name"}];
}

@EnD
```

code to invoke that :


ReactInteraction * reactInteraction=[[ReactInteraction alloc]init];
[reactInteraction notifyModeChange];


React Native Environment Info:
System:
OS: macOS 10.15.5
CPU: (2) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Memory: 800.96 MB / 8.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 14.2.0 - /usr/local/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 6.14.4 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
IDEs:
Xcode: 11.5/11E608c - /usr/bin/xcodebuild
npmPackages:
react: 16.6.3 => 16.6.3
react-native: 0.57.8 => 0.57.8
npmGlobalPackages:
react-native-cli: 2.0.1

**Comment by sunnylqm** [comment]
这种模块是不能自己去初始化的，否则拿不到bridge

https://reactnative.cn/docs/native-modules-ios#%E4%BE%9D%E8%B5%96%E6%B3%A8%E5%85%A5

**Comment by xuezhy** [comment]
亲，我觉得您说的很有道理，可是我看了你发的连接。如下：
给 JavaScript 端发送事件
即使没有被 JavaScript 调用，原生模块也可以给 JavaScript 发送事件通知。最好的方法是继承RCTEventEmitter，实现suppportEvents方法并调用self sendEventWithName:。

// CalendarManager.h
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

@interface CalendarManager : RCTEventEmitter <RCTBridgeModule>

@end
// CalendarManager.m
#import "CalendarManager.h"

@implementation CalendarManager

RCT_EXPORT_MODULE();

- (NSArray<NSString *> *)supportedEvents
{
  return @[@"EventReminder"];
}

- (void)calendarEventReminderReceived:(NSNotification *)notification
{
  NSString *eventName = notification.userInfo[@"name"];
  [self sendEventWithName:@"EventReminder" body:@{@"name": eventName}];
}

@end

这个和我写的我没看出有什么不同啊？您能帮我具体指出哪句话有问题吗？万分感谢，不胜感激。

**Comment by sunnylqm** [comment]
我说的是你不能自己去init，除非你自己先控制bridge的初始化
```
ReactInteraction * reactInteraction=[[ReactInteraction alloc]init];
```

**Comment by xuezhy** [comment]
您好，我看网上有人说这块用单例模式：
  ReactInteraction * reactInteraction=[ReactInteraction allocWithZone:nil];
我试了，不好用，您能赐教一下这块到底该怎么弄吗？谢谢您！

**Comment by sunnylqm** [comment]
问题在于你要保证这个模块正确获得bridge -> 一般的做法是由bridge去初始化（你自己初始化就拿不到）-> 单例也是一种办法，但其原理仍然是bridge先初始化，你拿到的是bridge初始化之后的同一个实例（你在bridge之前初始化还是一样拿不到）
