### ISSUE TITLE
react-native 在IOS14下调试无法显示图片

### ISSUE THREAD

**Issue by Lenlyl** [reactnativecn/react-native-website#299]
iOS 14 调试模式，所有图片都不显示

解决办法：
找到文件：RCTUIImageViewAnimated.m
修改代码如下
#pragma mark - CALayerDelegate

- (void)displayLayer:(CALayer *)layer
{
  if (_currentFrame) {
    layer.contentsScale = self.animatedImageScale;
    layer.contents = (__bridge id)_currentFrame.CGImage;
  }else{
      [super displayLayer:layer];
  }
}

**Comment by Lenlyl** [comment]
"react-native": "0.61.5"

**Comment by yz1311** [comment]
以前的RN版本都有这个问题，0.63.2及以上才修复这个问题

**Comment by sendsnow** [comment]
我在0.59.9版本没有找到RCTUIImageViewAnimated.m文件，该怎么处理呢
