### ISSUE TITLE
初始化init项目后，直接npx react-native run-ios就报错

### ISSUE THREAD

**Issue by halophy** [reactnativecn/react-native-website#300]
## 初始化init项目后，直接npx react-native run-ios就报错

The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal x86_64 /Users/mac/react-native/IOSdemo/MyProject/ios/Pods/YogaKit/YogaKit/Source/YGLayoutExtensions.swift
(2 failures)

npm ERR! code 1
npm ERR! command failed
npm ERR! command sh -c react-native run-ios

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2020-11-11T04_15_10_389Z-debug.log
MacdeMacBook-Pro:MyProject mac$ react-native info
-bash: react-native: command not found

以及附上
mac$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 27.95 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

小白表示看不懂，而且搜索无果，呜呜

**或许可以有偿蹲一个大佬帮忙配置环境，！就是帮我解决前面部分的繁琐就好！！！**

**Comment by sunnylqm** [comment]
xcode 11.3有已知的bug，需要升级到xcode 11.6以上
