### ISSUE TITLE
App在安卓手机上reload的时候会出现多个Runing application xxx

### ISSUE THREAD

**Issue by YFBook** [reactnativecn/react-native-website#303]
如图所示：

![截屏2020-11-17 下午4 22 19](https://user-images.githubusercontent.com/10337076/99367129-84cb9d80-28f4-11eb-89cb-a7cac6887d7f.png)

像是Application被创建了两次，请问这是什么原因？有规避的方式吗？

**Comment by sunnylqm** [comment]
我也注意到reload时有这个现象，暂未观察到副作用

**Comment by YFBook** [comment]
@sunnylqm  首页constructor执行了两次，而该函数里面注册了store的监听器，造成了多次触发this.props.navigation.navigate('A')的现象，导致在A里面执行一次goback的时候，无法返回首页。

请问这是安卓系统本身的问题吗？

**Comment by sunnylqm** [comment]
不知道具体问题  https://github.com/facebook/react-native/issues/19377

但具体到你这个问题，我感觉可以把监听函数剥离出来，不与页面耦合
