### ISSUE TITLE
真机运行，调用后端接口时，出现 index.android.bundle错误

### ISSUE THREAD

**Issue by mamzip** [reactnativecn/react-native-website#304]
请按以下格式提供问题的相关信息。

## 问题的具体描述
在模拟器上调试没有出现这种错误，但是在真机构建发行版，调用后端接口/patientInfo时报错，由于无法在已发布的应用程序中获取任何日志，因此我进一步采取了措施来记录错误消息。原来，返回错误消息是
![image](https://user-images.githubusercontent.com/31251332/99928289-6695ef80-2d83-11eb-9215-5bdf2188900e.png)

{'line'：809，'column'：867，'sourceURL'：'index.android.bundle'}
## 请描述完整的环境/版本信息
- 安卓版本4.0

## 预期结果
- 能够以正常调用接口

**Comment by sunnylqm** [comment]
是http接口吗？是的话需要在main/AndroidManifest.xml里添加android:usesCleartextTraffic="true"
如果已经是https接口或者已经启用了明文传输，那么打印日志的时候这样打印
```
catch(e) {
Alert.alert(e.message); // <- 打印message，而不是打印整个e
}
```

**Comment by mamzip** [comment]
> 是http接口吗？是的话需要在main/AndroidManifest.xml里添加android:usesCleartextTraffic="true"
> 如果已经是https接口或者已经启用了明文传输，那么打印日志的时候这样打印
> 
> ```
> catch(e) {
> Alert.alert(e.message); // <- 打印message，而不是打印整个e
> }
> ```

您好，谢谢大佬您回复我的问题。我是http请求，系统是安卓的4.0版本，我现在去尝试下 ps:就这个接口会出现，其他的都没问题
