### ISSUE TITLE
npx react-native run-ios的时候遇到的问题，我是个新手不知道该如何解决。

### ISSUE THREAD

**Issue by bianxuerui** [reactnativecn/react-native-website#305]
Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening AwesomeProject.xcworkspace.

**Comment by sunnylqm** [comment]
run-ios有错请使用xcode运行查看具体错误

**Comment by finghtingjie** [comment]
> Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening AwesomeProject.xcworkspace.

估计是你打开的目录不对，尝试用xcode打开AwesomeProject.xcworkspace.然后构建试下

**Comment by xiaoyinliuyun** [comment]
> Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening AwesomeProject.xcworkspace.

这个问题怎么解决的啊？我也卡了一天了

**Comment by sunnylqm** [comment]
请使用xcode运行查看具体错误然后截图贴过来

**Comment by w1687021088** [comment]
我的问题也一样，使用xcode 运行也不行，
![image](https://user-images.githubusercontent.com/38272529/103464450-b8606b00-4d6e-11eb-8bb4-77594f94a9cc.png)
这是我xocde报的错误

**Comment by sunnylqm** [comment]
@w1687021088 你这个是xcode版本问题，需要升级到11.6以上
