### ISSUE TITLE
请问RCTCxxBridge runRunLoop为什么一直在运行呢

### ISSUE THREAD

**Issue by ks-stack** [reactnativecn/react-native-website#308]
请按以下格式提供问题的相关信息。

## 问题的具体描述
-请问下图中这三个的具体作用是什么，为什么会一直占用cpu，希望能有详细的解释，公司客户端团队问的rn团队
![image](https://user-images.githubusercontent.com/57781441/100533984-8034ac80-3245-11eb-8386-44df9e01578e.png)

**Comment by sunnylqm** [comment]
控制屏幕刷新的，所以要一直在执行

**Comment by ks-stack** [comment]
> 控制屏幕刷新的，所以要一直在执行

还有其他的作用吗？因为如果是屏幕刷新的话，完全可以在有了ReactRootView之后再开启，上面的截图我只是初始化了一个桥
