### ISSUE TITLE
0.63 ios10.问题

### ISSUE THREAD

**Issue by singeo** [reactnativecn/react-native-website#310]
IOS10系统闪退，报错：
###dyld: Library not loaded: @rpath/libswiftCore.dylib###
编译的时候设置：ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES 为YES 后，IPA包导入了swift标准库，包的体积增大（25M左右增加到100M左右），应用不再报错了。
请问有没有其他什么办法解决没有，不增加包的体积？

**Comment by sunnylqm** [comment]
剥离flipper的话应该就不需要swift库了（不过我不知道具体怎么剥离
