### ISSUE TITLE
初始化项目yarn iOS 运行正常 但是通过xcode12编译的时候报错

### ISSUE THREAD

**Issue by zhangxin129** [reactnativecn/react-native-website#312]
error reading '/Users/zhangxin/Desktop/rn/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/log.cpp'

**Comment by guoliang1206** [comment]
pod install 执行正常工作了不

**Comment by zhangxin129** [comment]
> pod install 执行正常工作了不

没有，一直是报这个错误 你也有吗

**Comment by guoliang1206** [comment]
删了重新pod install 一下
或者node_modules也删了重新下一下
示例demo吗？

**Comment by zhangxin129** [comment]
> 删了重新pod install 一下
> 或者node_modules也删了重新下一下
> 示例demo吗？

是的 示例demo，

**Comment by nichoice** [comment]
同样的问题，请问解决了吗
