### ISSUE TITLE
ccache-clang.sh failed with exit code 71

### ISSUE THREAD

**Issue by GJ100** [reactnativecn/react-native-website#318]
原来我是在windows上开发安卓的，现在想运行iOS，但是pod install也弄了，运行的时候就是报7这个错误，新版xcode
.
error: can't exec '/Users/ken/Desktop/NewShares/ios/Pods/../../node_modules/realm/scripts/ccache-clang.sh' (Permission denied)
Command /Users/ken/Desktop/NewShares/ios/Pods/../../node_modules/realm/scripts/ccache-clang.sh failed with exit code 71

**Comment by sunnylqm** [comment]
不要直接跨平台拷贝代码，尤其不要拷贝node_modules
代码应该始终通过git仓库分发，否则就会有这样的权限问题（以及其他各种问题）
