### ISSUE TITLE
大神 有谁知道 这个是咋回事吗 搞了一下午了 唉 Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

### ISSUE THREAD

**Issue by xiaoyaci** [reactnativecn/react-native-website#319]
:\ReactNativeItem\reactnativedemo\android>yarn android
yarn run v1.22.10
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 967 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
:ReactNative:Running '[node, -e, console.log(require('react-native/cli').bin);]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'I:\ReactNativeItem\reactnativedemo\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 179

* What went wrong:
A problem occurred evaluating script.
> Cannot run program "node" (in directory "I:\ReactNativeItem\reactnativedemo\android"): CreateProcess error=2, ϵͳ�Ҳ� ��ָ�����ļ���

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
:ReactNative:Running '[node, -e, console.log(require('react-native/cli').bin);]' command failed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by panZongLin** [comment]
试试看这上面说的
https://stackoverflow.com/questions/59422584/react-native-build-failed-in-android-react-native-community-cli-platform-andro

**Comment by DBAAZzz** [comment]
检查一下是不是本地的8081端口被其他服务占用了
