### ISSUE TITLE
请问要设置Text组件的内容置底，有什么办法吗？

### ISSUE THREAD

**Issue by YFBook** [reactnativecn/react-native-website#320]
Text里面的内容始终距离底部有一些距离，在查看了Text属性和相关文档，都没有找到对应的方法。

请问有任何建议或者思路吗？

**Comment by sunnylqm** [comment]
代码和实际渲染都截图看看？
textAlignVertical和includeFontPadding有使用吗

**Comment by YFBook** [comment]
@sunnylqm   

代码实现：
![截屏2020-12-15 上午9 57 20](https://user-images.githubusercontent.com/10337076/102158370-478b0900-3ebc-11eb-8acf-90bf0577e39f.png)
![截屏2020-12-15 上午9 57 33](https://user-images.githubusercontent.com/10337076/102158372-4954cc80-3ebc-11eb-9726-e4e4992a8b4c.png)

最终效果：

![截屏2020-12-15 上午9 59 05](https://user-images.githubusercontent.com/10337076/102158393-5376cb00-3ebc-11eb-8017-a6623a35ed28.png)


实际Text已经位于父容器的底部，但是可以很明显的看到，text里面的文本内容距离它底部还是有一些间距的。

我是想让其文本内容置底。

请问你有任何建议或者思路吗？

**Comment by sunnylqm** [comment]
includeFontPadding是放在style里面的

**Comment by YFBook** [comment]
@sunnylqm   尝试调整到style，依旧无法使其文本内容置底。

**Comment by sunnylqm** [comment]
不可能完全没有空隙的，可以配合负边距以及父容器的负内边距等手段做视觉上的调整

**Comment by YFBook** [comment]
@sunnylqm  好的，感谢你能花时间回答我的疑问。

负间距的方案我也曾考虑过。

目前我能找到比较理想的方式，应该是自定义原生组件来进行重新绘制了。

**Comment by Deadpool957** [comment]
> 不可能完全没有空隙的，可以配合负边距以及父容器的负内边距等手段做视觉上的调整

这2个属性不是只有Android有效吗
