### ISSUE TITLE
win10 yarn android 遇到的问题

### ISSUE THREAD

**Issue by ningboxiazhengqi** [reactnativecn/react-native-website#324]
info Successfully launched emulator.
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)
   :ReactNative:Unexpected empty result of running '[node, C:\Users\xzq\Desktop\�?课吧\RN\AwesomeProject\node_modules\@react-native-community\cli\build\bin.js, config]' command.
:ReactNative:Running '[node, C:\Users\xzq\Desktop\�?课吧\RN\AwesomeProject\node_modules\@react-native-community\cli\build\bin.js, config]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\xzq\Desktop\���ΰ�\RN\AwesomeProject\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 195

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:1083  throw err;  ^Error: Cannot find module 'C:\Users\xzq\Desktop\寮�璇惧惂\RN\AwesomeProject\node_modules\@react-native-community\cli\build\bin.js'    at Function.Module._resolveFilename (inte
rnal/modules/cjs/loader.js:1080:15)    at Function.Module._load (internal/modules/cjs/loader.js:923:27)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)    at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
:ReactNative:Unexpected empty result of running '[node, C:\Users\xzq\Desktop\�?课吧\RN\AwesomeProject\node_modules\@react-native-community\cli\build\bin.js, config]' command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
![36d8a4c74ad7e905ce2575e28ddc44d](https://user-images.githubusercontent.com/44761976/102486322-d3ab5500-40a3-11eb-957b-9490a4e98b1f.png)

**Comment by sunnylqm** [comment]
请不要使用中文路径

**Comment by ningboxiazhengqi** [comment]
傻逼了我
