### ISSUE TITLE
有大佬知道这是什么问题吗

### ISSUE THREAD

**Issue by wangyao333** [reactnativecn/react-native-website#325]
PS D:\Download\LGCloudLinkZiliao\LGCloudLink> npx react-native run-android
Scanning folders for symlinks in D:\Download\LGCloudLinkZiliao\LGCloudLink\node_modules (253ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
useNewCruncher has been deprecated. It will be removed in a future version of the gradle plugin. New cruncher is now always enabled.
Incremental java compilation is an incubating feature.                                                  
File C:\Users\24638\.android\repositories.cfg could not be loaded.                                      
                                                                                                        
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-camera'.
      > Could not resolve all dependencies for configuration ':react-native-camera:_debugPublishCopy'.  
         > Could not resolve com.android.support:support-annotations:26.0.1.
           Required by:
               LGCloudLink:react-native-camera:unspecified > com.android.support:exifinterface:26.0.0-alpha1
            > Could not resolve com.android.support:support-annotations:26.0.1.
               > Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.0.1/support-annotations-26.0.1.pom'.
                  > Could not GET 'https://maven.google.com/com/android/support/support-annotations/26.0.1/support-annotations-26.0.1.pom'.
                     > Remote host closed connection during handshake
            > Could not resolve com.android.support:support-annotations:26.0.1.
               > Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.0.1/support-annotations-26.0.1.pom'.
                  > Could not GET 'https://maven.google.com/com/android/support/support-annotations/26.0.1/support-annotations-26.0.1.pom'.
                     > Connect to maven.google.com:443 [maven.google.com/216.58.199.110] failed: Read timed out
         > Could not resolve com.android.support:support-annotations:26.0.1.
           Required by:
               LGCloudLink:react-native-camera:unspecified > com.github.react-native-community:cameraview:cc47bb28ed2fc54a8c56a4ce9ce53edd1f0af3a5
               LGCloudLink:react-native-camera:unspecified > com.github.react-native-community:cameraview:cc47bb28ed2fc54a8c56a4ce9ce53edd1f0af3a5 > com.android.support:support-v4:26.0.1 > com.android.support:support-compat:26.0.1
               LGCloudLink:react-native-camera:unspecified > com.github.react-native-community:cameraview:cc47bb28ed2fc54a8c56a4ce9ce53edd1f0af3a5 > com.android.support:support-v4:26.0.1 > com.android.support:support-media-compat:26.0.1
               LGCloudLink:react-native-camera:unspecified > com.github.react-native-community:cameraview:cc47bb28ed2fc54a8c56a4ce9ce53edd1f0af3a5 > com.android.support:support-v4:26.0.1 > com.android.support:support-core-utils:26.0.1
               LGCloudLink:react-native-camera:unspecified > com.github.react-native-community:cameraview:cc47bb28ed2fc54a8c56a4ce9ce53edd1f0af3a5 > com.android.support:support-v4:26.0.1 > com.android.support:support-core-ui:26.0.1
            > Could not resolve com.android.support:support-annotations:26.0.1.
               > Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.0.1/support-annotations-26.0.1.pom'.
                  > Could not GET 'https://maven.google.com/com/android/support/support-annotations/26.0.1/support-annotations-26.0.1.pom'.
                     > Remote host closed connection during handshake
            > Could not resolve com.android.support:support-annotations:26.0.1.
               > Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.0.1/support-annotations-26.0.1.pom'.
                  > Could not GET 'https://maven.google.com/com/android/support/support-annotations/26.0.1/support-annotations-26.0.1.pom'.
                     > Connect to maven.google.com:443 [maven.google.com/216.58.199.110] failed: Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 33 mins 39.218 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by sunnylqm** [comment]
翻墙问题

**Comment by sunnylqm** [comment]
可以用阿里云maven源解决

**Comment by wangyao333** [comment]
大佬有阿里云maven源地址吗，谢谢

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/102505996-9e136580-40bd-11eb-8bfc-d26fa7dfde4c.png)
