### ISSUE TITLE
react-native-webview引入h5页面

### ISSUE THREAD

**Issue by hello-libiao** [reactnativecn/react-native-website#332]
请按以下格式提供问题的相关信息。

## 问题的具体描述
想调试h5页面，在h5页面进行打印捕获错误之类的操作，但是打印的信息不会显示在手机摇一摇的debug上，应该在哪里查看打印的信息，怎么去调试引入的h5页面，希望大佬解惑~

**Comment by sunnylqm** [comment]
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Debugging.md

**Comment by KouSyurei** [comment]
H5页面引用vconsle.min.js，手机屏幕会显示控制内容
