### ISSUE TITLE
React Native为什么移除了大量的内置组件

### ISSUE THREAD

**Issue by cheekhan** [reactnativecn/react-native-website#335]
想知道以后的生态会怎么变化，是否还有继续投入精力的价值

**Comment by sunnylqm** [comment]
https://github.com/react-native-community/discussions-and-proposals/issues/6

简单来说，官方希望把尽可能多的非核心组件移交给社区管理，使得依赖关系更简单，彼此迭代速度都可以更快。同时核心文件减少，利于减小app大小，提升启动速度，促进社区交流等等
