### ISSUE TITLE
Android project not found

### ISSUE THREAD

**Issue by cheekhan** [reactnativecn/react-native-website#336]
【版本信息】
"react-native": "0.63.4",
"react-native-camera": "^3.40.0",
【问题描述】
安装react-native-camera库后，重新运行项目 yarn android，提示以下错误信息
`
λ yarn android

yarn run v1.22.10

$ react-native run-android

error Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard location (e.g. not inside 'android' folder), consider setting ‘project.android.sourceDir’ option to point to a new location. Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
【问题】
请问这是什么问题，已经发生了好几次，在安装其他的npm包后，都提示Android project not found。

**Comment by sunnylqm** [comment]
可能是因为你修改了androidmanifest.xml文件，但是改错了某个地方

**Comment by cheekhan** [comment]
> 可能是因为你修改了androidmanifest.xml文件，但是改错了某个地方

确实是这样，可能是注释写的不对。这个文件应该对缩进没有什么要求吧
