### ISSUE TITLE
有大佬知道这个问题 A problem occurred configuring project ':react-native-camera'吗

### ISSUE THREAD

**Issue by wangyao333** [reactnativecn/react-native-website#337]
"react-native": "0.54.2",

build.gradle文件

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        //  classpath 'com.android.tools.build:gradle:3.0.0'
    //   classpath 'com.android.tools.build:gradle:3.3.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()

            maven {url 'https://maven.google.com'}

            // maven { url "http://maven.aliyun.com/nexus/content/groups/public/"}
        
            // maven {
            //     url "https://maven.aliyun.com/repository/public"
            // }
            // maven {
            //     url "https://maven.aliyun.com/repository/google"
            // }
            // maven {
            //     url "https://maven.aliyun.com/repository/gradle-plugin"
            // }
            // maven {
            //     url "https://maven.aliyun.com/repository/jcenter"
            // }
            // maven { url "https://dl.google.com/dl/android/maven2/"}
// maven{
//     url "https://maven.aliyun.com/nexus/content/repositories/central"
// }

            maven { url "https://jitpack.io" }

            
            maven {
                // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url "$rootDir/../node_modules/react-native/android"
            }
        
    }
}

ext {
    googlePlayServicesVersion = "11.8.0"
}

报错
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-camera'.
      > Could not resolve all dependencies for configuration ':react-native-camera:classpath'.
         > Could not download gradle.jar (com.android.tools.build:gradle:3.0.0)
            > Could not get resource 'https://maven.google.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar'.
               > Could not GET 'https://maven.google.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar'.
                  > Connect to maven.google.com:443 [maven.google.com/216.58.200.46] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 33.291 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by sunnylqm** [comment]
翻墙问题，可用阿里云mave镜像源解决

**Comment by wangyao333** [comment]
你有什么源可以推荐吗，谢谢

**Comment by sunnylqm** [comment]
？？上面不是说了阿里云吗

**Comment by sunnylqm** [comment]
一模一样的问题又问了一遍？
https://github.com/reactnativecn/react-native-website/issues/325#issuecomment-747500182

**Comment by wangyao333** [comment]
我说的意思阿里云的源可以推荐，因为阿里云的源都试过没用

**Comment by sunnylqm** [comment]
不可能没用的
