### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by chenofgit** [reactnativecn/react-native-website#343]
安装官方文档初始化项目 Xcode 报错

Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sunnylqm** [comment]
升级xcode到11.6版本以上

**Comment by chenofgit** [comment]
升级Xcode11.7 已解决。多谢
