### ISSUE TITLE
某些机型配置状态栏透明后依然还是有遮罩

### ISSUE THREAD

**Issue by xiongyuezheng** [reactnativecn/react-native-website#345]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- android/app/src/main/res/values/styles配置完状态栏透明后配置截图如下：
- 
<img width="545" alt="微信图片_20210112161913" src="https://user-images.githubusercontent.com/42833565/104288392-b460e580-54f2-11eb-8b7d-1bd6fb764981.png">
<img width="248" alt="微信图片_20210112162030" src="https://user-images.githubusercontent.com/42833565/104288399-b5921280-54f2-11eb-9b0a-fc2032148c5c.png">

## 预期结果
- 如何处理部分机型出现的这个问题。如果哪位大佬处理过的可以分享的话分享一下谢谢。

**Comment by sunnylqm** [comment]
不要去改原生配置，直接用rn自带的statusbar模块啊
