### ISSUE TITLE
RN在Chrome调试中报错

### ISSUE THREAD

**Issue by bald-donkey** [reactnativecn/react-native-website#348]
Calling synchronous methods on native modules is not supported in Chrome.
Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.

**Comment by sunnylqm** [comment]
如果是调用Appearance模块引起的，那么升级到0.63以上可以解决
否则得看具体是哪个原生模块引起的

**Comment by bald-donkey** [comment]
> 如果是调用Appearance模块引起的，那么升级到0.63以上可以解决
> 否则得看具体是该原生模块引起的

我遇到的问题详细描述如下：
1.RN在调试运行时，打开chrom，此时真机上运行正常
2. 当我与真机产生交互时（真机与电脑通过USB连接），程序报以下错误：
Calling synchronous methods on native modules is not supported in Chrome.
Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.

怎样能使真机在交互时能去正常运行，并且能在chrome的consloe上正常打印调试

真机是机器人，用的语言是ReactNative

**Comment by sunnylqm** [comment]
如果是代码中有调用Appearance模块，且RN版本是0.62的话，这是个已知的问题，升级到0.63可以解决

如果不是上面的情况，那可能是某个第三方的模块引起的，具体你没有列出使用了哪些原生模块，无从判断
