### ISSUE TITLE
RN在Chrome中调试，报错Calling synchronous methods on native modules is not supported in Chrome.

### ISSUE THREAD

**Issue by bald-donkey** [reactnativecn/react-native-website#349]
1.RN在调试运行时，打开chrom，此时真机上运行正常
2. 当我与真机产生交互时（真机与电脑通过USB连接），程序报以下错误：
Calling synchronous methods on native modules is not supported in Chrome.
Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.

怎样能使真机在交互时能去正常运行，并且能在chrome的consloe上正常打印调试

真机是机器人，用的语言是ReactNative

**Comment by arrywu** [comment]
我遇到同样的问题，目前无法解决，有人能帮忙吗？
https://stackoverflow.com/questions/61067004/invariant-violation-calling-synchronous-methods-on-native-modules-is-not-suppor上的方法试过，不再报错，但再也不能进入debug状态
