### ISSUE TITLE
yarn android  之后报错，在Android Studio 可以运行

### ISSUE THREAD

**Issue by zhaozhuangwang** [reactnativecn/react-native-website#351]
Mac 10.15.7 系统 
根据官方文档配置后运行项目报错，但是在Android Studio 里运行可以的，问题如下！

- 在项目中  yarn android  之后报错
- info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_3a_API_30_x86(AVD) - 11' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 6s
28 actionable tasks: 2 executed, 26 up-to-date
info Connecting to the development server...
warn Failed to connect to development server using "adb reverse": spawnSync adb ENOENT
info Starting the app...
error Failed to start the app. Run CLI with --verbose flag for more details.
Error: spawnSync adb ENOENT
    at Object.spawnSync (internal/child_process.js:1067:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ------------------------------------------------------------------------
Android Studio   4.1.1  ，jdk按照官方配置的 ，默认的模拟器可以运行

![image](https://user-images.githubusercontent.com/42265723/104869365-d0480980-5980-11eb-95fb-68bfb1d26500.png)

但是把 android  目录在 Android Studio 里手动运行是可以的  但是官方推荐的 q 29 运行是黑屏

![image](https://user-images.githubusercontent.com/42265723/104869156-44ce7880-5980-11eb-9bd4-419549aea509.png)

package.json 配置

![image](https://user-images.githubusercontent.com/42265723/104869229-78110780-5980-11eb-8c4c-28dd78eb9c1e.png)

两个问题  
1 是在终端 yarn android  之后未能运行项目  ，Android Studio 手动可以运行，
![image](https://user-images.githubusercontent.com/42265723/104869714-a4795380-5981-11eb-8be3-e5724f84eebb.png)

2 模拟器，默认的模拟器可以运行，q29 运行之后黑屏，

是我哪里配置有问题？谢谢赐教！

**Comment by sunnylqm** [comment]
1、在as中运行后，需要额外手动运行yarn start 以启动metro服务
2、q29运行黑屏难说具体什么原因，可能也是导致yarn android启动失败的问题。可以删掉重建再试试。

**Comment by zhaozhuangwang** [comment]
首先谢谢兄台的回答！
现在我是这样操作的
iOS部分 我是run-ios  运行的
安卓部分  我是直接在as里运行的模拟器后 启动的， 跟直接点。  （一开始我是以为与ios一样那种，还我哪里配置错了，
关于 q29 即使在as里运行也不行，  创建两个项目了，
是我哪里还少点配置么？

**Comment by sunnylqm** [comment]
？我的回答还是一样啊？



---Original---

**Comment by sunnylqm** [comment]
只要能编译通过，那么配置就没有问题




至于某个模拟器不能启动，不清楚原因，也没有必要去深究，删除重建甚至换用模拟器都可以



---Original---

**Comment by zhaozhuangwang** [comment]
好的吧！，谢谢你的回答！
确实不影响开发，只是喜欢丝滑 哈哈，

**Comment by KevinHao1314** [comment]
如果可以，还是直接用真机测试吧，流畅多了
