### ISSUE TITLE
yarn android出错！

### ISSUE THREAD

**Issue by lixiansen1511** [reactnativecn/react-native-website#353]
yarn [android报错！]

用代理，改host都试过没用！

Connection refused:connect
IOExpection https://dl.google.com/android/repository/addons_list-3.xml
IOExpection https://dl.google.com/android/repository/addons_list-2.xml
......

**Comment by sunnylqm** [comment]
那这没办法，只能接着尝试更换代理

**Comment by KevinHao1314** [comment]
这种用下vpn就解决了
