### ISSUE TITLE
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. 

### ISSUE THREAD

**Issue by xiongyuezheng** [reactnativecn/react-native-website#355]
第一次使用黑苹果开发react native的iOS端，但是按官网的步骤将环境搭建好以后，创建一个项目，结果跑起来的时候报了这个错：error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. 找了很多解决方案，还爱不行，哪位大佬遇到过这个问题解决过的，请教一下。谢谢。

**Comment by sunnylqm** [comment]
用xcode运行看具体错误



---Original---

**Comment by xiongyuezheng** [comment]
linker command failed with exit code 1 (use -v to see invocation). xcode运行报这个错误。

**Comment by xiongyuezheng** [comment]
ld: warning: directory not found for option '-L/Users/xiongyuezheng/Downloads/Xcode 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator'
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)





Showing Recent Issues
:-1: directory not found for option '-L/Users/xiongyuezheng/Downloads/Xcode 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator'

:-1: symbol(s) not found for architecture x86_64

:-1: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sunnylqm** [comment]
升级xcode到11.6版本以上



---Original---

**Comment by xiongyuezheng** [comment]
请教一下大佬，我下载了一个Xcode 11.7的装不上去，我的系统是，10.14.6的，在不升级系统的情况下，如何解决上上述问题？谢谢。

**Comment by sunnylqm** [comment]
如果xcode要求新的系统版本，那么没办法，只能升级系统，要么你就降级到xcode10试试

**Comment by xiongyuezheng** [comment]
大佬，Xcode 11.3.1都不行，找到一个低版本系统安装高版本的xcode的办法，我装好了可以了，确实需要高一些的Xcode版本才行。感谢大佬，项目跑起来了。

**Comment by sunnylqm** [comment]
xcode 11 中11.6以下都有这个bug，但是xcode10系列可以

**Comment by xiongyuezheng** [comment]
有个问题请教一下大佬，前一天Xcode编译还好好的，第二天跑的时候就一直卡在，loading dependency graph, done.  等了很久了快一个小时了还卡在这个位置，请问一下怎么处理这个问题，谢谢。

**Comment by sunnylqm** [comment]
metro的运行和xcode完全无关，不知道你在说什么

**Comment by xiongyuezheng** [comment]
已经处理好了，谢谢。

**Comment by ArthurYung** [comment]
请问怎么处理的？

**Comment by song52wow** [comment]
![image](https://user-images.githubusercontent.com/22537086/116354062-70d48200-a82a-11eb-821b-060f7dd0357e.png)

@sunnylqm 请问这个是什么问题？

**Comment by sunnylqm** [comment]
@song52wow 目前不兼容xcode12.5版本，待官方修复 https://github.com/facebook/react-native/issues/31179

**Comment by song52wow** [comment]
Get, Thx @sunnylqm
