### ISSUE TITLE
Image require 请求问题 ，请教大佬

### ISSUE THREAD

**Issue by Shilver-afka** [reactnativecn/react-native-website#358]
我打算抽象出一个头像组件，准备通过父组件传递props.src的形式传递给Image的require  。具体代码 ：
let src="../../Public/JPG/gril.jpg"  
let srt=props.src+"";  
console.log(srt.length,src.length);  
console.log(typeof src,typeof srt)  
if(srt===src){  
  console.log("yes");  
}  
return (`   
           <View>  
                  <Image source={require(src)}/>   //在这里替换成srt
           </View>`
）；
运行结果 ：
[Sat Jan 23 2021 12:57:37.930]  LOG      25 25
[Sat Jan 23 2021 12:57:37.939]  LOG      string string
[Sat Jan 23 2021 12:57:37.940]  LOG      yes

为什么src 可以通过，而将src替换成srt却报 Error: TransformError Src\Avatar\Avatar.js: Src\Avatar\Avatar.js:Invalid call at line 13: require(srt)]错误。

**Comment by sunnylqm** [comment]
https://reactnative.cn/docs/images

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/105572435-11318b00-5d92-11eb-92a5-ba85dd7bb88e.png)

**Comment by liao-tian-8** [comment]
你连文档都不看的？
