### ISSUE TITLE
win10 npm run  android遇到问题

### ISSUE THREAD

**Issue by w2015long** [reactnativecn/react-native-website#360]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 如果是安装过程中的问题，请再三确认你有使用稳定的翻墙工具，且翻墙工具对命令行有生效（如开启全局模式等等）
- 请说明具体操作步骤和现象（例如执行什么命令，或者点击哪里，出现了什么异常现象或错误信息）
- 请尽量配上相关报错截图
- Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cpgame@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cpgame@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2021-01-25T03_33_26_527Z-debug.log
截图
![image](https://user-images.githubusercontent.com/45002790/105658369-4d372e00-5f01-11eb-9faf-bb8df237e82c.png)

   - 如果设备上有红屏报错请直接截图
   - 如果命令行有报错请直接截图
   - 警告(warning)一般不用管
   - 如果设备上看不到报错，请先尝试[调试模式](https://reactnative.cn/docs/debugging)。
   - 如果是发行版本无法调试，对于安卓设备请使用[adb logcat命令](https://developer.android.google.cn/studio/command-line/logcat)来捕获日志并粘贴到这里。iOS设备查看日志的[一些方法](https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a)。
- 请尽量配上相关代码截图

## 请描述完整的环境/版本信息
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 4.13 GB / 15.87 GB
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_131
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.63.2 => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
- 请在命令行的项目目录中运行`react-native info`命令，并将其输出结果粘贴到这里。

## 预期结果
配置环境应该没有问题 我从官网拉的react native demo连接上安卓模拟器就可以运行 
但是这个项目有问题
而且这个项目用mac不需要怎么配置环境 mac完全可以运行并启动这个项目 我用window就报了这个错误

**Comment by sunnylqm** [comment]
这个是环境变量设置有问题

**Comment by w2015long** [comment]
卸载又重新按官网配置一遍，还是老样子

**Comment by sunnylqm** [comment]
环境变量的配置，为什么要卸载？

**Comment by w2015long** [comment]
不是 
卸载android studio重装 并且 按照官网看了环境变量没有问题 路径也对
![image](https://user-images.githubusercontent.com/45002790/105666577-8927be80-5f14-11eb-8e8d-4f72ca0e2fda.png)

![image](https://user-images.githubusercontent.com/45002790/105666479-4a920400-5f14-11eb-9373-2da07a29fd7a.png)

**Comment by sunnylqm** [comment]
看下PATH变量

**Comment by w2015long** [comment]
![image](https://user-images.githubusercontent.com/45002790/105667175-c771ad80-5f15-11eb-8345-ee2a5dcc6840.png)

**Comment by sunnylqm** [comment]
第一个javapath是什么

**Comment by sunnylqm** [comment]
看起来没问题，那大概这个项目的gradle.bat改错了什么地方

**Comment by w2015long** [comment]
帮我看一下gradle.bat文件
我油箱
w2015long@qq.com

**Comment by w2015long** [comment]
我可以把这个文件发你邮箱嘛，帮我看一下吧
打扰了

**Comment by sunnylqm** [comment]
我没有研究，可以考虑直接新建个同版本的项目，把同名文件复制过来覆盖

**Comment by duobancc** [comment]
> 不是
> 卸载android studio重装 并且 按照官网看了环境变量没有问题 路径也对
> ![image](https://user-images.githubusercontent.com/45002790/105666577-8927be80-5f14-11eb-8e8d-4f72ca0e2fda.png)
> 
> ![image](https://user-images.githubusercontent.com/45002790/105666479-4a920400-5f14-11eb-9373-2da07a29fd7a.png)

碰到了相同的问题，我检查了java 的环境变量，然后解决了， 只配置了 JAVA_HOME 、CLASSPATH、JDK ， 没有配置JRE, 然后系统和用户应该 只需要配置一个就可以了，一般都是系统

**Comment by duobancc** [comment]
![image](https://user-images.githubusercontent.com/37232082/117116431-f2935500-adc0-11eb-9e6c-45cfb46e3edd.png)
![image](https://user-images.githubusercontent.com/37232082/117116606-22daf380-adc1-11eb-94f8-d87039dd23a3.png)
