### ISSUE TITLE
android studio run app:时 npm start出现错误并且 连接不上模拟器

### ISSUE THREAD

**Issue by w2015long** [reactnativecn/react-native-website#362]
请按以下格式提供问题的相关信息。

## 问题的具体描述
cmd npm start报错如下
internal/fs/watchers.js:177
    throw error;
    ^

Error: ENOENT: no such file or directory, watch 'D:\work\zhp-app\android\app\build\intermediates\transforms\dexBuilder\development\debug\0\androidx\activity'
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1415:11)
    at NodeWatcher.watchdir (D:\work\zhp-app\node_modules\sane\src\node_watcher.js:159:22)
    at Walker.<anonymous> (D:\work\zhp-app\node_modules\sane\src\common.js:109:31)
    at Walker.emit (events.js:315:20)
    at D:\work\zhp-app\node_modules\walker\lib\walker.js:69:16
    at FSReqCallback.oncomplete (fs.js:155:23) {
  errno: -4058,
  syscall: 'watch',
  code: 'ENOENT',
  path: 'D:\\work\\zhp-app\\android\\app\\build\\intermediates\\transforms\\dexBuilder\\development\\debug\\0\\androidx\\activity',
  filename: 'D:\\work\\zhp-app\\android\\app\\build\\intermediates\\transforms\\dexBuilder\\development\\debug\\0\\androidx\\activity'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cpgame@0.0.1 start: `react-native start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cpgame@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2021-01-29T02_01_43_284Z-debug.log
## 请描述完整的环境/版本信息
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 6.62 GB / 15.87 GB
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
。

## 预期结果
使用android studio连不上模拟器?

**Comment by sunnylqm** [comment]
as能正常编译并运行吗？如果可以的话，建议编译运行完成之后再运行npm start，不要两者同时运行

**Comment by w2015long** [comment]
我的操作是
1：android studio先 build 并且成功 BUILD SUCCESSFUL in 13s
2: 然后在终端npm start 也正常
3:就是在as 点击上方的run App 后 终端死掉了 上面的错误就是终端报错

**Comment by sunnylqm** [comment]
我上面已经说过了啊？两者不要同时运行

**Comment by w2015long** [comment]
谢谢 回答 
我先操作的第一步 as build成功后才操作第二步 终端npm start
两者 先后顺序的 这些 都是正常的
关键第三步 出问题了

**Comment by sunnylqm** [comment]
那就没有第三步了啊，第三步和第一步不是重复的吗？

**Comment by w2015long** [comment]
![图片](https://user-images.githubusercontent.com/45002790/106226808-027c2580-6223-11eb-8d7e-6430dc326e28.png)

**Comment by w2015long** [comment]
上面的上传的图片你那边显示吗
就是第三步 点击run app启动模拟器 有问题

**Comment by sunnylqm** [comment]
正常的流程（以下三选一）：
1、不用as，直接yarn android （它自动启动模拟器，编译，安装，运行同时自动yarn start）
2、手动启动模拟器，点击模拟器上之前已经装好的app，然后yarn start ，刷新
3、在as里点run（不用点build，run已经包含了build），等模拟器和app跑起来，然后yarn start， 刷新

**Comment by w2015long** [comment]
谢谢哈
我用你的第三个方案
在as里点run 正常成功了 可是没有弹出模拟器APP

然后yarn start也正常

奇怪的是没有弹出模拟器APP

**Comment by sunnylqm** [comment]
那就删了模拟器镜像重新创建模拟设备

**Comment by w2015long** [comment]
[抱拳][抱拳]
1.其实的说的方案一 我之前是用过的连接夜神模拟器 直接npm android 不行有报错
2.第三个方案 我删了模拟器镜像 重新创建模拟设备 还是老样子 弹不出模拟器

**Comment by sunnylqm** [comment]
那就手动打开模拟器
