### ISSUE TITLE
yarn android 出错

### ISSUE THREAD

**Issue by TianYu0605** [reactnativecn/react-native-website#367]
![image](https://user-images.githubusercontent.com/49590847/106720413-6b5a0800-663e-11eb-8e5f-1b60b0cbaf68.png)

**Comment by sunnylqm** [comment]
![gradle](https://user-images.githubusercontent.com/615282/106722196-9e9d9680-6640-11eb-9f8d-0a52e5308e37.png)

**Comment by TianYu0605** [comment]
![image](https://user-images.githubusercontent.com/49590847/106729448-7154e680-6648-11eb-8b5e-5e2d7143585e.png)
大佬，执行一般突然停止了

**Comment by sunnylqm** [comment]
你这个已经执行完成了
