### ISSUE TITLE
ScrollView效果

### ISSUE THREAD

**Issue by Shilver-afka** [reactnativecn/react-native-website#368]
我想实现如上图的效果，红色区域是背景图片，上滑红色区域被卷去，第二个元素吸顶，选项卡A和选项B都有滚动条，我使用
ScrollVIew嵌套的形式，通过判断滚动条的位置，利用scrollEnabled达到滚动条控制交换。但是在交界处有卡顿。大佬有没有什么好的建议。
![效果图](https://user-images.githubusercontent.com/68523529/106770194-af69fe80-6678-11eb-92b1-650e18104a85.jpg)

**Comment by sunnylqm** [comment]
scrollview单独做不了的，必须要用gesture-handler + animated来做，我只能说比较复杂，但应该也有一些现成的接近的第三方组件，自己找找吧

**Comment by matthew-maozhu-wang** [comment]
哈喽，请问这个问题你有解决吗？我现在项目有类似的效果需要实现，也是在交界的地方会有问题，需要手机释放重新滑动才有效果
