### ISSUE TITLE
如何去掉项目启动时显示项目名称的白色界面

### ISSUE THREAD

**Issue by xiongyuezheng** [reactnativecn/react-native-website#369]
请教一下大佬，android 和 iOS 同一套代码，在iOS中启动项目时出现的带有项目名称的白色界面如何去掉？我查了一下，有人说的是，直接删掉LaunchScreen.xib就行，我尝试了删掉了还是不行，请问一下在Xcode中如何设置才能去掉这个带项目名称的白色界面？  谢谢。

**Comment by sunnylqm** [comment]
最新版本是LaunchScreen.storyboard

**Comment by xiongyuezheng** [comment]
![Simulator Screen Shot - iPhone 8 - 2021-02-04 at 15 41 24](https://user-images.githubusercontent.com/42833565/106860740-c273e180-66ff-11eb-9697-538345e8b701.png)

这样的，启动页自己写了，所有有没有办法在启动项目的时候不展示这个页面。

**Comment by sunnylqm** [comment]
只能修改/更换，不能去掉（苹果的要求）

**Comment by xiongyuezheng** [comment]
好的明白了，谢谢。
