### ISSUE TITLE
ios项目编译失败请看这里(event2/event-config.h)

### ISSUE THREAD

**Issue by Mr-SanShou** [reactnativecn/react-native-website#370]
附图vscode运行截图：
![image](https://user-images.githubusercontent.com/73738964/106991427-24d8ea80-67b1-11eb-9bf1-82216bf0ab25.png)

附图xcode报错截图：
![image](https://user-images.githubusercontent.com/73738964/106991564-75e8de80-67b1-11eb-9726-537411a50a6f.png)

xcode版本：12.4

**Comment by sunnylqm** [comment]
Flipper的一个依赖有问题，更新到最新版本可解决
首先cocoapods需要更新到1.10版本以上

```sh
sudo gem install cocoapods
```

然后修改Podfile中的use_filpper那行，添加版本

```
use_flipper!({ 'Flipper' => '0.75.1' })
```

删掉Podfile.lock文件以及pods目录
重新在ios目录下执行

```
pod install
```

**Comment by Mr-SanShou** [comment]
@sunnylqm    改了跑起来还是没用啊
![image](https://user-images.githubusercontent.com/73738964/106999637-85702380-67c1-11eb-9c01-3a1c87b431ad.png)

**Comment by sunnylqm** [comment]
删掉Podfile.lock后重新pod install

**Comment by Mr-SanShou** [comment]
@sunnylqm 
![image](https://user-images.githubusercontent.com/73738964/107000461-dd5b5a00-67c2-11eb-9f40-e6610c8e3c99.png)

**Comment by sunnylqm** [comment]
删掉`Podfile.lock`  不是 `Podfile`
以及`pod install`命令是在`项目/ios`目录中执行，而不是项目根目录中

**Comment by Mr-SanShou** [comment]
@sunnylqm 感谢大佬 成功了

**Comment by xiutingwangGitHub** [comment]
> Flipper的一个依赖有问题，更新到最新版本可解决
> 修改Podfile中的use_filpper那行，添加版本
> 
> ```
> use_flipper!('Flipper' => '0.75.1')
> ```
> 
> 删掉Podfile.lock后重新在ios目录下执行pod install

请问改了以后下载就会卡住，不改就不会卡，我的网络应该能联上

**Comment by hw20101101** [comment]
@sunnylqm 

按照楼主说的改了，也删掉了 Podfile.lock，但是在 ios 目录下执行 pod install 时报错，如下：
Invalid `Podfile` file: unknown keyword: "Flipper".


Podfile文件如下：
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ReactDemo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ReactDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.75.1')
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ReactDemo-tvOS' do
  # Pods for ReactDemo-tvOS

  target 'ReactDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

```

**Comment by sunnylqm** [comment]
报错截图看下，还有执行npx react-native info看下

**Comment by hw20101101** [comment]
@sunnylqm 

<img width="782" alt="WX20210226-101722@2x" src="https://user-images.githubusercontent.com/9107226/109245701-f84a4880-781b-11eb-8416-180a932ffdb7.png">

![Xnip2021-02-26_10-33-03](https://user-images.githubusercontent.com/9107226/109247150-5e37cf80-781e-11eb-92c4-1da237d06760.jpg)

**Comment by sunnylqm** [comment]
不好意思，少了括号，应该是
use_flipper!({ 'Flipper' => '0.75.1' })

**Comment by hw20101101** [comment]
@sunnylqm 😭  好的，我再试试，谢谢！！

**Comment by yanglvyou** [comment]
@sunnylqm  按照楼主说的改了，重新在ios下删掉了Podfile.lock，pod install, 但是还是不行!
<img width="1126" alt="截屏2021-02-28 下午7 45 03" src="https://user-images.githubusercontent.com/40206669/109417283-e45e3c80-79fd-11eb-8edd-c028c8ee6098.png">
<img width="988" alt="截屏2021-02-28 下午7 46 59" src="https://user-images.githubusercontent.com/40206669/109417284-e6c09680-79fd-11eb-856f-f5ccc43a25a7.png">

**Comment by sunnylqm** [comment]
@yanglvyou 有什么报错

**Comment by yanglvyou** [comment]
@sunnylqm 就我发的第一张图的报错

**Comment by cmcreborn** [comment]
> @sunnylqm 按照楼主说的改了，重新在ios下删掉了Podfile.lock，pod install, 但是还是不行!
> <img alt="截屏2021-02-28 下午7 45 03" width="1126" src="https://user-images.githubusercontent.com/40206669/109417283-e45e3c80-79fd-11eb-8edd-c028c8ee6098.png">
> <img alt="截屏2021-02-28 下午7 46 59" width="988" src="https://user-images.githubusercontent.com/40206669/109417284-e6c09680-79fd-11eb-856f-f5ccc43a25a7.png">

pod install 或 pod update 有错误讯息吗？还是都正常install好没问题？
我用相同版本的Flipper 正常没问题

**Comment by sunnylqm** [comment]
@yanglvyou 报错要看xcode的截图

**Comment by yanglvyou** [comment]
@sunnylqm  
<img width="704" alt="截屏2021-03-03 下午5 54 40" src="https://user-images.githubusercontent.com/40206669/109788013-cbe26200-7c49-11eb-9eef-09934f4a23eb.png">

**Comment by sunnylqm** [comment]
@yanglvyou 8081端口被占了，比如mcafee什么的

**Comment by yanglvyou** [comment]
@sunnylqm  惭愧，多谢了！

**Comment by Walker023** [comment]
![image](https://user-images.githubusercontent.com/29306180/110657060-7e429800-81fb-11eb-93d6-be12f0741f5d.png)
![image](https://user-images.githubusercontent.com/29306180/110657292-af22cd00-81fb-11eb-92eb-aa513bd0426a.png)
@sunnylqm 一直运行不起来，救救孩子T_T

**Comment by sunnylqm** [comment]
@Memoried 
https://github.com/facebook/react-native/issues/30922#issuecomment-778700328
cocoapods的版本问题
升级下cocoapods，删pods目录，删podfile.lock，再pod install试试

**Comment by Walker023** [comment]
> @Memoried
> [facebook / react-native＃30922（评论）](https://github.com/facebook/react-native/issues/30922#issuecomment-778700328)
> cocoapods的版本问题
> 升级下cocoapods，删除了pods目录，删除了podfile.lock，再将pod安装试试

终于跑起来了，谢谢大佬~

**Comment by Morphone0429** [comment]
![image](https://user-images.githubusercontent.com/30744484/110765088-c6f76100-828e-11eb-819d-33ef60b381d8.png)我这个是什么问题
 @sunnylqm

**Comment by sunnylqm** [comment]
@Morphone0429 截xcode中的图

**Comment by Morphone0429** [comment]
@sunnylqm  非常抱歉，rn是个纯新手，已经搞了一天了 xcode报错
![image](https://user-images.githubusercontent.com/30744484/110772309-6f5cf380-8296-11eb-8b17-7c74ab59e5f3.png)

**Comment by sunnylqm** [comment]
@Morphone0429 pod install有任何报错吗

**Comment by Morphone0429** [comment]
@sunnylqm   pod install没有报错  我已经翻墙了,应该没什么问题

**Comment by sunnylqm** [comment]
@Morphone0429 你清掉pods目录，重新pod install截图看看

**Comment by Morphone0429** [comment]
@sunnylqm  我把boost-for-react-native删除下载多次了  确定有这个文件，但是xcode中好像缺少
![image](https://user-images.githubusercontent.com/30744484/110776895-7d614300-829b-11eb-92cf-8b6d47ceeebf.png)

![image](https://user-images.githubusercontent.com/30744484/110776707-5571df80-829b-11eb-9ff7-c23a6c5e22f4.png)

**Comment by sunnylqm** [comment]
你是不是用了legacy build system? @Morphone0429

**Comment by Morphone0429** [comment]
@sunnylqm xcode我都是默认的配置没有动过
![image](https://user-images.githubusercontent.com/30744484/110780221-6b819f00-829f-11eb-9306-98f47ac0ddd7.png)

**Comment by sunnylqm** [comment]
@Morphone0429 加我qq34731408 详细看看

**Comment by Morphone0429** [comment]
@sunnylqm  已加 感谢大佬

**Comment by Morphone0429** [comment]
我上面的解决方法是  
pod cache clean --all 全局操作
进自己的项目再删pods  重新pod install
已成功运行

**Comment by caiNiao0820** [comment]
![image](https://user-images.githubusercontent.com/51197178/111915964-bc6d7080-8ab3-11eb-8858-1ddd47386eae.png)
![Uploading image.png…]()

**Comment by caiNiao0820** [comment]
![image](https://user-images.githubusercontent.com/51197178/111916094-4584a780-8ab4-11eb-9549-28d2e9818a95.png)
![image](https://user-images.githubusercontent.com/51197178/111916095-49182e80-8ab4-11eb-886f-1e8d977b8fe1.png)

**Comment by fengdanbailu** [comment]
楼主帮忙看下
1）运行yarn ios报错如下：
/Users/gmchen/MyProgram/git_devops/xcode/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'YogaKit' from project 'Pods')
warning: no rule to process file '/Users/gmchen/MyProgram/git_devops/xcode/AwesomeProject/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/gmchen/MyProgram/git_devops/xcode/AwesomeProject/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/gmchen/MyProgram/git_devops/xcode/AwesomeProject/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')

** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/gmchen/Library/Developer/Xcode/DerivedData/AwesomeProject-dvjmlbqepqobejhakrsaiztjbanw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-EEDB620F0153517E5A4A90B5722E6E65.sh
(1 failure)

info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2）运行npx react-native info，如下：
ogon:AwesomeProject gmchen$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 2.23 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5/12E5244e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
bogon:AwesomeProject gmchen$ pwd
/Users/gmchen/MyProgram/git_devops/xcode/AwesomeProject

3）更改  use_flipper!({ 'Flipper' => '0.75.1' })，并删除podfile.lock，再pod install；仍然是相同的错误。（ios模拟器启动了）

**Comment by sunnylqm** [comment]
@fengdanbailu 我注意到你的xcode版本是12.5，这个有已知的不兼容问题，https://github.com/facebook/react-native/issues/31179    

建议始终使用xcode的正式版而不是测试版（而且正式版也尽量不要第一时间更新）

**Comment by fengdanbailu** [comment]
改成商店的12.4版本了，问题依旧存在，你有什么思路，我可从哪几方面做尝试呢？
模拟器能运行起来，然后窗口还是报相同的错误

**Comment by fengdanbailu** [comment]
我的重启可以了在模拟器运行了，谢了。经验教训xcode不能升级太快。

**Comment by chieway** [comment]
为什么生成的项目没有podfile.lock文件啊

**Comment by sunnylqm** [comment]
说明pod install没有完成



---Original---
From: ***@***.***&gt;
Sent at: 2021年3月26日(Fri) Noon11:16
To: ***@***.***&gt;;
Cc: "Sunny ***@***.******@***.***&gt;;
Subject: Re: [reactnativecn/react-native-website] ios项目编译失败请看这里(event2/event-config.h) (#370)




 
为什么生成的项目没有podfile.lock文件啊

**Comment by mobei12** [comment]
我的是build不成
![image](https://user-images.githubusercontent.com/15901240/113080049-cbb59200-9208-11eb-9671-8446bfa0b763.png)
@sunnylqm

**Comment by sunnylqm** [comment]
报错已经说了，需要你去掉PREFIX这个环境变量

**Comment by mobei12** [comment]
> 报错已经说了，需要你去掉PREFIX这个环境变量
去掉以后就到这了,
![image](https://user-images.githubusercontent.com/15901240/113098205-c406e500-922a-11eb-9e3e-81b311b4e219.png)
我用x-code直接跑的话,可以启动Metro服务
![image](https://user-images.githubusercontent.com/15901240/113098317-e8fb5800-922a-11eb-92a7-435bc3da4025.png)

**Comment by sunnylqm** [comment]
点下那个xcode里的红叉，看下具体报错

**Comment by mobei12** [comment]
> 点下那个xcode里的红叉，看下具体报错
感觉又回来了😂,第一次用Xcode这些,不是很懂
![image](https://user-images.githubusercontent.com/15901240/113102084-1b5b8400-9230-11eb-8548-a27b6bdca690.png)

**Comment by sunnylqm** [comment]
说明你的环境变量没有去掉啊

**Comment by OceanFlooor** [comment]
请问我这个是什么问题？
<img width="849" alt="DEC37890-5A90-460D-9729-EF044D7F1C98" src="https://user-images.githubusercontent.com/41851552/115962876-f832a480-a54f-11eb-88a3-8606944c0ad7.png">

**Comment by DebbieL** [comment]
![image](https://user-images.githubusercontent.com/33309873/129684231-dcccb26d-9374-4d43-a98f-e7450a3d6e27.png)

The app identifier "org.reactjs.native.example.AwesomeProject" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again.

求问各位大佬这是咋肥事？

**Comment by sunnylqm** [comment]
@DebbieL 无关的问题请重新开贴。你这个问题截图已经说得很清楚了，换个名字（bundle identifier）完事。

**Comment by DebbieL** [comment]
> @DebbieL 无关的问题请重新开贴。你这个问题截图已经说得很清楚了，换个名字（bundle identifier）完事。

好的，谢谢～
