### ISSUE TITLE
ios提交应用商城反馈问题

### ISSUE THREAD

**Issue by xiongyuezheng** [reactnativecn/react-native-website#372]
请教一下大佬，ios打包上传苹果应用商城审核后邮件反馈为：ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
我通过终端在项目的iOS文件夹下执行：grep -r UIWebView .命令后得到：Binary file ./RN_App.xcodeproj/project.xcworkspace/xcuserdata/xiongyuezheng.xcuserdatad/UserInterfaceState.xcuserstate matches

请教一下UserInterfaceState.xcuserstate这个文件我该怎么改？  谢谢。

**Comment by sunnylqm** [comment]
如果rn版本低于0.60，需要手动移除相关代码或者升级到0.60以上
如果rn已经在0.60以上，那么需要检查第三方，常见的比如一些比较老的微信组件有这个问题，需要更新sdk

**Comment by xiongyuezheng** [comment]
我的rn版本是0.59.9的，我全局检索了查不到有关UIWebView代码，但是一打包就出现在UserInterfaceState.xcuserstate文件中，有点迷。

**Comment by sunnylqm** [comment]
因为代码在node_modules中，全局搜索一般不会搜索第三方的目录

**Comment by xiongyuezheng** [comment]
对了，现在找到了一一个是react-narive-wechat这个库中的libWeChatSDK. a里面含得有，我查了一下这个库目前的最新版本是1.9.12，我的版本也是这个版本，但是这个文件我无法编辑，现在卡在这个位置。

**Comment by sunnylqm** [comment]
你可以直接替换掉libWebChatSDK.a，但同时你也需要升级rn或者替换rn中相关的webview代码（建议升级）

**Comment by luckyGTL** [comment]
> 请教一下大佬，ios打包上传苹果应用商城审核后邮件反馈为：ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). 我通过终端在项目的iOS文件夹下执行：grep -r UIWebView .命令后得到：Binary file ./RN_App.xcodeproj/project.xcworkspace/xcuserdata/xiongyuezheng.xcuserdatad/UserInterfaceState.xcuserstate matches
> 
> 请教一下UserInterfaceState.xcuserstate这个文件我该怎么改？ 谢谢。

我也碰到了这个问题，我的rn版本是0.66的，请问你是怎么解决的
