### ISSUE TITLE
运行run-android后，开始下载gradle，但解压报错。

### ISSUE THREAD

**Issue by 826327700** [reactnativecn/react-native-website#373]
平台：mac
rn版本：0.63.4
![image](https://user-images.githubusercontent.com/23014381/107192209-514a6c00-6a28-11eb-803f-5fd675dda1f3.png)

文字版报错：
Could not unzip /var/root/.gradle/wrapper/dists/gradle-6.2-all/74ez15qvgms12zoi6xyxw9rrs/gradle-6.2-all.zip to /var/root/.gradle/wrapper/dists/gradle-6.2-all/74ez15qvgms12zoi6xyxw9rrs.
Reason: /var/root/.gradle/wrapper/dists/gradle-6.2-all/74ez15qvgms12zoi6xyxw9rrs/__MACOSX/._gradle-6.2-all (No such file or directory)
Exception in thread "main" java.io.FileNotFoundException: /var/root/.gradle/wrapper/dists/gradle-6.2-all/74ez15qvgms12zoi6xyxw9rrs/__MACOSX/._gradle-6.2-all (No such file or directory)

**Comment by sunnylqm** [comment]
下载不完整所以报错

![image](https://user-images.githubusercontent.com/615282/107205749-2a486600-6a39-11eb-9573-6bea1c93beec.png)

**Comment by 826327700** [comment]
> 下载不完整所以报错
> 
> ![image](https://user-images.githubusercontent.com/615282/107205749-2a486600-6a39-11eb-9573-6bea1c93beec.png)

你可以看到，我的下载地址是我自己私人的阿里云存储，也就是说，我已经先下载到本地了。。。。 嗯。。。唯一可能的就是我下载的那份zip也有问题，但我手工解压是正常的呀。。搞不懂
