### ISSUE TITLE
RN中不识别jsx后缀文件

### ISSUE THREAD

**Issue by JustTheice** [reactnativecn/react-native-website#374]
## 引入JSX后缀文件 无法始别
在reactcli中组件一般都定义为.jsx格式，但在rn中无法识别.jsx的后缀
![屏幕截图 2021-02-09 131326](https://user-images.githubusercontent.com/56528674/107319210-4b609380-6ad9-11eb-864e-b1904d649ba2.jpg)
```javascript
```
报错：
![Uploading sj.jpg…]()

##请描述完整的环境/版本信息

- 请在命令行的项目目录中运行`react-native info`命令，并将其输出结果粘贴到这里。
- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

**Comment by sunnylqm** [comment]
确实无法使用jsx后缀，不过这个没什么关系吧
倒是可以使用tsx后缀
