### ISSUE TITLE
npx react-native init xxx后，run-ios报错

### ISSUE THREAD

**Issue by 826327700** [reactnativecn/react-native-website#376]
## 问题的具体描述
直接init完项目，全程使用梯子，等待依赖安装完毕，中途没有任何报错或者中断，run-ios报错：
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/xiaobaozi/Library/Developer/Xcode/DerivedData/taskapp-cdjddbqgndrmoyawzcgpapjybjod/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperRSocketResponder.o /Users/xiaobaozi/Documents/developer/app/taskapp/ios/Pods/Flipper/xplat/Flipper/FlipperRSocketResponder.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

## 请描述完整的环境/版本信息
- mac平台，11.0.1
- react-native 0.63.4

## 预期结果
能正常运行

**Comment by singleton-altman** [comment]
巧了， 米兔

**Comment by singleton-altman** [comment]
libevent造成的。

**Comment by wjheha** [comment]
> libevent造成的。

怎么解决呢？我在xcode运行也看到是libevent造成的

**Comment by singleton-altman** [comment]
我也没有解决。。。给event2的文件夹引入了也不行。。。等官方解决吧。issue里面很多报错的

**Comment by sunnylqm** [comment]
看这里 https://github.com/reactnativecn/react-native-website/issues/370#issuecomment-773820385

**Comment by singleton-altman** [comment]
cool，解决了

**Comment by singleton-altman** [comment]
吐槽一下， RN这么久了。。。新人上手还能被卡在配置环境这一步，实属不应该

**Comment by sunnylqm** [comment]
开源社区就是这样运作的，开源的代码/依赖互相引用提供了便利，也自然带来了连带的影响。某个第三方某个时间点出了问题，开发者自己没办法时刻知道，只能靠用户反馈

**Comment by wjheha** [comment]
> 开源社区就是这样运作的，开源的代码/依赖互相引用提供了便利，也自然带来了连带的影响。某个第三方某个时间点出了问题，开发者自己没办法时刻知道，只能靠用户反馈

感谢大佬及时回复，按照大佬说的方案解决了，考虑是不是可以按照问题的出现频率做一下排序置顶啥的，

**Comment by sunnylqm** [comment]
早上之前已经置顶了

**Comment by haxifang-aircos** [comment]
https://github.com/reactnativecn/react-native-website/issues/376#issuecomment-776414164 这解决了我的问题
