### ISSUE TITLE
npx react-native init xxx后，run-ios报错

### ISSUE THREAD

**Issue by Zigei** [reactnativecn/react-native-website#377]
## 问题的具体描述
![image](https://user-images.githubusercontent.com/25807986/107947862-fedff100-6fcd-11eb-9655-6a4b613ac283.png)

改了 use_flipper!('Flipper' => '0.74.0')  也没有用。

## 请描述完整的环境/版本信息
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 113.30 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5014246
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## 预期结果
有没有老哥帮忙看下是什么问题啊

**Comment by sunnylqm** [comment]
xcode要11.6版本以上
