### ISSUE TITLE
Package size exceeded the configured limit of 50 MB. Try https://github.com/reactnativecn/react-native-website/tree/gh-pages/main.a2639480.css instead.

### ISSUE THREAD

**Issue by yolinsoft** [reactnativecn/react-native-website#381]
请按以下格式提供问题的相关信息。

## 问题的具体描述
cdn加速服务导致站点https://reactnative.cn/访问样式错乱，查看链接
https://cdn.jsdelivr.net/gh/reactnativecn/react-native-website@gh-pages/main.a2639480.css
提示 Package size exceeded the configured limit of 50 MB. Try https://github.com/reactnativecn/react-native-website/tree/gh-pages/main.a2639480.css instead.

请及时解决下

**Comment by sunnylqm** [comment]
没有看到这个报错，有截图吗？

**Comment by yolinsoft** [comment]
现在貌似好了
