### ISSUE TITLE
编译后一直有个tab “connect to metro to develop”

### ISSUE THREAD

**Issue by zacard-orc** [reactnativecn/react-native-website#384]
## 编译后一直有个tab “connect to metro to develop”

rn 打包编译后
react-native bundle --entry-file index.js --bundle-output ./dist/index.ios.jsbundle --platform ios --assets-dest ./dist --dev false
，ios从本地加载bundle，无论模拟器，还是真机，每次进viewcontroller上都会出现connect to metro to develop
本地已经把各种debug工具都关掉了，真机拔了usb线还是有

![image](https://user-images.githubusercontent.com/6058537/108686374-4adfe800-7530-11eb-90f0-e75aaf5f41b3.png)

- 请尽量配上相关代码截图
```js
RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:url moduleName:@"RNDemo" initialProperties:nil launchOptions:nil];
        
        RNVC *vcx = (RNVC*)vc;
        vcx.view = rootView;
        
        [self.navigationController pushViewController:vcx animated:YES];
```

## 请描述完整的环境/版本信息
- rn 0.62.2
- iossdk 14.1
- iphone 8 or 模拟器
- xcode 12.1
- node 14.5

## 预期结果
- 有啥参数可以不要这个弹出的tab，又或者我哪里打包有问题？

**Comment by sunnylqm** [comment]
离线运行的话scheme改成release即可，不需要也不应该手动执行bundle
https://reactnative.cn/docs/publishing-to-app-store

**Comment by zacard-orc** [comment]
> 离线运行的话scheme改成release即可，不需要也不应该手动执行bundle
> https://reactnative.cn/docs/publishing-to-app-store

OK，Thanks
