### ISSUE TITLE
ios项目编译成功准备安装到模拟器上时出现 error Unexpected token b in JSON at position 41724

### ISSUE THREAD

**Issue by qq565999484** [reactnativecn/react-native-website#388]
### ios项目编译成功准备安装到模拟器上时出现 error Unexpected token b in JSON at position 41724
![问题截图](https://user-images.githubusercontent.com/12536862/109749008-d0d8ee80-7c14-11eb-8654-6a5079f93e3b.png)
npm版本：7.6.0

**Comment by sunnylqm** [comment]
请提供更详细的环境信息，在项目目录内执行 npx react-native info 截图

**Comment by qq565999484** [comment]
已解决，是npm版本过高引起的原因。
