### ISSUE TITLE
yarn android 后报错

### ISSUE THREAD

**Issue by sernz** [reactnativecn/react-native-website#389]
## 问题的具体描述
![image](https://user-images.githubusercontent.com/38930176/109752103-befa4a00-7c1a-11eb-81da-f4b3c95db939.png)
## sdk安装情况如下
![image](https://user-images.githubusercontent.com/38930176/109752232-f9fc7d80-7c1a-11eb-8291-92114de4dd56.png)
![image](https://user-images.githubusercontent.com/38930176/109752269-0aacf380-7c1b-11eb-8fb5-e1f51162f061.png)

**Comment by sunnylqm** [comment]
jdk版本多少

**Comment by sernz** [comment]
> jdk版本多少

![image](https://user-images.githubusercontent.com/38930176/109758672-e6efaa80-7c26-11eb-8298-ae1d067faee3.png)

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/109758776-13a3c200-7c27-11eb-91bb-861d438b0fb8.png)

**Comment by sernz** [comment]
![image](https://user-images.githubusercontent.com/38930176/109762713-04734300-7c2c-11eb-94f4-12414c0aa68d.png)
还是不行

**Comment by sunnylqm** [comment]
现在javac输出什么版本

**Comment by sernz** [comment]
> 现在javac输出什么版本

还是15.0.2

**Comment by sunnylqm** [comment]
https://www.lotharschulz.info/2019/08/21/mac-change-default-java-version/

把JAVA_HOME写到shell的配置文件，
或者干脆删掉另外一个版本的jdk

**Comment by sernz** [comment]
> https://www.lotharschulz.info/2019/08/21/mac-change-default-java-version/
> 
> 把JAVA_HOME写到shell的配置文件，
> 或者干脆删掉另外一个版本的jdk

ok 了我把原来装的15.0.2的删了就行了 谢谢
