### ISSUE TITLE
M1 react native 0.62.2 所有接口都调用不通

### ISSUE THREAD

**Issue by bianxuerui** [reactnativecn/react-native-website#390]
M1 react native 0.62.2 所有接口都调用不通，有知道原因的吗？

**Comment by bianxuerui** [comment]
其他电脑上正在运行的项目，项目一点代码没问题，会不会是依赖不对或者不支持，有人能给一个思路吗？

**Comment by sunnylqm** [comment]
截图

**Comment by BianXuerui** [comment]
> 截图

我觉着应该不是组件的问题应该是我个人的问题。
![image](https://user-images.githubusercontent.com/50104688/109783722-43fa5900-7c45-11eb-8095-9f4927859cf9.png)
![image](https://user-images.githubusercontent.com/50104688/109783785-5379a200-7c45-11eb-8fad-a94e468e6a92.png)

**Comment by bianxuerui** [comment]
> > 截图
> 
> 我觉着应该不是组件的问题应该是我个人的问题。
> ![image](https://user-images.githubusercontent.com/50104688/109783722-43fa5900-7c45-11eb-8095-9f4927859cf9.png)
> ![image](https://user-images.githubusercontent.com/50104688/109783785-5379a200-7c45-11eb-8fad-a94e468e6a92.png)

如果有遇到过的希望能给一个解决方案，谢谢。

**Comment by sunnylqm** [comment]
用flipper看下网络请求和回复，你这控制台看着请求像是发出去了但是服务器返回有问题
不过0.62.2版本带的flipper好像有问题，建议用最新版本测试
