### ISSUE TITLE
关于react-native android项目启动时的问题

### ISSUE THREAD

**Issue by cnFulin** [reactnativecn/react-native-website#391]
cmd 输入react-native run-andoird 会一直卡在
Resolve dependencies of :app:debugRuntimeClasspath > maven-metadata.xml
，请问时什么原因，该怎么解决呢

**Comment by sunnylqm** [comment]
建议替换阿里云的maven源，在RN中文网的环境搭建文档里有说明

**Comment by cnFulin** [comment]
已经解决了 项目太老了有些东西 版本太低出现的问题
