### ISSUE TITLE
android scrollview contentOffset

### ISSUE THREAD

**Issue by chuhangyu** [reactnativecn/react-native-website#395]
安卓的scrollview没有contentOffset 这个属性吗，我现在的需求是需要将scrollview先向上移动一部分距离，但是是默认移动，不展示动画，如果手动去scroll的话会有一个移动的过程，

**Comment by sunnylqm** [comment]
0.64版本加入  https://github.com/facebook/react-native/commit/ed29ba13f97f240c91fdf6c0ef3fb601046697b9
