### ISSUE TITLE
ReactNative初始化项目失败，POD INStall安装失败

### ISSUE THREAD

**Issue by leisurele** [reactnativecn/react-native-website#397]
请按以下格式提供问题的相关信息。

## 问题的具体描述
初始化项目后，安装pod install报如下的错误
### Error

```
ArgumentError - unknown keyword: :configuration
/Users/XX/.rvm/gems/ruby-2.7.2/gems/cocoapods-optimize-2.0.28/lib/cocoapods-optimize/options/isolate_build.rb:63:in `header_search_paths'
/Users/xx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:874:in `block in <class:PodTargetSettings>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=unknown+keyword%3A+%3Aconfiguration&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Build errors when linting projects that expose C++ in headers
   https://github.com/CocoaPods/CocoaPods/issues/5152 [open] [48 comments]
   04 Aug 2018

## 请描述完整的环境/版本信息
 CocoaPods : 1.10.1
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.7 (19H524)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/XX/.rvm/rubies/ruby-2.7.2/lib

## 预期结果
pod install安装成功

**Comment by sunnylqm** [comment]
怎么初始化的，对podfile有什么修改吗
