### ISSUE TITLE
哪位大佬知道如何实现底部tab中含有溢出图标的按钮

### ISSUE THREAD

**Issue by ryb1995** [reactnativecn/react-native-website#401]
<img width="402" alt="WeChat75dce23b7e604182ed0ec09f0321ecff" src="https://user-images.githubusercontent.com/72651465/111413482-5088b200-8719-11eb-8989-22accda01786.png">

使用react-navigation/bottom-tab，将图标附上之后样式是可以了，ios上正常，但是android上面溢出部分无法实现点击跳转
![截屏2021-03-17 下午12 09 47](https://user-images.githubusercontent.com/72651465/111413701-b5dca300-8719-11eb-9590-599c2c34ac72.png)

![WechatIMG58](https://user-images.githubusercontent.com/72651465/111413648-9d6c8880-8719-11eb-928d-014cc883b412.jpeg)

**Comment by sunnylqm** [comment]
安卓上必须要让父容器高过子容器，哪怕多套几层
