### ISSUE TITLE
react-native-video的相关问题

### ISSUE THREAD

**Issue by xiongyuezheng** [reactnativecn/react-native-website#404]
请问一下大佬，这个组件打包后安装到电视机上后视频出现一条线在屏幕的左上角，在模拟器和真机上都没有问题。给Video加边框又是铺满全屏的，视频能正常播放，请问如何处理？

**Comment by sunnylqm** [comment]
第三方组件的问题建议直接去第三方的issue提问

**Comment by xiongyuezheng** [comment]
好的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sunny ***@***.***&gt;; 
发送时间: 2021年3月19日(星期五) 下午5:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reactnativecn/react-native-website] react-native-video的相关问题 (#404)





 
第三方组件的问题建议直接去第三方的issue提问
