### ISSUE TITLE
有大佬知道onPress与onLongPress同时在TouchableOpacity中使用发现只生效onLongPress而onPress没生效

### ISSUE THREAD

**Issue by wangyao333** [reactnativecn/react-native-website#407]
<TouchableOpacity 
                     style={{
                        width: 60,
                        height: 30,
                        backgroundColor: k.ischeck == true ? '#00aaee' : '#f5f5f5',
                        borderRadius: 8,
                        alignItems: 'center',
                        justifyContent: 'center',
                        marginLeft: 10,
                        marginTop: 10,
                    }}
                    onPress={() => {
                        this.onCheckedChange2(i)
                    }}
                    onLongPress={() => {
                        this.setState({
                            colorname: k.colorname,
                            id: k.colorid,
                            colornum: k.colornum,
                            state: k.state,
                        })
                        const { modal6 } = this.refs;
                        modal6.open();
                    }}
                >
                    <Text style={{
                        color: k.ischeck  == true ? '#fff' : '#505050',
                    }}>{k.colorname}</Text>

**Comment by Grewer** [comment]
```
 <TouchableOpacity
      style={styles.item}
      delayLongPress={800}
      onPress={() => {
      
      }}
      onLongPress={() => {
       
      }}
    >
</TouchableOpacity>
```
