### ISSUE TITLE
yarn ios报错

### ISSUE THREAD

**Issue by LittleXu** [reactnativecn/react-native-website#408]
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/a111/Library/Developer/Xcode/DerivedData/AwesomeProject-eoxpriflsbfuiqeoylogieksdmjc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-6F313F108841D5D7FEB93982F15CD38F.sh
(1 failure)

直接使用xcode运行项目
bash: Native/AwesomeProject/node_modules/react-native/scripts/../Libraries: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by sunnylqm** [comment]
请给下截图

**Comment by LittleXu** [comment]
xcode 截图
![1617074763249](https://user-images.githubusercontent.com/15767257/112929997-1ae9bd00-914c-11eb-817d-c9dd59316569.jpg)
命令行截图
![1617074989807](https://user-images.githubusercontent.com/15767257/112930017-22a96180-914c-11eb-9f07-6e914e63f8cb.jpg)

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/112939336-debf5800-915d-11eb-8cc3-cf100471dbd1.png)

**Comment by LittleXu** [comment]
🤦‍♂️非常感谢
