### ISSUE TITLE
编译ios失败，急等

### ISSUE THREAD

**Issue by jasonsalex** [reactnativecn/react-native-website#409]
`The following build commands failed:
	CompileC /Users/alexjason/Library/Developer/Xcode/DerivedData/mapApp-btexxpxswnzkvoalykbtghfviywv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNDeviceInfo.build/Objects-normal/x86_64/RNDeviceInfo.o /Users/alexjason/Downloads/quanquan-app-2/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
`
这个错误如何解决，谢谢大家。

**Comment by sunnylqm** [comment]
请打开xcode编译截图

**Comment by jasonsalex** [comment]
> 请打开xcode编译截图

<img width="814" alt="image" src="https://user-images.githubusercontent.com/5329759/113514899-bc856a00-95a3-11eb-9033-40c9d0c3f545.png">

**Comment by jasonsalex** [comment]
> 请打开xcode编译截图

<img width="630" alt="image" src="https://user-images.githubusercontent.com/5329759/113515277-125b1180-95a6-11eb-9130-2d793e5852a9.png">

**Comment by sunnylqm** [comment]
???编译报错的截图啊

**Comment by jasonsalex** [comment]
> ???编译报错的截图啊

<img width="272" alt="image" src="https://user-images.githubusercontent.com/5329759/113552521-d321d480-9628-11eb-9f49-66eca50d0c07.png">

**Comment by sunnylqm** [comment]
看起来是xcode版本低了

**Comment by jasonsalex** [comment]
> 看起来是xcode版本低了
我的是11.3版本
<img width="474" alt="image" src="https://user-images.githubusercontent.com/5329759/113558707-bbe7e480-9632-11eb-804d-83e41c855d65.png">

**Comment by sunnylqm** [comment]
报错的这几个属性都需要xcode 12以上

**Comment by jasonsalex** [comment]
> 报错的这几个属性都需要xcode 12以上
 现在又报错这个

<img width="754" alt="image" src="https://user-images.githubusercontent.com/5329759/113583317-16496b00-965c-11eb-9b45-20e189b0c566.png">

**Comment by sunnylqm** [comment]
报错明确和某个第三方库相关，就去那个第三方库的issues里搜索，你碰到的问题基本都会有别人碰到
https://github.com/qiuxiang/react-native-amap3d/issues/654

**Comment by jasonsalex** [comment]
> 报错明确和某个第三方库相关，就去那个第三方库的issues里搜索，你碰到的问题基本都会有别人碰到
> [qiuxiang/react-native-amap3d#654](https://github.com/qiuxiang/react-native-amap3d/issues/654)
现在又运行报错
<img width="822" alt="image" src="https://user-images.githubusercontent.com/5329759/113655550-a1fae000-96cc-11eb-80c0-906b72ed5e07.png">

**Comment by sunnylqm** [comment]
这个报错是这个库的问题  https://github.com/shahen94/react-native-video-processing
至于是你配置问题（说明文档中该做的步骤都做了吗），还是这个库的兼容问题（是否支持当前的rn版本），我无法判断

**Comment by wubaibin** [comment]
TypeError: null is not an object (evaluating ‘AMapSdk.initSDK’) 这个问题后面是怎么解决的，我安装最新版本，在iOS下依然报错
