### ISSUE TITLE
pod install 报错贴上，有科学上网！

### ISSUE THREAD

**Issue by dagedan** [reactnativecn/react-native-website#410]
`pod install`

报错如下：
`Auto-linking React Native modules for target `lnb`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNPermissions, RNReanimated, RNSVG, RNScreens, kingstinct-react-native-healthkit, react-native-amap-geolocation, react-native-amap3d, react-native-camera, react-native-safe-area-context, and react-native-webview
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing AMap3DMap (7.5.0)
Installing AMapFoundation (1.6.6)
Installing AMapLocation (2.6.7)
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.64.0)
Installing FBReactNativeSpec (0.64.0)
[!] /bin/bash -c 
set -e
mkdir -p /Users/dagongzai/Documents/space/carelocation/lnb/node_modules/react-native/scripts/../React/FBReactNativeSpec/FBReactNativeSpec && touch /Users/dagongzai/Documents/space/carelocation/lnb/node_modules/react-native/scripts/../React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h /Users/dagongzai/Documents/space/carelocation/lnb/node_modules/react-native/scripts/../React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec-generated.mm

touch: /Users/dagongzai/Documents/space/carelocation/lnb/node_modules/react-native/scripts/../React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h: Permission denied
touch: /Users/dagongzai/Documents/space/carelocation/lnb/node_modules/react-native/scripts/../React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec-generated.mm: Permission denied`

**Comment by sunnylqm** [comment]
Permission denied  权限报错  
注意创建项目时不要用sudo命令

**Comment by dagedan** [comment]
问题是我已经创建了，只能删除项目，重头再来？
@sunnylqm

**Comment by sunnylqm** [comment]
可以用chown命令修改

```sh
sudo chown -R $(whoami) ~/Documents/space/carelocation/lnb
```

**Comment by dagedan** [comment]
问题太多了，我都不好意思问了。 react-native 经过那么多年的发展了， 还是对新手不友好。令人汗颜

**Comment by dagedan** [comment]
`pod install`
[!] Error installing Flipper-Folly
[!] /usr/local/bin/git clone https://github.com/facebook/folly.git /var/folders/0v/pwn6x0t16433wfbk2tddcctc0000gn/T/d20210409-4408-4bynhu --template= --single-branch --depth 1 --branch v2020.04.06.00

Cloning into '/var/folders/0v/pwn6x0t16433wfbk2tddcctc0000gn/T/d20210409-4408-4bynhu'...
fatal: unable to access 'https://github.com/facebook/folly.git/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54`
@sunnylqm  这就按照 百度上说的，多试几次 就可以成功吗？

**Comment by dagedan** [comment]
`[!] Error installing Flipper-Folly
[!] /usr/local/bin/git clone https://github.com/facebook/folly.git /var/folders/0v/pwn6x0t16433wfbk2tddcctc0000gn/T/d20210409-4777-1oqu0ma --template= --single-branch --depth 1 --branch v2020.04.06.00

Cloning into '/var/folders/0v/pwn6x0t16433wfbk2tddcctc0000gn/T/d20210409-4777-1oqu0ma'...
fatal: unable to access 'https://github.com/facebook/folly.git/': Error in the HTTP2 framing layer
`  


每次错误都还不一样

**Comment by sunnylqm** [comment]
1、前面这个错误是你自己的错误操作（自己加上了sudo）。新手更应该仔细读文档，不要自己加戏。
2、大多数问题是网络屏蔽的问题，任何业界和社区都无能为力。包括你后面贴的这个错误，文档里也着重强调了。你如果使用了代理，应该检查代理是否对命令行生效了。（用什么代理？代理怎么配置？如何检查？各种网络错误如何调试？各自有什么含义？命令行如何使用？各种第三方工具的作用是什么？出错了问谁？谁负责？……不好意思，没人有这么长的篇幅一次给你讲清，教育自己是新手必经的过程）

**Comment by dagedan** [comment]
https://cocoapods.org/pods/Flipper-Folly
https://cocoapods.org/
这些地址都访问不了，是不是意味着，不可能成功搭建的？ @sunnylqm

**Comment by sunnylqm** [comment]
大多数国外服务器访问都非常困难，教授别人使用和直接提供工具都面临法律风险，我只能说这些了

**Comment by dagedan** [comment]
网络这个我有，然而这个网站是  直接返回500， pod这个好难  @sunnylqm

**Comment by dagedan** [comment]
Flipper-Folly 连这个玩意是啥都不知道， 直接 Internal Server Error 了。

**Comment by sunnylqm** [comment]
你有但它没有起到作用，和没有的区别在哪？

这个网站存在，且正常运行。你需要一个正确配置的代理工具来正常访问，这就是唯一的问题。

**Comment by sunnylqm** [comment]
cocoapods.org 这会儿还真的服务器挂掉了

**Comment by dagedan** [comment]
不是这回儿的问题，我从昨天到现在，科不一致就这样嘛。  被pod 卡脖子，也没有替代方案。 我反反复复的创建了 几十次项目了。

**Comment by sunnylqm** [comment]
但是主站(cocoapods.org)挂掉不会影响安装的  安装是走github.com的    
你的报错仍然是代理的问题（浏览器能访问外网不等于命令行能访问）

**Comment by dagedan** [comment]
ping 不能说明，终端可以访问外网吗？

**Comment by dagedan** [comment]
我这边的上网是公司采购的， 多次助我大杀四方。 这次却不灵了

**Comment by sunnylqm** [comment]
Ping走的是不同的协议
应该用curl测试

**Comment by dagedan** [comment]
只有个全局代理 和 自动代理  可选择的。 我一直都是全局代理。

**Comment by dagedan** [comment]
看起来这个也不科学了。

**Comment by dagedan** [comment]
@sunnylqm   经过九曲十八弯，终于跑起来了。 感谢大佬
