### ISSUE TITLE
yarn ios 报错 #import <React/RCTBridgeDelegate.h> 1 error generated.

### ISSUE THREAD

**Issue by Jeana-f** [reactnativecn/react-native-website#411]
In file included from /Users/fanfan/zfeng/myproject/AwesomeProject/ios/AwesomeProject/main.m:3:
/Users/fanfan/zfeng/myproject/AwesomeProject/ios/AwesomeProject/AppDelegate.h:1:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/fanfan/Library/Developer/Xcode/DerivedData/AwesomeProject-behbdbsrowiiumdkidxohvkqdpue/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphonesimulator/AwesomeProject.build/Objects-normal/x86_64/main.o /Users/fanfan/zfeng/myproject/AwesomeProject/ios/AwesomeProject/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  AwesomeProject

**Comment by 285878535** [comment]
the same as me
