### ISSUE TITLE
pod install报错[!] Invalid `Podfile` file: [!] Unable to locate the executable `node`.

### ISSUE THREAD

**Issue by Jeana-f** [reactnativecn/react-native-website#412]
[!] Invalid `Podfile` file: [!] Unable to locate the executable `node`.

 #  from /Users/fanfan/zfeng/myproject/AwesomeProject/ios/Podfile:7
 #  -------------------------------------------
 #  target 'AwesomeProject' do
 >    config = use_native_modules!
 #
 #  -------------------------------------------

**Comment by sunnylqm** [comment]
一般是cocoapods版本太低



---Original---
From: ***@***.***&gt;
Sent at: 2021年4月9日(Fri) PM4:39
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [reactnativecn/react-native-website] pod install报错[!] Invalid `Podfile` file: [!] Unable to locate the executable `node`. (#412)




 
[!] Invalid Podfile file: [!] Unable to locate the executable node.
 
from /Users/fanfan/zfeng/myproject/AwesomeProject/ios/Podfile:7
 
-------------------------------------------
 
target 'AwesomeProject' do
  
config = use_native_modules!
  

 
-------------------------------------------

**Comment by Jeana-f** [comment]
> 一般是cocoapods版本太低
> […](#)
> ---Original--- From: ***@***.***&gt; Sent at: 2021年4月9日(Fri) PM4:39 To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [reactnativecn/react-native-website] pod install报错[!] Invalid `Podfile` file: [!] Unable to locate the executable `node`. (#412) [!] Invalid Podfile file: [!] Unable to locate the executable node. from /Users/fanfan/zfeng/myproject/AwesomeProject/ios/Podfile:7
> ------------------------------------------- target 'AwesomeProject' do config = use_native_modules!
> ------------------------------------------- — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/20606924/114160183-3b3e2680-9959-11eb-973d-6570a3cce5d0.png)

**Comment by sunnylqm** [comment]
我说的是cocoapods，不是xcode



---Original---
From: ***@***.***&gt;
Sent at: 2021年4月9日(Fri) PM5:30
To: ***@***.***&gt;;
Cc: "Sunny ***@***.******@***.***&gt;;
Subject: Re: [reactnativecn/react-native-website] pod install报错[!] Invalid `Podfile` file: [!] Unable to locate the executable `node`. (#412)




  
一般是cocoapods版本太低
 …
 ---Original--- From: @.&gt; Sent at: 2021年4月9日(Fri) PM4:39 To: @.&gt;; Cc: @.***&gt;; Subject: [reactnativecn/react-native-website] pod install报错[!] Invalid Podfile file: [!] Unable to locate the executable node. (#412) [!] Invalid Podfile file: [!] Unable to locate the executable node. from /Users/fanfan/zfeng/myproject/AwesomeProject/ios/Podfile:7
 ------------------------------------------- target 'AwesomeProject' do config = use_native_modules!

**Comment by Jeana-f** [comment]
> > 一般是cocoapods版本太低
> > […](#)
> > ---Original--- From: _**@**_._**> Sent at: 2021年4月9日(Fri) PM4:39 To: _**@**_.**_>; Cc: _**@**_.***>; Subject: [reactnativecn/react-native-website] pod install报错[!] Invalid `Podfile` file: [!] Unable to locate the executable `node`. (#412) [!] Invalid Podfile file: [!] Unable to locate the executable node. from /Users/fanfan/zfeng/myproject/AwesomeProject/ios/Podfile:7
> > ------------------------------------------- target 'AwesomeProject' do config = use_native_modules!
> > ------------------------------------------- — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> ![image](https://user-images.githubusercontent.com/20606924/114160183-3b3e2680-9959-11eb-973d-6570a3cce5d0.png)

![image](https://user-images.githubusercontent.com/20606924/114162865-18f9d800-995c-11eb-8548-e2994d962484.png)
默认安装的这个版本？如何指定更高版本

**Comment by sunnylqm** [comment]
默认安装的是最新版本  
看看其他环境信息  运行npx react-native info截图看下

**Comment by Jeana-f** [comment]
> npx react-native info

![Uploading image.png…]()

**Comment by Jeana-f** [comment]
> 默认安装的是最新版本
> 看看其他环境信息 运行npx react-native info截图看下

![Uploading image.png…]()
