### ISSUE TITLE
请求网络失败

### ISSUE THREAD

**Issue by Qchuanwudi** [reactnativecn/react-native-website#413]
[Thu Apr 15 2021 16:11:11.920]  WARN     Possible Unhandled Promise Rejection (id: 0):
Error: Network Error
createError@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:127470:26
handleError@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:127374:27
dispatchEvent@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:32324:31
setReadyState@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:31497:33
__didCompleteResponse@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:31313:29
emit@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:3574:42
__callFunction@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2784:36
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2516:31
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2738:15
callFunctionReturnFlushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2515:21
callFunctionReturnFlushedQueue@[native code]

**Comment by sunnylqm** [comment]
代码里有报错

**Comment by Qchuanwudi** [comment]
这是什么原因呢

**Comment by Qchuanwudi** [comment]
别的问题都是好的，就是请求发不出去

**Comment by sunnylqm** [comment]
你的请求代码里有报错，至于是客户端代码有错还是服务器端代码有错，从你目前给的信息无法判断

**Comment by Fcscanf** [comment]
我也遇到了同样的问题，后台接口测过没问题，就是请求发不出去，以前是没问题的，突然就遇到
![image](https://user-images.githubusercontent.com/27654200/115103634-faac6180-9f85-11eb-98e9-17f5c6bad594.png)

**Comment by sunnylqm** [comment]
0.64开始进一步收紧了网络策略，默认不支持http接口，需自行修改manifest文件修改默认策略，参考

https://github.com/sunnylqm/flowermate/blob/master/android/app/src/main/AndroidManifest.xml#L8

**Comment by Qchuanwudi** [comment]
> 0.64开始进一步收紧了网络策略，默认不支持http接口，需自行修改manifest文件修改默认策略，参考
> 
> https://github.com/sunnylqm/flowermate/blob/master/android/app/src/main/AndroidManifest.xml#L8
谢谢
