### ISSUE TITLE
yarn ios pod install 443

### ISSUE THREAD

**Issue by wjiantao** [reactnativecn/react-native-website#414]
> [!] Error installing boost-for-react-native
> [!] /usr/bin/git clone https://github.com/react-native-community/boost-for-react-native.git > >/var/folders/m3/pxd1jp613xnbt1z7x_sy2n4r0000gn/T/d20210415-767-vd3kqk --template= --single-branch --depth 1 --branch v1.63.0-0

>Cloning into '/var/folders/m3/pxd1jp613xnbt1z7x_sy2n4r0000gn/T/d20210415-767-vd3kqk'...
>fatal: unable to access 'https://github.com/react-native-community/boost-for-react-native.git/': Failed to connect to >github.com port 443: Operation timed out

请大佬帮忙解答， 急～～

**Comment by sunnylqm** [comment]
翻墙问题



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 15, 2021 20:02 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [reactnativecn/react-native-website] yarn ios pod install 443 (#414)




  
[!] Error installing boost-for-react-native
 [!] /usr/bin/git clone https://github.com/react-native-community/boost-for-react-native.git &gt; &gt;/var/folders/m3/pxd1jp613xnbt1z7x_sy2n4r0000gn/T/d20210415-767-vd3kqk --template= --single-branch --depth 1 --branch v1.63.0-0
   
Cloning into '/var/folders/m3/pxd1jp613xnbt1z7x_sy2n4r0000gn/T/d20210415-767-vd3kqk'...
 fatal: unable to access 'https://github.com/react-native-community/boost-for-react-native.git/': Failed to connect to &gt;github.com port 443: Operation timed out
  
请大佬帮忙解答， 急～～

**Comment by wjiantao** [comment]
> 翻墙问题
> […](#)
> ---原始文件---发件人：***@***.***& gt; 日期：2021年4月15日，星期四，下午20:02收件人：***@***.***> ;; 抄送：***@***.***> ;; 主题：[reactnativecn / react-native-website] yarn ios pod pod 443（[＃414](https://github.com/reactnativecn/react-native-website/issues/414)）[！]安装boost-for-react-native [！] / usr / bin / git clone [https://github.com/本地社区/boost-for-react-native.git＆gt](https://github.com/react-native-community/boost-for-react-native.git) ; ＆gt; / var / folders / m3 / pxd1jp613xnbt1z7x_sy2n4r0000gn / T / d20210415-767-vd3kqk --template = --single-branch --depth 1 --branch v1.63.0-0克隆为'/ var / folders / m3 / pxd1jp613xnbt1z7x_sy2n / T / d20210415-767-vd3kqk'...致命：无法访问' https://github.com/react-native-community/boost-for-react-native.git/'：无法连接到＆gt; github.com端口443：操作超时请大佬帮忙解答，急～～ —您收到此消息是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

谢谢🙏
