### ISSUE TITLE
ios http请求 Network request failed

### ISSUE THREAD

**Issue by wjiantao** [reactnativecn/react-native-website#415]
> 已在 demo/ios/demo/Info.plist 中添加  

>     <key>NSAllowsArbitraryLoads</key>
>      <true/>

为何还是不行？

这是错误信息：
> TypeError: Network request failed
  >  at fetch.umd.js:535
   > at JSTimers.js:231
   > at _callTimer (JSTimers.js:123)
   > at Object.callTimers (JSTimers.js:379)
   > at MessageQueue.__callFunction (MessageQueue.js:414)
   > at MessageQueue.js:113
   > at MessageQueue.__guard (MessageQueue.js:365)
   > at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:112)
   > at debuggerWorker.aca173c4.js:4

模拟器版本为 iphone 12  ios: 14.4

请大佬霸霸指教～～～

**Comment by ybf970928** [comment]
好像得设置Xcode
