### ISSUE TITLE
真机测试问题

### ISSUE THREAD

**Issue by Qchuanwudi** [reactnativecn/react-native-website#417]
电脑安装了模拟器，想用真机调试，项目运行会自动默认启动模拟器，在模拟器运行，怎么吧默认改成真机

**Comment by sunnylqm** [comment]
真机插上线开启usb调试，只要adb devices命令里能看到真机就会从真机启动，否则启动模拟器

**Comment by Qchuanwudi** [comment]
> 真机插上线开启usb调试，只要adb devices命令里能看到真机就会从真机启动，否则启动模拟器

谢谢了

**Comment by chenzl0723** [comment]
可以把模拟器的可调试开关关了
