### ISSUE TITLE
键盘吊起，底部样式被顶上来怎么解决

### ISSUE THREAD

**Issue by Qchuanwudi** [reactnativecn/react-native-website#418]
![ef5a08da21e232ee3ba51535635d244](https://user-images.githubusercontent.com/54746375/115179428-decfc980-a105-11eb-9140-f1fd4f539239.png)

**Comment by sunnylqm** [comment]
安卓的manifest里有个设置叫做windowSoftInputMode，用来设置键盘获得焦点后对应用屏幕的调整行为，自己根据需要调整，必要时配合keyboardAvoidingView容器组件等等

**Comment by chenzl0723** [comment]
可以根据KeyboardAvoidingViewI设置键盘属性
