### ISSUE TITLE
目标：想要集成RN库之后输出framework给第三方使用。经过：目前通过官方的例子RNTesterPods项目安装好了RN的依赖库。把所有.a和对应头文件摘取出来放到自己项目中，发现有如下问题不知道该怎么解决？或者对于这种需求，有没有其他获取RN所有库的解决方案？

### ISSUE THREAD

**Issue by benlinhuo** [reactnativecn/react-native-website#421]
RN库使用的版本是0.64。官方的RNTesterPods项目都跑起来了，Products目录下生成的.a 被摘取出来使用。
我在自己项目中的关键配置：
![image](https://user-images.githubusercontent.com/5523793/115533099-fe631f80-a2c8-11eb-95d4-0eb9f5b886bc.png)
![image](https://user-images.githubusercontent.com/5523793/115533149-0a4ee180-a2c9-11eb-9948-6862a4cc098d.png)

但编译这个framework的时候会报以下的错误，麻烦指导下
![image](https://user-images.githubusercontent.com/5523793/115533223-1d61b180-a2c9-11eb-9743-e565349f8e33.png)

**Comment by benlinhuo** [comment]
能帮忙看下问题嘛？@sunnylqm

**Comment by sunnylqm** [comment]
可以参考的只有这个老版本  https://github.com/sportsbet/react-native-static-build
新版本没有看到谁有公开的方案
