### ISSUE TITLE
RN库使用的版本是0.64。如果想要使用framework ，终端pod install 会报如下错误，请问应该如何解决？

### ISSUE THREAD

**Issue by benlinhuo** [reactnativecn/react-native-website#422]
![image](https://user-images.githubusercontent.com/5523793/115542691-1d66af00-a2d3-11eb-911b-0c14d20713df.png)

**Comment by benlinhuo** [comment]
补充 Podfile 的内容，两张图拼接。podfile 没有更改，用的是github上源码默认的podfile
![image](https://user-images.githubusercontent.com/5523793/115544345-0fb22900-a2d5-11eb-9a96-1b1d97458a65.png)
![image](https://user-images.githubusercontent.com/5523793/115544431-25bfe980-a2d5-11eb-9ec6-7b15b04592d6.png)

![image](https://user-images.githubusercontent.com/5523793/115544166-d7aae600-a2d4-11eb-81d5-858b842b7b70.png)

**Comment by benlinhuo** [comment]
@sunnylqm 能帮忙解答下嘛

**Comment by lgh89** [comment]
我也遇到了同样的问题，请问有解决方案了吗 @benlinhuo @sunnylqm
