### ISSUE TITLE
react native关于android TV

### ISSUE THREAD

**Issue by xiongyuezheng** [reactnativecn/react-native-website#423]
请问一下大佬，在react native中怎么解决android TV 播放视频的问题。使用过react-native-video但是在tv上只有音频没有视频，视频形成一条线在屏幕的左上角，请问一下在rn中除react-native-video外还有其他解决方案吗？

**Comment by sunnylqm** [comment]
确定尺寸有给对吗？任何播放器方案都可以用，只要别人或者你自己会封装

**Comment by xiongyuezheng** [comment]
给尺寸了，直接给video边框是铺满全屏的，在其他android设备上都正常，就是安装到tv上后出现这个问题。使用webview 嵌套H5是可以正常播放的但是,我们的需求是使用本地缓存视频源，webview下的h5中的video不支持本地路径，同时无法监控到视频播放结束，所以此方案暂时放弃。

**Comment by sunnylqm** [comment]
webview可以结合起一个本地服务器来播放，也有播放结束的事件可以回调。方案肯定很多，就是需要非常熟悉各种跨越式的封装和调用了。
