### ISSUE TITLE
npx react-native run-ios报错了请问怎么解决？

### ISSUE THREAD

**Issue by OceanFlooor** [reactnativecn/react-native-website#425]
npx react-native run-ios报错了请问怎么解决？

## 我按照官方文档一步步进行，前面都没什么问题，但是运行`npx react-native run-ios`命令报错如下：
```
The following build commands failed:
	CompileC /Users/oceanfloor/Library/Developer/Xcode/DerivedData/AwesomeProject-fmjkktobmchkqigdnqlqwjfnfeju/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-Folly.build/Objects-normal/x86_64/DistributedMutex.o /Users/oceanfloor/AwesomeProject/ios/Pods/Flipper-Folly/folly/synchronization/DistributedMutex.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

## 环境/版本信息
"react-native": "0.64.0"
cocopods:  ‘1.10.1’
xcode：Version 12.5 beta 3

我试过了各种方法都不行，无论是删除`podfile.lock`重新`pod install`，还是添加`use_flipper!({ 'Flipper' => '0.75.0' })`，重新初始化一个项目，都是得到同样的错误

<img width="913" alt="61994EE1-0758-42AB-81AC-6FE2D2DACA49" src="https://user-images.githubusercontent.com/41851552/115980213-75483300-a5bd-11eb-98f4-d10727787083.png">

<img width="849" alt="DEC37890-5A90-460D-9729-EF044D7F1C98" src="https://user-images.githubusercontent.com/41851552/115980201-52b61a00-a5bd-11eb-8c96-9460bba65784.png">

**Comment by sunnylqm** [comment]
请运行 npx react-native info 看下环境

**Comment by sunnylqm** [comment]
是用了xcode 12.5beta吗？退回12.4正式版，不要用beta版
