### ISSUE TITLE
ios xcode编译问题

### ISSUE THREAD

**Issue by ERiver-Freddie** [reactnativecn/react-native-website#431]
请按以下格式提供问题的相关信息。

## 问题描述
  - 我在编写rn app时，引入了react-native-linear-gardient插件，android可以完美运行，但是在mac上编译始终报错以下两条信息，经百度未得到任何有效信息，也不明白下面这两条信息到底是什么引起的问题。最初以为是安装的插件没有手动添加，所以按照网上的教程手动添加后无任何作用（右击Libraries add files，选中插件，然后点击该插件的build phases 中的Link Binary With Libraries，按照npm上ios添加该插件的说明操作再次清空后编译，仍然无用），后来我就把该插件删除但仍然不能运行，先是yarn remove 这个插件，然后在Libraries中删除，Recovered References中删除，然后进入项目的build phases 将Link Binary With Libraries中的这个插件也删除了。在clean build folder 后再次编译仍然得到以下两条报错（第一次时strip的报错，然后在不动任何代码的情况下再点编译就会得到destination那条报错）
  - 如果可以希望大佬们指点我两条错误信息为什么产生，明白意思了就有研究方向了
## 报错信息

   - Showing Recent Errors Only
strip /Users/apple/Desktop/finalXrt/app-c/ios/build/Products/Release-iphoneos/xrtApp.app.dSYM/Contents/Resources/DWARF/xrtApp: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip exited with 1

Showing Recent Errors Only
destination '/Users/apple/Desktop/finalXrt/app-c/ios/Build/Products/Release-iphoneos/xrtApp.app/build' is inside source '/Users/apple/Desktop/finalXrt/app-c/ios/Build' (not copied)

Showing Recent Errors Only
strip /Users/apple/Desktop/finalXrt/app-c/ios/build/Products/Release-iphoneos/xrtApp.app.dSYM/Contents/Resources/DWARF/xrtApp: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip exited with 1

## ios运行环境
- System:
      OS: macOS 10.15.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 850.53 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4
## packag.json
  - {
    "name": "xxx", //名字不予展示
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "start": "node ./script.ts",
        "test": "jest",
        "build": "cd android && ./gradlew assembleRelease",
        "build-ios": "node node_modules/react-native/local-cli/cli.js bundle --entry-file index.js --platform ios --dev false --bundle-output ./ios/build/index.jsbundle --assets-dest ./ios/build",
        "lint": "eslint .",
        "fix-modal": "node node_modules/react-native-modal-translucent/scripts/translucent-modal.js",
        "postinstall": "npm run fix-modal"
    },
    "dependencies": {
        "@types/react-native-tab-navigator": "^0.3.3",
        "eslint": "5.9.0",
        "moment": "^2.24.0",
        "native-echarts": "^0.5.0",
        "net": "^1.0.2",
        "react": "16.8.3",
        "react-native": "0.59.4",
        "react-native-check-box": "^2.1.7",
        "react-native-checkbox": "^2.0.0",
        "react-native-device-info": "^5.5.3",
        "react-native-ezswiper": "^1.3.0",
        "react-native-fs": "^2.16.6",
        "react-native-htmlview": "^0.15.0",
        "react-native-image-picker": "^1.1.0",
        **"react-native-linear-gradient": "^2.5.6",**
        "react-native-marquee-ab": "^1.2.6",
        "react-native-modal-datetime-picker": "^7.6.0",
        "react-native-modal-translucent": "^5.0.0",
        "react-native-picker": "^4.3.7",
        "react-native-roll-picker": "^1.0.6",
        "react-native-root-toast": "^3.2.0",
        "react-native-simple-radio-button": "^2.7.4",
        "react-native-step-indicator": "^0.0.11",
        "react-native-storage": "^1.0.1",
        "react-native-svg": "^12.1.0",
        "react-native-swiper": "^1.5.14",
        "react-native-tab-navigator": "^0.3.4",
        "react-native-webview": "^8.0.6",
        "react-navigation": "2.18.2",
        "react-redux": "^7.1.3",
        "redux": "^4.0.4",
        "redux-actions": "^2.6.5",
        "redux-react-hook": "^4.0.1",
        "redux-thunk": "^2.3.0",
        "sockjs-client": "^1.4.0",
        "stompjs": "^2.3.3"
    },
    "devDependencies": {
        "@babel/core": "^7.7.2",
        "@babel/runtime": "^7.7.2",
        "babel-jest": "^24.9.0",
        "jest": "^24.9.0",
        "metro-react-native-babel-preset": "^0.57.0",
        "react-native-iconfont-cli": "^2.0.0",
        "react-test-renderer": "16.8.3"
    },
    "jest": {
        "preset": "react-native"
    }
}
## 预期结果
- 希望能够编译成功并在真机上运行（之前是可以成功运行的）

**Comment by sunnylqm** [comment]
请截图

**Comment by ERiver-Freddie** [comment]
个人原因需要删除截图

**Comment by sunnylqm** [comment]
应该是你的build phase设置有问题，这个报错的build目录应该是不需要copy的

**Comment by ERiver-Freddie** [comment]
个人原因需要删除截图

**Comment by sunnylqm** [comment]
Copy Bundle Resources 里面有个build目录，应该是需要去掉的

总得而言，这类配置错误你都应该通过版本控制来还原（你自己乱改，不知道为什么，又不知道改了哪里。捅娄子容易，要修复就难。所以必须要通过版本控制来谨慎修改和恢复）

**Comment by ERiver-Freddie** [comment]
感谢大佬！去掉之后就可以运行了。不过为啥要去掉build目录呢？ @sunnylqm

**Comment by sunnylqm** [comment]
问题其实应该是，你为什么会加上（本来就是没有这个目录的）

**Comment by ERiver-Freddie** [comment]
了解了，下来我自己研究下（我是半路临时被叫来做这个的，android那边还好，ios简直就是一头蒙，xocde完全看不懂）。感谢大佬帮助
