### ISSUE TITLE
在输入框内点击键盘下一步触发到下一个输入框，键盘会先关闭在弹出

### ISSUE THREAD

**Issue by vs2pk0** [reactnativecn/react-native-website#436]
请按以下格式提供问题的相关信息。

## 问题的具体描述
多个输入框，在输入框里面点击键盘“下一步”，触发下一个输入框focus事件，键盘会出现先关闭后启动的现象
- 请尽量配上相关代码截图
![image](https://user-images.githubusercontent.com/3499503/117445183-fd8ae880-af6c-11eb-91c3-e349ba914169.png)
![录制_2021_05_07_19_55_00_1272021571955491](https://user-images.githubusercontent.com/3499503/117446344-89514480-af6e-11eb-8aef-3af9a7954e04.gif)

## 请描述完整的环境/版本信息
  "react": "17.0.1",
   "react-native": "0.64.1"

## 预期结果
键盘不关闭，直到失去焦点

**Comment by Onedayago** [comment]
你把 TextInput 放到 scrollView 里面，然后设置 scrollView 设置下面这个属性就可以了
keyboardShouldPersistTaps#
如果当前界面有软键盘，那么点击 scrollview 后是否收起键盘，取决于本属性的设置。（译注：很多人反应 TextInput 无法自动失去焦点/需要点击多次切换到其他组件等等问题，其关键都是需要将 TextInput 放到 ScrollView 中再设置本属性）

'never' （默认值），点击 TextInput 以外的子组件会使当前的软键盘收起。此时子元素不会收到点击事件。
'always'，键盘不会自动收起，ScrollView 也不会捕捉点击事件，但子组件可以捕获。
'handled'，当点击事件被子组件捕获时，键盘不会自动收起。这样切换 TextInput 时键盘可以保持状态。多数带有 TextInput 的情况下你应该选择此项。
false，已过时，请使用'never'代替。
true，已过时，请使用'always'代替。
