### ISSUE TITLE
本地文件开启服务报错Error in callNativeModules():3,2,2,0,25,100,1620799466827,false,161  Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by fk5785186** [reactnativecn/react-native-website#438]
Error in callNativeModules():3,2,2,0,25,100,1620799466827,false,161

Malformed calls from JS: field sizes are different.
[[3,2],[2,0],[[25,100,1620799466827,false]],161]
run
    NativeRunnable.java
handleCallback
    Handler.java:790
dispatchMessage
    Handler.java:99
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:764

**Comment by sunnylqm** [comment]
请按提问模板补充相关问题细节
