### ISSUE TITLE
使用jsx结尾的文件就报错，

### ISSUE THREAD

**Issue by xjdqq** [reactnativecn/react-native-website#439]
None of these files exist

**Comment by sunnylqm** [comment]
很遗憾jsx格式文件确实不支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月13日(周四) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 使用jsx结尾的文件就报错， (#439)




 
None of these files exist

**Comment by xjdqq** [comment]
我自己新建的项目用jsx就不行。
但是我们公司react-native项目中有jsx文件，是因为Expo有关系吗
