### ISSUE TITLE
npm run ios 报错：Unable to find a destination matching the provided destination specifier:

### ISSUE THREAD

**Issue by wangyupeng993** [reactnativecn/react-native-website#440]
react-native：0.63.2
Xcode：12.4

Podfile 文件：
<img width="1080" alt="微信图片_20210514005655" src="https://user-images.githubusercontent.com/39769538/118159390-8c0cd780-b44f-11eb-851d-c57a46148e18.png">

报错信息：
<img width="1393" alt="微信图片_20210514005237" src="https://user-images.githubusercontent.com/39769538/118159491-a47cf200-b44f-11eb-9a4b-1ab5b9b93a64.png">

**Comment by sunnylqm** [comment]
请用xcode运行截图报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月14日(周五) 凌晨1:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] npm run ios 报错：Unable to find a destination matching the provided destination specifier: (#440)




 
react-native：0.63.2
 Xcode：12.4
 
Podfile 文件：
 
 
报错信息：
