### ISSUE TITLE
react native 怎么集成微信支付，如何引入微信sdk

### ISSUE THREAD

**Issue by Qchuanwudi** [reactnativecn/react-native-website#441]
react native 怎么集成微信支付，如何引入微信sdk

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/118596256-0043d400-b7de-11eb-8b15-ff74d8d3207f.png)

**Comment by kangyilong** [comment]
https://github.com/little-snow-fox/react-native-wechat-lib
