### ISSUE TITLE
Mac系统更新到Big Sur后出现问题

### ISSUE THREAD

**Issue by laojiang308** [reactnativecn/react-native-website#444]
error node_modules/react-native/node_modules/base64-js/index.js: Cannot find module 'private'

**Comment by laojiang308** [comment]
error node_modules/react-native/node_modules/base64-js/index.js: Cannot find module 'private'
Require stack:
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/regenerator-transform/lib/meta.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/regenerator-transform/lib/emit.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/regenerator-transform/lib/visit.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/regenerator-transform/lib/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/@babel/plugin-transform-regenerator/lib/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/metro-react-native-babel-preset/src/configs/main.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/metro-react-native-babel-preset/src/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/@babel/core/lib/config/files/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/@babel/core/lib/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/metro/src/JSTransformer/worker.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/jest-worker/build/workers/processChild.js. Run CLI with --verbose flag for more details.
Error: Cannot find module 'private'
Require stack:
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/regenerator-transform/lib/meta.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/regenerator-transform/lib/emit.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/regenerator-transform/lib/visit.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/regenerator-transform/lib/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/@babel/plugin-transform-regenerator/lib/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/metro-react-native-babel-preset/src/configs/main.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/metro-react-native-babel-preset/src/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/@babel/core/lib/config/files/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/@babel/core/lib/index.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/metro/src/JSTransformer/worker.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/jest-worker/build/workers/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/technologyco.ltd.xingyi/Downloads/BulkPurchase/node_modules/regenerator-transform/lib/meta.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
error Command failed with exit code 1.

**Comment by sunnylqm** [comment]
删掉node_modules后重装试试
