### ISSUE TITLE
使用fetch 时一直报警告：equire cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle. 

### ISSUE THREAD

**Issue by liangyi-h5** [reactnativecn/react-native-website#445]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 使用fetch 时一直报警告：equire cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
- 只要用了fetch 请求方法就出现警告

> ![image](https://user-images.githubusercontent.com/65635875/120417547-99075180-c391-11eb-8140-750318ef5b11.png)

**Comment by sunnylqm** [comment]
不重要，忽略即可。（警告类的东西都差不多这样处理，尤其是第三方的警告，你也做不了什么）
