### ISSUE TITLE
react-native 图片上传组件

### ISSUE THREAD

**Issue by cnFulin** [reactnativecn/react-native-website#446]
请问一下 有什么适合react-native用的 图片上传组件呢？

**Comment by sunnylqm** [comment]
图片选取需要一些image-picker组件，但上传并不需要任何组件啊

**Comment by cnFulin** [comment]
> 图片选取需要一些image-picker组件，但上传并不需要任何组件啊

获取到的文件类型是object格式的  formData方式上传失败了

**Comment by sunnylqm** [comment]
formdata只需要传文件路径

参考 https://github.com/sunnylqm/flowermate/blob/114199633a1b313c5ef03bbfec4c1440afd261a3/src/components/UploadButton.tsx#L41

**Comment by cnFulin** [comment]
> formdata只需要传文件路径
> 
> 参考 https://github.com/sunnylqm/flowermate/blob/114199633a1b313c5ef03bbfec4c1440afd261a3/src/components/UploadButton.tsx#L41

![image](https://user-images.githubusercontent.com/47142694/120768621-ee3c9200-c54e-11eb-84bd-43a098fdefe0.png)
这种情况是什么大概原因呢 网上查了也没有解决办法

**Comment by sunnylqm** [comment]
你这是用什么截的图

**Comment by QAQMrchen** [comment]
> 你这是用什么截的图

QQ的截图工具 
![image](https://user-images.githubusercontent.com/47142694/120769764-05c84a80-c550-11eb-83a2-a10c2933e68b.png)
![image](https://user-images.githubusercontent.com/47142694/120769793-0eb91c00-c550-11eb-8bd5-24d48f0f4668.png)
这样写的方式不对吗 请求中不是期望的样子；
![image](https://user-images.githubusercontent.com/47142694/120769923-2ee8db00-c550-11eb-9c47-b1e16bfd803b.png)
这种才是我期望的格式；

**Comment by sunnylqm** [comment]
……我是说你在哪里看到这个网络请求的

**Comment by sunnylqm** [comment]
如果是用react-native-debugger或者其他基于chrome的调试工具查看的，都无法正确查看formdata

**Comment by sunnylqm** [comment]
只有flipper可以正确查看rn的网络请求，但也正是一些早期的flipper版本会导致上传失败（解决办法是升级rn自带的flipper到最新版本）

**Comment by cnFulin** [comment]
> ……我是说你在哪里看到这个网络请求的



> 只有flipper可以正确查看rn的网络请求，但也正是一些早期的flipper版本会导致上传失败（解决办法是升级rn自带的flipper到最新版本）

嗯嗯 好的 非常干感谢 我再去尝试一下
