### ISSUE TITLE
按照官网教程yarn ios报错

### ISSUE THREAD

**Issue by 285878535** [reactnativecn/react-native-website#447]
`   export VERSION_INFO_BUILDER\=xingjiaxing
    export VERSION_INFO_FILE\=FBReactNativeSpec_vers.c
    export VERSION_INFO_STRING\=\"@\(\#\)PROGRAM:FBReactNativeSpec\ \ PROJECT:Pods-\"
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES\=NO
    export XCODE_APP_SUPPORT_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION\=12E262
    export XCODE_VERSION_ACTUAL\=1250
    export XCODE_VERSION_MAJOR\=1200
    export XCODE_VERSION_MINOR\=1250
    export XPCSERVICES_FOLDER_PATH\=/XPCServices
    export YACC\=yacc
    export arch\=undefined_arch
    export variant\=normal
    /bin/sh -c /Users/xingjiaxing/Library/Developer/Xcode/DerivedData/AwesomeProject-cmogsjxwzxsxihhblnbwekwijrcw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-C8E2B4515927472D1D1D4EBF4AC58DF1.sh
/Users/xingjiaxing/.bash_profile: line 31: /Users/xingjiaxing/.bashr: No such file or directory
bash: -: command not found
Command PhaseScriptExecution failed with a nonzero exit code

/Users/xingjiaxing/Documents/文稿 - abaMacBook Air/practice/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'boost-for-react-native' from project 'Pods')
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the AwesomeProject editor. (in target 'AwesomeProject' from project 'AwesomeProject')
/Users/xingjiaxing/Documents/文稿 - abaMacBook Air/practice/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'YogaKit' from project 'Pods')
/Users/xingjiaxing/Documents/文稿 - abaMacBook Air/practice/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Flipper-PeerTalk' from project 'Pods')
/Users/xingjiaxing/Documents/文稿 - abaMacBook Air/practice/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Flipper-Glog' from project 'Pods')
/Users/xingjiaxing/Documents/文稿 - abaMacBook Air/practice/AwesomeProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Flipper-DoubleConversion' from project 'Pods')
warning: Skipping duplicate build file in Copy Headers build phase: /Users/xingjiaxing/Documents/文稿 - abaMacBook Air/practice/AwesomeProject/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h (in target 'FBReactNativeSpec' from project 'Pods')
warning: Skipping duplicate build file in Compile Sources build phase: /Users/xingjiaxing/Documents/文稿 - abaMacBook Air/practice/AwesomeProject/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec-generated.mm (in target 'FBReactNativeSpec' from project 'Pods')

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/xingjiaxing/Library/Developer/Xcode/DerivedData/AwesomeProject-cmogsjxwzxsxihhblnbwekwijrcw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-C8E2B4515927472D1D1D4EBF4AC58DF1.sh
(1 failure)

info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarn`

很长，没有全部复制。ios模拟器吊起来了，但是项目没有运行起来

**Comment by 285878535** [comment]
日志里有报错和好多警告，但是不知道该怎么改
/Users/xingjiaxing/.bash_profile: line 31: /Users/xingjiaxing/.bashr: No such file or directory
bash: -: command not found

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/121136378-294d0700-c868-11eb-86c8-f2c5b1ee36f4.png)

![image](https://user-images.githubusercontent.com/615282/121136315-15a1a080-c868-11eb-9683-aca2c8c3aee6.png)

**Comment by 285878535** [comment]
这个文稿不是macos自带的文件夹吗？不是我自己写的

**Comment by sunnylqm** [comment]
它自带它也还是中文啊，并不享有什么特权啊。原先不认识中文路径的工具，不可能说碰到它就突然会认识了啊

**Comment by 285878535** [comment]
的确是路径问题 感谢大佬 非常感谢
