### ISSUE TITLE
pod install --project-directory=ios报错了

### ISSUE THREAD

**Issue by 285878535** [reactnativecn/react-native-website#448]
第一步：yarn add react-native-navigation正常
第二步：pod install --project-directory=ios报错

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
Auto-linking React Native module for target `AwesomeProject`: ReactNativeNavigation
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "ReactNativeNavigation":
  In Podfile:
    ReactNativeNavigation (from `../node_modules/react-native-navigation`)

Specs satisfying the `ReactNativeNavigation (from `../node_modules/react-native-navigation`)` dependency were found, but they required a higher minimum deployment target.

**Comment by 285878535** [comment]
index.js
`import { Navigation } from "react-native-navigation";
import App from "./App";
Navigation.registerComponent('com.myApp.WelcomeScreen', () => App);
Navigation.events().registerAppLaunchedListener(() => {
   Navigation.setRoot({
     root: {
       stack: {
         children: [
           {
             component: {
               name: 'com.myApp.WelcomeScreen'
             }
           }
         ]
       }
     }
  });
});`

**Comment by sunnylqm** [comment]
我看了下react native navigation的文档，中间还有别的步骤你没做啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月8日(周二) 晚上11:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] pod install --project-directory=ios报错了 (#448)




 
第一步：yarn add react-native-navigation正常
 第二步：pod install --project-directory=ios报错
 
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
 Auto-linking React Native module for target AwesomeProject: ReactNativeNavigation
 Analyzing dependencies
 [!] CocoaPods could not find compatible versions for pod "ReactNativeNavigation":
 In Podfile:
 ReactNativeNavigation (from ../node_modules/react-native-navigation)
 
Specs satisfying the ReactNativeNavigation (from ../node_modules/react-native-navigation) dependency were found, but they required a higher minimum deployment target.

**Comment by 285878535** [comment]
import { Navigation } from "react-native-navigation";
import App from "./App";
Navigation.registerComponent('com.myApp.WelcomeScreen', () => App);
Navigation.events().registerAppLaunchedListener(() => {
   Navigation.setRoot({
     root: {
       stack: {
         children: [
           {
             component: {
               name: 'com.myApp.WelcomeScreen'
             }
           }
         ]
       }
     }
  });
});
index.js 文档里说改这个 我一开始就改过了啊

**Comment by sunnylqm** [comment]
我不想重复，但你确实还有步骤没做。
