### ISSUE TITLE
App Store-ITMS-90338: Non-public API usage《_isKeyDown, _modifiedInput, _modifierFlags, currentSession， handleNotification:, onSuccess:, setCategoryID:》

### ISSUE THREAD

**Issue by siwei123** [reactnativecn/react-native-website#449]
Description
![image](https://user-images.githubusercontent.com/17057163/122347983-39a66580-cf7d-11eb-8dd0-856a1eb3d8d4.png)

以上图中部分api的使用被苹果认为是私有api，不允许通过

React Native version:
0.64.1

Steps To Reproduce
1.使用RN0.64.1的iOS版本打包上传至苹果商店，即可复现
2.

Expected Results
希望可以正常通过苹果的审核，进行上线发布

**Comment by sunnylqm** [comment]
搜了下，有人说是因为打包选择了debug而非release导致的
https://github.com/facebook/react-native/issues/31507#issuecomment-859972967
