### ISSUE TITLE
react-native 在MainActivity中如何传递事件或参数给JS端。

### ISSUE THREAD

**Issue by congpeiran** [reactnativecn/react-native-website#450]
我正在集成厂商通道推送，现在厂商通道打开MainActivity的时候我想把推送的消息传递到JS页面上显示，各位大神有没有好的办法呀，求教求教，麻烦了。
![image](https://user-images.githubusercontent.com/53423401/122377228-7a12dd00-cf97-11eb-9b89-f7b826b98168.png)
简单来说，就是怎么在MainActivity中怎么获得ReactContext鸭

**Comment by sunnylqm** [comment]
只能在 ReactContextBaseJavaModule 中获得

https://github.com/reactnativecn/react-native-pushy/blob/master/android/src/main/java/cn/reactnative/modules/update/UpdateModule.java#L41

**Comment by congpeiran** [comment]
您好，可以帮我看下么，我改了一下正常打开时好用，debug刷新（摇一摇 reload）之后，出现红屏提示Map already consumed，这是什么原因吖，拜托拜托啦~
![image](https://user-images.githubusercontent.com/53423401/122493077-a0795c80-d019-11eb-871e-b307734fad6d.png)
![image](https://user-images.githubusercontent.com/53423401/122493111-b25aff80-d019-11eb-9e40-63bf9ec78664.png)
![image](https://user-images.githubusercontent.com/53423401/122493228-e2a29e00-d019-11eb-842a-3643778c0451.png)
![image](https://user-images.githubusercontent.com/53423401/122493256-f221e700-d019-11eb-8624-dc69dd0b9227.png)

**Comment by sunnylqm** [comment]
Map应copy后使用
https://github.com/invertase/react-native-firebase/pull/5236/files#diff-945d05be567b9871eff943790a8b6ff7efde8bcd48a0b41d24d240b4687859c0R234

你这个场景也应该用事件而非回调

**Comment by leonsimple** [comment]
用 RCTDeviceEventEmitter 发送事件到rn
