### ISSUE TITLE
iOS的蓝牙和socket的收到的数据流用什么module可以传给react native

### ISSUE THREAD

**Issue by xuyushiguang** [reactnativecn/react-native-website#452]
##  iOS的蓝牙和socket的收到的数据流用什么module可以传给react native
- 我在iOS端使用蓝牙和socket,收到的数据流要传给react 去解析和展示,我发现找不到合适的module去传输流数据,你们是怎么做的?有这块的解决办法吗?

**Comment by leonsimple** [comment]
试下将数据流转成字符串，通过EventEmitter 发送事件

**Comment by tyanbiao** [comment]
编码成 BASE64，发送给 Native 再 decode

**Comment by xuyushiguang** [comment]
> 编码成 BASE64，发送给 Native 再 decode
想直接使用字节流的发给native或者js,有这样的方法吗,不想转成字符串;

**Comment by sunnylqm** [comment]
rn现在没有原生支持字节流
