### ISSUE TITLE
RN启动问题

### ISSUE THREAD

**Issue by BlinkZF** [reactnativecn/react-native-website#454]
大佬们好，我是RN初学者：启动项目的时候出现的问题，
执行命令：react-native run-android。
试了网上很多方法都没有起作用...
求教，感谢🙏
![image](https://user-images.githubusercontent.com/38147870/123532507-3743c880-d740-11eb-92f7-7c14f0068ac3.png)

**Comment by sunnylqm** [comment]
请按问题模板填写问题
