### ISSUE TITLE
导航问题

### ISSUE THREAD

**Issue by jy02409187** [reactnativecn/react-native-website#456]
入口文件

![SQT5RQ`QCDJ4T83E6V53%$W](https://user-images.githubusercontent.com/86599979/123618729-0c8a6a80-d83b-11eb-8229-02f8864961e2.png)

导航文件

![3M3RKW8D(M~R3 KUA{K9S8S](https://user-images.githubusercontent.com/86599979/123618812-1e6c0d80-d83b-11eb-829b-aa01d791f925.png)

运行报错了

![3)W4TC8W%)N6@NP4%9O6J~X](https://user-images.githubusercontent.com/86599979/123618862-2c219300-d83b-11eb-8cc6-38436faa2a5d.png)

请问怎么解决啊

**Comment by sunnylqm** [comment]
1、报错表示找不到react-navigation这个模块，你确定你装了吗
2、你这代码哪里找的，现在的版本也不是这么写的
