### ISSUE TITLE
页面跳转问题

### ISSUE THREAD

**Issue by jy02409187** [reactnativecn/react-native-website#457]
![5Z`H5@JNJ9VA7}`(8MSQ2UG](https://user-images.githubusercontent.com/86599979/123778428-a9183f80-d903-11eb-839a-9d681132b05d.png)

我想从 index.js 页面 点击按钮跳转到 detail.js 页面 代码应该怎么写啊

**Comment by sunnylqm** [comment]
就是你截图的代码这么写啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月29日(周二) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 页面跳转问题 (#457)




 

 
我想从 index.js 页面 点击按钮跳转到 detail.js 页面 代码应该怎么写啊

**Comment by jy02409187** [comment]
我截图的代码都是写在index.js里的，跳转也只在index.js内部，上面我并没有创建detail.js文件

**Comment by sunnylqm** [comment]
所以……你创建一个，把detail的代码分过去不就完了……如果你不知道怎么分，那你应该去补es模块相关的基础知识



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月30日(周三) 上午10:00
收件人: ***@***.***&gt;;
抄送: "Sunny ***@***.******@***.***&gt;;
主题: Re: [reactnativecn/react-native-website] 页面跳转问题 (#457)




 
我截图的代码都是写在index.js里的，跳转也只在index.js内部，上面我并没有创建detail.js文件

**Comment by jy02409187** [comment]
我知道怎么分，我还上来问个啥啊。。。

**Comment by sunnylqm** [comment]
这里并不是小学生补习课堂。上面已经给出了关键词，请自行搜索学习。

**Comment by jy02409187** [comment]
就是不懂才问啊。。。
