### ISSUE TITLE
按照官网环境搭建，yarn ios失败

### ISSUE THREAD

**Issue by Sangzl** [reactnativecn/react-native-website#458]
请按以下格式提供问题的相关信息。

## 问题的具体描述
   ios编译报错，Xcode运行后对报错截图 
![image](https://user-images.githubusercontent.com/47103754/123903259-f26a9c80-d9a0-11eb-9f84-07eacc20debb.png)
![image](https://user-images.githubusercontent.com/47103754/123903425-437a9080-d9a1-11eb-8476-685af564046b.png)
![image](https://user-images.githubusercontent.com/47103754/123903690-bd127e80-d9a1-11eb-9b65-ca3d8dac643a.png)

iOS设备查看日志的[一些方法](https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a)。
- 请尽量配上相关代码截图

## 请描述完整的环境/版本信息
- 请在命令行的项目目录中运行`npx react-native info`命令，并将其输出结果粘贴到这里。
info Fetching system and libraries information...
System:
    OS: macOS 11.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 514.51 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.14.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
   就是如官方文档所示的那样，能在模拟器上看到welcome to react界面

**Comment by sunnylqm** [comment]
podfile截图看下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月30日(周三) 中午12:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 按照官网环境搭建，yarn ios失败 (#458)




 
请按以下格式提供问题的相关信息。
 
问题的具体描述
 
ios编译报错，Xcode运行后对报错截图
 
 
 
 
iOS设备查看日志的一些方法。
  
请尽量配上相关代码截图 
 
请描述完整的环境/版本信息
  
请在命令行的项目目录中运行npx react-native info命令，并将其输出结果粘贴到这里。
 info Fetching system and libraries information...
 System:
 OS: macOS 11.2
 CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 Memory: 514.51 MB / 16.00 GB
 Shell: 5.8 - /bin/zsh
 Binaries:
 Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
 Yarn: 1.22.10 - ~/.nvm/versions/node/v12.14.1/bin/yarn
 npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
 Watchman: 2021.06.07.00 - /usr/local/bin/watchman
 Managers:
 CocoaPods: 1.10.1 - /usr/local/bin/pod
 SDKs:
 iOS SDK:
 Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
 Android SDK: Not Found
 IDEs:
 Android Studio: Not Found
 Xcode: 11.7/11E801a - /usr/bin/xcodebuild
 Languages:
 Java: Not Found
 npmPackages:
 @react-native-community/cli: Not Found
 react: 17.0.1 =&gt; 17.0.1
 react-native: 0.64.2 =&gt; 0.64.2
 react-native-macos: Not Found
 npmGlobalPackages:
 react-native: Not Found 

如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。 
 
预期结果
  
请描述你觉得代码正常运行的情况应该是什么样子。
 就是如官方文档所示的那样，能在模拟器上看到welcome to react界面

**Comment by Sangzl** [comment]
![image](https://user-images.githubusercontent.com/47103754/123907594-c6ebb000-d9a8-11eb-83a9-f7a4b9035cf3.png)

**Comment by sunnylqm** [comment]
需要升级xcode到最新正式版
