### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by jy02409187** [reactnativecn/react-native-website#459]
![{ KP5PZ9J8NA0`L{YK%7FU](https://user-images.githubusercontent.com/86599979/123923518-aaa53e80-d9bb-11eb-95e5-63a178c3452e.png)

![4H{NBV 1GQQJR%IA(((J%CN](https://user-images.githubusercontent.com/86599979/123923650-c6104980-d9bb-11eb-91fb-c8f256a7eb1f.png)

**Comment by sunnylqm** [comment]
请读文档
![image](https://user-images.githubusercontent.com/615282/123924003-1e474b80-d9bc-11eb-9a0e-b53a036e8683.png)

**Comment by jy02409187** [comment]
![WFQW$ Y%Z{G$_A8@QB8S6C](https://user-images.githubusercontent.com/86599979/123925358-69159300-d9bd-11eb-9a7b-ec83a79e0acb.png)

metro 服务已启动

**Comment by jy02409187** [comment]
就是重启系统后就这样了

**Comment by sunnylqm** [comment]
检查模拟器网络是否连通，不通的话重启模拟器

**Comment by jy02409187** [comment]
![4CZ@~O1JX5OQ26FJ{Y%)XMP](https://user-images.githubusercontent.com/86599979/123927464-73389100-d9bf-11eb-863f-8b5768274269.png)

**Comment by sunnylqm** [comment]
这个报错常见于webstorm的临时文件备份选项。如果你用的webstorm，关掉下面那个选项

![image](https://user-images.githubusercontent.com/615282/123929287-45ece280-d9c1-11eb-9ca9-bb1badff8870.png)

**Comment by jy02409187** [comment]
设置了也没用，模拟器也重启了，在网上也找了一圈，也没找到解决方法

**Comment by sunnylqm** [comment]
看下package.json

**Comment by jy02409187** [comment]
```
{
  "name": "abc",
  "version": "0.0.1",
  "private": true,
  "license": "ISC",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.2.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

我重新建了一个项目也是一样

**Comment by sunnylqm** [comment]
运行期间关闭webstorm和android studio再试试
