### ISSUE TITLE
ios虚拟机没有任何反应

### ISSUE THREAD

**Issue by zhaozhuangwang** [reactnativecn/react-native-website#465]
## 问题的具体描述
packge 配置
"scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.0"  // "react-native": "0.64.2"
  },
  "devDependencies": {
    "@babel/core": "^7.14.6",
    "@babel/runtime": "^7.14.6",
    "@react-native-community/eslint-config": "^3.0.0",
    "babel-jest": "^27.0.6",
    "eslint": "^7.30.0",
    "jest": "^27.0.6",
    "metro-react-native-babel-preset": "^0.66.0",
    "react-test-renderer": "17.0.1"
  },

yarn ios  运行之后显示如下

 Welcome to Metro!
              Fast - Scalable - Integrated

To reload the app press "r"
To open developer menu press "d"

warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
info Reloading app...

ios虚拟机没有任何反应

## 请描述完整的环境/版本信息
在前两月，创建项目后 运行yarn ios 是没有任何问题，现在运行出现此问题
请问 是哪里出错了

**Comment by sunnylqm** [comment]
截图看下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月3日(周六) 下午4:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] ios虚拟机没有任何反应 (#465)




 
问题的具体描述
 
packge 配置
 "scripts": {
 "android": "react-native run-android",
 "ios": "react-native run-ios",
 "start": "react-native start",
 "test": "jest",
 "lint": "eslint ."
 },
 "dependencies": {
 "react": "17.0.1",
 "react-native": "0.64.0"  // "react-native": "0.64.2"
 },
 "devDependencies": {
 ***@***.***/core": "^7.14.6",
 ***@***.***/runtime": "^7.14.6",
 ***@***.***/eslint-config": "^3.0.0",
 "babel-jest": "^27.0.6",
 "eslint": "^7.30.0",
 "jest": "^27.0.6",
 "metro-react-native-babel-preset": "^0.66.0",
 "react-test-renderer": "17.0.1"
 },
 
yarn ios  运行之后显示如下
 
Welcome to Metro!
 Fast - Scalable - Integrated
 
To reload the app press "r"
 To open developer menu press "d"
 
warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
 info Reloading app...
 
ios虚拟机没有任何反应
 
请描述完整的环境/版本信息
 
在前两月，创建项目后 运行yarn ios 是没有任何问题，现在运行出现此问题
 请问 是哪里出错了

**Comment by zhaozhuangwang** [comment]
![image](https://user-images.githubusercontent.com/42265723/124348543-1a663400-dc1d-11eb-9676-63cea4961004.png)

**Comment by zhaozhuangwang** [comment]
@sunnylqm

**Comment by sunnylqm** [comment]
编译报错了，用xcode运行看下，截图具体的报错

**Comment by zhaozhuangwang** [comment]
@sunnylqm ![image](https://user-images.githubusercontent.com/42265723/124350607-15f34880-dc28-11eb-9506-aabacd15c673.png)

这个项目是我 刚刚创建的

**Comment by sunnylqm** [comment]
你打开的是xcworkspace文件吗？为啥没有pods目录？

**Comment by zhaozhuangwang** [comment]
@sunnylqm ![image](https://user-images.githubusercontent.com/42265723/124352031-78e8dd80-dc30-11eb-8f34-29d158aebbdb.png)

**Comment by sunnylqm** [comment]
正常情况下是有个demoapp1.xcworkspace文件的，你这个如果不是自己删了，那就是初始化没有完成。至于初始化为什么没有完成，一般是翻墙问题，具体得截图初始化的那个窗口看有什么报错

**Comment by zhaozhuangwang** [comment]
@sunnylqm 

这就是按照要求初始化的项目，
![image](https://user-images.githubusercontent.com/42265723/124373915-24457100-dcc9-11eb-96ea-3d038f2d1a8f.png)

**Comment by sunnylqm** [comment]
初始化是有报错的，按提示手动操作看下具体报错原因

```
cd ios && pod install
```
