### ISSUE TITLE
"Yellowbox" has been abandoned, how to solve it

### ISSUE THREAD

**Issue by ehbhgh** [reactnativecn/react-native-website#468]
Real machine debugging, remove the bottom of the Yellow code has been abandoned, I would like to ask the new version of reacct native how to achieve, thank you

**Comment by ehbhgh** [comment]
console.ignoredYellowBox = ['Warning: BackAndroid is deprecated. Please use BackHandler instead.','source.uri should not be an empty string','Invalid props.style key'];
 
console.disableYellowBox = true 
？
The above code is invalid？The above code is invalid. How to write the new version？

**Comment by sunnylqm** [comment]
还能怎么做？读文档啊
https://reactnative.cn/docs/debugging#%E6%8E%A7%E5%88%B6%E5%8F%B0%E7%9A%84%E9%94%99%E8%AF%AF%E4%B8%8E%E8%AD%A6%E5%91%8A%E6%8F%90%E7%A4%BA
