### ISSUE TITLE
npx react-native init MyTestApp  Android

### ISSUE THREAD

**Issue by yfyh20231002** [reactnativecn/react-native-website#470]
![image](https://user-images.githubusercontent.com/20272899/125415222-8c6c2959-9833-4bf8-84da-e9ca788d976a.png)

这个是什么原因

**Comment by sunnylqm** [comment]
建议先回滚到npm6版本

```
npm i -g npm@6
```

**Comment by yfyh20231002** [comment]
好的，我试下
