### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by tytom2003** [reactnativecn/react-native-website#471]
当我在command里输入"react-native run-android"去执行程式时出现以下这个错误，是怎样解决? 多谢
FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\react\MyApp\android\settings.gradle'

* What went wrong:
Could not compile settings file 'D:\react\MyApp\android\settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60

**Comment by sunnylqm** [comment]
jdk版本不对

**Comment by tytom2003** [comment]
> jdk版本不对

请问是否需要安装java sdk 1.6版本?

**Comment by sunnylqm** [comment]
请 看 文 档

**Comment by encoboy** [comment]
https://stackoverflow.com/questions/58293436/could-not-compile-settings-gradle-react-native
