### ISSUE TITLE
安卓11 该怎么获取存储权限，急！求大神解答

### ISSUE THREAD

**Issue by zxmta** [reactnativecn/react-native-website#475]
在手机权限管理中始终看不到存储权限，添加android:requestLegacyExternalStorage="true"也没有效果，使用PermissionsAndroid.PERMISSIONS返回的都是denied! 求助

**Comment by zxmta** [comment]
权限清单在AndroidManifest.xml也写上了

**Comment by sunnylqm** [comment]
你要写哪个目录

**Comment by zxmta** [comment]
啊？小白表示很疑惑

**Comment by sunnylqm** [comment]
你要存储权限干啥？

**Comment by zxmta** [comment]
> 你要存储权限干啥？
访问手机相册

**Comment by sunnylqm** [comment]
手机相册并不需要存储权限

**Comment by zxmta** [comment]
![92113631ab4922fa31542a770f391b2](https://user-images.githubusercontent.com/77133704/127082280-16e95408-6f4b-42f7-97d9-9fb47a56977c.jpg)

**Comment by sunnylqm** [comment]
这是用的哪个库，安卓什么版本

**Comment by zxmta** [comment]
react-native 

> 这是用的哪个库，安卓什么版本

zoontek/react-native-permissions          安卓11

**Comment by sunnylqm** [comment]
我问你读取图片用的哪个库

**Comment by zxmta** [comment]
react-native-syan-image-picker

**Comment by sunnylqm** [comment]
主流的图片选择库很多啊，都不需要额外权限，为啥要选个星星数量这么少的还要权限的？

**Comment by zxmta** [comment]
> 主流的图片选择库很多啊，都不需要额外权限，为啥要选个星星数量这么少的还要权限的？

那我换着试试，十分感谢您

**Comment by sunnylqm** [comment]
我好奇选图片库为啥你会跳过第一第二去选第三个？（因为是中文？）
![image](https://user-images.githubusercontent.com/615282/127083098-c0ac6635-c06f-4ebc-8422-0d6d6ee9d075.png)
