### ISSUE TITLE
有人支持了mac平台么

### ISSUE THREAD

**Issue by lh9403** [reactnativecn/react-native-website#476]
现在RN支持catalyst来直接运行么，我钩上后就报错了

**Comment by sunnylqm** [comment]
建议用这个 https://microsoft.github.io/react-native-windows/

**Comment by lh9403** [comment]
> 建议用这个 https://microsoft.github.io/react-native-windows/

这个有些第三方的库不支持好像就跑不起来了，catalyst是不是只要ipad能跑起来mac就能跑起来？
