### ISSUE TITLE
yarn ios 报错 

### ISSUE THREAD

**Issue by longjiecn** [reactnativecn/react-native-website#477]
tuitui@tuituideMacBook-Pro myProject % yarn ios             
yarn run v1.22.10
$ react-native run-ios
info Found Xcode workspace "myProject.xcworkspace"
info Building (using "xcodebuild -workspace myProject.xcworkspace -configuration Debug -scheme myProject -destination id=CA6D6844-9B5A-4C85-97B0-FFB689679126")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening myProject.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace myProject.xcworkspace -configuration Debug -scheme myProject -destination id=CA6D6844-9B5A-4C85-97B0-FFB689679126

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Using build description from disk
note: Build preparation complete
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the myProject editor. (in target 'myProject' from project 'myProject')
PhaseScriptExecution Start\ Packager /Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Intermediates.noindex/myProject.build/Debug-iphonesimulator/myProject.build/Script-FD10A7F022414F080027D42C.sh (in target 'myProject' from project 'myProject')
    cd /Users/tuitui/Desktop/code/RN/myProject/ios
    /bin/sh -c /Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Intermediates.noindex/myProject.build/Debug-iphonesimulator/myProject.build/Script-FD10A7F022414F080027D42C.sh

Ld /Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/myProject.app/myProject normal (in target 'myProject' from project 'myProject')
    cd /Users/tuitui/Desktop/code/RN/myProject/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios10.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/CocoaAsyncSocket -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/DoubleConversion -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/FBReactNativeSpec -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/Flipper -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/Flipper-DoubleConversion -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/Flipper-Folly -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/Flipper-Glog -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/Flipper-PeerTalk -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/Flipper-RSocket -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/FlipperKit -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/RCT-Folly -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/RCTTypeSafety -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-Core -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-CoreModules -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-RCTAnimation -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-RCTBlob -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-RCTImage -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-RCTLinking -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-RCTNetwork -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-RCTSettings -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-RCTText -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-RCTVibration -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-cxxreact -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-jsi -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-jsiexecutor -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-jsinspector -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/React-perflogger -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/ReactCommon -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/Yoga -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/YogaKit -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/glog -L/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/libevent -F/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator -F/Users/tuitui/Desktop/code/RN/myProject/ios/Pods/OpenSSL-Universal/Frameworks -F/Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OpenSSL -filelist /Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Intermediates.noindex/myProject.build/Debug-iphonesimulator/myProject.build/Objects-normal/arm64/myProject.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Intermediates.noindex/myProject.build/Debug-iphonesimulator/myProject.build/Objects-normal/arm64/myProject_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -lCocoaAsyncSocket -lDoubleConversion -lFBReactNativeSpec -lFlipper -lFlipper-DoubleConversion -lFlipper-Folly -lFlipper-Glog -lFlipper-PeerTalk -lFlipper-RSocket -lFlipperKit -lRCT-Folly -lRCTTypeSafety -lReact-Core -lReact-CoreModules -lReact-RCTAnimation -lReact-RCTBlob -lReact-RCTImage -lReact-RCTLinking -lReact-RCTNetwork -lReact-RCTSettings -lReact-RCTText -lReact-RCTVibration -lReact-cxxreact -lReact-jsi -lReact-jsiexecutor -lReact-jsinspector -lReact-perflogger -lReactCommon -lYoga -lYogaKit -lglog -llibevent -lstdc++ -framework AudioToolbox -framework CFNetwork -framework JavaScriptCore -framework MobileCoreServices -framework OpenSSL -framework Security -framework UIKit -ObjC -lc++ -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Intermediates.noindex/myProject.build/Debug-iphonesimulator/myProject.build/myProject.app-Simulated.xcent -lPods-myProject -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Intermediates.noindex/myProject.build/Debug-iphonesimulator/myProject.build/Objects-normal/arm64/myProject_dependency_info.dat -o /Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/myProject.app/myProject
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftUIKit'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftMetal'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
Undefined symbols for architecture arm64:
  "protocol descriptor for Swift.ExpressibleByFloatLiteral", referenced from:
      l_got.$ss25ExpressibleByFloatLiteralMp in libYogaKit.a(YGLayoutExtensions.o)
  "associated type descriptor for Swift.ExpressibleByIntegerLiteral.IntegerLiteralType", referenced from:
      l_got.$s18IntegerLiteralTypes013ExpressibleByaB0PTl in libYogaKit.a(YGLayoutExtensions.o)
  "associated conformance descriptor for Swift.ExpressibleByIntegerLiteral.Swift.ExpressibleByIntegerLiteral.IntegerLiteralType: Swift._ExpressibleByBuiltinIntegerLiteral", referenced from:
      l_got.$ss27ExpressibleByIntegerLiteralP0cD4TypeAB_s01_ab7BuiltincD0Tn in libYogaKit.a(YGLayoutExtensions.o)
  "method descriptor for Swift.ExpressibleByFloatLiteral.init(floatLiteral: A.FloatLiteralType) -> A", referenced from:
      l_got.$ss25ExpressibleByFloatLiteralP05floatD0x0cD4TypeQz_tcfCTq in libYogaKit.a(YGLayoutExtensions.o)
  "protocol descriptor for Swift.ExpressibleByIntegerLiteral", referenced from:
      l_got.$ss27ExpressibleByIntegerLiteralMp in libYogaKit.a(YGLayoutExtensions.o)
  "value witness table for Builtin.Int32", referenced from:
      full type metadata for __C.YGUnit in libYogaKit.a(YGLayoutExtensions.o)
  "__swift_FORCE_LOAD_$_swiftCoreImage", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreImage_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreImage_$_YogaKit)
  "associated type descriptor for Swift.ExpressibleByFloatLiteral.FloatLiteralType", referenced from:
      l_got.$s16FloatLiteralTypes013ExpressibleByaB0PTl in libYogaKit.a(YGLayoutExtensions.o)
  "__swift_FORCE_LOAD_$_swiftQuartzCore", referenced from:
      __swift_FORCE_LOAD_$_swiftQuartzCore_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftQuartzCore_$_YogaKit)
  "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
      __swift_FORCE_LOAD_$_swiftDispatch_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_YogaKit)
  "method descriptor for Swift.ExpressibleByIntegerLiteral.init(integerLiteral: A.IntegerLiteralType) -> A", referenced from:
      l_got.$ss27ExpressibleByIntegerLiteralP07integerD0x0cD4TypeQz_tcfCTq in libYogaKit.a(YGLayoutExtensions.o)
  "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_YogaKit)
  "protocol witness table for Swift.Int : Swift._ExpressibleByBuiltinIntegerLiteral in Swift", referenced from:
      associated type witness table accessor for Swift.ExpressibleByIntegerLiteral.IntegerLiteralType : Swift._ExpressibleByBuiltinIntegerLiteral in __C.YGValue : Swift.ExpressibleByIntegerLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
      __swift_FORCE_LOAD_$_swiftObjectiveC_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_YogaKit)
  "__swift_FORCE_LOAD_$_swiftCoreGraphics", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreGraphics_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreGraphics_$_YogaKit)
  "_swift_getForeignTypeMetadata", referenced from:
      type metadata accessor for __C.YGValue in libYogaKit.a(YGLayoutExtensions.o)
      type metadata accessor for __C.YGUnit in libYogaKit.a(YGLayoutExtensions.o)
  "__swift_FORCE_LOAD_$_swiftFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftFoundation_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFoundation_$_YogaKit)
  "associated conformance descriptor for Swift.ExpressibleByFloatLiteral.Swift.ExpressibleByFloatLiteral.FloatLiteralType: Swift._ExpressibleByBuiltinFloatLiteral", referenced from:
      l_got.$ss25ExpressibleByFloatLiteralP0cD4TypeAB_s01_ab7BuiltincD0Tn in libYogaKit.a(YGLayoutExtensions.o)
  "__swift_FORCE_LOAD_$_swiftUIKit", referenced from:
      __swift_FORCE_LOAD_$_swiftUIKit_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUIKit_$_YogaKit)
  "__swift_FORCE_LOAD_$_swiftMetal", referenced from:
      __swift_FORCE_LOAD_$_swiftMetal_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftMetal_$_YogaKit)
  "Swift.Float.init(Swift.Double) -> Swift.Float", referenced from:
      static (extension in YogaKit):CoreGraphics.CGFloat.% postfix(CoreGraphics.CGFloat) -> __C.YGValue in libYogaKit.a(YGLayoutExtensions.o)
      (extension in YogaKit):__C.YGValue.init(CoreGraphics.CGFloat) -> __C.YGValue in libYogaKit.a(YGLayoutExtensions.o)
  "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
      __swift_FORCE_LOAD_$_swiftDarwin_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_YogaKit)
  "protocol witness table for Swift.Float : Swift._ExpressibleByBuiltinFloatLiteral in Swift", referenced from:
      associated type witness table accessor for Swift.ExpressibleByFloatLiteral.FloatLiteralType : Swift._ExpressibleByBuiltinFloatLiteral in __C.YGValue : Swift.ExpressibleByFloatLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

/Users/tuitui/Desktop/code/RN/myProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Flipper-PeerTalk' from project 'Pods')
/Users/tuitui/Desktop/code/RN/myProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'boost-for-react-native' from project 'Pods')
/Users/tuitui/Desktop/code/RN/myProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Flipper-DoubleConversion' from project 'Pods')
/Users/tuitui/Desktop/code/RN/myProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Flipper-Glog' from project 'Pods')
/Users/tuitui/Desktop/code/RN/myProject/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'YogaKit' from project 'Pods')

objc[45810]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x202346c10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1163d02b8). One of the two will be used. Which one is undefined.
objc[45810]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x202346c60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1163d0308). One of the two will be used. Which one is undefined.
** BUILD FAILED **

The following build commands failed:
        Ld /Users/tuitui/Library/Developer/Xcode/DerivedData/myProject-bxfjywrzwkhtbcdjyefdvuufuyjd/Build/Products/Debug-iphonesimulator/myProject.app/myProject normal
(1 failure)

**Comment by longjiecn** [comment]
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 195.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.19.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by WuDiTangYuan** [comment]
我在M1的Mac上也遇到了和你一样的问题，但是intel的mac可以正常跑起项目

**Comment by sunnylqm** [comment]
当前flipper在M1上有些兼容问题，可以暂时禁用掉flipper（podfile里把use_flipper注释掉）
