### ISSUE TITLE
AsyncStorage被弃用了，新的存储方法是啥？

### ISSUE THREAD

**Issue by writeDream** [reactnativecn/react-native-website#478]

**Comment by sunnylqm** [comment]
移到社区了


https://github.com/react-native-async-storage/async-storage


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月28日(周三) 上午9:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] AsyncStorage被弃用了，新的存储方法是啥？ (#478)
