### ISSUE TITLE
permission is denied using Android Q ffmpeg": error=13, Permission denied

### ISSUE THREAD

**Issue by chen236310** [reactnativecn/react-native-website#479]
安卓压缩视频时报这个错permission is denied using Android Q ffmpeg": error=13, Permission denied,除了把
 targetSdkVersion 29 改低之外,还有其他方法或者哪个第三方库可以解决这个问题吗?

**Comment by sunnylqm** [comment]
看起来这个库是支持的 https://github.com/shahen94/react-native-video-processing/pull/287
