### ISSUE TITLE
请问怎样能够在react-native 使用ListView?

### ISSUE THREAD

**Issue by tytom2003** [reactnativecn/react-native-website#480]
我试了在程式加入"import { ListView } from react-native"，但是react-native 已经删除了ListView 模组，我在网上找资料其他人说要用"deprecated-react-native-listview", 然后我在程式里加入" import ListView from 'deprecated-react-native-listview';"，仍然都是不能使用ListView。请问怎样在程式里使用ListView? 多谢

是否要改用FlatList?
https://reactnative.cn/docs/flatlist

**Comment by sunnylqm** [comment]
listview已经删除了好几年了，现在就是用flatlist
