### ISSUE TITLE
请问有什么解决办法"error Failed to install the app."

### ISSUE THREAD

**Issue by tytom2003** [reactnativecn/react-native-website#483]
我在WINDOWS 7安装react native环境，但是当我执行第一个程序时，就出现以下错误，请问有什么解决办法？

error Failed to install the app. Make sure you have the Android development envi
ronment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8
081
Note: D:\Downloads\react\AwesomeProject\android\app\src\debug\java\com\awesomepr
oject\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
[ddms]: ADB rejected shell command (am get-config): closed

FAILURE: Build failed with an exception.

**Comment by sunnylqm** [comment]
截图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月31日(周六) 晚上10:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 请问有什么解决办法"error Failed to install the app." (#483)




 
我在WINDOWS 7安装react native环境，但是当我执行第一个程序时，就出现以下错误，请问有什么解决办法？
 
error Failed to install the app. Make sure you have the Android development envi
 ronment set up: https://reactnative.dev/docs/environment-setup.
 Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8
 081
 Note: D:\Downloads\react\AwesomeProject\android\app\src\debug\java\com\awesomepr
 oject\ReactNativeFlipper.java uses or overrides a deprecated API.
 Note: Recompile with -Xlint:deprecation for details.
 [ddms]: ADB rejected shell command (am get-config): closed
 
FAILURE: Build failed with an exception.

**Comment by tytom2003** [comment]
![1](https://user-images.githubusercontent.com/25719095/127757522-10a25da4-021c-4d87-8b94-a54363b7ed6f.JPG)
![2](https://user-images.githubusercontent.com/25719095/127757527-4343b383-e850-497c-825e-3f682047d96b.JPG)
THANK YOU

**Comment by tytom2003** [comment]
如果不能，我用WINDOWS 10的电脑再试一试

**Comment by sunnylqm** [comment]
模拟器能正常启动运行吗？运行速度正常吗？如果以前正常那重启电脑试试，如果一直不正常那考虑各种更新（显卡驱动，android studio版本，emulator版本等等）或者使用真机尝试。


另外不应该再使用旧的react-native全局命令，如果安装了应该卸载，具体看文档说明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月1日(周日) 上午10:51
收件人: ***@***.***&gt;;
抄送: "Sunny ***@***.******@***.***&gt;;
主题: Re: [reactnativecn/react-native-website] 请问有什么解决办法"error Failed to install the app." (#483)




 

 
 THANK YOU

**Comment by tytom2003** [comment]
> 模拟器能正常启动运行吗？运行速度正常吗？如果以前正常那重启电脑试试，如果一直不正常那考虑各种更新（显卡驱动，android studio版本，emulator版本等等）或者使用真机尝试。 另外不应该再使用旧的react-native全局命令，如果安装了应该卸载，具体看文档说明
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年8月1日(周日) 上午10:51 收件人: ***@***.***&gt;; 抄送: "Sunny ***@***.******@***.***&gt;; 主题: Re: [reactnativecn/react-native-website] 请问有什么解决办法"error Failed to install the app." (#483) THANK YOU — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.


我根据这个网页的方法已经重新设置，解决问题了。多谢你的帮忙。
[https://www.cnblogs.com/jcxfighting/p/11214458.html](url)
