### ISSUE TITLE
报错Property body[6] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

### ISSUE THREAD

**Issue by Carolinely** [reactnativecn/react-native-website#487]
--  RN  v0.64.2
-- npm v6.14.11
-- node v12.20.2
step 1: 用 npx react-native init AwesomeProject 创建项目
step 2: 用 npx react-native run-android 启动，然后报错如下
命令行报错：
 BUNDLE  ./index.js 
error: node_modules/react-native/Libraries/Image/ImageAnalyticsTagContext.js: Property body[6] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

模拟器报错：
The development server returned response error code: 500

---

问题原因和解决方案：

babel刚刚发布了一个有问题的插件版本，导致大范围项目运行出错，在等待babel官方发布修复版本 https://github.com/babel/babel/pull/13637 之前，
目前的解决方案只有在package.json中通过 yarn resolution 锁定旧版本：

```diff
--- package.json
+++ package.json
@@ -25,5 +25,8 @@
   },
   "jest": {
     "preset": "react-native"
+  },
+  "resolutions": {
+    "@babel/plugin-transform-react-display-name": "7.14.5"
   }
 }
```

修改完package.json之后重新运行yarn （注意只有yarn可用，npm不支持resolutions)

参考 https://github.com/facebook/react-native/issues/31960#issuecomment-893176992

**Comment by liqiangnd** [comment]
我也遇到了同样的问题

**Comment by tenderness-yang** [comment]
npm v7.15.0
node v16.1.0
java v1.8.0_291
遇到同样的问题，模拟器和真机运行都会出现

**Comment by sunnylqm** [comment]
babel有问题，解决方案见顶楼分割线下内容

**Comment by afc163** [comment]
antd 遇到了同样的问题。https://github.com/ant-design/ant-design/issues/31671

**Comment by sunnylqm** [comment]
babel已发布修复版本7.15.1   删掉锁文件后重装即可
