### ISSUE TITLE
怎么解决"selectedIndex:undefined"出现undefined。

### ISSUE THREAD

**Issue by tytom2003** [reactnativecn/react-native-website#488]
我想在SegmentedControl里想有人按时，它会自动去其他位置，但是我console.log(this.setState.selectedIndex)他的位置数字，它出现未定义的时候，请问怎么解决？多谢

export default class App extends Component {
  constructor(prop:any)
  {
    super(prop);
    this.state = {
      selectedIndex:0
    };
  }

  handleIndexChange = (index: any) => {
    this.setState({
      ...this.state,
      selectedIndex: index
    });
  };
  render() {
    return (
     <SegmentedControl
     style={{top:100}}
     onValueChange={(value)=>{
       console.log("index:"+ value);
       console.log("selectedIndex:"+this.setState.selectedIndex);
     }}

     selectedIndex={this.setState.selectedIndex}
     tintColor='red'
     values={['one', 'two', 'three']}
     onTabPress={this.handleIndexChange}

     />
    );
  }
}

我是参考这个网页的
https://github.com/kirankalyan5/react-native-segmented-control-tab

**Comment by sunnylqm** [comment]
你这错误很多
首先 setState 自己会合并状态，不需要手动合并

```
this.setState({
  // ...this.state,   //  这一行是不需要的
  selectedIndex: index
})
```

即可

其次 this.`setState`.selectedIndex本身就是写错了，应该是 this.`state`.selectedIndex
