### ISSUE TITLE
为什么segmentcontrol 里的selectedIndex不是显示0?

### ISSUE THREAD

**Issue by tytom2003** [reactnativecn/react-native-website#489]
就像当我在segmentcontrol 按下“One”按钮时，为什么它的selectedIndex不是显示0，可能有可能是1或者2？
它是否由使用者按下时由0开始计算?
SegmentIndex 不是按"One" = 1, "Two" = 2, "Three" = 3去知道使用者是按去那個位置?
多谢

export default class App extends Component {
  constructor(prop:any)
  {
    super(prop);
    this.state = {
      selectedIndex:0
    };
  }

  render() {
    return (
    
     <SegmentedControl
     values={['One', 'Two','Three']}
     selectedIndex={this.state.selectedIndex}
     onChange={(event) => {
       this.setState({selectedIndex: event.nativeEvent.selectedSegmentIndex});
       console.log(this.state.selectedIndex);
     }}
   />
    );
  }
}

**Comment by sunnylqm** [comment]
因为setState是异步的，不是马上生效的。这类基础问题你该去找个react的课程系统学习。

**Comment by sunnylqm** [comment]
https://zh-hans.reactjs.org/docs/faq-state.html#why-is-setstate-giving-me-the-wrong-value
