### ISSUE TITLE
请问geolocation是否需要设定androidmanifest.xml?

### ISSUE THREAD

**Issue by tytom2003** [reactnativecn/react-native-website#493]
我跟书写了以下的程式，但是它显示"ERROR"，是否需要在androidmanifest.xml里加入
"<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />"? 和androidmanifest.xml档案是放在那里?

render() {
    return (
      <View>
        <Button title="GEO" onPress={() => {
          Geolocation.getCurrentPosition((obj:any) => {
            console.log(obj);
          }, ()=>{
            console.log("error");
          },{
            timeout:10000,
            maximumAge:100000,
            enableHighAccuracy:false,
            distanceFilter:10
          });
        }}/>
      </View>
      );
    }
  }

**Comment by sunnylqm** [comment]
不知道你看的什么书，不建议再看了，都是过时的东西了
geolocation已弃用，而且在国内由于谷歌框架的问题不好用
国内做定位基本都靠一些国内地图厂商的模块来做。权限的话manifest里要加，代码里也要加，具体我就没空说了。

**Comment by tytom2003** [comment]
> 不知道你看的什么书，不建议再看了，都是过时的东西了
> geolocation已弃用，而且在国内由于谷歌框架的问题不好用
> 国内做定位基本都靠一些国内地图厂商的模块来做。权限的话manifest里要加，代码里也要加，具体我就没空说了。

我是看"React Native全教程：移动端跨平台应用开发"去学习react native, 请问有没有推介书借给初学者看? 多谢
https://e.jd.com/30425700.html

**Comment by sunnylqm** [comment]
看react和react native的官方文档就够了。模块或者api什么的，用到哪个就去看哪个，没有必要挨个过一遍。
