### ISSUE TITLE
vscode运行RN代码，使用的是android studio虚拟机，能正常运行，但是我更新代码后，点击‘r’，但是没有更新

### ISSUE THREAD

**Issue by feelgooda** [reactnativecn/react-native-website#495]
## vscode运行RN代码，使用的是android studio虚拟机，能正常运行，但是我更新代码后，点击‘r’，但是没有更新，并且还警告我
No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.（但是我执行 run-android 成功了的，项目也成功运行到了虚拟机上） 环境windows

**Comment by zjtt** [comment]
我也遇到了相同的问题，兄弟最后怎么解决的？
