### ISSUE TITLE
求助安卓原生集成RN打包问题

### ISSUE THREAD

**Issue by bibubi** [reactnativecn/react-native-website#499]
我按着[官网步骤](https://www.react-native.cn/docs/next/integration-with-existing-apps)做了个Demo测试
可以真机调试，但到最后一步打包生成离线jsbundle文件时，命令行报错了
![image](https://user-images.githubusercontent.com/18078927/130722362-67f4dc27-b1de-4fd8-a9a9-9fc7a541578e.png)

output路径是准确的

**Comment by sunnylqm** [comment]
是monorepo吗？是的话参考下这个帖子  
https://github.com/react-native-community/cli/issues/877
