### ISSUE TITLE
android compile failed. "armeabi-v7a/package.json as JSON: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by wustwg** [reactnativecn/react-native-website#502]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 如果是安装过程中的问题，请再三确认你有使用稳定的翻墙工具，且翻墙工具对命令行有生效（如开启全局模式等等）
- 请说明具体操作步骤和现象（例如执行什么命令，或者点击哪里，出现了什么异常现象或错误信息）
- 请尽量配上相关报错截图
   - 如果是ios编译报错，请打开Xcode运行后对报错截图 
   - 如果设备上有红屏报错请直接截图
   - 如果命令行有报错请直接截图
   - 警告(warning)一般不用管
   - 如果设备上看不到报错，请先尝试[调试模式](https://reactnative.cn/docs/debugging)。
   - 如果是发行版本无法调试，对于安卓设备请使用[adb logcat命令](https://developer.android.google.cn/studio/command-line/logcat)来捕获日志并粘贴到这里。iOS设备查看日志的[一些方法](https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a)。
- 请尽量配上相关代码截图

 android 打包失败，概率性问题，但有很大概率能出现。
执行的任务是 assembleRelease , 报错截图：
![图片](https://user-images.githubusercontent.com/20111696/132607776-b5ec8c17-be54-447e-b133-b49de5e1b9c9.png)
这个报错位置的json内容我看了，是空的
我对比了正常打包成功的时候的armbeabi-v7a文件夹，没有这个文件。
该问题和android架构无关，arm64编译也会出现该问题

## 请描述完整的环境/版本信息
- 请在命令行的项目目录中运行`npx react-native info`命令，并将其输出结果粘贴到这里。
- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 204.63 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.15.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /Users/atrust/.rvm/rubies/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

正常应该打包成功。

**Comment by sunnylqm** [comment]
这个地方就不应该出现package.json  
甚至产生这个目录都很少见，这表示有ndk介入编译，但我都想不起有哪个常见的模块需要用到ndk编译
你应该先检查你有什么地方用到了ndk，再看它相关的编译配置
