### ISSUE TITLE
报错AAPT: error: resource android:attr/lStar not found

### ISSUE THREAD

**Issue by McWangFei** [reactnativecn/react-native-website#504]
一直报安卓环境的错误是怎么回事

E:\PrivateProject\CloudPos>yarn android
yarn run v1.22.11
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1287 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...
> Task :app:processDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
239 actionable tasks: 4 executed, 235 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\aaa1d65c708bd44ba1748eb3dfd7c0f0\core-1.7.0-alpha02\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

请问各位大佬这是怎么解决呢，我已经检查了好几遍环境没问题和重启好几次了都不行

**Comment by sunnylqm** [comment]
环境信息呢  npx react-native info

**Comment by McWangFei** [comment]
E:\PrivateProject\CloudPos&gt;npx react-native info
info Fetching system and libraries information...
System:
&nbsp; &nbsp; OS: Windows 7 6.1.7601
&nbsp; &nbsp; CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
&nbsp; &nbsp; Memory: 7.77 GB / 15.89 GB
&nbsp; Binaries:
&nbsp; &nbsp; Node: 12.16.2 - E:\node-v12.16.2-win-x64\node.EXE
&nbsp; &nbsp; Yarn: 1.22.11 - E:\node-v12.16.2-win-x64\yarn.CMD
&nbsp; &nbsp; npm: 6.14.4 - E:\node-v12.16.2-win-x64\npm.CMD
&nbsp; &nbsp; Watchman: Not Found
&nbsp; SDKs:
&nbsp; &nbsp; Android SDK:
&nbsp; &nbsp; &nbsp; API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
&nbsp; &nbsp; &nbsp; Build Tools: 23.0.2, 24.0.1, 24.0.2, 25.0.1, 27.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3
&nbsp; &nbsp; &nbsp; System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 A
tom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-Q | Android TV Intel x86 Atom
&nbsp; &nbsp; &nbsp; Android NDK: Not Found
&nbsp; &nbsp; Windows SDK: Not Found
&nbsp; IDEs:
&nbsp; &nbsp; Android Studio: Version&nbsp; 3.5.0.0 AI-191.8026.42.35.5977832
&nbsp; &nbsp; Visual Studio: 16.11.31624.102 (Visual Studio Community 2019)
&nbsp; Languages:
&nbsp; &nbsp; Java: 1.8.0_191
&nbsp; &nbsp; Python: Not Found
&nbsp; npmPackages:
&nbsp; &nbsp; @react-native-community/cli: Not Found
&nbsp; &nbsp; react: 16.13.1 =&gt; 16.13.1
&nbsp; &nbsp; react-native: 0.63.3 =&gt; 0.63.3
&nbsp; &nbsp; react-native-windows: Not Found
&nbsp; npmGlobalPackages:
&nbsp; &nbsp; *react-native*: Not Found



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reactnativecn/react-native-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 中午12:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [reactnativecn/react-native-website] android studio 运行rn一直报错 (#504)





 
环境信息呢  npx react-native info
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sunnylqm** [comment]
我搜了下，很多人说跟netinfo这个包有关，你有用这个吗？package.json贴出来看下

**Comment by McWangFei** [comment]
不理解netinfo这个包，这个项目是我刚入职接手的&nbsp;
{
  "name": "CloudPos",
  "version": "0.0.2",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    ***@***.***/async-storage": "^1.13.2",
    ***@***.***/datetimepicker": "^3.0.6",
    ***@***.***/masked-view": "^0.1.10",
    ***@***.***/bottom-tabs": "^5.11.2",
    ***@***.***/material-top-tabs": "^5.3.10",
    ***@***.***/native": "^5.9.3",
    ***@***.***/stack": "^5.12.6",
    ***@***.***/uuid": "^8.3.0",
    "crypto-js": "3.3.0",
    "decimal.js": "^10.2.1",
    "events": "^3.2.0",
    "immer": "^8.0.0",
    "install": "^0.13.0",
    "invariant": "^2.2.4",
    "md5": "^2.3.0",
    "moment": "^2.29.1",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-background-timer": "^2.4.1",
    "react-native-camera": "^3.40.0",
    "react-native-cli": "^2.0.1",
    "react-native-common-date-picker": "^2.3.3",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-get-random-values": "^1.5.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-reanimated": "^1.13.2",
    "react-native-root-siblings": "^4.0.6",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.15.0",
    "react-native-swipeable": "^0.6.0",
    "react-native-tab-view": "^2.15.2",
    "react-native-vector-icons": "^7.1.0",
    "react-navigation": "^4.4.3",
    "react-navigation-stack": "react-navigation/stack",
    "react-redux": "^7.2.2",
    "realm": "^10.0.1",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0",
    "uuid": "^8.3.1"
  },
  "devDependencies": {
    ***@***.***/core": "^7.8.4",
    ***@***.***/runtime": "^7.8.4",
    ***@***.***/cli": "^11.0.0",
    ***@***.***/config-angular": "^11.0.0",
    ***@***.***/bob": "^0.16.2",
    ***@***.***/eslint-config": "^1.1.0",
    ***@***.***/crypto-js": "^4.0.1",
    ***@***.***/jest": "^25.2.3",
    ***@***.***/lodash": "^4.14.167",
    ***@***.***/md5": "^2.2.1",
    ***@***.***/react-native": "^0.63.2",
    ***@***.***/react-native-background-timer": "^2.0.0",
    ***@***.***/react-native-datepicker": "^1.7.0",
    ***@***.***/react-redux": "^7.1.11",
    ***@***.***/react-test-renderer": "^16.9.2",
    ***@***.***/eslint-plugin": "^2.27.0",
    ***@***.***/parser": "^2.27.0",
    "babel-jest": "^25.1.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^6.15.0",
    "husky": "^4.3.0",
    "jest": "^25.1.0",
    "lint-staged": "^10.5.1",
    "lodash": "^4.17.20",
    "metro-react-native-babel-preset": "^0.59.0",
    "prettier": "^2.1.2",
    "react-test-renderer": "16.13.1",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "lint-staged": {
    "*.{js,jsx,vue,ts,tsx}": [
      "eslint . --fix --ext .js,.jsx,.ts,.tsx",
      "git add"
    ]
  },
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  },
  "description": "Android Sdk",
  "main": "index.js",
  "license": "MIT"
}





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sunny ***@***.***&gt;; 
发送时间: 2021年9月15日(星期三) 中午1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reactnativecn/react-native-website] android studio 运行rn一直报错 (#504)





 
我搜了下，很多人说跟netinfo这个包有关，你有用这个吗？package.json贴出来看下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sunnylqm** [comment]
这是由某个第三方模块引起的问题：

https://stackoverflow.com/questions/69019631/android-resource-linking-fails-on-test-execution-even-when-nothing-has-been-cha/69020629#69020629

简而言之，某个第三方模块引用了`androidx.core:core-ktx:+`这个安卓依赖，但这个月初`core-ktx`官方更新到了1.7版本，最低sdk版本要求为31，否则就会报这个错。所以解决方案是

1、把项目的compilesdkversion升级到31（顺带可能也要升级buildtools, gralde plugin, gradle等，根据编译时的提示操作），

或者

2、找到依赖了core-ktx的组件（这个很难找），锁死其版本为1.6

**Comment by sunnylqm** [comment]
另外你的组件依赖很混乱，导航器有多个重复版本，可能引发更多冲突。

**Comment by McWangFei** [comment]
解决了 谢谢大佬


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reactnativecn/react-native-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [reactnativecn/react-native-website] android studio 运行rn一直报错 (#504)





 
这是由某个第三方模块引起的问题：
 
https://stackoverflow.com/questions/69019631/android-resource-linking-fails-on-test-execution-even-when-nothing-has-been-cha/69020629#69020629
 
简而言之，某个第三方模块引用了androidx.core:core-ktx:+这个安卓依赖，但这个月初core-ktx官方更新到了1.7版本，最低sdk版本要求为31，否则就会报这个错。所以解决方案是把项目的compilesdkversion升级到31，或者找到依赖了core-ktx的组件（这个很难找），锁死其版本为1.6
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
