### ISSUE TITLE
无法运行到ios 救救我吧都弄了4天了

### ISSUE THREAD

**Issue by yueqiqi** [reactnativecn/react-native-website#506]
### ios模拟器能唤醒 xcworkspace在xcode中也不能运行,
<img width="544" alt="截屏2021-09-17 下午9 14 43" src="https://user-images.githubusercontent.com/50952334/133789196-2a0b12c4-6d07-4918-93c7-a273f439701f.png">
<img width="591" alt="截屏2021-09-17 下午9 20 15" src="https://user-images.githubusercontent.com/50952334/133789449-26b7c4e6-072c-4830-9993-f8b8f66bd024.png">
<img width="589" alt="截屏2021-09-17 下午9 20 35" src="https://user-images.githubusercontent.com/50952334/133789607-7da22f69-7977-40c4-92e6-53f333ee99ea.png">
<img width="600" alt="截屏2021-09-17 下午9 21 14" src="https://user-images.githubusercontent.com/50952334/133789717-449cc9a3-70cf-4090-b7f5-b15bdd030ab9.png">
<img width="568" alt="截屏2021-09-17 下午9 21 02" src="https://user-images.githubusercontent.com/50952334/133789724-1ddac2c4-5f24-47f7-b38e-848db4b33d75.png">

**Comment by sunnylqm** [comment]
首先，ios运行报错应该在xcode中截图，命令行中的报错不太明确


其次m1目前还有些兼容问题，我不确定官方有没有全部解决完，你可以试下刚发的最新测试版本


npx react-native init RN066 --version 0.66.0-rc.3




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月17日(周五) 晚上9:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 无法运行到ios 救救我吧都弄了4天了 (#506)




 
ios模拟器能唤醒 xcworkspace在xcode中也不能运行,

**Comment by yueqiqi** [comment]
好的谢谢大佬

**Comment by yueqiqi** [comment]
> 首先ios报错，应该在xcode中截图，命令行中的出现还不太清楚m1的问题，我明确官方有没有全部解决完，你可以试下刚发的最新测试版本npx react-本机初始化 RN066 --version 0.66.0-rc.3

好的谢谢大佬

**Comment by gssggssg** [comment]
解决问题了么？我也没有运行起来

**Comment by longjiecn** [comment]
同m1 mac，xcode下12.4的版本，然后按照这个流程弄一下试试 https://github.com/aiba/react-native-m1/blob/main/README.md

**Comment by Wang-yubo** [comment]
同问，m1 12.0.1系统，react-native 0.66.4, 
 PhaseScriptExecution [CP-User]\ Generate\ Specs 的问题跑不起来
