### ISSUE TITLE
【TextInput】the placeholderTextColor did not work

### ISSUE THREAD

**Issue by wyx0scottwu** [reactnativecn/react-native-website#507]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- placeholderTextColor 属性不生效
- 尝试过 string rgb 16进制色值都不生效
- 请尽量配上相关代码截图
- ![image](https://user-images.githubusercontent.com/87452707/133870852-1f3a12a2-00bd-4db9-8b2c-624bae4e48ce.png)

## 请描述完整的环境/版本信息
- System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
    Memory: 20.83 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: Not Found
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.14.0 => 16.14.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## 预期结果
- 正常显示占位符配置颜色

**Comment by sunnylqm** [comment]
实际显示截图看下
