### ISSUE TITLE
本地存储的数据怎么做安全啊

### ISSUE THREAD

**Issue by lh9403** [reactnativecn/react-native-website#511]
当前用的react-native-sqlite-storage，但是好像已经很久没有更新了，并且貌似也不支持设置数据库密码啥的，特别是在安卓上，用户会不会直接能打开数据库进行编辑

**Comment by sunnylqm** [comment]
本地没有安全可言，不要存敏感数据，就这样



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月23日(周四) 上午10:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 本地存储的数据怎么做安全啊 (#511)




 
当前用的react-native-sqlite-storage，但是好像已经很久没有更新了，并且貌似也不支持设置数据库密码啥的

**Comment by tyanbiao** [comment]
自己封装 SQLite 的 CRUD，Android 上可以用 android-database-sqlcipher 这个库来加密SQLite
