### ISSUE TITLE
更新rn0.66依赖安装后pod 卡在Installing boost (1.76.0)

### ISSUE THREAD

**Issue by wowtrxqn** [reactnativecn/react-native-website#514]
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 26.34 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.9.1/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

rn0.65.1升级0.66后 安卓可以运行, ios在pod install 卡在最后一步Installing boost (1.76.0) , 已经用了vpn

**Comment by sunnylqm** [comment]
确定下vpn是否对命令行生效了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月12日(周二) 中午11:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 更新rn0.66依赖安装后pod 卡在Installing boost (1.76.0) (#514)




 
info Fetching system and libraries information...
 System:
 OS: macOS 11.6
 CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 Memory: 26.34 MB / 16.00 GB
 Shell: 3.2.57 - /bin/bash
 Binaries:
 Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
 Yarn: 1.22.11 - ~/.nvm/versions/node/v16.9.1/bin/yarn
 npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
 Watchman: Not Found
 Managers:
 CocoaPods: 1.11.2 - /usr/local/bin/pod
 SDKs:
 iOS SDK:
 Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
 Android SDK: Not Found
 IDEs:
 Android Studio: 4.1 AI-201.8743.12.41.7042882
 Xcode: 13.0/13A233 - /usr/bin/xcodebuild
 Languages:
 Java: javac 15 - /usr/bin/javac
 npmPackages:
 @react-native-community/cli: Not Found
 react: Not Found
 react-native: Not Found
 react-native-macos: Not Found
 npmGlobalPackages:
 react-native: Not Found
 
rn0.65.1升级0.66后 安卓可以运行, ios在pod install 卡在最后一步Installing boost (1.76.0) , 已经用了vpn

**Comment by wowtrxqn** [comment]
> 确定下vpn是否对命令行生效了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年10月12日(周二) 中午11:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [reactnativecn/react-native-website] 更新rn0.66依赖安装后pod 卡在Installing boost (1.76.0) (#514) info Fetching system and libraries information... System: OS: macOS 11.6 CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz Memory: 26.34 MB / 16.00 GB Shell: 3.2.57 - /bin/bash Binaries: Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node Yarn: 1.22.11 - ~/.nvm/versions/node/v16.9.1/bin/yarn npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm Watchman: Not Found Managers: CocoaPods: 1.11.2 - /usr/local/bin/pod SDKs: iOS SDK: Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0 Android SDK: Not Found IDEs: Android Studio: 4.1 AI-201.8743.12.41.7042882 Xcode: 13.0/13A233 - /usr/bin/xcodebuild Languages: Java: javac 15 - /usr/bin/javac npmPackages: @react-native-community/cli: Not Found react: Not Found react-native: Not Found react-native-macos: Not Found npmGlobalPackages: react-native: Not Found rn0.65.1升级0.66后 安卓可以运行, ios在pod install 卡在最后一步Installing boost (1.76.0) , 已经用了vpn — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我都没搜到boost-for-react-native 1.76.0的版本...

**Comment by sunnylqm** [comment]
现在是直接取boost的源码编译

https://github.com/facebook/react-native/blob/main/third-party-podspecs/boost.podspec#L13

**Comment by wowtrxqn** [comment]
可以了 ,谢谢

**Comment by wowtrxqn** [comment]
ios && android 运行ok
