### ISSUE TITLE
android还是不支持动态图

### ISSUE THREAD

**Issue by gujunwuxichina** [reactnativecn/react-native-website#515]
## 问题的具体描述
android加了如下还是不支持gif动态图
implementation 'com.facebook.fresco:animated-gif:2.0.0'

## 请描述完整的环境/版本信息
"react-native": "0.66.0"

## 预期结果
。

**Comment by sunnylqm** [comment]
0.66现在用的是2.5.0版本

https://github.com/facebook/react-native/blob/v0.66.0/ReactAndroid/gradle.properties#L14

**Comment by 8656361** [comment]
![image](https://user-images.githubusercontent.com/62878617/138631087-2b6533d3-58de-4f11-9131-27c12370aea7.png)
0.65   一个个试了一遍，安卓还是gif还是不会动， ios正常

**Comment by 8656361** [comment]
有人试过安卓加载gif吗？

**Comment by sunnylqm** [comment]
???你试了啥??? 0.65它也是2.5.0的版本啊  https://github.com/facebook/react-native/blob/0.65-stable/ReactAndroid/gradle.properties

**Comment by 8656361** [comment]
> ![image](https://user-images.githubusercontent.com/62878617/138631087-2b6533d3-58de-4f11-9131-27c12370aea7.png) 0.65 一个个试了一遍，安卓还是gif还是不会动， ios正常
感谢大佬，解决了，animated-gif: 用的2.5.0， animated-webp:2.1.0 都不存在，官方文档也不靠谱
![EQ0`8HH2TZQUIAVSC 1O1%O](https://user-images.githubusercontent.com/62878617/138643079-d4168cc8-015e-4882-808c-663287db5ab6.jpg)

**Comment by 8656361** [comment]
![image](https://user-images.githubusercontent.com/62878617/138643218-f7516b4d-47b9-4aed-9bdd-f18341316eb9.png)
用这个

**Comment by sunnylqm** [comment]
我上面已经提示了这个问题的根源（版本不匹配）。文档是人写的，没人更新它就永远不会更新。你遇到了这个问题，验证了，你想起来去提交个pr更新下文档不？
