### ISSUE TITLE
react native  高版本flex:1 显示的问题

### ISSUE THREAD

**Issue by Shilver-afka** [reactnativecn/react-native-website#516]
## 问题的具体描述
   目前在做react native 项目升级 ， 现在项目的版本 是0.30 ， 升级后的版本是0.63 . 升级之后项目运行起来，出现了很多显示上的问题，其中很多都是flex:1 引起的 ，删除了部分flex:1显示正常。
     我找了一份代码，在0.3环境有无flex:1显示都一样，在0.63环境删除flex:1 显示出现变化。有知道是什么问题么？
           <View>
              <View
                style={{
                  flex: 1,
                  margin: 40,
                  padding: 10,
                  backgroundColor: 'red',
                }}
              >
                <Text>111111</Text>
              </View>
            </View

**Comment by sunnylqm** [comment]
你这个版本跨度好几年了，很早以前这个布局行为就有变化

**Comment by sunnylqm** [comment]
比如0.39升级了yoga布局引擎（那时候还叫csslayout） https://github.com/facebook/react-native/commit/d63ba47b59e3261403800c1f741d979a089efb48  修正了一些布局bug也提高了性能，但副作用是以前版本的一些flex: 1实际是不必要或者不正确的，在新版本中会导致布局的变化

**Comment by sunnylqm** [comment]
那时候（5年前了。。。）的一些讨论 https://github.com/facebook/react-native/issues/11441
