### ISSUE TITLE
版本 0.6.6  按照官网流程安装报错FBReactNNativeSpec错误

### ISSUE THREAD

**Issue by JulyEve** [reactnativecn/react-native-website#517]
or/FlipperKit.build/Objects-normal/x86_64/FBCxxFollyDynamicConvert.o

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/julyeve/Library/Developer/Xcode/DerivedData/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-337605CB7CDF90939BEBF863ED22C375.sh (in target 'FBReactNativeSpec' from project 'Pods')
(1 failure)

信息： 
![image](https://user-images.githubusercontent.com/18692248/140633991-894674d0-a193-4120-8264-efd02593ddf9.png)

**Comment by likeSo** [comment]
```ruby
installer.pods_project.targets.each do |target|
     if (target.name&.eql?('FBReactNativeSpec'))
       target.build_phases.each do |build_phase|
         if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
           target.build_phases.move(build_phase, 0)
         end
       end
     end
end
```
 复制到你的Podfile里面

**Comment by Wang-yubo** [comment]
> ```ruby
> .pods_project.targets.each do |target|
>      if (target.name&.eql?('FBReactNativeSpec'))
>        target.build_phases.each do |build_phase|
>          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
>            target.build_phases.move(build_phase, 0)
>          end
>        end
>      end
> end
> ```

请问具体是放到那个位置呢？我试了直接放在末尾或者放在use_flipper!() 的后面都会报错

**Comment by likeSo** [comment]
> > ```ruby
> > .pods_project.targets.each do |target|
> >      if (target.name&.eql?('FBReactNativeSpec'))
> >        target.build_phases.each do |build_phase|
> >          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
> >            target.build_phases.move(build_phase, 0)
> >          end
> >        end
> >      end
> > end
> > ```
> 
> 请问具体是放到那个位置呢？我试了直接放在末尾或者放在use_flipper!() 的后面都会报错

官方文档里面的Podfile配置项不是最新的，你可以使用`npx react-native init`命令创建一个新项目，然后把Podfile复制出来。大概长这样：
```ruby
post_install do |installer|
   react_native_post_install(installer)
   installer.pods_project.targets.each do |target|
     if (target.name&.eql?('FBReactNativeSpec'))
       target.build_phases.each do |build_phase|
         if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
           target.build_phases.move(build_phase, 0)
         end
       end
     end
end
```

**Comment by Wang-yubo** [comment]
> > > ```ruby
> > > .pods_project.targets.each do |target|
> > >      if (target.name&.eql?('FBReactNativeSpec'))
> > >        target.build_phases.each do |build_phase|
> > >          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
> > >            target.build_phases.move(build_phase, 0)
> > >          end
> > >        end
> > >      end
> > > end
> > > ```
> > 
> > 
> > 请问具体是放到那个位置呢？我试了直接放在末尾或者放在use_flipper!() 的后面都会报错
> 
> 官方文档里面的Podfile配置项不是最新的，你可以使用`npx react-native init`命令创建一个新项目，然后把Podfile复制出来。大概长这样：
> 
> ```ruby
> post_install do |installer|
>    react_native_post_install(installer)
>    installer.pods_project.targets.each do |target|
>      if (target.name&.eql?('FBReactNativeSpec'))
>        target.build_phases.each do |build_phase|
>          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
>            target.build_phases.move(build_phase, 0)
>          end
>        end
>      end
> end
> ```

好的，感谢回复。补充一下，我现在是刚init了一个0.66.4版本的项目。现在的Podlife是这样的：
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'AwesomeProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'AwesomeProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end


现在在Xcode中可以运行起来，但是在终端中运行就会报： PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/wangyubo/Library/Developer/Xcode/DerivedData/AwesomeProject-dazyvhlafdzloobmkkqjxuylcwxi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-337605CB7CDF90939BEBF863ED22C375.sh (in target 'FBReactNativeSpec' from project 'Pods')
这样的问题。

**Comment by likeSo** [comment]
> > > > ```ruby
> > > > .pods_project.targets.each do |target|
> > > >      if (target.name&.eql?('FBReactNativeSpec'))
> > > >        target.build_phases.each do |build_phase|
> > > >          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
> > > >            target.build_phases.move(build_phase, 0)
> > > >          end
> > > >        end
> > > >      end
> > > > end
> > > > ```
> > > 
> > > 
> > > 请问具体是放到那个位置呢？我试了直接放在末尾或者放在use_flipper!() 的后面都会报错
> > 
> > 
> > 官方文档里面的Podfile配置项不是最新的，你可以使用`npx react-native init`命令创建一个新项目，然后把Podfile复制出来。大概长这样：
> > ```ruby
> > post_install do |installer|
> >    react_native_post_install(installer)
> >    installer.pods_project.targets.each do |target|
> >      if (target.name&.eql?('FBReactNativeSpec'))
> >        target.build_phases.each do |build_phase|
> >          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
> >            target.build_phases.move(build_phase, 0)
> >          end
> >        end
> >      end
> > end
> > ```
> 
> 好的，感谢回复。补充一下，我现在是刚init了一个0.66.4版本的项目。现在的Podlife是这样的： require_relative '../node_modules/react-native/scripts/react_native_pods' require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> platform :ios, '11.0'
> 
> target 'AwesomeProject' do config = use_native_modules!
> 
> use_react_native!( :path => config[:reactNativePath], # to enable hermes on iOS, change `false` to `true` and then install pods :hermes_enabled => true )
> 
> target 'AwesomeProjectTests' do inherit! :complete # Pods for testing end
> 
> # Enables Flipper.
> # Note that if you have use_frameworks! enabled, Flipper will not work and
> # you should disable the next line.
> use_flipper!()
> 
> post_install do |installer| react_native_post_install(installer) __apply_Xcode_12_5_M1_post_install_workaround(installer) end end
> 
> 现在在Xcode中可以运行起来，但是在终端中运行就会报： PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/wangyubo/Library/Developer/Xcode/DerivedData/AwesomeProject-dazyvhlafdzloobmkkqjxuylcwxi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-337605CB7CDF90939BEBF863ED22C375.sh (in target 'FBReactNativeSpec' from project 'Pods') 这样的问题。

不是报错就问题不大

**Comment by Wang-yubo** [comment]
m1 的 iOS端 我终于解决了，换了启动命令，用这两个：arch -arm64 yarn ios 或者 arch -arm64 npx react-native run-ios
