### ISSUE TITLE
mac m1 build android BUILD SUCCESSFUL in 2h 7m 54s

### ISSUE THREAD

**Issue by Darcula666** [reactnativecn/react-native-website#518]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2h 7m 54s
451 actionable tasks: 55 executed, 33 from cache, 363 up-to-date
12:56:31: Task execution finished 'assembleRelease'.
Disconnected from the target VM, address: '127.0.0.1:64623', transport: 'socket'

**Comment by sunnylqm** [comment]
编译已经完成，但安装到模拟器上的步骤失败（不明原因，我也不知道怎么解决）
能做的就是，重试，重启，重装模拟器，换模拟器，换真机
