### ISSUE TITLE
react-native init xxx 【初始化报错 mac上】

### ISSUE THREAD

**Issue by zhangyu0812** [reactnativecn/react-native-website#520]
<img width="840" alt="WeChatb6365930e91925b140c1e772141b02fe" src="https://user-images.githubusercontent.com/44884657/142587603-41a898c5-a3f3-4b37-af58-9d3db3ba33b9.png">

**Comment by sunnylqm** [comment]
刚刚已经回答过你，你现在还额外犯了一个错误

![image](https://user-images.githubusercontent.com/615282/142587890-5636652e-5550-46d4-a515-a63d1b86b491.png)
