### ISSUE TITLE
初始化报错

### ISSUE THREAD

**Issue by zhangyu0812** [reactnativecn/react-native-website#522]
<img width="840" alt="WeChatb6365930e91925b140c1e772141b02fe" src="https://user-images.githubusercontent.com/44884657/142589630-1278b64c-a72b-4fae-aec9-befcef1dc5ec.png">

官方要求的弄的版本是大于12，我这14怎么不行呢。 windows上12的版本就可以，

**Comment by sunnylqm** [comment]
rn有rn的要求，第三方有第三方的要求，最终的要求等于所有依赖要求的交集. 部分node版本有已知的问题（可能还针对某些平台），所以某些依赖强行明确要求跳过咯。要求什么就给什么，有什么好纠结的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月19日(周五) 下午4:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 初始化报错 (Issue #522)




 

 
官方要求的弄的版本是大于12，我这14怎么不行呢。 windows上12的版本就可以，

**Comment by sunnylqm** [comment]
如果你是看不懂上面的报错，上面说的是14版本可以，但是必须大于14.15版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月19日(周五) 下午4:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 初始化报错 (Issue #522)




 

 
官方要求的弄的版本是大于12，我这14怎么不行呢。 windows上12的版本就可以，

**Comment by sunnylqm** [comment]
另外，可以不要一直重复开issue么

**Comment by zhangyu0812** [comment]
> rn有rn的要求，第三方有第三方的要求，最终的要求等于所有依赖要求的交集. 部分node版本有已知的问题（可能还针对某些平台），所以某些依赖强行明确要求跳过咯。要求什么就给什么，有什么好纠结的？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月19日(周五) 下午4:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [reactnativecn/react-native-website] 初始化报错 (Issue #522) 官方要求的弄的版本是大于12，我这14怎么不行呢。 windows上12的版本就可以， — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的 谢谢 已解决
