### ISSUE TITLE
yarn ios 报错，搞了一天了还是不行，各位帮看看 谢谢

### ISSUE THREAD

**Issue by zhangyu0812** [reactnativecn/react-native-website#525]
mac环境搭建了一天运行安卓可以 yarn ios不行
<img width="853" alt="WeChat97c9474236da35379efcfe977ac2f0c8" src="https://user-images.githubusercontent.com/44884657/142651194-cbdfa803-8de2-4cfc-9a54-eba34611d369.png">
初始化项目react-native init myapp 到这一步就一直卡着不动。
然后我就ctr+c 停止了 发现项目是初始化成功了 运行yarn android也是成功的。
但运行yarn ios就报错了。而且ios文件夹下面文件好像不全 没有官方说的. xcworkspace文件。
<img width="500" alt="WeChatfd5d0dd4b02458f1f5fcd417c55d3f20" src="https://user-images.githubusercontent.com/44884657/142651412-3bd4e8ca-09fb-49ec-9585-f054dfbbfcc6.png">
件
<img width="685" alt="WeChat16f2356031c034efdc558361aa5d5ca4" src="https://user-images.githubusercontent.com/44884657/142651419-57f517cf-a248-49ac-a0d7-cc015c465749.png">
都是按着文档一步步来的，不知道哪里出了错
<img width="470" alt="WeChat49a97906da82963d2f8263c42015dc3f" src="https://user-images.githubusercontent.com/44884657/142651495-8641c620-c1f3-4f5c-b7c5-d45e40fcc210.png">

<img width="535" alt="WeChatf5e4dbd6ce5824541293f9a23f9a45f2" src="https://user-images.githubusercontent.com/44884657/142651503-ecc17428-eeeb-4b5c-8b37-bebcc0bc98cc.png">

我的mac是i5的 不是m1

**Comment by sunnylqm** [comment]
需要配置代理的

**Comment by zhangyu0812** [comment]
> 需要配置代理的
您说的是项目初始化不完全缺少文件么？网络 不行？

**Comment by sunnylqm** [comment]
是的，网络问题导致cocoapods初始化没有完成，所以不完整



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月20日(周六) 上午10:54
收件人: ***@***.***&gt;;
抄送: "Sunny ***@***.******@***.***&gt;;
主题: Re: [reactnativecn/react-native-website] yarn ios 报错，搞了一天了还是不行，各位帮看看 谢谢 (Issue #525)




  
需要配置代理的
 您说的是项目初始化不完全缺少文件么？网络 不行？

**Comment by zhangyu0812** [comment]
> 是的，网络问题导致cocoapods初始化没有完成，所以不完整
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月20日(周六) 上午10:54 收件人: ***@***.***&gt;; 抄送: "Sunny ***@***.******@***.***&gt;; 主题: Re: [reactnativecn/react-native-website] yarn ios 报错，搞了一天了还是不行，各位帮看看 谢谢 (Issue #525) 需要配置代理的 您说的是项目初始化不完全缺少文件么？网络 不行？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
windows下初始化项目为什么没有这一项呢，react-native会识别当前电脑环境么？

**Comment by binSty** [comment]
npx react-native init MyApp, 初始化成功的iOS项目是pod管理的(注意 0.60 版本之后的主项目文件是.xcworkspace，不是.xcodeproj！)，很显然，你的项目结构不对，如果初始化成功，iOS项目结构肯定是带.xcworkspace文件的。你也可以尝试一下，自己创建iOS Pod管理的项目。
