### ISSUE TITLE
cocopads这个怎么快速安装啊，试了很多次都不行

### ISSUE THREAD

**Issue by zhangyu0812** [reactnativecn/react-native-website#526]
![image](https://user-images.githubusercontent.com/44884657/142716364-9f71a1dd-c4db-4f47-a57d-445e2185ec3a.png)

**Comment by sunnylqm** [comment]
你不是已经安装了么，还安装它干什么？

cocoapods类比npm，它本身已经安装完成了，但是在rn初始化的过程中它还要执行类似npm install的操作，这一步必须挂代理

**Comment by zhangyu0812** [comment]
> 你不是已经安装了么，还安装它干什么？
> 
> cocoapods类比npm，它本身已经安装完成了，但是在rn初始化的过程中它还要执行类似npm install的操作，这一步必须挂
哎，不是很懂啊也不知道哪里出了问题。这个ios搞了很久还是跑不起来。
![image](https://user-images.githubusercontent.com/44884657/142716713-874c4bc1-ae91-405b-80b7-8550def58da1.png)
用brew一下就装好了，用gem装就报错，也不知道到底装成功没有。
看了一下好像没有 cocoapods啊。都是cocoapods- xxx 什么的

**Comment by sunnylqm** [comment]
用`pod --version`命令查看

**Comment by sunnylqm** [comment]
`npm install`是干什么不懂吗？

**Comment by zhangyu0812** [comment]
> pod --version
![image](https://user-images.githubusercontent.com/44884657/142717027-da69f1a6-76f4-4d13-a4f5-fb1122670221.png)
这个是you有的。 npm install 不就是装一些需要的依赖么

**Comment by sunnylqm** [comment]
那就是已经装好了啊。pod也是干装依赖的事情啊，rn初始化的时候其实就是先调用`npm install`（或者yarn，如果你装了yarn的话），然后在ios目录中执行`pod install`，这个过程必须通过代理访问源，否则安装失败

**Comment by zhangyu0812** [comment]
> 那就是已经装好了啊。pod也是干装依赖的事情啊，rn初始化的时候其实就是先调用`npm install`（或者yarn，如果你装了yarn的话），然后在ios目录中执行`pod install`，这个过程必须通过代理访问源，否则安装失败
![image](https://user-images.githubusercontent.com/44884657/142717253-84223c99-d529-45ef-89a0-e6b2288e021c.png)
好的，xie xi谢谢，再问一下哈。这个初始化项目的时候卡在这理。这个是不是相当于在pod Install。 我把它停止了 手动进入ios下执行 pod install 是不是一样可以。 这个操作是对的吧？

**Comment by sunnylqm** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月20日(周六) 下午2:42
收件人: ***@***.***&gt;;
抄送: "Sunny ***@***.******@***.***&gt;;
主题: Re: [reactnativecn/react-native-website] cocopads这个怎么快速安装啊，试了很多次都不行 (Issue #526)




  
那就是已经装好了啊。pod也是干装依赖的事情啊，rn初始化的时候其实就是先调用npm install（或者yarn，如果你装了yarn的话），然后在ios目录中执行pod install，这个过程必须通过代理访问源，否则安装失败
 
 好的，xie xi谢谢，再问一下哈。这个初始化项目的时候卡在这理。这个是不是相当于在pod Install。 我把它停止了 手动进入ios下执行 pod install 是不是一样可以。 这个操作是对的吧？

**Comment by zhangyu0812** [comment]
> 
谢谢大佬 ，已经解决。 respsect！

**Comment by zhangyu0812** [comment]
> 是的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月20日(周六) 下午2:42 收件人: ***@***.***&gt;; 抄送: "Sunny ***@***.******@***.***&gt;; 主题: Re: [reactnativecn/react-native-website] cocopads这个怎么快速安装啊，试了很多次都不行 (Issue #526) 那就是已经装好了啊。pod也是干装依赖的事情啊，rn初始化的时候其实就是先调用npm install（或者yarn，如果你装了yarn的话），然后在ios目录中执行pod install，这个过程必须通过代理访问源，否则安装失败 好的，xie xi谢谢，再问一下哈。这个初始化项目的时候卡在这理。这个是不是相当于在pod Install。 我把它停止了 手动进入ios下执行 pod install 是不是一样可以。 这个操作是对的吧？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
谢谢大佬 ，已经解决。 respsect！
