### ISSUE TITLE
滚动页面 如何 tab sticky 

### ISSUE THREAD

**Issue by molikar** [reactnativecn/react-native-website#528]
如何实现页面滚动然后 tab 可以sticky 在最上面 左右滑动切换。试了网上的很多方法都不行
![a7a9df831fa2f422a35eaacae2af9f3](https://user-images.githubusercontent.com/27952297/142750398-47871bc5-8dcd-4598-aaa7-604f858dcda7.jpg)
类似这种header可以折叠，然后tab 可以切换

**Comment by sunnylqm** [comment]
总之挺复杂的，要用react-native-gesture-handler + react-native-reanimated

可参考
https://github.com/gorhom/react-native-bottom-sheet
https://github.com/jeremybarbet/react-native-modalize

**Comment by molikar** [comment]
这种效果，可以付费解决，希望得到大佬的帮助，感谢了

https://user-images.githubusercontent.com/27952297/142794516-80def011-2020-4bbb-bcb6-17e87a3ee9b1.mp4

**Comment by 282931** [comment]
react-native-collapsible-tab-view
