### ISSUE TITLE
pod install一直报错

### ISSUE THREAD

**Issue by frontend-winter** [reactnativecn/react-native-website#530]
请按以下格式提供问题的相关信息。

## 问题的具体描述
pod install 一直报错

## 请描述完整的环境/版本信息

 ```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 27.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 30.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
 *react-native*: Not Found

## 预期结果
能正常运行

**Comment by sunnylqm** [comment]
最重要的信息，报错截图呢

**Comment by knowledges** [comment]
![6151643206560_ pic](https://user-images.githubusercontent.com/8423645/151182084-07b6e6fb-a207-46fc-879e-c32b44596593.jpg)
图片中提示我 cocoapods 未安装，但是，我已经安装过了。通过 pod --version 可以查看到 路径
目前系统是最新的 11.6
xcode 也是最新的 13.2.1
gem 、brew、已经是最新版本
bury-2.7.4

**Comment by knowledges** [comment]
![image](https://user-images.githubusercontent.com/8423645/151183217-ee44a5e5-3ff1-4688-a29a-96242cab952d.png)

**Comment by sunnylqm** [comment]
我没有用过rvm，不了解它的机制，但我注意到在你的截图里，在项目目录里不能运行pod，但在上一层目录里就可以，是否rvm的环境是与目录相关而非全局有效的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 晚上10:38
收件人: ***@***.***&gt;;
抄送: "Sunny ***@***.******@***.***&gt;;
主题: Re: [reactnativecn/react-native-website] pod install一直报错 (Issue #530)

**Comment by knowledges** [comment]
我的问题已经解决。我能正常运行了。
