### ISSUE TITLE
iOS Debug模式正常，Release报错

### ISSUE THREAD

**Issue by binSty** [reactnativecn/react-native-website#532]
1. 最开始尝试iOS项目里面嵌入一个RN页面，Debug模式都正常的，bundle也正常加载。但是Xcode切换Release，就报错Pod原生项目集成的三方找不到。
2. 然后尝试npx react-native init NewProject创建新的项目，Debug正常, Release也是启动不了。

刚开始接触RN，请问，原生集成RN在Release模式下是需要什么额外的配置或者额外的注意点吗？

**Comment by sunnylqm** [comment]
要看具体的报错，先确定是你这边个别的问题，还是某个版本特定的共有的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月10日(周五) 上午10:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] iOS Debug模式正常，Release报错 (Issue #532)




  
最开始尝试iOS项目里面嵌入一个RN页面，Debug模式都正常的，bundle也正常加载。但是Xcode切换Release，就报错Pod原生项目集成的三方找不到。 

然后尝试npx react-native init NewProject创建新的项目，Debug正常, Release也是启动不了。 
 
刚开始接触RN，请问，原生集成RN在Release模式下是需要什么额外的配置或者额外的注意点吗？

**Comment by binSty** [comment]
我是使用RN 0.66版本的Pod，iOS项目嵌入RN，比如之前项目Pod有AFNetworking，在Debug正常，Release会在AFNetworking头文件导入那里报错找不到

**Comment by binSty** [comment]
> 要看具体的报错，先确定是你这边个别的问题，还是某个版本特定的共有的问题
> […](#)

npx reaxt-native init NewProject的项目 模拟器报错也许是Xcode的未知问题影响的，真机可以运行Release版本。
我个人项目 嵌入RN后，Release模式下，之前Pod的三方头文件都提示找不到。我只能一步步尝试去修改了。。

**Comment by likeSo** [comment]
> > 要看具体的报错，先确定是你这边个别的问题，还是某个版本特定的共有的问题
> > […](#)
> 
> npx reaxt-native init NewProject的项目 模拟器报错也许是Xcode的未知问题影响的，真机可以运行Release版本。 我个人项目 嵌入RN后，Release模式下，之前Pod的三方头文件都提示找不到。我只能一步步尝试去修改了。。

你是不是改过AppDele文件，是不是添加过其他的头文件？检查下是不是放错地方了，上面都有预编译指令的

**Comment by binSty** [comment]
> > > 要看具体的报错，先确定是你这边个别的问题，还是某个版本特定的共有的问题
> > > […](#)
> > 
> > 
> > npx reaxt-native init NewProject的项目 模拟器报错也许是Xcode的未知问题影响的，真机可以运行Release版本。 我个人项目 嵌入RN后，Release模式下，之前Pod的三方头文件都提示找不到。我只能一步步尝试去修改了。。
> 
> 你是不是改过AppDele文件，是不是添加过其他的头文件？检查下是不是放错地方了，上面都有预编译指令的

没、是原生项目里面单独某个按钮点击进入RN页面，没在AppDelegate里面处理。目前问题是，我们项目单独Release正常，仅仅加入RN的标准库，就报错找不到Pod第三方了，比如(AF、MJ)这些原Pod。额外的演示Demo没问题，也行是我们项目的问题。就是没找到解决办法。。。

**Comment by binSty** [comment]
项目Pod版本问题
