### ISSUE TITLE
createMaterialTopTabNavigator 侧滑返回失效

### ISSUE THREAD

**Issue by DaiyiLL** [reactnativecn/react-native-website#533]
代码如下，在子页面侧滑返回没有了，找了文档没有发现哪个是
export default class TopTabController extends React.Component {

  render() {
    const {navigation, route} = this.props;
    return (
      <Tab.Navigator
        backBehavior="none"
        visible={true}
        screenOptions={{
          tabBarItemStyle: () => <Text>12344</Text>,
          swipeEnabled: true,
          scrollEnabled: true,
          backBehavior: 'none',
        }}>
        <Tab.Screen
          name="All"
          component={() => (
            <TopChildController backgroundColor="red" tab="All" />
          )}
          options={{
            tabBarLabel: '全部',
            tabBarIcon: ({tintColor, focused}) => (
              <Ionicons
                name={focused ? 'ios-home' : 'ios-home-outline'}
                size={24}
                style={{color: tintColor}}
              />
            ),
          }}
        />
        <Tab.Screen
          name="Doing"
          component={() => (
            <TopChildController backgroundColor="green" tab="Doing" />
          )}
        />
        <Tab.Screen
          name="Done"
          component={() => (
            <TopChildController backgroundColor="blue" tab="Done" />
          )}
        />
      </Tab.Navigator>
    );
  }

  componentDidMount() {
    this.props.navigation.setOptions({
      title: '个人中心',
    });
  }
}

function MyTabBar({state, descriptors, navigation, position}) {
  return (
    <View
      style={{
        flexDirection: 'row',
        height: 44,
        width: Dimensions.get('window').width,
        justifyContent: 'center',
        alignItems: 'center',
      }}>
      {state.routes.map((route, index) => {
        const {options} = descriptors[route.key];
        const label =
          options.tabBarLabel !== undefined
            ? options.tabBarLabel
            : options.title !== undefined
            ? options.title
            : route.name;

        const isFocused = state.index === index;

        const onPress = () => {
          const event = navigation.emit({
            type: 'tabPress',
            target: route.key,
            canPreventDefault: true,
          });

          if (!isFocused && !event.defaultPrevented) {
            // The `merge: true` option makes sure that the params inside the tab screen are preserved
            navigation.navigate({name: route.name, merge: true});
          }
        };

        const onLongPress = () => {
          navigation.emit({
            type: 'tabLongPress',
            target: route.key,
          });
        };

        const inputRange = state.routes.map((_, i) => i);
        const opacity = position.interpolate({
          inputRange,
          outputRange: inputRange.map(i => (i === index ? 1 : 0)),
        });

        return (
          <TouchableOpacity
            accessibilityRole="button"
            accessibilityState={isFocused ? {selected: true} : {}}
            accessibilityLabel={options.tabBarAccessibilityLabel}
            testID={options.tabBarTestID}
            onPress={onPress}
            onLongPress={onLongPress}
            style={{flex: 1}}>
            <Animated.Text style={{opacity}}>{label}</Animated.Text>
          </TouchableOpacity>
        );
      })}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'green',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

**Comment by memoryseven** [comment]
gestureEnabled ？
