### ISSUE TITLE
react native版本为0.66.4，不能通过Linking.openURL()拨打电话

### ISSUE THREAD

**Issue by zhangshengmao** [reactnativecn/react-native-website#534]
function (phone: string) {
  phone = `tel:188888888`;
  Linking.canOpenURL(phone)
    .then(supported => {
      if (!supported) {
        console.log("Can't handle url: " + phone);
      } else {
        return Linking.openURL(phone);
      }
    })
    .catch(err => console.error('An error occurred', err));
}
升级到最新版本之后android不能拨打电话

react native版本为0.66.4，
猜测是因为sdk升级从29到了30
 ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
    }

## 预期结果
能够拨打电话，打开短信编辑

**Comment by sixstones-sys** [comment]
我也有类似的需求，请问解决了吗

**Comment by qilovehua** [comment]
0.66.4 我这试了ios/android可以拨打

buildToolsVersion = "30.0.2"
minSdkVersion = 23
compileSdkVersion = 31
targetSdkVersion = 31

**Comment by sixstones-sys** [comment]
谢谢，我试了用这个方法可以解决 openURL
Linking.openURL(`tel:${this.corp_info?.contact_mobile}`).then(supported => {
                  if (!supported) {
                    // 手机不支持
                  }
                  return Linking.openURL(this.corp_info?.contact_mobile || '');
                }).catch(err => {
                  Toast.info('错误:' + err)
                })
