### ISSUE TITLE
yarn react-native run-ios 报错error Could not find "Podfile.lock" at null.lock. Did you run "pod install" in iOS directory?

### ISSUE THREAD

**Issue by xiaowasly** [reactnativecn/react-native-website#535]
xcode启动没问题 用yarn react-native run-ios 
报错error Could not find "Podfile.lock" at null.lock. Did you run "pod install" in iOS directory?

xodce版本13.1  cocopods版本1.11.2  node v14.18.2

**Comment by sunnylqm** [comment]
ios目录里的文件截图看下，package.json也截图看下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月16日(周四) 上午10:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] yarn react-native run-ios 报错error Could not find "Podfile.lock" at null.lock. Did you run "pod install" in iOS directory? (Issue #535)




 
xcode启动没问题 用yarn react-native run-ios
 报错error Could not find "Podfile.lock" at null.lock. Did you run "pod install" in iOS directory?
 
xodce版本13.1  cocopods版本1.11.2  node v14.18.2

**Comment by xiaowasly** [comment]
<img width="448" alt="123" src="https://user-images.githubusercontent.com/22368246/146298591-ce926708-45b4-47ae-b2cd-b508e1dc501d.png">
<img width="882" alt="234" src="https://user-images.githubusercontent.com/22368246/146298610-2be5887c-1ca5-4e03-b577-1bef77f34661.png">
<img width="876" alt="345" src="https://user-images.githubusercontent.com/22368246/146298622-d7af0409-feb3-4cd9-8a4f-30bebdb2c22f.png">
<img width="871" alt="456" src="https://user-images.githubusercontent.com/22368246/146298629-d4486910-44c3-49ad-9287-6028635d25ff.png">

package.json内容有点多  麻烦了

**Comment by sunnylqm** [comment]
具体报错再截个图，还有npx react-native info截个图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月16日(周四) 上午10:46
收件人: ***@***.***&gt;;
抄送: "Sunny ***@***.******@***.***&gt;;
主题: Re: [reactnativecn/react-native-website] yarn react-native run-ios 报错error Could not find "Podfile.lock" at null.lock. Did you run "pod install" in iOS directory? (Issue #535)




 

 

 

 

 
package.json内容有点多  麻烦了

**Comment by xiaowasly** [comment]
<img width="1274" alt="123" src="https://user-images.githubusercontent.com/22368246/146300154-32fd78da-d340-46a2-bda6-9fc4c80f77a7.png">
<img width="1050" alt="234" src="https://user-images.githubusercontent.com/22368246/146300164-bf722611-bec5-4d13-8193-e73dd45a8b9d.png">

**Comment by Wang-yubo** [comment]
error code 65 这个问题我遇到很多次。我建议你试下 arch -arm64 npx react-native run-ios

**Comment by sunnylqm** [comment]
@Wang-yubo code 65 没有任何具体信息，只是一个通用的报错代号。人家这也不是m1的机器

**Comment by xiaowasly** [comment]
@Wang-yubo 对的 我不是M1的机子
<img width="745" alt="123" src="https://user-images.githubusercontent.com/22368246/146343904-56b9b252-29fe-4f06-a5f7-2e4f575f256b.png">

**Comment by sunnylqm** [comment]
如果xcode能执行的话，那就可能是这个版本的cli的bug，建议升级rn

**Comment by xiaowasly** [comment]
嗯嗯 非常感谢耐心的回复 


| |
xiao990610
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年12月16日 17:31，Sunny ***@***.***> 写道：

如果xcode能执行的话，那就可能是这个版本的cli的bug，建议升级rn

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hitanquan** [comment]
兄弟，这个问题后来怎么解决的，我刚接触react-native，也是遇到这个问题。
