### ISSUE TITLE
请教一下原生模块的问题

### ISSUE THREAD

**Issue by qianduanxiaobai1114** [reactnativecn/react-native-website#536]
刚开始学ract-native，按照官网教程写了android原生模块ToastModule，但是NativeModules里面没有东西。
ToastExample.show报错 ‘null is not an object’。
我是使用react-native init 创建的项目，只加了CustomToastPackage.java和ToastModule.java2个文件，其他都没动过。
请问有谁知道怎么回事吗？
"react": "17.0.2",
"react-native": "0.66.4"

原来是沙盒模式的问题......

**Comment by xiangwang1965** [comment]
我现在还有这种问题，请问是如何解决的呢
