### ISSUE TITLE
RN 原英文网站已更新 `设计 - 使用 Flexbox 布局` 部分 `flexShrink` 默认值相关文档，中文版需跟进更新

### ISSUE THREAD

**Issue by shotforsky** [reactnativecn/react-native-website#548]
## 问题的具体描述
在查阅中发现，中英文文档存在差异，其中 `设计 - 使用 Flexbox 布局` 部分 `flexShrink` 默认值 的文档，截止目前(2021-01-04)，差异如下

![image](https://user-images.githubusercontent.com/14038117/148036871-a953ace4-4fcd-4596-ac0a-3e9f0b6b13cb.png)

通过查阅英文版文档的提交记录发现，存在如下的更改记录：
![image](https://user-images.githubusercontent.com/14038117/148036943-76d5a9bb-15fa-4ed4-86be-7155754bc843.png)

## 请描述完整的环境/版本信息
- 中文 react native 文档地址：
[https://www.react-native.cn/docs/flexbox#flex-basis-grow-and-shrink](https://www.react-native.cn/docs/flexbox#flex-basis-grow-and-shrink)

## 预期结果
- 同步更改中文版的 `flexShrink` 默认值文档，保证文档的时效性。

谢谢

**Comment by sunnylqm** [comment]
感谢提醒，如有空的话可直接提交pr



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月4日(周二) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] RN 原英文网站已更新 `设计 - 使用 Flexbox 布局` 部分 `flexShrink` 默认值相关文档，中文版需跟进更新 (Issue #548)




 
问题的具体描述
 
在查阅中发现，中英文文档存在差异，其中 设计 - 使用 Flexbox 布局 部分 flexShrink 默认值 的文档，截止目前(2021-01-04)，差异如下
 

 
通过查阅英文版文档的提交记录发现，存在如下的更改记录：
 
 
请描述完整的环境/版本信息
  
中文 react native 文档地址：
 https://www.react-native.cn/docs/flexbox#flex-basis-grow-and-shrink 
 
预期结果
  
同步更改中文版的 flexShrink 默认值文档，保证文档的时效性。 
 
谢谢

**Comment by sunnylqm** [comment]
已更新
