### ISSUE TITLE
iOS-android均出现APP打开页面显示异常情况

### ISSUE THREAD

**Issue by tengjingyao** [reactnativecn/react-native-website#550]
iOS及Android均出现打开APP，界面组件尺寸显示异常。如下图：

![WechatIMG7803](https://user-images.githubusercontent.com/59214951/149259629-09d026d9-ce39-4a71-8c76-0cb98aac3569.jpeg)

## 请描述完整的环境/版本信息
System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 742.93 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/Desktop/newMS/meetsleep/node_modules/.bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by sunnylqm** [comment]
这是webview？是的话是viewport还有缩放等等设置的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月13日(周四) 中午11:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] iOS-android均出现APP打开页面显示异常情况 (Issue #550)




 
iOS及Android均出现打开APP，界面组件尺寸显示异常。如下图：
 

 
请描述完整的环境/版本信息
 
System:
 OS: macOS 11.6.1
 CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
 Memory: 742.93 MB / 32.00 GB
 Shell: 3.2.57 - /bin/bash
 Binaries:
 Node: 14.13.1 - /usr/local/bin/node
 Yarn: 1.22.17 - ~/Desktop/newMS/meetsleep/node_modules/.bin/yarn
 npm: 6.14.8 - /usr/local/bin/npm
 Watchman: 4.9.0 - /usr/local/bin/watchman
 Managers:
 CocoaPods: 1.10.1 - /usr/local/bin/pod
 SDKs:
 iOS SDK:
 Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
 Android SDK:
 API Levels: 28, 29, 30
 Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3
 System Images: android-30 | Google APIs Intel x86 Atom
 Android NDK: Not Found
 IDEs:
 Android Studio: 4.2 AI-202.7660.26.42.7351085
 Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
 Languages:
 Java: 1.8.0_191 - /usr/bin/javac
 npmPackages:
 @react-native-community/cli: Not Found
 react: 17.0.1 =&gt; 17.0.1
 react-native: 0.64.0 =&gt; 0.64.0
 react-native-macos: Not Found
 npmGlobalPackages:
 react-native: Not Found

**Comment by tengjingyao** [comment]
> 这是网页浏览量吗？是的话，是视图端口、缩放和设置的问题
> [...](#)
> ---原始邮件---发件人：***@***.***&gt;发送时间：1922年1月13日（周四）11:17收件人：***@***.***&gt;;抄送：***@***.***&gt;主题：[reactnativecn/react-native-website] iOS-android都出现APP打开页面显示异常情况（问题#550）iOS和Android都显示打开APP，界面组件尺寸显示异常。如下图：请描述完整的环境/版本信息系统：OS：macOS 11.6.1CPU：（12）x64 Intel（R）酷睿（TM）i7-8700B CPU @ 3.20GHz内存：742.93 MB/32.00 GB外壳：3.57 - /bin/bash二进制文件：节点：14.13.1 - /usr/local/bin/node纱线：1.22.17 - ~/Desktop/newMS/meetsleep/node_modules/.bin/yarnnpm：6.14.8 - /usr/local/bin/npm守望者：4.9.0 - /usr/local/bin/watchman经理：CocoaPods：1.10.1 - /usr/local/bin/podSDK：iOS SDK：平台：DriverKit 21.2、iOS 15.2、macOS 12.1、tvOS 15.2、watchOS 8.3Android SDK：API级别：28、29、30构建工具：28.0.3、29.0.0、29.0.2、29.0.3、30.0.2、30.0.3系统映像：android-30 | Google API Intel x86 AtomAndroid NDK：未找到IDE：Android Studio：4.2 AI-202.7660.26.42.7351085Xcode：13.2.1/13C100 - /usr/bin/xcodebuild语言：Java：1.8.0_191 - /usr/bin/javacnpmPackages：@react-native-community/cli：未找到反应：17.0.1 =&gt; 17.0.1react-native：0.64.0 =&gt; 0.64.0反应原生瘤：未找到npmGlobalPackages：反应原生：未找到—直接回复此电子邮件，在GitHub上查看，或取消订阅。您之所以收到这个，是因为您订阅了此主题。消息ID：***@***.***&gt;

不是webview

> 这是webview？是的话是viewport还有缩放等等设置的问题
> […](#)

不是webView

**Comment by sunnylqm** [comment]
贴页面代码看看

**Comment by tengjingyao** [comment]
> 贴页面代码看看

这是个根视图，不是必现的，只是目前在一台iphone7-14.7版本系统上出现了
