### ISSUE TITLE
文档内容或许需要更新

### ISSUE THREAD

**Issue by luyuhong0329** [reactnativecn/react-native-website#551]
近几天在学习react-native时，初始化项目时会，发现直接yarn ios并不能直接打包，而是需要yarn start进行Start Metro之后才能yarn ios，项目才能正常跑起来，请问这是需要更新了么？

**Comment by sunnylqm** [comment]
yarn ios 就应该能正常跑起来（自动启动metro)，不需要额外手动启动metro


如果不能，就是哪里有问题（从你的描述无法判断）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月19日(周三) 下午4:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-website] 文档内容或许需要更新 (Issue #551)




 
近几天在学习react-native时，初始化项目时会，发现直接yarn ios并不能直接打包，而是需要yarn start进行Start Metro之后才能yarn ios，项目才能正常跑起来，请问这是需要更新了么？

**Comment by lyh19980329** [comment]
> yarn ios 就应该能正常跑起来（自动启动metro)，不需要额外手动启动metro 如果不能，就是哪里有问题（从你的描述无法判断）
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月19日(周三) 下午4:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [reactnativecn/react-native-website] 文档内容或许需要更新 (Issue #551) 近几天在学习react-native时，初始化项目时会，发现直接yarn ios并不能直接打包，而是需要yarn start进行Start Metro之后才能yarn ios，项目才能正常跑起来，请问这是需要更新了么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

直接启动会出现这样的问题
![image](https://user-images.githubusercontent.com/70092798/150102838-59450c05-bafc-432a-98cc-79a050140e56.png)
![image](https://user-images.githubusercontent.com/70092798/150102981-35d59c76-4200-4a06-944b-7b079a557611.png)

**Comment by lyh19980329** [comment]
使用的系统是mac12，arm64的，项目是最原始的demo，请问与系统有关系嘛

**Comment by luyuhong0329** [comment]
可能与我操作不当有关系，莫名其妙又好了，谢谢回答
