### ISSUE TITLE
求热更新的方案

### ISSUE THREAD

**Issue by ZacharyLv** [reactnativecn/react-native-website#554]
求不依赖三方库的热更新的实现方案

**Comment by sunnylqm** [comment]
就是下载包，把bundle指向新下载的包然后重启。当然在这基础上还要考虑客户端的打包，上传，标记，对比，异常回滚等等情况。不用三方库无非就是自己把这些逻辑写出来。

**Comment by ZacharyLv** [comment]
>

**Comment by ZacharyLv** [comment]
> 就是下载包，把bundle指向新下载的包然后重启。当然在这基础上还要考虑客户端的打包，上传，标记，对比，异常回滚等等情况。不用三方库无非就是自己把这些逻辑写出来。

下载最新的bundle我是理解的，具体怎么替换成新拿到的bundle，这块的实现细节不是很懂，网上也没找到详细的实现方案。

**Comment by sunnylqm** [comment]
我们的热更新方案react-native-update是开源的，你可以在源代码里看细节





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月25日(周二) 下午5:17
收件人: ***@***.***&gt;;
抄送: "Sunny ***@***.******@***.***&gt;;
主题: Re: [reactnativecn/react-native-website] 求热更新的方案 (Issue #554)




  
就是下载包，把bundle指向新下载的包然后重启。当然在这基础上还要考虑客户端的打包，上传，标记，对比，异常回滚等等情况。不用三方库无非就是自己把这些逻辑写出来。
  
下载最新的bundle我是理解的，具体怎么替换成新拿到的bundle，这块的实现细节不是很懂，网上也没找到详细的实现方案。

**Comment by ZacharyLv** [comment]
> 我们的热更新方案react-native-update是开源的，你可以在源代码里看细节
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月25日(周二) 下午5:17 收件人: ***@***.***&gt;; 抄送: "Sunny ***@***.******@***.***&gt;; 主题: Re: [reactnativecn/react-native-website] 求热更新的方案 (Issue #554) 就是下载包，把bundle指向新下载的包然后重启。当然在这基础上还要考虑客户端的打包，上传，标记，对比，异常回滚等等情况。不用三方库无非就是自己把这些逻辑写出来。 下载最新的bundle我是理解的，具体怎么替换成新拿到的bundle，这块的实现细节不是很懂，网上也没找到详细的实现方案。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

明白了，你们用的是这个吗：https://github.com/remobile/react-native-update

**Comment by sunnylqm** [comment]
我们是这个  https://github.com/reactnativecn/react-native-pushy

**Comment by ZacharyLv** [comment]
> 我们是这个 https://github.com/reactnativecn/react-native-pushy

明白了，非常感谢[抱拳]
