### ISSUE TITLE
请教在浏览器访问的react-native项目（非app）怎么dom截屏

### ISSUE THREAD

**Issue by melolee93** [reactnativecn/react-native-website#557]
## 问题的具体描述
最近刚接手了一个react-native开发的微信公众号项目，这个项目不是app（我看是转了web，用浏览器访问的），因此调用不到原生的截屏api， ViewShot和react-native-view-shot都用不了。目前有一个功能需要实现就是要把页面的某个区域截图生成一张图片，请教各位老师如何能解决？

**Comment by memoryseven** [comment]
web？那就用 react的组件

**Comment by melolee93** [comment]
> 

但是接手的这个项目是一个reactnative编写的项目，在部署的时候转成html5了

**Comment by memoryseven** [comment]
我将尽快给您回复。

**Comment by memoryseven** [comment]
不然你用原始的web方式，搞个js，然后 直接引用到那个html5里就行了啊。

**Comment by melolee93** [comment]
> 不然你用原始的web方式，搞个js，然后 直接引用到那个html5里就行了啊。

感谢回复，现在发现，这个项目虽然是reactnative架构，但是我新建一个react的组件，也是可以在在项目中运行的，这样我就可以用html2canvas进行dom截图了

**Comment by memoryseven** [comment]
我将尽快给您回复。
