### ISSUE TITLE
pod-install报错assertAnyTypeAnnotation is not defined

### ISSUE THREAD

**Issue by krisli007** [reactnativecn/react-native-website#559]
请按以下格式提供问题的相关信息。

## 问题的具体描述
初始化rn项目时，执行pod-install报错assertAnyTypeAnnotation is not defined

![image](https://user-images.githubusercontent.com/52608740/151657956-2591e8f1-d1ad-44f1-a78f-68ed14a7be70.png)

## 请描述完整的环境/版本信息
- 可以安装pod的模块

**Comment by knowledges** [comment]
个人感觉是你环境安装的时候，有些东西没有下载全。你可以尝试吧 Pods 和 podfile 删除，重新执行 pod install 和 pod update

**Comment by knowledges** [comment]
#558 你是这样的系统嘛？

**Comment by knowledges** [comment]
#558 你是这样的系统嘛？

**Comment by knowledges** [comment]
请参考：https://www.jianshu.com/p/c092e17c0f5e
