### ISSUE TITLE
yarn android

### ISSUE THREAD

**Issue by Alanqiu** [reactnativecn/react-native-website#561]
![image](https://user-images.githubusercontent.com/5857925/153576605-5381478a-75ad-44b0-92d3-305a525a5377.png)

**Comment by sunnylqm** [comment]
没有配置sdk环境变量

**Comment by Alanqiu** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by Alanqiu** [comment]
> 没有配置sdk环境变量

谢谢
