### ISSUE TITLE
RN有办法实现这种效果的tip提示吗

### ISSUE THREAD

**Issue by chuhangyu** [reactnativecn/react-native-website#562]
![image](https://user-images.githubusercontent.com/20681613/154396225-b3f4f67b-f433-403c-a797-1b868bd8c373.png)
需求是点击屏幕上的任意位置，点击返回遥控模式的这个tip消失，如果点击到有onPress事件的按钮上，也要让这个tip消失，就是说让它消失还要不影响其它的点击事件。
问了ios的开发，他们是有一个hitTest的调用链可以使用，RN上有办法实现这种效果吗，找了一圈好像都没找到

**Comment by qilovehua** [comment]
这个好实现的吧，pointerEvents可以让他穿透。
最外层用个onTouchStart，有触发就可以隐藏tip
