### ISSUE TITLE
xdm，帮帮孩子吧。搞一天了还是运行不起来！！！

### ISSUE THREAD

**Issue by lengthy-daydream** [reactnativecn/react-native-website#566]
![image](https://user-images.githubusercontent.com/58502519/156520473-c899b7e3-cebb-45e6-a639-d94290c9b22b.png)
yarn ios 启动一直报这个错

**Comment by lengthy-daydream** [comment]
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/58502519/156523579-29e7e94a-2457-4cb2-bd3e-322f94672dc3.png">
用xcode运行报这个错和警告

**Comment by sunnylqm** [comment]
package.json看下，还有npx react-native info截图

**Comment by lengthy-daydream** [comment]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/58502519/156684681-4bb5a651-e036-4d20-b287-a089d91e6262.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58502519/156686307-8e796192-6788-4e60-a4b1-8e81e4ed5118.png">

我好像找到问题了，是这个CocoaPods的问题。我这个电脑不知道为啥下载不好。重新下载的项目也不行。pod install的命令拉下来的包也有问题。

**Comment by lengthy-daydream** [comment]
> package.json 看下，还有npx react-native info截图

完全按照官网来的，这个下载下来就是有问题...
<img width="826" alt="image" src="https://user-images.githubusercontent.com/58502519/156685305-8bb9035f-4c6b-4555-81e5-14c738b91d54.png">

**Comment by lengthy-daydream** [comment]
> npx react-native info

<img width="822" alt="image" src="https://user-images.githubusercontent.com/58502519/156685869-90561c11-efaa-4888-b6f3-c92bad0ae060.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58502519/156685930-6d7dac01-12c9-4ba4-93fa-52c07987a2ef.png">

**Comment by sunnylqm** [comment]
pods那里就是标准的翻墙问题，连接被阻断
<img width="689" alt="image" src="https://user-images.githubusercontent.com/615282/156690505-b13ea06e-bc7e-4cb8-a248-656dde08e02c.png">

文档里已经强调过了啊
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/615282/156690473-42d3b3a6-4348-4c86-9da7-89bd43ba0e0e.png">

**Comment by lengthy-daydream** [comment]
> pods那里就是标准的翻墙问题，连接被阻断 <img alt="image" width="689" src="https://user-images.githubusercontent.com/615282/156690505-b13ea06e-bc7e-4cb8-a248-656dde08e02c.png">
> 
> 文档里已经强调过了啊 <img alt="image" width="1180" src="https://user-images.githubusercontent.com/615282/156690473-42d3b3a6-4348-4c86-9da7-89bd43ba0e0e.png">

我明明翻墙了呀，是我这个梯子有问题吗？
<img width="398" alt="image" src="https://user-images.githubusercontent.com/58502519/156706461-d3143f02-3c42-4152-8861-b451b6b84830.png">

**Comment by sunnylqm** [comment]
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/615282/156708152-5427ace7-896a-4a65-ac8e-698bc816bd55.png">

**Comment by lengthy-daydream** [comment]
> <img alt="图片" width="1063" src="https://user-images.githubusercontent.com/615282/156708152-5427ace7-896a-4a65-ac8e-698bc816bd55.png">

好的，谢谢大佬。我自己研究研究
