### ISSUE TITLE
请问新创建的项目报错A problem occurred evaluating project ':app'.如何解决，坐等大佬。

### ISSUE THREAD

**Issue by tian1711873821** [reactnativecn/react-native-website#568]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\native\AwesomeProject\android\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not initialize class com.android.build.gradle.internal.TaskManager

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\native\AwesomeProject\android\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not initialize class com.android.build.gradle.internal.TaskManager

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (D:\native\AwesomeProject\node_modules\execa\index.js:174:9)
    at D:\native\AwesomeProject\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (D:\native\AwesomeProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\native\AwesomeProject\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

项目使用android studio打开android文件可以正常运行，但是yarn react-native run-android却报错是为什么呢

**Comment by sunnylqm** [comment]
android studio带的jdk版本（我猜是jdk11）  和你自己装的jdk版本（我猜低于jdk11）不一致
