### ISSUE TITLE
大佬们 求帮忙看看 yarn ios 启动 一直报错 PhaseScriptExecution [CP-User]\ Generate\ Specs

### ISSUE THREAD

**Issue by dedencLichKing** [reactnativecn/react-native-website#569]
系统 MacBook Pro (16-inch, 2019)  macOS Monterey  12.1
Xcode版本 13.2.1 
react版本  0.67.3

使用yarn iOS  或者xcode运行都会报错 错误如下   没有中文路径 都是英文
![image](https://user-images.githubusercontent.com/28124734/157199454-f2bb1204-b812-4bda-8821-4efc084da62c.png)
![image](https://user-images.githubusercontent.com/28124734/157199489-99c7758f-438c-4748-885d-fcc38c5dab1f.png)

podfile按照提示已修改为 如下 而且pod install依赖都下载下来了
![image](https://user-images.githubusercontent.com/28124734/157199581-47a377f0-3f07-466f-a330-8a47a13deb9a.png)

package.json内容如下 
![image](https://user-images.githubusercontent.com/28124734/157199751-e907bcde-4823-4508-8d6f-d98628303f6c.png)

![image](https://user-images.githubusercontent.com/28124734/157199793-2710020a-1448-4c68-a514-8d97043cbdf7.png)

折腾了一天的环境了 也是按照官网一步步来的  请问拿这种事什么问题  缓存什么也都清理了

实在不知道如何解决这个问题  求指点一下

**Comment by alantoa** [comment]
看报错应该是 xCode 没找到 node 路径
运行一下
```sh
ln -s $(which node) /usr/local/bin/node
```
之后，清理下xcode build目录再试一下

**Comment by dedencLichKing** [comment]
> 

你好 我才回过头来回复你，  我这边node路径应该是没有问题的 ln: /usr/local/bin/node: File exists  感觉就是编译的时候哪里除了问题，xcode的缓存什么的都清理了还是不行 还是会报两个错误 
![image](https://user-images.githubusercontent.com/28124734/158756087-4dc51cb1-87c3-4ccc-87db-9d8b8c81a8d0.png)
