### ISSUE TITLE
Failed to build iOS project.（error code 65）

### ISSUE THREAD

**Issue by sunnleung** [reactnativecn/react-native-website#572]
最近研究react-native-ble-manager组件的使用，在github（https://github.com/innoveit/react-native-ble-manager）上把源码拉了下来，其中还附带有例子(example)。但在example上yarn ios时，终端报
```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65.
```
在xcode上跑则报“unable to open file(in target "example" in project "example")”

网上搜索上面的error code 65的解决方案（https://blog.csdn.net/Bearin/article/details/105811045）
```
node_modules/react-native/scripts/ios-install-third-party.sh
```
可能react native版本经过了升级，项目文件中不存在这个ios-install-third-party.sh文件。
请问现版本error code 65这个问题该如何解决

react native版本是0.65.0

**Comment by sunnylqm** [comment]
所有的报错几乎都是code 65（表示编译失败），所以需要在xcode中编译，然后对具体的报错截图
