### ISSUE TITLE
windows11  RN 初始化项目后下载第三方库后报错

### ISSUE THREAD

**Issue by ming-js** [reactnativecn/react-native-website#576]
通过 react-native init 初始化项目后再下载 第三方库 例如 react-native-elements出现如下情况:
### **node**
![1648538104(1)](https://user-images.githubusercontent.com/57613087/160560426-48bf05e2-32fd-494b-814f-982183c16043.jpg)

### **真机上**
![8498d467cff83853ef558e3609884fb](https://user-images.githubusercontent.com/57613087/160560481-91787cce-c97b-40c5-8652-e5d7071b3a48.jpg)

之后按照 node 上面的提示操作:
提示1与4不是内部或外部命令，也不是可运行的程序或批处理文件; -- 没有这个命令
提示2与3, 没有效果

没办法只有去安装 react-native-safe-area-context,
安装完成后出现以下报错:
![1648540163(1)](https://user-images.githubusercontent.com/57613087/160561002-e1ed2067-2eee-45cb-83de-8060d7fc40ef.jpg)

环境是没什么问题呀???

这个是环境配置
![H_J](https://user-images.githubusercontent.com/57613087/160561123-f6b45ea7-64a6-4b14-b5c2-328eb43225da.jpg)

**Comment by sunnylqm** [comment]
目录名中不要带空格这种骚操作

**Comment by ming-js** [comment]
但是我把文件名改成了驼峰命名，并且重新初始化一个项目，然后下载 react Navigation 按照教程修改运行报错信息没变化
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-safe-area-context'.
> Could not resolve all artifacts for configuration ':react-native-safe-area-context:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10.
     Required by:
         project :react-native-safe-area-context
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.6.10/kotlin-gradle-plugin-1.6.10.pom'.
            > org.apache.http.ssl.SSLInitializationException: E:lib\security\cacerts (ϵͳ�Ҳ���ָ����·����)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-safe-area-context'.
> Could not resolve all artifacts for configuration ':react-native-safe-area-context:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10.
     Required by:
         project :react-native-safe-area-context
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.6.10/kotlin-gradle-plugin-1.6.10.pom'.
            > org.apache.http.ssl.SSLInitializationException: E:lib\security\cacerts (ϵͳ�Ҳ���ָ����·����)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

    at makeError (E:\reactRative\test\node_modules\execa\index.js:174:9)
    at E:\reactRative\test\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (E:\reactRative\test\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (E:\reactRative\test\node_modules\@react-native-community\cli\build\index.js:192:9)

**Comment by sunnylqm** [comment]
Could not get resource 就是标准的翻墙问题（如果你有代理，那就是你的代理对命令行没有生效，需要额外配置）
