### ISSUE TITLE
请问 npx react-native info 这个指令中的 SDKs Android SDK 是这环境变量中的 SDK 吗？

### ISSUE THREAD

**Issue by ming-js** [reactnativecn/react-native-website#577]
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 4.40 GB / 7.87 GB
  Binaries:
    Node: 16.13.1 - E:\node\node.EXE
    Yarn: 1.22.18 - E:\node\node_global\yarn.CMD
    npm: 8.5.1 - E:\node\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.14 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.4 => 0.67.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by galooha** [comment]
是的
