### ISSUE TITLE
Pressable的onPress和onPressOut谁先被调用，文档描述有冲突

### ISSUE THREAD

**Issue by jcdhlzq** [reactnativecn/react-native-website#581]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/23273745/162196231-c8f86479-df40-42ae-b65f-771922b1697c.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/23273745/162196270-98544eb7-23bd-4f36-931a-4456118562f4.png">

**Comment by sunnylqm** [comment]
感谢提醒
