### ISSUE TITLE
react native 官网交互事例打不开

### ISSUE THREAD

**Issue by AngelinaTyrael** [reactnativecn/react-native-website#584]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- react native 官网交互事例打不开

## 请描述完整的环境/版本信息
- react native 0.68

## 预期结果
- 可以看到交互事例

**Comment by sunnylqm** [comment]
截个图？

**Comment by AngelinaTyrael** [comment]
现在好了，上午那会不行 …………^_^
