### ISSUE TITLE
大佬们请教一下有没有好用的识别图片中的二维码的rn依赖呢

### ISSUE THREAD

**Issue by boonook** [reactnativecn/react-native-website#587]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 搜索到的很多都很久没有更新了
- 
## 版本信息
- react-native 0.67.2

**Comment by sunnylqm** [comment]
https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/#barcodescannerscanfromurlasyncurl-barcodetypes

**Comment by Toni-Stark** [comment]
You can try https://github.com/MarnoDev/react-native-qrcode-scanner-view

**Comment by boonook** [comment]
> You can try https://github.com/MarnoDev/react-native-qrcode-scanner-view

This package has not been updated for a long time

**Comment by Toni-Stark** [comment]
> > 你可以试试https://github.com/MarnoDev/react-native-qrcode-scanner-view
> 
> 这个包好久没更新了



> > 你可以试试https://github.com/MarnoDev/react-native-qrcode-scanner-view
> 
> 这个包好久没更新了

> There is nothing wrong with the react-native-qrcode-scanner-view itself
