### ISSUE TITLE
watchman下载失败

### ISSUE THREAD

**Issue by c-ender** [reactnativecn/react-native-website#589]
请按以下格式提供问题的相关信息。

## 问题的具体描述
brew install watchman 运行时
Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/ca-certificates-202
curl: (22) The requested URL returned error: 404 

Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/zstd-1.5.2.arm64_mo
curl: (22) The requested URL returned error: 404

## 请描述完整的环境/版本信息
mac 终端 brew install watchman

## 预期结果
watchman安装成功

**Comment by sunnylqm** [comment]
你配置的brew源有问题

**Comment by hdouhua** [comment]
设置 homebrew 源，可以参考这个 https://mirrors.ustc.edu.cn/help/brew.git.html
