### ISSUE TITLE
使用 babel-plugin-module-resolver 

### ISSUE THREAD

**Issue by zhaozhuangwang** [reactnativecn/react-native-website#590]
根据文档生成项目，TypeScript

npx react-native init MyApp --template react-native-template-typescript

yarn android

运行项目  正常访问，

想引入这个包 用  babel-plugin-module-resolver 文件夹相对地址 

问题

按照文档 配置  https://reactnative.cn/docs/next/typescript
 babel.config.js tsconfig.json

 yarn android 运行之后

期望是  通过 @xxx/  使用文件夹相对地址

结果如下

![image](https://user-images.githubusercontent.com/42265723/166855401-b2878744-dd24-47fc-b3c3-4c9435f85966.png)

package.json 如下

[package.txt](https://github.com/reactnativecn/react-native-website/files/8628423/package.txt)

tsconfig.json 如下

[tsconfig.txt](https://github.com/reactnativecn/react-native-website/files/8628422/tsconfig.txt)

想请问是哪里配置错了

**Comment by sunnylqm** [comment]
你的tsconfig里的compilerOptions都重复了

**Comment by zhaozhuangwang** [comment]
compilerOptions 。。。好的 大牛 非常感谢！
