### ISSUE TITLE
ReactNative 0.49.1 版本老应用 安卓打包如何升级64位架构！

### ISSUE THREAD

**Issue by MR4AM** [reactnativecn/react-native-website#591]
## 问题的具体描述
现在包括google play 和国内很多应用市场都要求应用安卓包支持64位安装包了。我这边一个app应用是 ReactNative 0.49.1 版本老应用 ，安卓打包时如何升级64位架构会比较稳妥，目前增加应用64架构打包后真机运行闪退，初步判断是arm64-v8a架构下有部分so库不支持！
- 下面是我ndk 打包加入arm64-v8a架构后打包出来的应用apk分析，感觉apk的arm64-v8a文件夹下的so库与armeabi-v7a的so库差别好大啊。
## apk分析截图
- ![image](https://user-images.githubusercontent.com/35839017/167251097-c7ba9d04-a897-438f-80bf-6724a5c1f8be.png)

**Comment by sunnylqm** [comment]
rn从0.59版本开始才支持64位
