### ISSUE TITLE
android打包发布的时候 修改build.gradle里面ndk为 "armeabi-v7a", "x86" 打包的时候还是之前的四个 不生效

### ISSUE THREAD

**Issue by 438690519** [reactnativecn/react-native-website#592]
请按以下格式提供问题的相关信息。

## android打包发布的时候 修改build.gradle里面ndk为 "armeabi-v7a", "x86" 打包的时候还是之前的四个 不生效
 
- 请尽量配上相关代码截图
![image](https://user-images.githubusercontent.com/20351236/169262748-aeff0050-989f-4bf0-ac73-a7f979e4407e.png)
然后打的apk包 解压之后 lib文件还是这4个 
![image](https://user-images.githubusercontent.com/20351236/169262910-259923ea-aac2-49c0-b562-0b435a92af6b.png)

## 请描述完整的环境/版本信息
info Fetching system and libraries information...
System:                                                   
    OS: Windows 10 10.0.17763                             
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 
    Memory: 583.84 MB / 7.75 GB                           
  Binaries:                                               
    Node: 16.15.0 - D:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 8.5.5 - D:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 26.0.2, 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15 - D:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
- 预期是打出来的包只包含armeabi-v7a", "x86 这2个引擎就行了 这样包的体积会小一点

**Comment by jypleo** [comment]
我没这么用过，一直这么配置的
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "arm64-v8a"
        }
    }
