### ISSUE TITLE
react-native启动项目一直报这个错，求大佬解惑

### ISSUE THREAD

**Issue by accound** [reactnativecn/react-native-website#593]
请按以下格式提供问题的相关信息。

## 问题的具体描述
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-gradle-plugin'.
> Could not resolve all files for configuration ':react-native-gradle-plugin:classpath'.
   > Could not download semver4j-0.16.4-nodeps.jar (com.github.gundy:semver4j:0.16.4)
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/gundy/semver4j/0.16.4/semver4j-0.16.4-nodeps.jar'.
         > Could not HEAD 'https://repo.maven.apache.org/maven2/com/github/gundy/semver4j/0.16.4/semver4j-0.16.4-nodeps.jar'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1] failed: Connection refused: connect

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by sunnylqm** [comment]
翻墙问题

**Comment by MikeKen-Ken** [comment]
> 翻墙问题

已经翻墙了, 请问为什么还是报这个错呢

**Comment by zjj2022** [comment]
![图片](https://user-images.githubusercontent.com/79621076/169757304-bff9f87d-0920-42c5-bc44-f8cada779aa7.png)
看看这些对了没

**Comment by accound** [comment]
改了的，一直卡在下面这步





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reactnativecn/react-native-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [reactnativecn/react-native-website] react-native启动项目一直报这个错，求大佬解惑 (Issue #593)





 

 看看这些对了没

**Comment by accound** [comment]
![团青2](https://user-images.githubusercontent.com/102423275/169782377-04b80ad5-6b44-444b-a63e-34d67b8b431f.png)

**Comment by accound** [comment]
![1653296159(1)](https://user-images.githubusercontent.com/102423275/169782599-43fe5fac-232c-4bff-a1c8-a6b31cf3dea6.jpg)
这个也改了，
诊断也都OK
![1653296286(1)](https://user-images.githubusercontent.com/102423275/169783120-68b49d25-b6b5-4812-b9b7-079099a54aea.jpg)
但是一直卡在这步
![1653296414(1)](https://user-images.githubusercontent.com/102423275/169783569-a6fc1c12-ac9f-4011-8a69-c17b657682c4.jpg)

**Comment by zjj2022** [comment]
我看官网推荐的才到30.0.2    SDK到30

**Comment by accound** [comment]
改成30还是一样的
