### ISSUE TITLE
编译时报错Unexpected token punc ?:?, expected punc ?{? in file node_modules\react-native\Libraries\Components\Touchable\TouchableWithoutFeedback.js at 40:30

### ISSUE THREAD

**Issue by fangelyt** [reactnativecn/react-native-website#600]
按文档升级到0.86后编译android 报错提示Unexpected token punc ?:?, expected punc ?{? in file node_modules\react-native\Libraries\Components\Touchable\TouchableWithoutFeedback.js at 40:30

**Comment by sunnylqm** [comment]
升级有各种疑难杂症的话，建议直接新建项目然后把老项目的代码搬运过去
