### ISSUE TITLE
RN打包成release包后，静态资源文件名被修改

### ISSUE THREAD

**Issue by jingmo2015** [reactnativecn/react-native-website#601]
我在通过`./gradlew assembleRelease`打包命令打包成apk后，js静态资源（图片和xml）文件名被修改。
<img width="742" alt="image" src="https://user-images.githubusercontent.com/9572684/172641495-f8770ce3-37d6-42a5-b8b6-696553ff54e4.png">

我希望打包到apk后的图片能保留原来的文件名，看到官方文档说可以琢磨下android/app/build.gradle 文件。
<img width="801" alt="image" src="https://user-images.githubusercontent.com/9572684/172641842-a0a4dbc1-49a8-4800-bc4f-7124642d4804.png">

但是看了下这个配置文件里面的内容，不知道该修改哪些配置，才能让js静态图片按原来的文件名打包进APK。

**Comment by sunnylqm** [comment]
高版本AGP带来的默认特性，确实也搜不到太多说明，供参考：

https://www.reddit.com/r/android_devs/comments/rjz9an/agp_42_disable_resource_renaming/
https://developer.android.com/studio/build/shrink-code#shrink-resources

**Comment by jingmo2015** [comment]
> 高版本AGP带来的默认特性，确实也搜不到太多说明，供参考：
> 
> https://www.reddit.com/r/android_devs/comments/rjz9an/agp_42_disable_resource_renaming/ https://developer.android.com/studio/build/shrink-code#shrink-resources

<img width="640" alt="image" src="https://user-images.githubusercontent.com/9572684/172773748-7296e689-6af5-4fa5-ad1e-eeb6f2056149.png">
修改下这个配置解决了，多谢
