### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by xkong1112** [reactnativecn/react-native-website#605]
## 搭建安卓环境的教程有typo

<img width="996" alt="Q's API level is 29, R's API level is 30" src="https://user-images.githubusercontent.com/53178847/174542062-28dd78c1-f593-4f91-8393-4f326fccefe5.png">
<img width="1102" alt="Q:30" src="https://user-images.githubusercontent.com/53178847/174542242-1a654e8b-4e23-43e3-9a30-af5accb45b9c.png">

**Comment by sunnylqm** [comment]
具体哪里？

**Comment by xkong1112** [comment]
就是安卓版本和代号的对应关系不对啦


Sunny Luo ***@***.***> 于2022年7月1日周五 10:18写道：
