### ISSUE TITLE
No bundle URL present. Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

### ISSUE THREAD

**Issue by Qianben122136** [reactnativecn/react-native-website#607]
## No bundle URL present.
- 按照官网上面的环境装了
- node
- watchman
- Xcode 
- Xcode 的命令行工具
- CocoaPods
- npm uninstall -g react-native-cli卸载了
- npx react-native init AwesomeProject 让后创建项目
- 然后cd AwesomeProject
- yarn ios
但是还是一直

![Uploading 截屏2022-06-24 10.47.31.png…]()
图片的文字就是这个
No bundle URL present.
Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

想解决这个问题正常的运行起来

**Comment by Qianben122136** [comment]
macOS 版本12.4 (21F79)
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

![截屏2022-06-24 10 47 31](https://user-images.githubusercontent.com/40136007/175452683-a349d1e4-b46b-4c1f-8993-9f07f2506637.png)

**Comment by sunnylqm** [comment]
终端命令行截图看下

**Comment by Qianben122136** [comment]
稍等一下, Building the app 中,  每次编译项目这么都只能这么慢吗

**Comment by sunnylqm** [comment]
只有第一次比较慢

**Comment by Qianben122136** [comment]
![Uploading 截屏2022-06-24 13.36.36.png…]()

**Comment by Qianben122136** [comment]
![截屏2022-06-24 13 36 36](https://user-images.githubusercontent.com/40136007/175469524-a76c3689-efdb-44b7-aa93-872b5323d20b.png)

**Comment by Qianben122136** [comment]
![截屏2022-06-24 13 37 50](https://user-images.githubusercontent.com/40136007/175469602-ddec6fe4-7da6-40ea-a260-5787f598d5e1.png)

**Comment by Qianben122136** [comment]
![截屏2022-06-24 13 38 39](https://user-images.githubusercontent.com/40136007/175469708-ced32fe8-b2c4-4761-8333-98b6ba216c5c.png)

**Comment by Qianben122136** [comment]
第一个 和第二个是一个终端

**Comment by sunnylqm** [comment]
这个据说是最新的watchman有问题，其实卸载掉watchman也可以运行的

**Comment by Qianben122136** [comment]
谢谢
