### ISSUE TITLE
RN ,IOS启动，报错 XXXX.app/main.jsbundle does not exist.This must be a bug with

### ISSUE THREAD

**Issue by ss-zf-520** [reactnativecn/react-native-website#612]
## RN ,IOS启动【build】，报错 XXXX.app/main.jsbundle does not exist.This must be a bug with

![image](https://user-images.githubusercontent.com/47528311/177442364-ccb6ced0-eea6-4a17-b38b-5c9180b9a8b0.png)

## 请描述完整的环境/版本信息
允许环境： XCode 最新版本    RN版本： 0.63

## 预期结果
有什么方式可以去处理呢？各位大佬有什么好的方案

**Comment by sunnylqm** [comment]
https://github.com/react-native-webview/react-native-webview/issues/2325#issuecomment-1012305604

**Comment by ss-zf-520** [comment]
change "metro-react-native-babel-preset" to "^0.66.2" in package.json，but you can try
