### ISSUE TITLE
创建新项目时 同时指定版本号和TS

### ISSUE THREAD

**Issue by cl1885** [reactnativecn/react-native-website#614]
请按以下格式提供问题的相关信息。

## 问题的具体描述
npx react-native init x1 --verbose --version 0.68.1  --template react-native-template-typescript 

这样创建的项目 是 最新的 0.69的

npx react-native init x1 --verbose --version 0.68.1

这样才能创建 0.68的项目

## 预期结果

请问 现在怎么创建 ts 的0.68版本项目？

**Comment by sunnylqm** [comment]
https://github.com/react-native-community/react-native-template-typescript#usage-with-older-versions-of-react-native
