### ISSUE TITLE
as  执行 run  命令后报的 missing  错误

### ISSUE THREAD

**Issue by Rookie-baiqi** [reactnativecn/react-native-website#617]
![image](https://user-images.githubusercontent.com/54833166/178686021-6ded3984-b5ab-4aba-a6ad-02336aab5201.png)
##  小白一个，看到missing .env file ,感觉是这个的问题，但是项目拿到手时时没有这个文件的！
-这里只在 android studio 上执行了命令，有大佬知道麻烦告知如何配置！谢谢

**Comment by sunnylqm** [comment]
.env里面一般都是一些敏感的密钥，所以都不会随项目保存的，这个你要问项目的来源方拿
