### ISSUE TITLE
react-native-amap3d 在iOS中报错

### ISSUE THREAD

**Issue by wubaibin** [reactnativecn/react-native-website#618]
TypeError: null is not an object (evaluating 'AMapSdk.initSDK')

**Comment by sunnylqm** [comment]
任何带有原生代码的第三方引入，第一步在ios目录中执行 pod install 安装原生库，第二步使用xcode或yarn ios编译，之后js才能引用到原生模块的代码（反之就会报各种null，undefined，因为没有对应的原生方法）
