### ISSUE TITLE
RN如何在多屏幕的设备上实现多入口

### ISSUE THREAD

**Issue by littledu** [reactnativecn/react-native-website#620]
## 问题的具体描述

我需要在一个硬件设备上做一个安卓应用，硬件设备上有两个屏幕，一个主屏，一个副屏，我希望应用启动的时候，两个屏幕能分别加载我不同的页面，RN 应该怎么实现呢？

**Comment by sunnylqm** [comment]
https://github.com/mybigday/react-native-external-display

**Comment by littledu** [comment]
@sunnylqm 谢谢，没有跑起来，我去问一下
