### ISSUE TITLE
no-unused-vars 设置 ‘error’，无效

### ISSUE THREAD

**Issue by Span134** [reactnativecn/react-native-website#623]
## 问题的具体描述
![image](https://user-images.githubusercontent.com/111031222/184105790-6bdcacfe-1a82-46f0-aaf1-25ddbc3ac476.png)

项目命令 npx react-native init AwesomeTSProject --template react-native-template-typescript 生成,
然后App.tsx添加了未使用的变量，tsconfig与eslintrc分别添加配置，启动项目

预期结果 ： 希望编译失败，模拟器直接提示 'abc' is decleared but value never read !
实际结果 :    项目编译成功

## 请描述完整的环境/版本信息
win10
node 16.16.0
"eslint": "^7.32.0",
"typescript": "^4.4.4"
"@typescript-eslint/eslint-plugin": "^5.29.0",
"@typescript-eslint/parser": "^5.29.0",

**Comment by sunnylqm** [comment]
rn是通过babel来支持ts的，而babel是不做类型检查的
https://babeljs.io/docs/en/babel-plugin-transform-typescript#impartial-namespace-support
<img width="830" alt="image" src="https://user-images.githubusercontent.com/615282/184117307-b267d844-4123-42cc-a2d5-8ffb3348604e.png">

一般来说，我们在npm scripts中添加tsc命令来做额外的检查，但也只在提交代码或者pr，或者发布版本前做检查，平时依靠编辑器做检查就行了，编译前做检查纯粹是浪费时间
