### ISSUE TITLE
手机更新到iOS16 Xcode14运行报错……

### ISSUE THREAD

**Issue by bingoShawn** [reactnativecn/react-native-website#650]
react-native版本：  "react-native": "0.62.2"

报错信息：'Application circumvented Objective-C runtime dealloc initiation for <RCTRootContentView> object.'
terminating with uncaught exception of type NSException

有没有大神指点一下 不胜感激！

**Comment by sunnylqm** [comment]
别说0.62了，最新的0.70都不支持xcode14，cocoapods好像也有兼容问题，且官方还没有明确说明改动

https://github.com/facebook/react-native/issues/34673
https://github.com/CocoaPods/CocoaPods/issues/11402

建议先回滚xcode（以及任何时候不要首先更新）

**Comment by bingoShawn** [comment]
> 别说0.62了，最新的0.70都不支持xcode14，cocoapods好像也有兼容问题，且官方还没有明确说明改动
> 
> [facebook/react-native#34673](https://github.com/facebook/react-native/issues/34673) [CocoaPods/CocoaPods#11402](https://github.com/CocoaPods/CocoaPods/issues/11402)
> 
> 建议先回滚xcode（以及任何时候不要首先更新）
回滚Xcode没问题 但是手机已经更新到iOS16了 真机调试没法跑了 这个咋办呢？有什么建议吗？ 谢谢了

**Comment by xiangsj** [comment]
我也报错，刚更新到
macOS 13.0.1  
xcode14.1
请问 新系统里 xcode 能回滚不？

**Comment by bingoShawn** [comment]
> 我也报错，刚更新到 macOS 13.0.1 xcode14.1 请问 新系统里 xcode 能回滚不？
目前我的做法是还是用xcode13  然后下载最新的iOS真机的支持包放进去用 就行了  邮件里说错了 还是得回滚低版本xcode  但是我的macOS是12.6  你升级了macOS能不能装xcode13就不知道了 你可以试试 如果不行那你再研究一下该怎么办吧 解决了以后别忘了告诉我一下哈 因为我以后也要面临同样的问题呢

**Comment by sunnylqm** [comment]
更新到0.70.3或更高版本，或自己把这个补丁写到 podfile 里
https://github.com/facebook/react-native/commit/37790e450791caafb15b265f8d1e28413ea0d9d9#diff-9237612755b27db29ea9b295070f8a09850608a97583fac9d3555c4a987c2cc0
