### ISSUE TITLE
应用商店审核时，用户隐私检测不通过

### ISSUE THREAD

**Issue by ChenLM88** [reactnativecn/react-native-website#653]
平台报告反馈是说必须要在应用启动之前就展示隐私政策弹窗，而不是在应用启动之后。请问一下如何在启动页添加隐私政策的弹窗，用户同意之后再正常进入到页面中？
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/37339479/195348439-f7ca830c-c9f0-4d04-8d8a-fb4331416c97.png">

**Comment by sunnylqm** [comment]
这个一般来说要[用工具逐个排查第三方库](https://github.com/search?q=%E9%9A%90%E7%A7%81%E5%90%88%E8%A7%84)，常见的有问题的比如老版本的react-native-device-info会在启动时不合规地收集ANDROID_ID。然后需要升级的升级，替换的替换，手动打补丁的打补丁，使得它们不在启动时就收集数据

**Comment by 349989153** [comment]
> 这个一般来说要[用工具逐个排查第三方库](https://github.com/search?q=%E9%9A%90%E7%A7%81%E5%90%88%E8%A7%84)，常见的有问题的比如老版本的react-native-device-info会在启动时不合规地收集ANDROID_ID。然后需要升级的升级，替换的替换，手动打补丁的打补丁，使得它们不在启动时就收集数据

请问react-native-device-info至少升级到哪个版本才可以？有相关issue的链接也可以，感谢！

**Comment by 349989153** [comment]
哦找到了
https://github.com/react-native-device-info/react-native-device-info/issues/1427
