### ISSUE TITLE
如何在视图渲染前获取视图RectBounding!

### ISSUE THREAD

**Issue by zhuqingyv** [reactnativecn/react-native-website#658]
我想要手动计算一些属性以控制视图渲染，并且不希望视图渲染完以后再执行变更，有办法实现么？
当先Layout事件去计算会导致屏幕闪动一下，这会影响用户的体验，因为用户能感知到这一变更

**Comment by sunnylqm** [comment]
可以先控制透明度渲染，测量完成后再修改透明度，配合reanimated的可以做到无闪烁，当然写起来也会比较麻烦
