### ISSUE TITLE
初始化项目出错

### ISSUE THREAD

**Issue by sundial-dreams** [reactnativecn/react-native-website#659]
这块卡了好久了，也不知道为啥
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/32068218/200118372-ca10424e-57c3-409b-9d3b-abe556009fde.png">

`✔ Downloading template
✔ Copying template
✔ Processing template
ℹ Installing dependencies
✔ CocoaPods (https://cocoapods.org/) is not installed. CocoaPods is necessary for the iOS project to run correctly. Do you want to install it? › Yes, with Homebrew
✔ Installing CocoaPods
✔ Installing Bundler
✖ Installing CocoaPods dependencies (this may take a few minutes)
error warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md

✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.`

**Comment by sunnylqm** [comment]
标准翻墙问题，文档里已经特别强调过了

**Comment by sundial-dreams** [comment]
> 

刚玄学的解决了，似乎不是墙的问题，代理我这边是没问题的；
解决方法：到`ios`目录下`pod install`一下，然后用`npx react-native run-ios`运行，就是不知道下次还能不能这么玄学

**Comment by sunnylqm** [comment]
因为墙的问题所以 pod install 没成功，所以需要你手动去重新pod install
如果代理没问题，那么初始化的时候就能自动 pod install 成功
