### ISSUE TITLE
如何在 Node.js 环境里使用浏览器环境下的 document 对象

### ISSUE THREAD

**Issue by zhoubo20221107** [reactnativecn/react-native-website#662]
请按以下格式提供问题的相关信息。

## 问题的具体描述
今天使用 node.js运行 js 脚本时总是报错 ReferenceError: document is not defined

## 请描述完整的环境/版本信息
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
    Memory: 2.27 GB / 7.95 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.17 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: 0.70.4 => 0.70.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## 预期结果
可以在 Node.js 环境里使用浏览器环境下的 document 对象

**Comment by sunnylqm** [comment]
答案就是没有，不能
