### ISSUE TITLE
mac搭建RN环境问题

### ISSUE THREAD

**Issue by poisonfff** [reactnativecn/react-native-website#665]
执行npx react-native doctor报错
Common
 ✓ Node.js
 ✓ yarn
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2022.10.31.00
   - Version supported: 4.x

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.3
 ✖ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI

**Comment by poisonfff** [comment]
<img width="445" alt="Snipaste_2022-11-08_10-26-53" src="https://user-images.githubusercontent.com/117699504/200460009-6905ba85-e497-4572-b3ac-6799cb93f191.png">
![Uploading Snipaste_2022-11-08_10-20-58.png…]()

**Comment by poisonfff** [comment]
<img width="735" alt="Snipaste_2022-11-08_10-20-58" src="https://user-images.githubusercontent.com/117699504/200460079-b688a97f-bbe4-4161-8776-ed09f9e0e27e.png">

**Comment by sunnylqm** [comment]
缺什么补什么就行了，你这里缺
1. android sdk，打开android studio安装
2. ANDROID_HOME环境变量

总之文档步骤里应该都有啊？

**Comment by poisonfff** [comment]
<img width="712" alt="Snipaste_2022-11-08_10-38-18" src="https://user-images.githubusercontent.com/117699504/200461922-e862f9aa-84f5-4ade-83a5-6ce65be1154e.png">
<img width="721" alt="Snipaste_2022-11-08_10-38-34" src="https://user-images.githubusercontent.com/117699504/200461936-a3c1b00e-4762-4485-9191-17fb7ed8d505.png">
<img width="657" alt="Snipaste_2022-11-08_10-38-53" src="https://user-images.githubusercontent.com/117699504/200461954-0b09fa2b-2ad2-4043-ad70-393799a8a081.png">

**Comment by sunnylqm** [comment]
装了就行，doctor的检查可以忽略

**Comment by poisonfff** [comment]
<img width="410" alt="Snipaste_2022-11-08_10-41-29" src="https://user-images.githubusercontent.com/117699504/200462142-3f44ba8b-460d-4d91-9eda-5d648bc84ab5.png">
包括环境变量也是按照官方文档来的
依然报错

**Comment by sunnylqm** [comment]
doctor 这个工具未必同步更新了，以文档为准

**Comment by poisonfff** [comment]
<img width="585" alt="Snipaste_2022-11-08_10-43-58" src="https://user-images.githubusercontent.com/117699504/200462461-a35582e4-f011-4fb4-b3f9-7b65fda60c56.png">
但是项目跑不起来

**Comment by sunnylqm** [comment]
跑不起来就截跑不起来的图

**Comment by poisonfff** [comment]
帮忙看一下
<img width="1088" alt="Snipaste_2022-11-08_10-45-58" src="https://user-images.githubusercontent.com/117699504/200462790-60f7a1e5-3efc-4ae3-a778-6dd55030e81f.png">
<img width="1084" alt="Snipaste_2022-11-08_10-46-12" src="https://user-images.githubusercontent.com/117699504/200462804-e23d35c1-ebbb-4ee3-81c6-9b1f9799e6c8.png">

**Comment by sunnylqm** [comment]
老项目是吧，置顶的问题看了吗

**Comment by poisonfff** [comment]
是的，老项目，不知您说的置顶问题是指的哪一个？
<img width="755" alt="Snipaste_2022-11-08_11-06-04" src="https://user-images.githubusercontent.com/117699504/200465450-8572157a-f507-4d1a-b18b-6968360eee58.png">

**Comment by sunnylqm** [comment]
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/615282/200466437-40ac9b82-6254-4654-a41a-66d6cbb156bc.png">

https://github.com/reactnativecn/react-native-website/issues/660

**Comment by poisonfff** [comment]
版本从0.64.3上升到0.64.4，并重新下载依赖
<img width="1097" alt="Snipaste_2022-11-08_12-01-46" src="https://user-images.githubusercontent.com/117699504/200472433-82940fc3-eba6-49d7-9e0b-32c8609d04b9.png">

**Comment by sunnylqm** [comment]
往下截图，上面的看不到具体报错

**Comment by poisonfff** [comment]
<img width="1131" alt="Snipaste_2022-11-08_12-45-24" src="https://user-images.githubusercontent.com/117699504/200477369-024e458f-8c78-45ef-b8a5-3b311bf542f0.png">
<img width="1111" alt="Snipaste_2022-11-08_12-45-38" src="https://user-images.githubusercontent.com/117699504/200477400-f942a3b1-4dd6-46b7-b80f-b8441ebd4732.png">

**Comment by sunnylqm** [comment]
你是不是自己创建了个buildConfig文件？是的话删掉
删掉后在android目录中运行  `./gradlew clean` 再试试

**Comment by poisonfff** [comment]
如果，你是指的这个文件的话
<img width="442" alt="Snipaste_2022-11-08_14-29-34" src="https://user-images.githubusercontent.com/117699504/200491428-1e201cc3-9dd7-4de1-9914-9ca8c7fb38fe.png">
删除并执行命令后，启动项目
<img width="1183" alt="Snipaste_2022-11-08_14-31-49" src="https://user-images.githubusercontent.com/117699504/200491622-fbc6d192-7970-4c04-af45-4283baa679b1.png">
<img width="1178" alt="Snipaste_2022-11-08_14-31-34" src="https://user-images.githubusercontent.com/117699504/200491662-bafd8a29-6ba3-4457-944e-de5b20ba8226.png">

**Comment by sunnylqm** [comment]
不是在编译产生的build文件夹（灰色）中，要在你的源码文件夹（非灰色）中找到并删除

**Comment by poisonfff** [comment]
项目全局搜了一下，叫buildConfig的文件里面只有一个debug文件夹，应该不是您说的文件，源码里也没有
<img width="708" alt="Snipaste_2022-11-08_14-56-44" src="https://user-images.githubusercontent.com/117699504/200495579-c33968a2-14cb-4dee-afd6-e6c7d56f5d61.png">

<img width="242" alt="Snipaste_2022-11-08_14-54-26" src="https://user-images.githubusercontent.com/117699504/200495343-f5d33998-14f7-4625-af08-0843a0c3828c.png">

**Comment by sunnylqm** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/615282/200497670-5dbd070e-71be-460c-b4a1-a47ee17a1358.png">
这看命名就不是正常的文件啊

**Comment by poisonfff** [comment]
之前就是删的这3个文件，就是您说的灰色文件

**Comment by sunnylqm** [comment]
这几个文件不会凭空产生，一定是从源码产生

**Comment by poisonfff** [comment]
删除之后，进入android目录中运行 ./gradlew clean，再yarn react-native run-android，他只生成了一个BuildConfig.java文件，
还是报一小时前的错误

**Comment by sunnylqm** [comment]
一小时前的错误是什么错误，你上面截图里的错误只有这个几个BuildConfig，其他都只看到警告（不影响编译和运行）

**Comment by poisonfff** [comment]
请看
<img width="1062" alt="Snipaste_2022-11-08_15-40-43" src="https://user-images.githubusercontent.com/117699504/200503370-88b6a583-e6c9-4b6a-938e-3a90264af9cb.png">
<img width="1068" alt="Snipaste_2022-11-08_15-40-57" src="https://user-images.githubusercontent.com/117699504/200503421-3413e893-c1fe-490a-8f09-33419b1433cd.png">
<img width="1071" alt="Snipaste_2022-11-08_15-41-09" src="https://user-images.githubusercontent.com/117699504/200503454-ceab7796-db5e-4901-a545-de196e24b8fb.png">

**Comment by sunnylqm** [comment]
现在已经一切正常，编译也已完成
<img width="437" alt="image" src="https://user-images.githubusercontent.com/615282/200511256-ec133c87-087f-4f31-8e30-cc8fdb1c1302.png">

问题就是 No connected devices （链接手机，打开usd调试，或者创建一个模拟器）

**Comment by poisonfff** [comment]
电脑上有android studio，也连上了手机，有什么办法让他执行到手机上，而不是android studio的模拟器吗？

**Comment by sunnylqm** [comment]
https://reactnative.cn/docs/running-on-device

**Comment by poisonfff** [comment]
<img width="342" alt="Snipaste_2022-11-08_16-58-27" src="https://user-images.githubusercontent.com/117699504/200520465-7e42e217-37fc-42a9-a625-2a7b051c1f5c.png">
<img width="260" alt="Snipaste_2022-11-08_16-58-41" src="https://user-images.githubusercontent.com/117699504/200520495-5bf9afab-f040-467d-a855-e3aec9a6db3a.png">

**Comment by sunnylqm** [comment]
这是从别的系统复制过来的项目吧，权限不对，你需要用 chmod 命令给这个 launchPackager.command 文件加上执行权限

**Comment by sunnylqm** [comment]
或者 rm -rf node_modules && yarn 重装

**Comment by poisonfff** [comment]
权限问题没有解决，但是我手动打开了那个文件，跳过了这个问题
<img width="1192" alt="Snipaste_2022-11-08_17-27-14" src="https://user-images.githubusercontent.com/117699504/200528506-98051b57-ede4-4eac-b870-724a5615f09a.png">
