### ISSUE TITLE
react-native run-android失败

### ISSUE THREAD

**Issue by luomengxia** [reactnativecn/react-native-website#666]
react-native run-android报错，使用了clash for windows代理全局模式
![QQ截图20221110111110](https://user-images.githubusercontent.com/117897180/201037403-df5387b5-6a5b-4629-a7ba-21341980350a.png)

**Comment by sunnylqm** [comment]
截图里仍然是网络问题

**Comment by luomengxia** [comment]
> 截图里仍然是网络问题
请问有什么办法解决吗

**Comment by luomengxia** [comment]
已经使用翻墙了，但是还是出现这样错误，是翻墙问题吗

**Comment by sunnylqm** [comment]
是的，应该是你的代理有问题

**Comment by luomengxia** [comment]
有个疑问，这里是国内腾讯的库，按道理不应该和网络有问题啊

**Comment by sunnylqm** [comment]
你看截图的网址啊，不管哪个国家的库，都是提交给apache.org / google.com这样的源啊
