### ISSUE TITLE
最新版RN 框架获取IP 导致隐私协议不合格 无法上架

### ISSUE THREAD

**Issue by cl1885** [reactnativecn/react-native-website#672]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/4088197/203245624-1481cdd0-d853-44e7-ad2b-7d90f22ceb84.png">

(SDK: FaceBookReact) 读取设备IP

这个怎么解决？不符合政策不能上架

**Comment by sunnylqm** [comment]
看下 package.json

**Comment by cl1885** [comment]
{
  "name": "wlzs8",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-camera-roll/camera-roll": "^5.0.4",
    "@react-native-community/geolocation": "^3.0.3",
    "@react-native-community/netinfo": "^9.3.6",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "fbjs": "^3.0.4",
    "ffmpeg-kit-react-native": "^5.1.0",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-audio": "^4.3.0",
    "react-native-charts-wrapper": "^0.5.10",
    "react-native-fs": "^2.20.0",
    "react-native-image-picker": "^4.10.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-signature-capture": "^0.4.12",
    "react-native-sound": "^0.11.2",
    "react-native-swiper": "^1.6.0",
    "react-native-webview": "^11.23.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/react": "^18.0.21",
    "@types/react-native": "^0.70.6",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

**Comment by sunnylqm** [comment]
感觉更像是因为提前调用了 @react-native-community/netinfo

**Comment by cl1885** [comment]
> 感觉更像是因为提前调用了 @react-native-community/netinfo

应该不是 之前0.68 没问题

**Comment by xhanglizhu** [comment]
是不是因为TurboModules哦。

**Comment by admin8384** [comment]
应该是react-native-community/netinfo导致的

**Comment by reshub-ai** [comment]
大家最后是如何解决的？目前遇到同样问题，感谢
