### ISSUE TITLE
react-native 0.64.4版本最低支持iOS的系统版本是多少

### ISSUE THREAD

**Issue by CFPanda** [reactnativecn/react-native-website#674]
我们想集成react-native 0.64.4版本，我们希望可以支持到最低iOS系统版本为10.0，请问这个版本是否支持？感谢～

**Comment by sunnylqm** [comment]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/615282/204430860-81bf73aa-58aa-4865-bb1f-7a7cd2735f98.png">

**Comment by CFPanda** [comment]
这个我看到了，但是我在npm官网山看到这个
<img width="719" alt="截屏2022-11-29 上午11 34 32" src="https://user-images.githubusercontent.com/17490441/204432407-54d04eae-9cfb-4da3-8dd9-34a3821ef665.png">
不知道以哪一个为准

**Comment by sunnylqm** [comment]
以代码为准（逻辑根据代码执行还是根据文档执行？）

**Comment by CFPanda** [comment]
好的 谢谢
