### ISSUE TITLE
iOS上使用RN混合开发，多个RCTRootView对应一个RCTBridge比较好，还是一个RCTRootView就对应一个RCTBridge比较好？

### ISSUE THREAD

**Issue by CFPanda** [reactnativecn/react-native-website#677]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 如果是安装过程中的问题，请再三确认你有使用稳定的翻墙工具，且翻墙工具对命令行有生效（如开启全局模式等等）
- 请说明具体操作步骤和现象（例如执行什么命令，或者点击哪里，出现了什么异常现象或错误信息）
- 请尽量配上相关报错截图
   - 如果是ios编译报错，请打开Xcode运行后对报错截图 
   - 如果设备上有红屏报错请直接截图
   - 如果命令行有报错请直接截图
   - 警告(warning)一般不用管
   - 如果设备上看不到报错，请先尝试[调试模式](https://reactnative.cn/docs/debugging)。
   - 如果是发行版本无法调试，对于安卓设备请使用[adb logcat命令](https://developer.android.google.cn/studio/command-line/logcat)来捕获日志并粘贴到这里。iOS设备查看日志的[一些方法](https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a)。
- 请尽量配上相关代码截图

## 请描述完整的环境/版本信息
- 请在命令行的项目目录中运行`npx react-native info`命令，并将其输出结果粘贴到这里。
- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

## 预期结果
- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

**Comment by sunnylqm** [comment]
省资源优化 -> 共用
业务强隔离 -> 不共用

**Comment by CFPanda** [comment]
我采用了共用的方案，但是在使用过程中遇到了一个问题，就是只能显示一个RCTRootView
代码如下：我添加了两个view，但只能显示了rctView1的内容

**Comment by CFPanda** [comment]
<img width="1401" alt="截屏2022-12-05 上午10 06 47" src="https://user-images.githubusercontent.com/17490441/205534202-3945bb32-9020-488e-bf74-df3344f36714.png">

**Comment by sunnylqm** [comment]
需要你自己控制页面的切换和显隐

**Comment by CFPanda** [comment]
现在是我先add rctView1，rctView2就不显示，但是我先添加rctView2的话，rctView1就不显示，好像这两个view没办法同时显示，你说需要自己控制页面的显示和隐藏，具体是指怎么控制呢？

**Comment by sunnylqm** [comment]
不然你要怎么显示呢？你添加九个页面，九个自动变成九宫格吗？那当然是原生有自己的导航方法，自己决定页面的显示、隐藏、布局、跳转啊

**Comment by CFPanda** [comment]
我的代码已经决定了 我的页面布局了啊，就是一个native的view上add了两个rn的view，所在的区域和大小我都给了，不应该都显示么
