### ISSUE TITLE
刚接触rn，新建项目启动报错，有哪位大佬帮忙看一下

### ISSUE THREAD

**Issue by Jonesy-1212** [reactnativecn/react-native-website#681]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
12 actionable tasks: 1 executed, 11 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug.

**Comment by sunnylqm** [comment]
往上面一点截图

**Comment by Jonesy-1212** [comment]
> 往上面一点截图


<img width="1182" alt="WeChat714d09848220e5f94fdfe6729f8f86a1" src="https://user-images.githubusercontent.com/84960431/208356540-609a95c9-88f4-4891-bc8a-2f021608f1d7.png">

**Comment by Jonesy-1212** [comment]
(node:82155) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
info Starting JS server...
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...

> Task :app:compileDebugJavaWithJavac FAILED
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:5: 错误: 程序包com.facebook.react不存在
import com.facebook.react.ReactApplication;
                         ^
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:6: 错误: 程序包com.facebook.react不存在
import com.facebook.react.ReactNativeHost;
                         ^
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:7: 错误: 程序包com.facebook.react不存在
import com.facebook.react.ReactPackage;
                         ^
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:8: 错误: 程序包com.facebook.react.shell不存在
import com.facebook.react.shell.MainReactPackage;
                               ^
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:9: 错误: 程序包com.facebook.soloader不存在
import com.facebook.soloader.SoLoader;
                            ^
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:14: 错误: 找不到符号
public class MainApplication extends Application implements ReactApplication {
                                                            ^
  符号: 类 ReactApplication
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:16: 错误: 找不到符号
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                ^
  符号:   类 ReactNativeHost
  位置: 类 MainApplication
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:36: 错误: 找不到符号
  public ReactNativeHost getReactNativeHost() {
         ^
  符号:   类 ReactNativeHost
  位置: 类 MainApplication
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainActivity.java:3: 错误: 程序包com.facebook.react不存在
import com.facebook.react.ReactActivity;
                         ^
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainActivity.java:5: 错误: 找不到符号
public class MainActivity extends ReactActivity {
                                  ^
  符号: 类 ReactActivity
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:16: 错误: 找不到符号
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                       ^
  符号:   类 ReactNativeHost
  位置: 类 MainApplication
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:35: 错误: 方法不会覆盖或实现超类型的方法
  @Override
  ^
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainApplication.java:43: 错误: 找不到符号
    SoLoader.init(this, /* native exopackage */ false);
    ^
  符号:   变量 SoLoader
  位置: 类 MainApplication
/Applications/my-project/AwesomeProject/android/app/src/main/java/com/awesomeproject/MainActivity.java:11: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
14 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
12 actionable tasks: 1 executed, 11 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.

**Comment by sunnylqm** [comment]
看一下环境信息
npx react-native info

**Comment by Jonesy-1212** [comment]
> 看一下环境信息 npx react-native info

<img width="1506" alt="WeChat1f13fed80241576aae875576e837a2a2" src="https://user-images.githubusercontent.com/84960431/208358704-ebf28211-6254-4e8b-b63e-e86ba85d61a4.png">

**Comment by sunnylqm** [comment]
新建的项目为啥rn版本是0.59？

**Comment by Jonesy-1212** [comment]
> 新建的项目为啥rn版本是0.59？

因为公司项目版本是0.59.10，所以我新建了一样版本的rn😂

**Comment by sunnylqm** [comment]
你是用as打开过项目，然后升级过gradle？

**Comment by Jonesy-1212** [comment]
> 你是用as打开过项目，然后升级过gradle？

我用的as打开，然后在as下的Contents/gradle 换个3、5、6的版本。都是报错

**Comment by sunnylqm** [comment]
不要更改gradle版本
