### ISSUE TITLE
npm run android编译失败，无法解析android变量

### ISSUE THREAD

**Issue by Swordder** [reactnativecn/react-native-website#682]
## 无法正常启动项目
react-native初体验，第一次配置android并启动项目，终端报错
<img width="740" alt="image" src="https://user-images.githubusercontent.com/60690049/209632478-3d0fddd3-52cc-4585-bac0-85d103451cda.png">

-配置信息如下：

- jdk11 
- react-native 0.7.5

我猜大概是gradle.properties里的android变量读不出来，但不知道为什么

**Comment by sunnylqm** [comment]
去掉vector-icons能正常运行吗，能的话就是vector-icons配置不对，对照它的文档检查

**Comment by Swordder** [comment]
> 去掉vector-icons能正常运行吗，能的话就是vector-icons配置不对，对照它的文档检查

找到原因了,apply vector-icon错位置了
