### ISSUE TITLE
哪位大佬帮我看看啥问题，android测试不成功

### ISSUE THREAD

**Issue by liquan1998** [reactnativecn/react-native-website#687]
在mac电脑配置的环境，用npx react-native init test创建 test 项目，用 yarn android 命令测试，
出现如下错误：

![WX20230104-170643@2x](https://user-images.githubusercontent.com/29195726/210521097-935b6061-5d36-47aa-8935-440affc571fe.png)
![WX20230104-170706@2x](https://user-images.githubusercontent.com/29195726/210521122-6ca291a8-3ee9-409b-b469-7920e2354905.png)

**Comment by liquan1998** [comment]
是什么原因总是 app 安装不上。 我用 adb devices 检测有 安卓模拟器。

**Comment by sunnylqm** [comment]
网络问题，需要使用代理，且代理对命令行有效

**Comment by liquan1998** [comment]
怎么使用代理，我电脑上装了翻墙软件。还需要怎样设置

**Comment by liquan1998** [comment]
> 网络问题，需要使用代理，且代理对命令行有效

有办法解决吗

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/210760880-ce553226-35ea-4562-aaa2-a2adf2e7d3fe.png)

**Comment by liquan1998** [comment]
> ![image](https://user-images.githubusercontent.com/615282/210760880-ce553226-35ea-4562-aaa2-a2adf2e7d3fe.png)

我用的是收费的翻墙工具。比较稳定，浏览器没问题。但是怎样配置命令行呢。能再给点指导吗。谢谢。

**Comment by sunnylqm** [comment]
有个东西叫搜索引擎

**Comment by liquan1998** [comment]
> 安装不上。 我用 adb d



> 有个东西叫搜索引擎

搜了也不行，搜索引擎耶解决不了。你能帮我搞定吗，加微信，发红包
