### ISSUE TITLE
拆包后iOS打开白屏，安卓上是正常的

### ISSUE THREAD

**Issue by CFPanda** [reactnativecn/react-native-website#688]
有人遇到下面的报错吗？
Error: Requiring module "node_modules/react-native-reanimated/src/Animated.js", which threw an exception: TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes

**Comment by sunnylqm** [comment]
明显这个问题该去 reanimated 的仓库搜 https://github.com/software-mansion/react-native-reanimated/issues/3420
