### ISSUE TITLE
搭建开发环境的文档与官方英文文档不一致

### ISSUE THREAD

**Issue by doutv** [reactnativecn/react-native-website#696]
在[3. 配置 ANDROID_SDK_ROOT 环境变量](https://reactnative.cn/docs/environment-setup#3-%E9%85%8D%E7%BD%AE-android_sdk_root-%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)中，图片上 Variable Name 是 ANDROID_HOME，而其他地方使用的都是 ANDROID_SDK_ROOT，如下图所示

![image](https://user-images.githubusercontent.com/20609724/221079228-dc26b152-6b2a-4697-835f-018d11107ff4.png)

在官方英文文档中，使用的始终是 ANDROID_HOME ，而且需要配置的 PATH 的也只有一处 `%LOCALAPPDATA%\Android\Sdk\platform-tools`

![image](https://user-images.githubusercontent.com/20609724/221079663-b66aee0e-6afe-43e2-82e8-b7d0381b738f.png)

**Comment by sunnylqm** [comment]
感谢指正，可以的话能帮忙提个pr吗？

**Comment by doutv** [comment]
可以的，那我按照英文官方文档再翻译一下吧

**Comment by sunnylqm** [comment]
已修复这部分，如有兴趣可以再翻译其他地方

**Comment by doutv** [comment]
感谢~
