### ISSUE TITLE
使用react-native-camera库，启动项目报错，有没有大佬知道的

### ISSUE THREAD

**Issue by Jonesy-1212** [reactnativecn/react-native-website#697]
> Task :react-native-camera:compileGeneralDebugJavaWithJavac FAILED
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraView.java:10: 错误: 程序包android.support.v4.content不存在
import android.support.v4.content.ContextCompat;
                                 ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:27: 错误: 程序包android.support.annotation不存在
import android.support.annotation.IntDef;
                                 ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:28: 错误: 程序包android.support.annotation不存在
import android.support.annotation.NonNull;
                                 ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:29: 错误: 程序包android.support.annotation不存在
import android.support.annotation.Nullable;
                                 ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:30: 错误: 找不到符号
import android.support.v4.os.ParcelableCompat;
                            ^
  符号:   类 ParcelableCompat
  位置: 程序包 android.support.v4.os
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:31: 错误: 找不到符号
import android.support.v4.os.ParcelableCompatCreatorCallbacks;
                            ^
  符号:   类 ParcelableCompatCreatorCallbacks
  位置: 程序包 android.support.v4.os
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:32: 错误: 程序包android.support.v4.view不存在
import android.support.v4.view.ViewCompat;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/AspectRatio.java:21: 错误: 程序包android.support.annotation不存在
import android.support.annotation.NonNull;
                                 ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/AspectRatio.java:22: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.SparseArrayCompat;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Size.java:21: 错误: 程序包android.support.annotation不存在
import android.support.annotation.NonNull;
                                 ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/AspectRatio.java:29: 错误: 找不到符号
    private final static SparseArrayCompat<SparseArrayCompat<AspectRatio>> sCache
                         ^
  符号:   类 SparseArrayCompat
  位置: 类 AspectRatio
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/AspectRatio.java:29: 错误: 找不到符号
    private final static SparseArrayCompat<SparseArrayCompat<AspectRatio>> sCache
                                           ^
  符号:   类 SparseArrayCompat
  位置: 类 AspectRatio
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:9: 错误: 程序包android.support.media不存在
import android.support.media.ExifInterface;
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraViewManager.java:3: 错误: 程序包android.support.annotation不存在
import android.support.annotation.Nullable;
                                 ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:9: 错误: 程序包android.support.media不存在
import android.support.media.ExifInterface;
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:282: 错误: 找不到符号
  public static WritableMap getExifData(ExifInterface exifInterface) {
                                        ^
  符号:   类 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:312: 错误: 找不到符号
  public static void setExifData(ExifInterface exifInterface, WritableMap exifMap) {
                                 ^
  符号:   类 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/BarCodeReadEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/BarCodeReadEvent.java:18: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<BarCodeReadEvent> EVENTS_POOL =
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/PictureTakenEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/PictureTakenEvent.java:14: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<PictureTakenEvent> EVENTS_POOL = new Pools.SynchronizedPool<>(3);
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/BarcodeDetectionErrorEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/BarcodeDetectionErrorEvent.java:13: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<BarcodeDetectionErrorEvent> EVENTS_POOL = new Pools.SynchronizedPool<>(3);
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/BarcodesDetectedEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/BarcodesDetectedEvent.java:13: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<BarcodesDetectedEvent> EVENTS_POOL =
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/PictureSavedEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/PictureSavedEvent.java:12: 错误: 程序包Pools不存在
    private static final Pools.SynchronizedPool<PictureSavedEvent> EVENTS_POOL = new Pools.SynchronizedPool<>(5);
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/CameraReadyEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/CameraReadyEvent.java:14: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<CameraReadyEvent> EVENTS_POOL = new Pools.SynchronizedPool<>(3);
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/FaceDetectionErrorEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/FaceDetectionErrorEvent.java:12: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<FaceDetectionErrorEvent> EVENTS_POOL = new Pools.SynchronizedPool<>(3);
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/CameraMountErrorEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/CameraMountErrorEvent.java:11: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<CameraMountErrorEvent> EVENTS_POOL = new Pools.SynchronizedPool<>(3);
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/FacesDetectedEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/FacesDetectedEvent.java:13: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<FacesDetectedEvent> EVENTS_POOL =
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/TextRecognizedEvent.java:3: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.Pools;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/events/TextRecognizedEvent.java:16: 错误: 程序包Pools不存在
  private static final Pools.SynchronizedPool<TextRecognizedEvent> EVENTS_POOL =
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/lwansbrough/RCTCamera/MutableImage.java:6: 错误: 程序包android.support.media不存在
import android.support.media.ExifInterface;
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/lwansbrough/RCTCamera/MutableImage.java:229: 错误: 找不到符号
    private void rewriteOrientation(ExifInterface exif) {
                                    ^
  符号:   类 ExifInterface
  位置: 类 MutableImage
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/lwansbrough/RCTCamera/MutableImage.java:233: 错误: 找不到符号
    private void writeLocationExifData(ReadableMap options, ExifInterface exif) {
                                                            ^
  符号:   类 ExifInterface
  位置: 类 MutableImage
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/lwansbrough/RCTCamera/MutableImage.java:292: 错误: 找不到符号
        public static void writeExifData(double latitude, double longitude, ExifInterface exif) throws IOException {
                                                                            ^
  符号:   类 ExifInterface
  位置: 类 GPS
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraViewManager.java:3: 错误: 程序包android.support.annotation不存在
import android.support.annotation.Nullable;
                                 ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:56: 错误: 找不到符号
    @IntDef({FACING_BACK, FACING_FRONT})
     ^
  符号:   类 IntDef
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:78: 错误: 找不到符号
    @IntDef({FLASH_OFF, FLASH_ON, FLASH_TORCH, FLASH_AUTO, FLASH_RED_EYE})
     ^
  符号:   类 IntDef
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera1.java:27: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.SparseArrayCompat;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera1.java:48: 错误: 找不到符号
    private static final SparseArrayCompat<String> FLASH_MODES = new SparseArrayCompat<>();
                         ^
  符号:   类 SparseArrayCompat
  位置: 类 Camera1
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera1.java:58: 错误: 找不到符号
    private static final SparseArrayCompat<String> WB_MODES = new SparseArrayCompat<>();
                         ^
  符号:   类 SparseArrayCompat
  位置: 类 Camera1
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/SizeMap.java:19: 错误: 程序包android.support.v4.util不存在
import android.support.v4.util.ArrayMap;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/SizeMap.java:30: 错误: 找不到符号
    private final ArrayMap<AspectRatio, SortedSet<Size>> mRatios = new ArrayMap<>();
                  ^
  符号:   类 ArrayMap
  位置: 类 SizeMap
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java:40: 错误: 程序包android.support.annotation不存在
import android.support.annotation.NonNull;
                                 ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/SurfaceViewPreview.java:20: 错误: 程序包android.support.v4.view不存在
import android.support.v4.view.ViewCompat;
                              ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/general/java/org/reactnative/facedetector/tasks/FileFaceDetectionAsyncTask.java:6: 错误: 程序包android.support.media不存在
import android.support.media.ExifInterface;
                            ^
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:132: 错误: 找不到符号
    @NonNull
     ^
  符号:   类 NonNull
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:324: 错误: 找不到符号
    public void addCallback(@NonNull Callback callback) {
                             ^
  符号:   类 NonNull
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:334: 错误: 找不到符号
    public void removeCallback(@NonNull Callback callback) {
                                ^
  符号:   类 NonNull
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:399: 错误: 找不到符号
    public void setAspectRatio(@NonNull AspectRatio ratio) {
                                ^
  符号:   类 NonNull
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:410: 错误: 找不到符号
    @Nullable
     ^
  符号:   类 Nullable
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:420: 错误: 找不到符号
    public SortedSet<Size> getAvailablePictureSizes(@NonNull AspectRatio ratio) {
                                                     ^
  符号:   类 NonNull
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:429: 错误: 找不到符号
    public void setPictureSize(@NonNull Size size) {
                                ^
  符号:   类 NonNull
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/AspectRatio.java:136: 错误: 找不到符号
    public int compareTo(@NonNull AspectRatio another) {
                          ^
  符号:   类 NonNull
  位置: 类 AspectRatio
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Size.java:91: 错误: 找不到符号
    public int compareTo(@NonNull Size another) {
                          ^
  符号:   类 NonNull
  位置: 类 Size
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/CameraViewManager.java:62: 错误: 找不到符号
  @Nullable
   ^
  符号:   类 Nullable
  位置: 类 CameraViewManager
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraViewManager.java:40: 错误: 找不到符号
    public void receiveCommand(RCTCameraView view, int commandType, @Nullable ReadableArray args) {
                                                                     ^
  符号:   类 Nullable
  位置: 类 RCTCameraViewManager
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java:1335: 错误: 找不到符号
        public void onCaptureProgressed(@NonNull CameraCaptureSession session,
                                         ^
  符号:   类 NonNull
  位置: 类 PictureCaptureCallback
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java:1336: 错误: 找不到符号
                @NonNull CaptureRequest request, @NonNull CaptureResult partialResult) {
                 ^
  符号:   类 NonNull
  位置: 类 PictureCaptureCallback
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java:1336: 错误: 找不到符号
                @NonNull CaptureRequest request, @NonNull CaptureResult partialResult) {
                                                  ^
  符号:   类 NonNull
  位置: 类 PictureCaptureCallback
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java:1341: 错误: 找不到符号
        public void onCaptureCompleted(@NonNull CameraCaptureSession session,
                                        ^
  符号:   类 NonNull
  位置: 类 PictureCaptureCallback
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java:1342: 错误: 找不到符号
                @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                 ^
  符号:   类 NonNull
  位置: 类 PictureCaptureCallback
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java:1342: 错误: 找不到符号
                @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                                  ^
  符号:   类 NonNull
  位置: 类 PictureCaptureCallback
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java:1346: 错误: 找不到符号
        private void process(@NonNull CaptureResult result) {
                              ^
  符号:   类 NonNull
  位置: 类 PictureCaptureCallback
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:147: 错误: 找不到符号
            mDisplayOrientationDetector.enable(ViewCompat.getDisplay(this));
                                               ^
  符号:   变量 ViewCompat
  位置: 类 CameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:703: 错误: 找不到符号
                = ParcelableCompat.newCreator(new ParcelableCompatCreatorCallbacks<SavedState>() {
                                                  ^
  符号:   类 ParcelableCompatCreatorCallbacks
  位置: 类 SavedState
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/CameraView.java:703: 错误: 找不到符号
                = ParcelableCompat.newCreator(new ParcelableCompatCreatorCallbacks<SavedState>() {
                  ^
  符号:   变量 ParcelableCompat
  位置: 类 SavedState
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraView.java:515: 错误: 找不到符号
      int result = ContextCompat.checkSelfPermission(getContext(), Manifest.permission.CAMERA);
                   ^
  符号:   变量 ContextCompat
  位置: 类 RNCameraView
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/AspectRatio.java:30: 错误: 找不到符号
            = new SparseArrayCompat<>(16);
                  ^
  符号:   类 SparseArrayCompat
  位置: 类 AspectRatio
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/AspectRatio.java:47: 错误: 找不到符号
        SparseArrayCompat<AspectRatio> arrayX = sCache.get(x);
        ^
  符号:   类 SparseArrayCompat
  位置: 类 AspectRatio
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/AspectRatio.java:50: 错误: 找不到符号
            arrayX = new SparseArrayCompat<>();
                         ^
  符号:   类 SparseArrayCompat
  位置: 类 AspectRatio
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:100: 错误: 找不到符号
                ExifInterface exifInterface = new ExifInterface(inputStream);
                ^
  符号:   类 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:100: 错误: 找不到符号
                ExifInterface exifInterface = new ExifInterface(inputStream);
                                                  ^
  符号:   类 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:102: 错误: 找不到符号
                int orientation = exifInterface.getAttributeInt(ExifInterface.TAG_ORIENTATION,
                                                                ^
  符号:   变量 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:103: 错误: 找不到符号
                        ExifInterface.ORIENTATION_UNDEFINED);
                        ^
  符号:   变量 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:108: 错误: 找不到符号
                        && orientation != ExifInterface.ORIENTATION_UNDEFINED;
                                          ^
  符号:   变量 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:137: 错误: 找不到符号
                        fileExifData.putInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_NORMAL);
                                            ^
  符号:   变量 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:137: 错误: 找不到符号
                        fileExifData.putInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_NORMAL);
                                                                           ^
  符号:   变量 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:159: 错误: 找不到符号
                    ExifInterface fileExifInterface = new ExifInterface(filePath);
                    ^
  符号:   类 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:159: 错误: 找不到符号
                    ExifInterface fileExifInterface = new ExifInterface(filePath);
                                                          ^
  符号:   类 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:226: 错误: 找不到符号
        case ExifInterface.ORIENTATION_ROTATE_90:
             ^
  符号:   变量 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:229: 错误: 找不到符号
        case ExifInterface.ORIENTATION_ROTATE_180:
             ^
  符号:   变量 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java:232: 错误: 找不到符号
        case ExifInterface.ORIENTATION_ROTATE_270:
             ^
  符号:   变量 ExifInterface
  位置: 类 ResolveTakenPictureAsyncTask
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:29: 错误: 找不到符号
      {"string", ExifInterface.TAG_ARTIST},
                 ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:30: 错误: 找不到符号
      {"int", ExifInterface.TAG_BITS_PER_SAMPLE},
              ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:31: 错误: 找不到符号
      {"int", ExifInterface.TAG_COMPRESSION},
              ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:32: 错误: 找不到符号
      {"string", ExifInterface.TAG_COPYRIGHT},
                 ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:33: 错误: 找不到符号
      {"string", ExifInterface.TAG_DATETIME},
                 ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:34: 错误: 找不到符号
      {"string", ExifInterface.TAG_IMAGE_DESCRIPTION},
                 ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:35: 错误: 找不到符号
      {"int", ExifInterface.TAG_IMAGE_LENGTH},
              ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:36: 错误: 找不到符号
      {"int", ExifInterface.TAG_IMAGE_WIDTH},
              ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:37: 错误: 找不到符号
      {"int", ExifInterface.TAG_JPEG_INTERCHANGE_FORMAT},
              ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:38: 错误: 找不到符号
      {"int", ExifInterface.TAG_JPEG_INTERCHANGE_FORMAT_LENGTH},
              ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
/Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java:39: 错误: 找不到符号
      {"string", ExifInterface.TAG_MAKE},
                 ^
  符号:   变量 ExifInterface
  位置: 类 RNCameraViewHelper
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Applications/jtyWorkSpac/teacher-app/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
100 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-camera:compileGeneralDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by sunnylqm** [comment]
本身这个库废弃了，而且你用的还是更老的没有迁移到androidx的版本

**Comment by Jonesy-1212** [comment]
> 

要咋解决，只能迁移到androidx吗

**Comment by sunnylqm** [comment]
更新到新版本啊
