### ISSUE TITLE
/lib/arm64/libjsc.so大规模崩溃

### ISSUE THREAD

**Issue by joedan0104** [reactnativecn/react-native-website#699]
React Native页面打开出现libjsc.so崩溃。崩溃信息如下：
`# HeapHelper(31040)

SIGSEGV(SEGV_MAPERR)

解析原始
1
#00 pc 00000000000f7748 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (JSC::AccessCase::propagateTransitions(JSC::SlotVisitor&) const+16) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
2
#01 pc 0000000000143fe8 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (JSC::PolymorphicAccess::propagateTransitions(JSC::SlotVisitor&) const+48) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
3
#02 pc 000000000012f0a8 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (JSC::CodeBlock::propagateTransitions(JSC::ConcurrentJSLocker const&, JSC::SlotVisitor&)+556) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
4
#03 pc 0000000000139484 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (JSC::ExecutableToCodeBlockEdge::runConstraint(JSC::ConcurrentJSLocker const&, JSC::VM&, JSC::SlotVisitor&)+40) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
5
#04 pc 000000000013900c /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (JSC::ExecutableToCodeBlockEdge::visitChildren(JSC::JSCell*, JSC::SlotVisitor&)+1044) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
6
#05 pc 00000000001fb9c4 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (_ZZN3JSC11SlotVisitor5drainEN3WTF13MonotonicTimeEENK3$_3clERNS_14MarkStackArrayE+324) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
7
#06 pc 00000000001f8e90 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (JSC::SlotVisitor::drain(WTF::MonotonicTime)+132) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
8
#07 pc 00000000001f96bc /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (JSC::SlotVisitor::drainFromShared(JSC::SlotVisitor::SharedDrainMode, WTF::MonotonicTime)+580) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
9
#08 pc 00000000001e41a0 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (_ZN3WTF17SharedTaskFunctorIFvvEZN3JSC4Heap13runBeginPhaseENS2_11GCConductorEE4$_17E3runEv+580) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
10
#09 pc 00000000006171ec /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (WTF::ParallelHelperClient::runTask(WTF::RefPtr<WTF::SharedTask<void ()>, WTF::DumbPtrTraits<WTF::SharedTask<void ()> > > const&)+40) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
11
#10 pc 0000000000617950 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (WTF::ParallelHelperPool::Thread::work()+16) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
12
#11 pc 000000000060de7c /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (_ZN3WTF8FunctionIFvvEE15CallableWrapperIZNS_15AutomaticThread5startERKNS_14AbstractLockerEE3$_0E4callEv+376) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
13
#12 pc 000000000061b084 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)+212) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
14
#13 pc 0000000000646dc8 /data/app/com.qiyu.android.vrapp-cRd4WzmNAPh99cr9Jo6bnA==/lib/arm64/libjsc.so (WTF::wtfThreadEntryPoint(void*)+4) [arm64-v8a::c42a95481490bde03ca0bbcd7dacaa81]
`
## 请描述完整的环境/版本信息
React Native版本：0.64.3
android-jsc版本：org.webkit:android-jsc:r245459

崩溃次数统计
![image](https://user-images.githubusercontent.com/8829496/224882858-f8e09142-0c90-4cc2-ad4f-3cf73dbbf46e.png)

**Comment by sunnylqm** [comment]
更新jsc试试 
https://github.com/react-native-community/jsc-android-buildscripts
