### ISSUE TITLE
react native版本0.25，可以使用React-Native-Video组件吗？应该下载哪个版本的video？

### ISSUE THREAD

**Issue by wukexin77** [reactnativecn/react-native-website#701]
请按以下格式提供问题的相关信息。

## 问题的具体描述
0.25版本的react-native，有一个视频播放的功能
使用npm install react-native-video之后项目报错，运行不起来了，请问大佬是需要下载对应版本的video组件吗？对应版本是哪个？
![image](https://user-images.githubusercontent.com/57856751/225504281-e2f0209e-28e3-4d54-8967-b624688f9a6c.png)

**Comment by sunnylqm** [comment]
先升级rn吧，这种史前版本不可能再有组件支持了
