### ISSUE TITLE
react-native 首次运行时报错

### ISSUE THREAD

**Issue by huaicui-qulinjian** [reactnativecn/react-native-website#707]
模拟器，安卓环境等均已安装正确。
0.64.4 和 0.63.5均报错
error: TypeError: Cannot read properties of undefined (reading 'transformFile')
    at D:\wamp\wamp\www\Pro\n\money\node_modules\metro\src\Bundler.js:91:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\wamp\wamp\www\Pro\n\money\node_modules\metro\src\Bundler.js:14:24)
    at _next (D:\wamp\wamp\www\Pro\n\money\node_modules\metro\src\Bundler.js:34:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
网上搜索无解。求助

**Comment by GN-L** [comment]
我也遇到同样的问题  真是无语了  我是Mac M2芯片 ，  捣鼓两天了 ，  各种看文档，百度都不行，  这啥玩意儿 ，  感觉很坑啊

**Comment by GN-L** [comment]
> 

兄弟，你解决这个问题了吗

**Comment by cw0121** [comment]
我也是m2芯片，老项目启动失败，楼上的兄弟你的问题解决了么

**Comment by liuhm0284** [comment]
我直接打包可以，但是想运行到安卓设备上就直接卡在99%，看项目文件里apk文件已经生成了。。我就很郁闷，还有用as的模拟器，总是说我的 Your CPU does not support VT-x  ,去除X86 intel支持都不得行，现在只能用ios的机器或者模拟器测试，好郁闷啊。

**Comment by cw0121** [comment]
我在windows电脑上用mumu 模拟器测试了是好用的，发现问题出在我从远程仓库拉取代码的时候却少了一部分，后来又重新拉取的，现在可以运行了





------------------ 原始邮件 ------------------
发件人: 刘老根丶丶 ***@***.***&gt;
发送时间: 2023年7月25日 18:40
收件人: reactnativecn/react-native-website ***@***.***&gt;
抄送: cw0121 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [reactnativecn/react-native-website] react-native 首次运行时报错 (Issue #707)





 
我直接打包可以，但是想运行到安卓设备上就直接卡在99%，看项目文件里apk文件已经生成了。。我就很郁闷，还有用as的模拟器，总是说我的 Your CPU does not support VT-x  ,去除X86 intel支持都不得行，现在只能用ios的机器或者模拟器测试，好郁闷啊。
