### ISSUE TITLE
应该是 "non-scrolling" 而非 “non-scrollling”

### ISSUE THREAD

**Issue by 188102836** [reactnativecn/react-native-website#710]
此处应该是两个 "l" 而非三个 "l"

![image](https://github.com/reactnativecn/react-native-website/assets/69347367/8e90b8cf-7aa7-478f-bcda-64924439cd70)

链接如下：
https://www.reactnative.cn/docs/intro-react-native-components#核心组件
https://github.com/reactnativecn/react-native-website/blob/production/cndocs/intro-react-native-components.md#核心组件

**Comment by sunnylqm** [comment]
感谢提醒，可以的话以后可以直接点这里来修改提交pr的
![image](https://github.com/reactnativecn/react-native-website/assets/615282/a9e98d41-27da-40e6-a3af-8d974cdaa0ae)
