### ISSUE TITLE
metro启动后无法更新界面

### ISSUE THREAD

**Issue by almightyYantao** [reactnativecn/react-native-website#716]
启动metro之后，在系统双 R 没有更新代码。

终端启动：yarn android
然后用 android studio  编辑修改了app.tsx，但是没有更新

![image](https://github.com/reactnativecn/react-native-website/assets/34707560/cdb0d804-2c45-4fba-b48a-23f0fb6da596)

**Comment by almightyYantao** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/34707560/241af855-c687-4295-8413-51f7a6ac72b2)

**Comment by sunnylqm** [comment]
是否执行过bundle命令？以及不要用as来编辑文件（推荐用vscode）

**Comment by almightyYantao** [comment]
没有执行过bundle ，执行过 yarn start，好的，我用vscode试一下

**Comment by almightyYantao** [comment]
> 是否执行过bundle命令？以及不要用as来编辑文件（推荐用vscode）

大佬还是不行，一样的，我不管用run-iso 还是 android 都无法实现刷新

**Comment by almightyYantao** [comment]
> 是否执行过bundle命令？以及不要用as来编辑文件（推荐用vscode）

![image](https://github.com/reactnativecn/react-native-website/assets/34707560/1a408af5-334d-40f3-87dc-033cbce41f67)
一只在读取缓存的 BUNDLE

**Comment by sunnylqm** [comment]
是否执行过bundle命令
