### ISSUE TITLE
项目启动不起来，有知道原因的大佬吗？ 这破环境我配置两天，一点也启不了。。

### ISSUE THREAD

**Issue by GN-L** [reactnativecn/react-native-website#718]
命令行的项目目录中运行`npx react-native info`命令，输出结果：
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 233.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/lib/ruby/gems/3.2.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 29, 30, 33
      Build Tools: 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 33.0.2
      System Images: android-29 | Intel x86_64 Atom, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_372 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.5 => 0.66.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

#控制台报错截图：
<img width="1368" alt="截屏2023-06-08 12 48 06" src="https://github.com/reactnativecn/react-native-website/assets/28701580/33197269-f872-4419-8db9-9c032b4a73dd">

#启动不了，这项目我一点都启动不了，大佬帮我指点指点， 多谢了

**Comment by sunnylqm** [comment]
贴报错的截图啊

**Comment by GN-L** [comment]
> 

添加报错截图了

**Comment by LovesLolita** [comment]
android stdio 相关依赖装了吗

**Comment by GN-L** [comment]
> android stdio 相关依赖装了吗

都装了    用了梯子  把该装的都装了   照着文档来的  没有一次能行

**Comment by sunnylqm** [comment]
这个是node版本太高了，装node16（最新版本的rn才支持node18，你的是0.66比较老了），其他环境没问题，编译已经成功了

**Comment by raintoway** [comment]
If you are free after 9 pm tonight, I can help you，wechat：15015916809
