### ISSUE TITLE
npm run android failed

### ISSUE THREAD

**Issue by xiaohuaqqqq** [reactnativecn/react-native-website#719]
> Configure project :react-native-reanimated
Native libs debug enabled: false
Android gradle plugin: 4.1.3
Gradle: 6.7
building Reanimated2

> Task :react-native-maps:packageDebugAssets FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
53 actionable tasks: 4 executed, 49 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:packageDebugAssets'.
> Unable to delete file 'C:\Users\admin\Desktop\CleanMe-2\CleanMe-2\node_modules\react-native-maps\lib\android\build\intermediates\incremental\packageDebugAssets'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 27s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:packageDebugAssets'.
> Unable to delete file 'C:\Users\admin\Desktop\CleanMe-2\CleanMe-2\node_modules\react-native-maps\lib\android\build\intermediates\incremental\packageDebugAssets'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 27s

    at makeError (C:\Users\admin\Desktop\CleanMe-2\CleanMe-2\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\admin\Desktop\CleanMe-2\CleanMe-2\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\Users\admin\Desktop\CleanMe-2\CleanMe-2\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\admin\Desktop\CleanMe-2\CleanMe-2\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

**Comment by sunnylqm** [comment]
它说有个文件删不掉，你手动删一下试试？

**Comment by xiaohuaqqqq** [comment]
> 它说有个文件删不掉，你手动删一下试试？

我看了那个文件夹没有这个文件
