### ISSUE TITLE
无法正常启动模拟器

### ISSUE THREAD

**Issue by GeorgeHcc** [reactnativecn/react-native-website#723]
## run `npx react-native info`
![image](https://github.com/reactnativecn/react-native-website/assets/72842677/657ff904-3fb3-4ab6-b6bd-3fb08b92db9e)
![image](https://github.com/reactnativecn/react-native-website/assets/72842677/e0821119-55de-45cf-bfbe-e45925df3fef)

## run `npm run start`
![image](https://github.com/reactnativecn/react-native-website/assets/72842677/94ac3c54-697b-4654-9307-657accd806c4)

**Comment by haohuihai** [comment]
可以删除node_modules， 重新npm install，在运行试试，

**Comment by sunnylqm** [comment]
是纯rn项目还是原生集成？原生集成的话文档有误，已修复

https://github.com/reactnativecn/react-native-website/commit/8d8a4719fd211258bb3ddef97b813215f351d1cd

**Comment by GeorgeHcc** [comment]
是纯RN项目，初学者，删除node_modules也不行
