### ISSUE TITLE
>npx react-native run-android 报错 卡在 info JS server already running. 不动了

### ISSUE THREAD

**Issue by PNP-cpp** [reactnativecn/react-native-website#727]
>npx react-native run-android
![1689301802288](https://github.com/reactnativecn/react-native-website/assets/40652939/deec43e1-00c6-4309-8ba8-5a850cc2c3f2)

**Comment by PNP-cpp** [comment]
按照最新的官方教程走的

**Comment by sunnylqm** [comment]
模拟器那边的截图呢

**Comment by 810861180** [comment]
上个月学rn随便弄了个项目没啥问题，都正常启动了。今天想开个新项目好好写一下，结果也是这样，就在这一步不动了，但我之前那个学习用的项目可以正常启动。都是按照官网文档走的

**Comment by taobobobo** [comment]
请问解决了吗

**Comment by chenwenfeng** [comment]
第一次是很慢的会卡很久 以后就正常了
