### ISSUE TITLE
android虚拟手机中的app没有被打开

### ISSUE THREAD

**Issue by stealPigs-youth** [reactnativecn/react-native-website#729]
![我的问题](https://github.com/reactnativecn/react-native-website/assets/123810336/f3f64b29-d516-4818-9a10-594d24994499)

**Comment by sunnylqm** [comment]
控制台那个往下截图

**Comment by stealPigs-youth** [comment]
![图片儿](https://github.com/reactnativecn/react-native-website/assets/123810336/392af82a-da49-45e4-b612-615fb75d099b)

**Comment by stealPigs-youth** [comment]
r - reload the app
d - open developer menu
i - run on iOS
a - run on Android

info Opening the app on Android...
info JS server already running.
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
> Task :gradle-plugin:compileKotlin UP-TO-DATE
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :gradle-plugin:processResources UP-TO-DATE
> Task :gradle-plugin:classes UP-TO-DATE
> Task :gradle-plugin:jar UP-TO-DATE
> Task :gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE
> Task :app:buildCodegenCLI SKIPPED
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:checkDebugAarMetadata
|

**Comment by sunnylqm** [comment]
就卡在这里了？下面没有了？

**Comment by stealPigs-youth** [comment]
没有了，一直卡在这

**Comment by stealPigs-youth** [comment]
现在已经可以了，可以下载依赖和编译项目时间比较长
![成功了](https://github.com/reactnativecn/react-native-website/assets/123810336/a7c27b44-ea46-4784-af83-546addf8d415)

**Comment by sunnylqm** [comment]
https://github.com/reactnativecn/react-native-website/issues/731#issuecomment-1639700454
