### ISSUE TITLE
在 windows10 上搭建 RN 安卓开发环境一直跑不起来

### ISSUE THREAD

**Issue by Bourne115** [reactnativecn/react-native-website#732]
请按以下格式提供问题的相关信息。
## 问题的具体描述
已经对命令 powershell 配置了代理，并且能正常使用。
![image](https://github.com/reactnativecn/react-native-website/assets/35766694/00ee8155-850a-453c-8f44-83e839760ebf)
但每次使用 `yarn start` 然后再 `yarn android` 之后过一段时间就会出现下面的问题，并且在 demo 中也按照文档配置了 阿里云 maven镜像源地址
![image](https://github.com/reactnativecn/react-native-website/assets/35766694/d7c62f3f-f822-477c-953d-c80ce58f8f2d)

## 请描述完整的环境/版本信息
- 请在命令行的项目目录中运行`npx react-native info`命令，并将其输出结果粘贴到这里。
- 
![image](https://github.com/reactnativecn/react-native-website/assets/35766694/66459b64-aacb-4c95-8fbd-9200c3c8ad42)

- 如果问题涉及到第三方包/库/模块，请也将package.json的内容粘贴到这里。

## 预期结果
-  能正常的启动 demo 然后在模拟器中使用

**Comment by sunnylqm** [comment]
如果代理能正常使用，试试把两个maven仓库切回去

**Comment by Bourne115** [comment]
> 如果代理能正常使用，试试把两个maven仓库切回去
> >  切回去后，就卡在这里了，和 #731 issue 一样。😅😅😅
> >  ![image](https://github.com/reactnativecn/react-native-website/assets/35766694/a3db2b76-6283-48bc-941b-5c5194900c13)

**Comment by sunnylqm** [comment]
第一次运行下载时间会比较久

**Comment by Bourne115** [comment]
> 第一次运行下载时间会比较久

>>  感谢指导
![image](https://github.com/reactnativecn/react-native-website/assets/35766694/5e82ef12-2468-4772-9d74-dcbccac5806a)
