### ISSUE TITLE
在RN项目中使用Axios作为请求框架，设置请求代理失效。在抓包工具Charles中无法看到请求！！！

### ISSUE THREAD

**Issue by LiverpoolDX** [reactnativecn/react-native-website#733]
"axios": "^1.4.0",
    "react": "18.2.0",
<img width="461" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/44792321/3610e3ed-d743-4006-8036-592c7d01c208">

**Comment by sunnylqm** [comment]
没必要，而且很可能用不了

用flipper抓包更方便

**Comment by cctv1005s** [comment]
一般用 fetch 吧？

**Comment by chenwenfeng** [comment]
用axios优点是什么 直接fetch不是更简单
