### ISSUE TITLE
react native启动报错

### ISSUE THREAD

**Issue by rgbtdkjcel** [reactnativecn/react-native-website#736]
请按以下格式提供问题的相关信息。

## 问题的具体描述
- 在windows 11操作系统上面，执行react-native run-android,报如下错误 ：
- 
![image](https://github.com/reactnativecn/react-native-website/assets/7495659/86a0b0cf-d37e-41a1-8333-fde3fd723bd2)

一直卡在这个环节，都没有运行成功。求助SOS...SOS...

## 请描述完整的环境/版本信息
以下为下系统环境信息
![image](https://github.com/reactnativecn/react-native-website/assets/7495659/d3f5fb13-9a27-4e48-8968-da0767c15dc1)
以下为package.json
"dependencies": {
    "@ptomasroos/react-native-multi-slider": "^1.0.0",
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/cameraroll": "^1.4.0",
    "@react-native-community/cli": "^11.3.6",
    "beeshell": "^2.0.11",
    "date-fns": "^2.14.0",
    "jcore-react-native": "1.7.0",
    "jpush-react-native": "2.2.13",
    "moment": "^2.29.1",
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-amap-geolocation": "1.1.2",
    "react-native-amap3d": "3.2.4",
    "react-native-calendars": "^1.212.0",
    "react-native-camera": "^3.8.0",
    "react-native-code-push": "^6.1.1",
    "react-native-device-info": "^5.2.1",
    "react-native-eject": "^0.2.0",
    "react-native-elements": "^1.2.7",
    "react-native-fast-image": "^7.0.2",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "1.5.3",
    "react-native-image-crop-picker": "^0.26.1",
    "react-native-image-resizer": "1.2.2",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-pdf": "6.0.1",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-native-signature-capture": "0.4.10",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swiper": "^1.6.0-nightly.5",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^7.6.0",
    "react-native-wechat-lib": "^1.1.15",
    "react-navigation": "^4.0.10",
    "react-navigation-redux-helpers": "^4.0.1",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.5.6",
    "react-redux": "^7.1.3",
    "recyclerlistview": "^3.0.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "teaset": "0.7.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/runtime": "^7.6.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "@types/jest": "^25.1.4",
    "@types/react": "^16.9.23",
    "@types/react-native": "^0.61.20",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "^24.9.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint": "^6.6.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.3",
    "react-test-renderer": "16.9.0",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
## 预期结果
希望能够正常编译。

**Comment by sunnylqm** [comment]
报错是amap3d这个库没有找到compilesdkversion这个项目变量，早期的rn版本没有指定这个全局共享的变量，你可能需要参考下最新版本的rn的build.gradle文件去补一下这几个变量，补完之后再运行看看，也可能还需要其他的修改或者干脆得升级rn版本

**Comment by rgbtdkjcel** [comment]
升级的时候，报这个错误 。谢谢大佬指点
![image](https://github.com/reactnativecn/react-native-website/assets/7495659/dc5c970e-5e62-48a9-b212-489eae837974)

**Comment by rgbtdkjcel** [comment]
升级完成之后，还是报同样的错误 ，如下图：
![image](https://github.com/reactnativecn/react-native-website/assets/7495659/0b568bca-d71e-47d2-abd3-2a9f8a2c12fc)

版本信息如下：
![image](https://github.com/reactnativecn/react-native-website/assets/7495659/ea59300b-5772-4a38-a634-b7a4988948de)

**Comment by sunnylqm** [comment]
升级没有完成，你的项目没有添加到git，所以无法执行自动升级，即便能执行，也有大量需要手动修改的地方，具体见upgrade helper

**Comment by rgbtdkjcel** [comment]
大佬 ，有偿，能否帮忙远程解决一下下？

**Comment by sunnylqm** [comment]
加我qq 34731408

**Comment by rgbtdkjcel** [comment]
加你了，大佬 .麻烦通过一下下
