### ISSUE TITLE
android 安装环境

### ISSUE THREAD

**Issue by rgbtdkjcel** [reactnativecn/react-native-website#737]
请按以下格式提供问题的相关信息。

## 问题的具体描述
  我在windows10上安装了android sdk环境，但是通过npx @react-native-community/cli doctor进行检测时，提示找不到环境这个环境，请问一下下，是哪个环境出问题 了？
-  
 
![image](https://github.com/reactnativecn/react-native-website/assets/7495659/eab0b7e0-7bc9-4ce0-a522-9dd4bbc5c9a0)

执行ADB环境：
![image](https://github.com/reactnativecn/react-native-website/assets/7495659/3545f94b-a481-4921-afe8-a04b066372f4)

 现在不知道是哪个环节出问题了，求指点。

**Comment by sunnylqm** [comment]
没有配置环境变量

**Comment by rgbtdkjcel** [comment]
肯定配置了，兄弟，能不能加个V？有偿帮忙解决一下？

**Comment by wubaibin** [comment]
请问解决了吗

**Comment by sunnylqm** [comment]
doctor的输出其实不重要，具体编译过程中有什么错误再贴出来

**Comment by wubaibin** [comment]
`wubaibin@wubaibins-MacBook-Pro ~ % npx @react-native-community/cli doctor
⠏ Running diagnostics...
warn We couldn't find a package.json in this directory. Android SDK checks may fail. Doctor works best in a React Native project root.
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies
 ✓ npm - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✖ Adb - No devices and/or emulators connected. Please create emulator with Android Studio or connect Android device.
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: Not Found
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
`

**Comment by wubaibin** [comment]
An error occurred while installing json (2.6.3), and Bundler cannot continue.
Make sure that `gem install json -v '2.6.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  cocoapods was resolved to 1.13.0, which depends on
    cocoapods-core was resolved to 1.13.0, which depends on
      algoliasearch was resolved to 1.27.5, which depends on
        json
✖ Installing Ruby Gems
error Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/environment-setup?os=macos&platform=android and follow the React Native CLI QuickStart guide for macOS and iOS.

**Comment by sunnylqm** [comment]
An error occurred while installing json (2.6.3), and Bundler cannot continue.
Make sure that gem install json -v '2.6.3' --source 'https://rubygems.org/'
succeeds before bundling.

这不是已经告诉你要你干啥吗
