### ISSUE TITLE
通过yarn react-native run-android编译报错Could not find implementation class 'com.facebook.react.ReactPlugin' for plugin 'com.facebook.react' specified

### ISSUE THREAD

**Issue by shijieping0929** [reactnativecn/react-native-website#738]
通过指令编译运行android
报错Could not find implementation class 'com.facebook.react.ReactPlugin' for plugin 'com.facebook.react' specified和compileSdkVersion is not specified. Please add it to build.gradle
![微信截图_20230808152011](https://github.com/reactnativecn/react-native-website/assets/56946176/b6dc5775-308d-420c-af70-5749ea8a4809)

**Comment by shijieping0929** [comment]
配置信息：
![微信截图_20230808153853](https://github.com/reactnativecn/react-native-website/assets/56946176/0742d5b8-21f9-435b-97dd-d4af73af4b03)

**Comment by sunnylqm** [comment]
是否有全局的gradle配置？

**Comment by shijieping0929** [comment]
已解决。生成工程 java 版本不是11

**Comment by CuberLuo** [comment]
> 已解决。生成工程 java 版本不是11

请问什么意思？我也遇到了相同的问题，请问具体的解决方案是什么？
