### ISSUE TITLE
怎么设置小横条背景颜色

### ISSUE THREAD

**Issue by lstgithub578** [reactnativecn/react-native-website#740]
下面的小横条怎么设置成黑色
![image](https://github.com/reactnativecn/react-native-website/assets/55378864/00e1aebf-fde5-4d0e-8450-edf0dc6fb9fb)

**Comment by cctv1005s** [comment]
你这个是什么设备？

**Comment by lstgithub578** [comment]
> 你这个是什么设备？
小米10，加了下面这个配置之后变透明了，但是屏幕的内容会被状态栏遮挡一部分， 可能还有其它的设置方法，但是没找到
![image](https://github.com/reactnativecn/react-native-website/assets/55378864/b89990d8-0c58-4388-96f0-27a0b8095516)
![image](https://github.com/reactnativecn/react-native-website/assets/55378864/38d8360c-3689-45a2-bae9-005b3b244cf1)
