### ISSUE TITLE
RN显示中文乱码问题 

### ISSUE THREAD

**Issue by rgbtdkjcel** [reactnativecn/react-native-website#743]
请按以下格式提供问题的相关信息。

## 问题的具体描述
RN显示接口返回的数据，中文字体存在乱码的情况，使用调试工具，中文都能够显示正常。不知道问题出在哪里。
![乱码](https://github.com/reactnativecn/react-native-website/assets/7495659/c8962839-53bf-4799-b3af-c97ce351c5fb)
![乱码2](https://github.com/reactnativecn/react-native-website/assets/7495659/95df2c56-ba49-4957-a122-afde4781f6a3)

- 请尽量配上相关代码截图

**Comment by cctv1005s** [comment]
贴一下相关的代码？光看图不知道发生了什么
