### ISSUE TITLE
关于IOS下的cocoapods与ruby版本问题

### ISSUE THREAD

**Issue by rgbtdkjcel** [reactnativecn/react-native-website#744]
请按以下格式提供问题的相关信息。

## 问题的具体描述
请问一下，React-Native 0.63.5版本，在IOS下面，有没有cocoapods，Ruby的版本限制？我用cocoapods1.12.1执行pod install时，报错，如下图：
![image](https://github.com/reactnativecn/react-native-website/assets/7495659/cffe8c01-f8fc-450d-8c56-f7404886ac88)

**Comment by sunnylqm** [comment]
可能你某个第三方调用了你当前rn版本没有的模块
