### ISSUE TITLE
请问这个错误如何解决？

### ISSUE THREAD

**Issue by rgbtdkjcel** [reactnativecn/react-native-website#745]
请按以下格式提供问题的相关信息。

## 问题的具体描述
 执行react-native run-ios后，报图片中的错误 ，请问是什么原因呢？

![d9157ff36ecfc094b2435cd67373bb1d](https://github.com/reactnativecn/react-native-website/assets/7495659/adb535be-e3b8-4c1f-8711-b753bbe2fd22)

**Comment by sunnylqm** [comment]
Xcode版本低了
