### ISSUE TITLE
mac执行react-native run-ios报错

### ISSUE THREAD

**Issue by rgbtdkjcel** [reactnativecn/react-native-website#748]
请按以下格式提供问题的相关信息。

## 问题的具体描述
在MAC 13 系统上执行react-native run-ios时，显示：“Print: Entry, ":CFBundleIdentifier", Does Not Exist”。求大神指教
react-native:0.61.2
![error](https://github.com/reactnativecn/react-native-website/assets/7495659/94e0349c-bb25-4464-808a-5574f58da643)

**Comment by sunnylqm** [comment]
<img width="1203" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/615282/fe31d26a-00e4-455f-8596-c37e3c7cc118">

**Comment by rgbtdkjcel** [comment]
我用yarn启动，也是报错，用Xcode可以正常运行

**Comment by z-coder-hub** [comment]
把build包删了，重新安装试试
