### ISSUE TITLE
打包一直报错，已开代理，解决报错

### ISSUE THREAD

**Issue by 3283615145** [reactnativecn/react-native-website#750]
Failed to upload the project tarball to EAS Build
运行打包命令：eas build --profile production --platform android

Reason: request to https://storage.googleapis.com/turtle-v2-projects/production/71788c78-cb85-46d9-a53b-a1000a1d3cc4/23b207c7-e154-49e0-864a-c69fe5b06d56?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=www-production%40exponentjs.iam.gserviceaccount.com%2F20230914%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230914T021043Z&X-Goog-Expires=3601&X-Goog-SignedHeaders=host%3Bx-goog-content-length-range&X-Goog-Signature=9c862aea1edd7c4dc6afbf2c391c888910610923be20ea47c265b39484fbbd727c8cf61927de59749ecb2fcf513eeb08dbc6ca18ecaba271f4d89385a4bc6278108ef9629920118785a1de9b2ec8f313a78e8a49b19ec90681f28905e4d9a9151ed79d17a11665896ee1ba692e3070bf5ef81e3c76d04de106eaae2eafffde8200affa93ac00529f14c5bbe1ea3caf6d29b886923a76912235f7d7d0bb4e1b9d94d9fb470cfcde4902d14a8d76d5dcd3624327b5350995fa1b183e41f91c0d25eb809afe3bcae16a09fd976bafe9115111becaca059a139be3bdb5d36e088587b0a16e17cfbe7e86d0d2a83562276a04d902fafb2a6cb054f3bee9e10f996444 failed, reason: read ECONNRESET
![image](https://github.com/reactnativecn/react-native-website/assets/93861958/a4b8f93e-ca05-4264-86f8-a13b9fa55f9e)

**Comment by sunnylqm** [comment]
代理默认并不自动代理终端，请自行搜索相关资料

**Comment by 3283615145** [comment]
好的，谢谢
