### ISSUE TITLE
npx react-native run-android 报错 卡在 info JS server already running. 不动了

### ISSUE THREAD

**Issue by taobobobo** [reactnativecn/react-native-website#751]
第一个项目正常启动了，然后新开了第二个项目，就在这一步不动了，都是按照官网文档走的

<img width="313" alt="20489629e76b76eff75732ec1670df4" src="https://github.com/reactnativecn/react-native-website/assets/48616295/40085f5f-d38b-42a7-914c-cfe804b780c8">
<img width="1182" alt="89bae58d1370d73b1f9505456c1e714" src="https://github.com/reactnativecn/react-native-website/assets/48616295/9d861a66-c39c-47ed-a635-597e414a9a11">

**Comment by sunnylqm** [comment]
jdk版本多少

**Comment by taobobobo** [comment]
java version "1.8.0_381"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reactnativecn/react-native-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月16日(星期六) 上午9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [reactnativecn/react-native-website] npx react-native run-android 报错 卡在 info JS server already running. 不动了 (Issue #751)





 
jdk版本多少

**Comment by taobobobo** [comment]
> jdk版本多少

java version "1.8.0_381"

**Comment by taobobobo** [comment]
> jdk版本多少

方便加一下联系方式吗  有偿解决吗   V: TAOBO--

**Comment by sunnylqm** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/615282/bb67f0e7-bc42-4810-9b07-5e6aec6450b1)

**Comment by Joonson-lau** [comment]
从入门到放弃吧... 学习成本太高了..我准备放弃了..
