### ISSUE TITLE
 大佬救命！！！按照官网文档，mac使用react-native 创建项目一直报错  `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle

### ISSUE THREAD

**Issue by wukongyang** [reactnativecn/react-native-website#753]
Mac M1系统
ruby 版本   2.6.10p210
pod版本      1.12.1
node版本    v18.16.0
gem版本  3.4.19
使用 npx react-native@latest init AwesomeProject 命令创建项目，一直报错如下，终端执行 pod 命令是可以执行的 

<img width="1439" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/54463146/26c13ed2-5036-46f6-9075-d843f130de74">

**Comment by wukongyang** [comment]
android 项目可以正常启动

**Comment by sunnylqm** [comment]
https://www.jianshu.com/p/fef4ce7d5fc8

**Comment by wukongyang** [comment]
> https://www.jianshu.com/p/fef4ce7d5fc8

`find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException) 权限问题没有报错了。 还有这个问题，大佬

**Comment by sunnylqm** [comment]
有个东西叫搜索引擎，你问我我也是去搜

**Comment by Entschuldigung** [comment]
ruby版本更新下试试
$ rvm install ruby-3.1.4 --with-openssl-dir='brew --prefix openssl'
$ rvm list
   ruby-2.7.6 [ arm64 ]
   ruby-2.7.8 [ arm64 ]
=* ruby-3.1.4 [ arm64 ]

**Comment by lemonkang** [comment]
这个是依赖问题，不用理他正常开发项目

**Comment by lemonkang** [comment]
<img width="607" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/53658981/35203310-7fac-426c-8d21-e52b5548b80b">
我在初始化项目也遇到这个问题
![image](https://github.com/reactnativecn/react-native-website/assets/53658981/8dde4411-b5eb-4145-8226-3b7f99f80436)

**Comment by wukongyang** [comment]
> 这个是依赖问题，不用理他正常开发项目

可是ios项目没法启动啊

**Comment by SongBana** [comment]
我也遇到了，不过不影响，重新启动，ios和android都可以运行

**Comment by chenwenfeng** [comment]
gem手动装一下试试

**Comment by z-coder-hub** [comment]
ruby和pod重新安装
