### ISSUE TITLE
安卓编译gardle的时候报这个错误

### ISSUE THREAD

**Issue by zhehuiTong** [reactnativecn/react-native-website#756]
请按以下格式提供问题的相关信息。

## 编译总是报这个错误 Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.6.10'] was not found in any of the following sources: 
<img width="1440" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/28799557/e3040ac8-ca35-4d0e-b392-f80bd1beb6e1">

**Comment by sunnylqm** [comment]
请按格式提问
