### ISSUE TITLE
react native中文网论坛原地址停止使用，欢迎朋友们继续在这里讨论交流

### ISSUE THREAD

**Issue by sunnylqm** [reactnativecn/react-native-website#76]
原react native中文网论坛 https://bbs.reactnative.cn 性能较差，中文搜索也不好用，我们即日起使用github issues来承载讨论功能。

原论坛会停止注册和发帖功能，继续运行到20年年中，而后会停止访问。我将原论坛中值得搬运的文章迁移到wiki中，也欢迎朋友们在评论中提名或自行搬运。

**Comment by peerlessheidi** [comment]
RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD这个方法为何官方文档上没有呢？现在使用这个同步方法时，在方法中接入一个其它模块功能入口A，在第一次进入页面没问题，连续进两次便会在接入的A这里闪退，EXC_BAD_ACCESS，试了各种方法报错会变化，一时不知如何解决了

**Comment by sunnylqm** [comment]
文档上既然没有，那应该就是不推荐使用了。什么场景需要同步方法呢？

**Comment by peerlessheidi** [comment]
> 文档上既然没有，那应该就是不推荐使用了。什么场景需要同步方法呢？

有一些业务需要，还有个问题，多个bundle加载的问题，网上最新的是2018年的方法：给RCTBridge添加一个category暴露bridge的私有方法executeSourceCode，但是行不通，现在都是怎么做的呢？

**Comment by sunnylqm** [comment]
https://github.com/facebook/react-native/commit/6f627f684bb6506a677c9632b2710e4a541690a9

**Comment by tao-2021** [comment]
在ios端的react native项目中使用调用RNCamera.takePictureAsync拍摄照片，并设置参数exif=true，为什么获取到的照片信息里没有照片的exif信息？我要怎么做才能获得呢？

**Comment by lishiyanlishiyan** [comment]
ios端相册中图片点击分享，选择rn应用，或者微信中的文件点击其他应用打开选择rn应用，应用没有调起来，出来一个空白弹窗
