### ISSUE TITLE
新版本怎么修改成功 maven 的镜像地址，公司 jenkins 环境不能翻墙

### ISSUE THREAD

**Issue by linxianxi** [reactnativecn/react-native-website#761]
按照这里修改，还是不行，我看新版本应该只有 build.gradle 需要改吧？
<img width="1114" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/47104575/156b6120-e4b7-4aa4-98ad-d6165e289ba2">

修改前：
<img width="803" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/47104575/dc4f6dac-3d02-4727-bcbe-8831cc6524b9">

修改后：
<img width="841" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/47104575/8e6e4e2d-6b0c-4e27-8962-8ae079d7e39d">

报错信息：
<img width="1217" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/47104575/450d06ac-c464-448a-9a4d-d8765350845b">

**Comment by sunnylqm** [comment]
搜了下，好像gradle-plugins里面也需要改，建议用patch-package处理下
https://juejin.cn/post/7233261440500908091

**Comment by sunnylqm** [comment]
参考这里有更合适的做法

https://github.com/scwang90/SmartRefreshLayout/issues/1376#issuecomment-938422964
