### ISSUE TITLE
Plugin [id: 'com.facebook.react'] 这个插件还是找不到

### ISSUE THREAD

**Issue by LyingDoc** [reactnativecn/react-native-website#763]
问题：
![图片](https://github.com/reactnativecn/react-native-website/assets/131896721/4796ce5c-4d1a-4846-b894-72d4b93fe5ec)

用的版本：
![图片](https://github.com/reactnativecn/react-native-website/assets/131896721/044ef0b2-048e-4189-85ba-116a6fb9e6ab)

用的版本是0.72.6还是存在这个问题，无法构建

**Comment by sunnylqm** [comment]
应该还是网络问题

**Comment by LyingDoc** [comment]
> 应该还是网络问题
我改了库的都是阿里云拉下来的，就偏偏这个这个插件，一直报找不到，我重构好几次还是那样
