### ISSUE TITLE
Execution failed for task ':react-native-async-storage_async-storage:extractReleaseAnnotations'.

### ISSUE THREAD

**Issue by cshggg** [reactnativecn/react-native-website#764]
请按以下格式提供问题的相关信息。

## 问题的具体描述
打包失败了，是否与@react-native-async-storage/async-storage依赖版本问题，还是Gradle的问题

<img width="715" alt="Snipaste_2023-10-25_11-40-40" src="https://github.com/reactnativecn/react-native-website/assets/62009273/2c0ea8c1-5dd6-405f-9238-36ab89f00b87">

## 完整的环境/版本信息

System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.16 GB / 7.90 GB
  Binaries:
    Node: 14.0.0 - C:\dev\nodejs\node.EXE
    Yarn: 1.22.19 - D:\node\node_global\yarn.CMD
    npm: 6.14.4 - C:\dev\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

packjson.js
![(V{X9XF( 8@VOA6TDB_6E D](https://github.com/reactnativecn/react-native-website/assets/62009273/3cbbd2ae-c4ce-4668-9e3d-fdc2a874dfec)
![image](https://github.com/reactnativecn/react-native-website/assets/62009273/d5d22310-77f7-4b10-9662-e5feb88c1ee3)

**Comment by sunnylqm** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/615282/ce0e2424-42cf-47ca-b03e-fc883797135c)
典型的翻墙问题

**Comment by cshggg** [comment]
需要翻墙才能解决吗?

**Comment by sunnylqm** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/615282/352806bb-3151-4985-a14d-1d4671951c73)

**Comment by cshggg** [comment]
翻墙了然后报如下的错
![image](https://github.com/reactnativecn/react-native-website/assets/62009273/30c53013-e096-4e1b-b094-acae83c30d41)

**Comment by sunnylqm** [comment]
还是一样的问题（有看到报错的网址吗？有看到Read timed out吗？），不是你说翻墙了就等于翻墙了，命令行，gradle可能都需要单独的代理配置，或者需要更底层的透明代理

**Comment by cshggg** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/62009273/d1ba5435-2c96-4b59-9b0b-a6873d8dd2a1)
加了代理就可以了,谢谢

**Comment by sunnylqm** [comment]
也可以尝试tun模式，这个从更底层接管系统代理
