### ISSUE TITLE
reactnative访问https报SSL_PROTOCOL_ERROR，用x5内核也是这种情况

### ISSUE THREAD

**Issue by 18523237715** [reactnativecn/react-native-website#765]
reactnative访问https报SSL_PROTOCOL_ERROR，用x5内核也是这种情况  有大佬遇到过同样的情况吗

**Comment by sunnylqm** [comment]
对方服务器有问题吧

**Comment by 18523237715** [comment]
用手机浏览器能正常访问，就是在RN里面无法加载， 
@Override
    public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) 
      handler.proceed();
    }
几乎csdn上面的操作都已经试过了 还是不行，所以想在github上看看有人是否遇到相同的情况
