### ISSUE TITLE
集成的iOS项目中，加载main.jsbundle，报错RNGestureHandlerModule.attachGestureHandler was called with 2 arguments but expects 3 arguments. 

### ISSUE THREAD

**Issue by li-qingnan** [reactnativecn/react-native-website#767]
集成的iOS项目中，加载main.jsbundle，报错RNGestureHandlerModule.attachGestureHandler was called with 2 arguments but expects 3 arguments. 
RNGestureHandler 版本为 2.9.0，不知道是和其他的那个依赖没有匹配上。
请问如何找到匹配的版本，解决这个冲突？
![IMG_0313](https://github.com/reactnativecn/react-native-website/assets/10277390/53402387-7dc2-40fb-8599-135607ade49c)

ios端使用的是这个方法加载的，
NSURL *url = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
self.rctRootView = [[RCTRootView alloc] initWithBundleURL:url moduleName:@"taroDemo" initialProperties:@{} launchOptions:nil];

react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.0
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 336.00 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.13.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.1.0
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.13.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 4.0 AI-193.6911.18.40.6514223
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by sunnylqm** [comment]
用`yarn why react-native-gesture-handler` 或者 `npm ls react-native-gesture-handler` 看下有哪个库依赖了不同版本的react-native-gesture-handler
