### ISSUE TITLE
yarn android后初始化进度不动

### ISSUE THREAD

**Issue by namett3** [reactnativecn/react-native-website#770]
请按以下格式提供问题的相关信息。

## 问题的具体描述
配置好环境后，执行yarn android出现以下情况, 初始化进度一直是0%
![image](https://github.com/reactnativecn/react-native-website/assets/57053242/e67dc9a6-0a27-4069-8fed-1336df23cb7d)

## 请描述完整的环境/版本信息
系统: win10
node版本: 16.20.1

## 预期结果
如何才能成功启动

**Comment by sunnylqm** [comment]
挂代理，等着

**Comment by namett3** [comment]
> 挂代理，等着

你说的挂代理是yarn config set proxy 代理地址 这种方式嘛

**Comment by sunnylqm** [comment]
yarn有淘宝源可用，不需要代理，maven需要配置走阿里云镜像或者设置全局代理等
