### ISSUE TITLE
安装启动时报错:error xcodebuild: error: Unable to read project 'AwesomeProject.xcodeproj'.

### ISSUE THREAD

**Issue by ujfjntevtee28230** [reactnativecn/react-native-website#771]
我按照[文档](https://reactnative.cn/docs/environment-setup)的提示安装了所有的依赖,但是依旧运行不了项目,请问这是什么原因?
<img width="1207" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/138725706/f08f96b9-435a-4616-89a9-0bbb37215715">

**Comment by ujfjntevtee28230** [comment]
这是Xcode 的配置
<img width="760" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/138725706/b77886c3-fcae-4aaa-9866-aa38deb7e677">

**Comment by sunnylqm** [comment]
pod没有初始化成功吧，请问提问模板提供相关环境信息

**Comment by wqjiao** [comment]
> 我按照[文档](https://reactnative.cn/docs/environment-setup)的提示安装了所有的依赖,但是依旧运行不了项目,请问这是什么原因? <img alt="image" width="1207" src="https://private-user-images.githubusercontent.com/138725706/283995332-f08f96b9-435a-4616-89a9-0bbb37215715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjEyMzMsIm5iZiI6MTcxMTk2MDkzMywicGF0aCI6Ii8xMzg3MjU3MDYvMjgzOTk1MzMyLWYwOGY5NmI5LTQzNWEtNDYxNi04OWE5LTBiYmIzNzIxNTcxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwODQyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWRiOTgwN2FmZjE1NDIxZTM2YzEyM2M3NDgxNWI1OWQzMGEwZDI0OWFiYTE5OWQxMzkwOWU4NGNlMmI5MjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9ZuPbcyfs3GhSpZb98wLq46L-F9_iQu17Yz6XMWKO7U">

你好，这个问题解决了不，我也出现一样的问题，明明pod install后已经提示成功了，运行却报错
