### ISSUE TITLE
React Native so 异常 libreactnativejni

### ISSUE THREAD

**Issue by liuyak** [reactnativecn/react-native-website#772]
11-21 11:19:10.816367  7371  3886 E DEBUG   :     #40 pc 000000000005e758  /data/app/~~BdZB-3GdW_87bQdFwdNm7Q==/com.xueqiu.android-FUYOBT-MeNmrZ_fJuuA8-A==/lib/arm64/[libreactnativejni.so](http://libreactnativejni.so/)

应用在使用过程中高频率闪退，OPPO Android 14.0 系统，ReactNative版本0.68.0

**Comment by sunnylqm** [comment]
信息太少了

**Comment by liuyak** [comment]
> 信息太少了

[根因分析.txt](https://github.com/reactnativecn/react-native-website/files/13471331/default.txt)

文件中是完整的堆栈信息，帮看看还缺什么嘛

**Comment by sunnylqm** [comment]
最起码，用到哪些库？崩溃是否高发于某个特定交互或者页面？是否有相应埋点？你丢这么几行过来，觉得分析问题是靠占卦的？
