### ISSUE TITLE
ios系统调不起rn应用

### ISSUE THREAD

**Issue by lishiyanlishiyan** [reactnativecn/react-native-website#774]
请按以下格式提供问题的相关信息。

## 问题的具体描述

ios端相册中图片点击分享，选择rn应用，或者微信中的文件点击其他应用打开选择rn应用，应用没有调起来，出来一个空白弹窗，应用名称叫VBox
![Simulator Screen Shot - iPhone 13 Pro Max - 2023-11-28 at 15 14 31](https://github.com/reactnativecn/react-native-website/assets/43063974/f76536d3-b76b-4674-b334-1ca80bde2f12)
## 请描述完整的环境/版本信息
rn0.66。iOS17

## 预期结果

分享时调起应用

**Comment by lishiyanlishiyan** [comment]
这是模拟器截图，ios版本是15，真机是17，都是只有这样的弹窗，应用调不起来，安卓上正常

**Comment by sunnylqm** [comment]
https://github.com/Expensify/react-native-share-menu

**Comment by lishiyanlishiyan** [comment]
> https://github.com/Expensify/react-native-share-menu
有用这个库，安卓正常的，可ios就起不来
