### ISSUE TITLE
React Native: No apps connectedSending 'reload' to all React Native apps failed. Makesure your app is running in the simulator or on aphone connected via USB.

### ISSUE THREAD

**Issue by niniinnini** [reactnativecn/react-native-website#777]

**Comment by sunnylqm** [comment]
请按提问模板提供信息

**Comment by niniinnini** [comment]
这个吗
![报错](https://github.com/reactnativecn/react-native-website/assets/153725248/62b4474f-e0a4-4bf0-bdf4-363dfaf8fa9e)

**Comment by niniinnini** [comment]
> 请按提问模板提供信息
这个吗
![报错](https://github.com/reactnativecn/react-native-website/assets/153725248/93056333-7e7a-4770-bfe9-d7d8ba916bec)

**Comment by sunnylqm** [comment]
重新提issue

**Comment by niniinnini** [comment]
> 重新提issue

可以帮忙远程操作一下吗
