### ISSUE TITLE
React Native: No apps connectedSending 'reload' to all React Native apps failed. Makesure your app is running in the simulator or on aphone connected via USB

### ISSUE THREAD

**Issue by niniinnini** [reactnativecn/react-native-website#778]
<img width="1891" alt="屏幕截图 2023-12-14 092921" src="https://github.com/reactnativecn/react-native-website/assets/153725248/e0142cc8-d3f5-41c1-9ae6-49006c20932b">

**Comment by sunnylqm** [comment]
metro报错了（node版本太高了）

**Comment by niniinnini** [comment]
> metro报错了（node版本太高了）

降node版本了，按r还是连接不到模拟器

**Comment by niniinnini** [comment]
> metro报错了（node版本太高了）

<img width="1894" alt="修改后" src="https://github.com/reactnativecn/react-native-website/assets/153725248/4bca6137-da32-4222-b28e-110f35d5f030">

**Comment by sunnylqm** [comment]
右侧编译都没跑完

**Comment by sunnylqm** [comment]
我说你到底能不能按模板来提供信息，一定要问一句答一句这样折腾下去吗
