### ISSUE TITLE
RN 0.71.6 使用FlatList 设置horizontal水平滚动，导致内部的点击事件失效(或者说只有点击很上面部分才会出现效果)

### ISSUE THREAD

**Issue by DingTianYi9** [reactnativecn/react-native-website#779]
IOS上表现正常，Android上出现这个问题，滚动是正常的。
![image](https://github.com/reactnativecn/react-native-website/assets/50064250/6cef3441-3938-4907-913a-a7a649702b98)

<FlatList
      ref={ref=>{
        setFirstFlatList(ref)
      }}
      showsHorizontalScrollIndicator={false}
      showsVerticalScrollIndicator={false}
      data={firstData}
      horizontal={true}
      ItemSeparatorComponent={() => <View />}
      bounces={false}
      bouncesZoom={false}
      keyExtractor={(item, index) => index.toString()}
      renderItem={(data) =>
        renderFirstListItem(data.item, data.index)
      }
      removeClippedSubviews={false}
    />

const renderFirstListItem = (item, index) => {
    const appImgSrcIcon = item?.category?.appImgSrc
      ? { uri: item.category.appImgSrc }
      : defaultCategoriesIcon
    return (
      <TouchableOpacity
        onPress={() => {
          setIsShowMore(false)
          setShowTreeCheck(false)
          setSelectIndex(0)
          onPressFirstCategoriesItem(item, index);
        }}
        style={{ marginLeft: 3, marginRight: 3}}
      >
        <View style={styles.categoryContainer}>
          <View
            style={
              firstCategorieSeleted === index
                ? [
                    styles.categoryItem,
                    {
                      width: 50,
                      height: 50,
                      borderRadius: 50,
                      borderColor: "#fff",
                      borderWidth: 2,
                    },
                  ]
                : styles.categoryItem
            }
          >
            <FastImage
              source={appImgSrcIcon}
              style={
                firstCategorieSeleted === index
                  ? [
                      styles.categoryIcon,
                      { width: 46, height: 46, borderRadius: 46 },
                    ]
                  : styles.categoryIcon
              }
              resizeMode="contain"
            />
          </View>
        </View>
        <View
          style={
            firstCategorieSeleted === index
              ? [
                  styles.listSecondCategoriesButtonStyle,
                  { backgroundColor: "#fff" },
                ]
              : [
                  styles.listSecondCategoriesButtonStyle,
                  { backgroundColor: "transparent" },
                ]
          }
        >
          <Text
            style={{
              color: firstCategorieSeleted === index ? "#00984A" : "#fff",
              backgroundColor: "transparent",
              fontSize: ScreenUtil.setSpText(12),
              fontWeight: "bold",
            }}
          >
            {item.category.name}
          </Text>
        </View>
      </TouchableOpacity>
    );
  }

**Comment by sunnylqm** [comment]
用inspector看下是不是被什么挡住了，而且你这个描述最好配个录屏吧
代码用markdown括起来，这根本看不清楚

**Comment by sunnylqm** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/615282/1eeebdf0-43e3-4b52-abb9-92c041b9049d)

**Comment by DingTianYi9** [comment]
实验发现给FlatList设置俩倍的高度就可以正常使用了
![image](https://github.com/reactnativecn/react-native-website/assets/50064250/34dba5ff-f3dd-450a-bbdf-7289006fec42)

**Comment by DingTianYi9** [comment]
> ![image](https://private-user-images.githubusercontent.com/615282/290388027-1eeebdf0-43e3-4b52-abb9-92c041b9049d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjM2MzYsIm5iZiI6MTcwMjUyMzMzNiwicGF0aCI6Ii82MTUyODIvMjkwMzg4MDI3LTFlZWViZGYwLTQzZTMtNGI1Mi1hYmI5LTkyYzA0MWI5MDQ5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwMzA4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDIxNTE0NTdjZGE3ZmQ1NGMxMWZiY2IxOWRkNWEwNTZiNzNhODAzMTZhZGI2ODg2Y2E3MzhlZDE5MzJhNjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KeQKYiKPZXKy9-1awZnNdr8VvhdX66_-UFKfbk4wV-Y)

```
<FlatList
            ref={ref=>{
              setFirstFlatList(ref)
            }}
            showsHorizontalScrollIndicator={false}
            showsVerticalScrollIndicator={false}
            data={firstData}
            horizontal={true}
            ItemSeparatorComponent={() => <View />}
            bounces={false}
            bouncesZoom={false}
            keyExtractor={(item, index) => index.toString()}
            renderItem={(data) =>
              renderFirstListItem(data.item, data.index)
            }
            removeClippedSubviews={false}
          />
```

**Comment by DingTianYi9** [comment]
```
const renderFirstListItem = (item, index) => {
    const appImgSrcIcon = item?.category?.appImgSrc
      ? { uri: item.category.appImgSrc }
      : defaultCategoriesIcon
    return (
      <TouchableOpacity
        onPress={() => {
          setIsShowMore(false)
          setShowTreeCheck(false)
          setSelectIndex(0)
          onPressFirstCategoriesItem(item, index);
        }}
        style={{ marginLeft: 3, marginRight: 3}}
      >
        <View style={styles.categoryContainer}>
          <View
            style={
              firstCategorieSeleted === index
                ? [
                    styles.categoryItem,
                    {
                      width: 50,
                      height: 50,
                      borderRadius: 50,
                      borderColor: "#fff",
                      borderWidth: 2,
                    },
                  ]
                : styles.categoryItem
            }
          >
            <FastImage
              source={appImgSrcIcon}
              style={
                firstCategorieSeleted === index
                  ? [
                      styles.categoryIcon,
                      { width: 46, height: 46, borderRadius: 46 },
                    ]
                  : styles.categoryIcon
              }
              resizeMode="contain"
            />
          </View>
        </View>
        <View
          style={
            firstCategorieSeleted === index
              ? [
                  styles.listSecondCategoriesButtonStyle,
                  { backgroundColor: "#fff" },
                ]
              : [
                  styles.listSecondCategoriesButtonStyle,
                  { backgroundColor: "transparent" },
                ]
          }
        >
          <Text
            style={{
              color: firstCategorieSeleted === index ? "#00984A" : "#fff",
              backgroundColor: "transparent",
              fontSize: ScreenUtil.setSpText(12),
              fontWeight: "bold",
            }}
          >
            {item.category.name}
          </Text>
        </View>
      </TouchableOpacity>
    );
  }
```

**Comment by DingTianYi9** [comment]
> 用inspector看下是不是被什么挡住了，而且你这个描述最好配个录屏吧 代码用markdown括起来，这根本看不清楚

好的 

https://github.com/reactnativecn/react-native-website/assets/50064250/bb63fa41-3ddb-4c6c-9c5c-602a30ea5532


https://github.com/reactnativecn/react-native-website/assets/50064250/f44d8d73-c4cf-41ca-a5df-132cd0880356

**Comment by sunnylqm** [comment]
用inspector看了吗

**Comment by DingTianYi9** [comment]
> inspector

好 我试试 之前没用过inspector

**Comment by DingTianYi9** [comment]
> 用inspector看了吗

太感谢了哥 目前找到原因了 是因为下面的largeList像是溢出了一块
![WechatIMG127](https://github.com/reactnativecn/react-native-website/assets/50064250/ef6a5f61-3a76-4f2a-bf30-a88a5e185d3e)

我测试了这个largeList，这个溢出像是这个组件自带的
![WechatIMG128](https://github.com/reactnativecn/react-native-website/assets/50064250/87723ee2-da93-4e75-833b-f6b33d5c93a1)

通过外部View 设置了overflow:'hidden'临时解决了这个问题，但至于为什么这个largeList会溢出 我还没找到结论
