### ISSUE TITLE
执行yarn android ，启动不起来

### ISSUE THREAD

**Issue by idealog** [reactnativecn/react-native-website#783]
请按以下格式提供问题的相关信息。

## 问题的具体描述

info Installing the app...
Downloading https://services.gradle.org/distributions/gradle-8.3-all.zip

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 400 Bad Request"

## 请描述完整的环境/版本信息

MAC环境

## 预期结果

怎么才能跑起来？

**Comment by sunnylqm** [comment]
翻墙问题

**Comment by p0ssword** [comment]
可以把gradle下载下来, 然后使用本地路径
![Snipaste_2023-12-28_10-33-05](https://github.com/reactnativecn/react-native-website/assets/113674320/b1899a4b-1d1e-4794-b8f5-bc02d1744ba4)

注意: `:`之前要使用转义符号, 即在前面加个反斜杠(\)

**Comment by sunnylqm** [comment]
> 可以把gradle下载下来, 然后使用本地路径 ![Snipaste_2023-12-28_10-33-05](https://private-user-images.githubusercontent.com/113674320/293125844-b1899a4b-1d1e-4794-b8f5-bc02d1744ba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzQ1OTgsIm5iZiI6MTcwMzczNDI5OCwicGF0aCI6Ii8xMTM2NzQzMjAvMjkzMTI1ODQ0LWIxODk5YTRiLTFkMWUtNDc5NC1iOGY1LWJjMDJkMTc0NGJhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwMzMxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2I1MTAyYzJlNDI5MjcyZTIxZjEyZjZjYzM0OWJjZWM1Mzg4MzcyZmZiNTk3NjU2MmYxNGU2MWU2MDlhOTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GxQT8rE7Ycu1nTB3xCaJkQnihXqY1wxdEXQzyz-_RsM)
> 
> 注意: `:`之前要使用转义符号, 即在前面加个反斜杠()

完全没必要，你直接放在同一个目录就完全不用考虑目录的斜杠问题了，

**Comment by sunnylqm** [comment]
而且他的是代理本身报错，即便你本地下载了gradle，继续往下跑，任何网络请求都会报错

**Comment by p0ssword** [comment]
> 而且他的是代理本身报错，即便你本地下载了gradle，继续往下跑，任何网络请求都会报错

才看到他用了代理, 代理都报错400了

**Comment by p0ssword** [comment]
感情啥报错也是没看的😂

**Comment by zhanglkx** [comment]
建议先看报错，再去 Google/百度，能解决 99% 的问题
