### ISSUE TITLE
Cannot start server in new window because no terminal app was specified.

### ISSUE THREAD

**Issue by news00** [reactnativecn/react-native-website#784]
yarn android 提示 
error Cannot start server in new window because no terminal app was specified.
error Command failed with exit code 1.

---

update by @sunnylqm :

已知的[bug](https://github.com/react-native-community/cli/pull/2236)，待官方发新版本修复

在此之前，请单独开个窗口运行npm run start

**Comment by zeng-ge-7** [comment]
你试一下用 npm run start代替yarn android

**Comment by xlleng1** [comment]
我也是报的一样的错。。。 npm run start这也不是编译运行Android的啊 有啥意义

**Comment by Qiujianwu** [comment]
我也是这个问题，没查到解决方式

**Comment by Sunrisies** [comment]
我也遇到这个问题了，可以在最新的网站上面使用上面提供的方法就可以直接运行起来
![image](https://github.com/reactnativecn/react-native-website/assets/103256281/dd6f4d28-acb6-4218-83b5-dcb64244803e)
![image](https://github.com/reactnativecn/react-native-website/assets/103256281/dcd6a9b7-22b9-4a26-aae3-9368555cbd3f)
![image](https://github.com/reactnativecn/react-native-website/assets/103256281/9b14472c-c7d8-41c2-b8c7-25905416ece5)

**Comment by sunnylqm** [comment]
已知的bug，待官方修复

在此之前，请单独开个窗口运行`npm run start`

**Comment by geniyangge** [comment]
搞了半天呜~呜~呜~

**Comment by HyrKG** [comment]
两种解决方案：
1. yarn start打开metro，然后按a运行。
2. yarn start打开metro，然后新开一个窗口运行yarn android

**Comment by coder-xiaomo** [comment]
related issue: https://github.com/react-native-community/cli/issues/2219

the bug was fixed in react native 0.73.4
