### ISSUE TITLE
react native  yarn iOS 报错 ......com.apple.compilers.llvm.clang.1_0.compiler

### ISSUE THREAD

**Issue by FTW-001** [reactnativecn/react-native-website#786]
请按以下格式提供问题的相关信息。

Mac 创建 react native -iOS项目 执行yarn ios时程序报错

** BUILD FAILED **
The following build commands failed:
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/rntest01-bjtjdksylmxlnjdzttsdrsdpdtlr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/Objects-normal/x86_64/event.o /Users/apple/rntest01/node_modules/react-native/ReactCommon/yoga/yoga/event/event.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/rntest01-bjtjdksylmxlnjdzttsdrsdpdtlr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/Objects-normal/x86_64/Yoga.o /Users/apple/rntest01/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## 请描述完整的环境/版本信息
System:
  OS: macOS 10.15.7
  CPU: (4) x64 Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
  Memory: 69.57 MB / 8.00 GB
  Shell:
    version: 5.7.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.3
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - iOS 14.4
      - DriverKit 20.2
      - macOS 11.1
      - tvOS 14.3
      - watchOS 7.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 12.4/12D4e
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.2
    path: /Users/apple/.rvm/rubies/ruby-2.7.2/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
## 预期结果
急！！！！！！！！！！！！！！！！

**Comment by sunnylqm** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/615282/24405cbe-1be1-484c-a929-0a599f363805)

**Comment by FTW-001** [comment]
老师，您好，
后来我进到ios文件夹下，删除了pods 重新pod install 后，返回上一级 执行yarn ios  xcode中提示错误如下：
![WechatIMG8](https://github.com/reactnativecn/react-native-website/assets/61999790/6c7bb472-de74-4bf5-bb9a-05aa4461147a)
![WechatIMG6](https://github.com/reactnativecn/react-native-website/assets/61999790/335f793b-7075-4bf6-ba03-5c81527b9e5c)

**Comment by sunnylqm** [comment]
xcode需要升级到14.1以上

**Comment by FTW-001** [comment]
好的 谢谢
