### ISSUE TITLE
救救孩子~为什么打包release.apk 生成的是官方的demo?

### ISSUE THREAD

**Issue by Ccc437647** [reactnativecn/react-native-website#790]
请问各位大佬们 我这个是 taro开发的rn项目
使用android studio  打包安卓apk文件  
打包debug.apk 是我开发的项目工程文件  这个没问题
但是打包出来的release.apk  是框架的demo文件(App.js)   救救了  这个咋整

![19](https://github.com/reactnativecn/react-native-website/assets/74176833/5f80db4f-72a3-49b1-b412-baff257946fa)

**Comment by Ccc437647** [comment]
![18](https://github.com/reactnativecn/react-native-website/assets/74176833/1482fd6d-ce2d-42e9-8a3f-7a67246b87b6)

**Comment by sunnylqm** [comment]
应该会有个额外的手动生成/打包js bundle文件的步骤
这个得找你项目的说明文档，或者相关负责人咨询
