### ISSUE TITLE
新建项目提示警告 

### ISSUE THREAD

**Issue by gongml123** [reactnativecn/react-native-website#792]
使用官方文档npx npx react-native@latest init AwesomeProject 新建项目后提示警告
 Console Warning
RCTBridge required dispatch sync to loadRCTAccessibilityManager, This may lead to deadlocks
node v18.19.0
npm 10.2.3
java openjdk 17.0.9 2023-10-17 LTS
macos 14

**Comment by sunnylqm** [comment]
正常

**Comment by sunnylqm** [comment]
0.73.4 修复
https://github.com/facebook/react-native/pull/42734
