### ISSUE TITLE
TouchableHighlight 文档缺少部分内容，需要更新

### ISSUE THREAD

**Issue by coder-xiaomo** [reactnativecn/react-native-website#794]
cndocs/touchablehighlight.md 这部分文档缺少部分内容，如下图右侧目录：

中文站：https://reactnative.cn/docs/touchablehighlight

<img width="1081" alt="dcc585aa386096188dd6819f78d3cfbe" src="https://github.com/reactnativecn/react-native-website/assets/16949192/462df7c1-39bb-40e3-85a3-c8bc09804f43">

英文源站：https://reactnative.dev/docs/touchablehighlight

<img width="1082" alt="e267361214b8cbe7b8d49b6456178eb3" src="https://github.com/reactnativecn/react-native-website/assets/16949192/942d8874-ca89-4351-8633-2ea5c3c2f731">

**Comment by sunnylqm** [comment]
已更新
