### ISSUE TITLE
对AsyncStorage的getItem方法进行封装后，在别的组件中调用时得到的值总是[Object object]

### ISSUE THREAD

**Issue by ryen-z** [reactnativecn/react-native-website#80]
RN版本为3.3
如果在图1的then函数中打印输出jsonValue的值，可以看到数据，但在别的组件调用这个方法时，返回的却是Object。我理解的then函数就是等待它前面的方法执行完毕，然后根据前面方法返回的值做操作，我查了半天资料认为就是then没处理好，但具体错在哪又不知

1-先上AsyncStorage代码:
![10000000](https://user-images.githubusercontent.com/61915544/76706430-5a509180-6722-11ea-8f12-9b9aaf5711e6.png)

2-在另一个组件中调用:
![20000000000000](https://user-images.githubusercontent.com/61915544/76706444-6dfbf800-6722-11ea-91bd-2b7070d1f80a.png)

3-调用后返回的结果:
![300000](https://user-images.githubusercontent.com/61915544/76706460-88ce6c80-6722-11ea-9ae8-680d62f7ee93.png)

**Comment by sunnylqm** [comment]
`async` logic() {
   const account = `await` DeviceStorage.get('name');
   const pwd = `await` DeviceStorage.get('pwd');
   // ...
}

另外rn版本3.3是什么鬼？

**Comment by ryen-z** [comment]
> `async`逻辑（）{
> const account = `await`DeviceStorage.get（'name'）;
> const pwd = `await`DeviceStorage.get（'pwd'）;
> // ...
> }
> 
> 另外rn版本3.3是什么鬼？

@sunnylqm 是这样啊 谢了。RN就是react native

**Comment by ryen-z** [comment]
@sunnylqm 是这样啊 谢了。rn就是react native

**Comment by sunnylqm** [comment]
我知道rn是react native， 3.3是什么？

**Comment by ryen-z** [comment]
@sunnylqm 是版本号

**Comment by sunnylqm** [comment]
@ryen-z 哪有这么个版本 https://reactnative.cn/versions/

**Comment by ryen-z** [comment]
@sunnylqm 看错了。是react navigation的版本。再请教一下，在这个then函数外,怎么才能取到pwd的值
DeviceStorage.get('pwd').then(pwd =>{
  console.log(pwd)
})

**Comment by sunnylqm** [comment]
@ryen-z 不能，只能then内使用，或await使用
