### ISSUE TITLE
0.72.11版本react native  安卓真机运行闪退  控制台没有任何报错，求助各位大佬！！！

### ISSUE THREAD

**Issue by WesleyNiu** [reactnativecn/react-native-website#802]
请按以下格式提供问题的相关信息。

##  使用最新版本的react native 0.73版本，运行官网的示例app，安卓真机运行出现闪退现象，控制台没有报错或者异常提示
  
运行adb logcat 得到如下的日志信息：

   03-02 18:57:01.855 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 1. reason:!mustComposite
   03-02 18:57:01.872 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 2. reason:!mustComposite
   03-02 18:57:01.889 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 3. reason:!mustComposite
   03-02 18:57:01.906 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 4. reason:!mustComposite
   03-02 18:57:01.922 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 5. reason:!mustComposite
   03-02 18:57:01.939 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 6. reason:!mustComposite
   03-02 18:57:01.956 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 7. reason:!mustComposite
   03-02 18:57:01.973 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 8. reason:!mustComposite
   03-02 18:57:01.989 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 9. reason:!mustComposite
   03-02 18:57:02.006 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 10. reason:!mustComposite
   03-02 18:57:02.023 E/SurfaceFlinger( 1117): checkContinuousFrameMiss ADD 11. reason:!mustComposite
   03-02 18:57:02.023 E/SurfaceFlinger( 1117): continuous frame pending.

## jdk版本是 jdk17，SDK版本为33，Android Studio 官网最新客户端2023.3.1 

- [
![微信截图_20240302200458](https://github.com/reactnativecn/react-native-website/assets/95832918/461c4550-2186-4b18-a50e-a3a296f814df)
](url)
[
![微信截图_20240302200533](https://github.com/reactnativecn/react-native-website/assets/95832918/8533dbc9-6f1a-41a3-ba94-7046a8fd5b5f)
](url)
## 控制台没有任何报错 也没有warring提示
[
![微信截图_20240302200906](https://github.com/reactnativecn/react-native-website/assets/95832918/80401ffe-5cf6-4f10-854d-eadc4f64d469)
](url)

**Comment by sunnylqm** [comment]
logcat没有抓到报错的部分，建议用as运行，然后用as自带的logcat面板查看
