### ISSUE TITLE
0.73版本的RN，8081端口被McAfee占用，0.73版本的RN有修改Metro 默认端口的方法吗？网上的local-cli那个方法不适用了

### ISSUE THREAD

**Issue by gfisrubbish** [reactnativecn/react-native-website#808]
0.73版本的RN，8081端口被McAfee占用，0.73版本的RN有修改Metro 默认端口的方法吗？网上的local-cli那个方法不适用了，
现在yarn android 之后就红屏显示
unable to load script，make sure ....

**Comment by sunnylqm** [comment]
[`npm start -- --port=8088` 或者 `yarn start --port 8088`](https://reactnative.dev/docs/troubleshooting?package-manager=yarn#using-a-port-other-than-8081)

**Comment by LYS-png** [comment]
请问最后解决了吗
