### ISSUE TITLE
react-native自定义的一个组件内部部分内容onPress无效

### ISSUE THREAD

**Issue by chenxiaoleizi** [reactnativecn/react-native-website#81]
自己写了一个下拉组件。
![Screenshot_2020-03-17-13-52-32-954_com awesomepro](https://user-images.githubusercontent.com/24647177/76826562-c680e180-6857-11ea-8c54-c215f3c71346.png)
### 问题
组件的头部是已选择的option，添加了点击事件可以正常触发，下部的options采用的是`position:"absolute"`定位，但是列表添加的点击事件没有反应。
### 我的解决方法(有些奇怪)
如果设置组件的整体高度`height`增加到能够容纳options的高度，则option的点击事件才可以正常出发。
所以一个组件内的onPress事件必须是组件内的元素在组件的宽高区域范围内才能触发吗？

**Comment by sunnylqm** [comment]
对的，安卓目前有这个问题，超出父组件的子组件能够显示但是不能响应点击（在0.57之前连显示都不能）

**Comment by chenxiaoleizi** [comment]
> 
> 
> 对的，安卓目前有这个问题，超出父组件的子组件能够显示但是不能响应点击

有解决办法吗，这个问题会给页面布局造成很多限制。
