### ISSUE TITLE
Xcode15.2与react-native0.72.7版本是不是有冲突

### ISSUE THREAD

**Issue by lizhaoyang140901** [reactnativecn/react-native-website#812]
请按以下格式提供问题的相关信息。

## 问题的具体描述
在本地使用Xcode安装0.72.7版本react-native的app，正常启动，没有问题。但是打包之后，使用TestFlight安装下载后，首次打开100%崩溃。及时卸载后，再此从TestFlight上下载，首次打开还是会崩溃。

## 请描述完整的环境/版本信息
只在ios环境有这个问题，各种型号的ios手机都有问题。Xcode版本15.2，React-Native版本0.72.7。及时是清空缓存数据，再从testFlight上下载，首次打开还是会崩溃。

## 预期结果
不确定是不是react-native大版本升级导致的问题，希望达成的结果就是，首次安装不报错。

**Comment by sunnylqm** [comment]
用xcode改release schema运行看看具体报错

**Comment by lizhaoyang140901** [comment]
> 用xcode改release schema运行看看具体报错
release模式不是更看不到报错吗？release模式怎么看具体报错。
一打开就直接崩溃啦，等再次打开就没事啦。

**Comment by lizhaoyang140901** [comment]
![WechatIMG1470](https://github.com/reactnativecn/react-native-website/assets/61455726/3c903db5-e630-4e01-b4b6-3203c3a98524)
一打开就直接崩溃啦，页面也关啦，看不到报错。

**Comment by sunnylqm** [comment]
xcode里会有输出的，

提问模板里也有提到控制台方式，不需要xcode

https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a

**Comment by sunnylqm** [comment]
或者集成sentry之类的服务，自动上报

**Comment by lizhaoyang140901** [comment]
> xcode里会有输出的，
> 
> 提问模板里也有提到控制台方式，不需要xcode
> 
> https://juejin.im/post/5e7c5c8ce51d455c0e12dd7a

好的，我去试试，感谢。
