### ISSUE TITLE
yarn android 编译失败 

### ISSUE THREAD

**Issue by 17539351829** [reactnativecn/react-native-website#813]
![7eaab5ad55365f4f9629bcc2d10c807](https://github.com/reactnativecn/react-native-website/assets/68831786/4a96c2c7-7207-473d-a2e3-d3f6d0e04cb2)

**Comment by Tansir0317** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/103058940/726e0aec-3147-47d2-a953-1e3e98129417)

**Comment by 17539351829** [comment]
上周已经下载运行成功过了 没有使用代理软件 今天在跑一下就这样了

**Comment by RedTomatoCat** [comment]
检查下你的配置环境，看看环境配置是否完整
npx react-native info
