### ISSUE TITLE
初次启动慢

### ISSUE THREAD

**Issue by wumo1016** [reactnativecn/react-native-website#817]
## 使用react -native-cli 创建的项目初次启动很慢 是什么原因
![image](https://github.com/reactnativecn/react-native-website/assets/47590453/3aa23bc5-265f-4480-8600-62fe5276377c)

## 请描述完整的环境/版本信息

System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
  Memory: 4.22 GB / 15.79 GB
Binaries:
  Node:
    version: 20.11.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 33.0.0
      - 34.0.0
    System Images:
      - android-33 | Intel x86_64 Atom
      - android-34 | Intel x86_64 Atom
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

## 预期结果
启动快一些

**Comment by sunnylqm** [comment]
你截图的部分是还在下载编译的依赖，下载完了还要编译，编译完了还有安装，安装完了才是启动
