### ISSUE TITLE
第一次搭建RN项目执行npm run android报错

### ISSUE THREAD

**Issue by LiYuanshen20** [reactnativecn/react-native-website#819]
![屏幕截图 2024-03-27 145848](https://github.com/reactnativecn/react-native-website/assets/73769342/97f6c0fb-9e41-4a30-9deb-159cc6b99a10)

![屏幕截图 2024-03-27 150042](https://github.com/reactnativecn/react-native-website/assets/73769342/1fc26ec6-9d4f-4ccb-b39e-65e904b87232)
![屏幕截图 2024-03-27 150055](https://github.com/reactnativecn/react-native-website/assets/73769342/ff17fb68-a457-4ae3-a8c9-7c9c81ae4153)
请问这个问题怎么解决，第一个问题说找不到java_home，但我已经在环境变量中配置了，第二个问题也没看懂

**Comment by sunnylqm** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/615282/5f89995b-e313-454b-a730-67da1a2ed1a4)
重点是上面这句，你设置了，但设置的路径不对，jre和jdk是不同的概念（应该指向jdk而不是jre）

**Comment by wh-hujinyun** [comment]
请问最后解决了吗?
