### ISSUE TITLE
使用 yarn android 报错，在issues中未找到同类，特此请教一下

### ISSUE THREAD

**Issue by chenJJ-88** [reactnativecn/react-native-website#827]
![image](https://github.com/reactnativecn/react-native-website/assets/118970817/9146dd1d-510b-4b41-b214-76216a4905c7)
这是baocuo报错的信息，请大佬指教

**Comment by chenJJ-88** [comment]
文档中的配置
![image](https://github.com/reactnativecn/react-native-website/assets/118970817/27ef4696-37d7-4225-8492-0386fbaaa965)
但是我看我下载的文件中没有tools，请问一下就是
![image](https://github.com/reactnativecn/react-native-website/assets/118970817/e30e9a65-3539-454e-a424-39bb6d64fc57)
这个吗

**Comment by sunnylqm** [comment]
打开android studio先创建一个模拟器

**Comment by chenJJ-88** [comment]
> 打开android studio先创建一个模拟器

今天没得那个问题了，请问一下这个是好了吗
![image](https://github.com/reactnativecn/react-native-website/assets/118970817/640d4e11-1218-4551-89ad-5c3aad4e4f06)
但是模拟器上什么都看不到
![image](https://github.com/reactnativecn/react-native-website/assets/118970817/2bd6b35e-4fd1-480d-a376-728c2744916d)
