### ISSUE TITLE
react-native doctor检测不到 Android Studio: android studio not found

### ISSUE THREAD

**Issue by 15240021857** [reactnativecn/react-native-website#829]
请按以下格式提供问题的相关信息。

## 问题的具体描述
本机已经装了Android Studio和VScode,
npx react-native doctor 检测不到
npx react-native info也检测不到,说没有...
![doctor](https://github.com/reactnativecn/react-native-website/assets/29224941/ff2fc5a8-7305-4059-823c-ca7ac0bff041)

## 请描述完整的环境/版本信息

![rninfo](https://github.com/reactnativecn/react-native-website/assets/29224941/6aff60f7-473d-4224-99b2-993127d0cfa3)

## 预期结果
应该能检测到本机装了Android Studio

**Comment by sunnylqm** [comment]
doctor不准确，也不重要，仅供参考

**Comment by Redjuice** [comment]
我这边重新安装到默认目录解决了
