### ISSUE TITLE
react-navigation 得createBottomTabNavigator配置tabBarIcon报错

### ISSUE THREAD

**Issue by chenxiaoleizi** [reactnativecn/react-native-website#83]
创建底部的tab栏时，为其配置图标，使用tabBarIcon这个属性，代码如下
![20200318113725](https://user-images.githubusercontent.com/24647177/76923086-6cdaee80-690d-11ea-9361-199528cf341f.png)

tabBarIcon部分是从react-navigation得官网拿得，报错如下
![Screenshot_2020-03-18-11-38-28-172_com awesomepro](https://user-images.githubusercontent.com/24647177/76922992-2eddca80-690d-11ea-9444-81eb63e18a24.png)

**Comment by sunnylqm** [comment]
Image有import吗

**Comment by chenxiaoleizi** [comment]
> 
> 
> Image有import吗

引了，我试过如果不引image得话会报找不到image变量的错误，跟上面的错误不一样。如果上面的函数返回true,false和null就不会报错，但页面也没有任何反应。

**Comment by chenxiaoleizi** [comment]
> 
> 
> Image有import吗

![QQ截图20200319095805](https://user-images.githubusercontent.com/24647177/77023946-2e563a00-69c8-11ea-958c-43f75d047f08.png)
我将Image包装在一个自定义的组件里，再import这个自定义组件TabBarIcon,然后就可以正常运行了，不明白为什么
