### ISSUE TITLE
按照官方一步步走使用rn的run-Android打开模拟器的时候失败，但是Android打开应用问题没有问题

### ISSUE THREAD

**Issue by Crane1043778796** [reactnativecn/react-native-website#836]
请按以下格式提供问题的相关信息。

## 问题的具体描述

- 如果是安装过程中的问题，请再三确认你有使用稳定的代理工具，且代理工具对命令行有生效（如开启全局模式等等）
- 请说明具体操作步骤和现象（例如执行什么命令，或者点击哪里，出现了什么异常现象或错误信息）
- 顺序下来的截图
![image](https://github.com/reactnativecn/react-native-website/assets/63647975/713847ac-7db1-44a8-9846-0b9c5907fc83)
![image](https://github.com/reactnativecn/react-native-website/assets/63647975/62aeb443-22c1-4234-b0ab-c3a716f92ed8)
![image](https://github.com/reactnativecn/react-native-website/assets/63647975/e06f137a-308e-4b2d-922d-bb533ba87d62)

## 请描述完整的环境/版本信息
命令行环境变量已经按照官网文档设置为jdk17
![image](https://github.com/reactnativecn/react-native-website/assets/63647975/1a65a9ce-f3f0-403c-b5ae-69815b24319b)

Androidstudio的gradle jdk设置为17
![image](https://github.com/reactnativecn/react-native-website/assets/63647975/e0b348e3-5d17-418a-97eb-dfef1137d7d1)

安卓模拟器是推荐的33版本，以及安装必要的platform和镜像
![image](https://github.com/reactnativecn/react-native-website/assets/63647975/c18f470e-fb12-48b4-86f9-275bf3abd48d)

## 预期结果
按照文档那样，正常唤醒我的Androidstudio模拟机

**Comment by Crane1043778796** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/63647975/f05c6f33-e8fb-4772-b253-c1f41b877b0f)
执行npx react-native info后被告知缺少了许多东西 麻烦请告知是哪里的问题

**Comment by sunnylqm** [comment]
这个报错仍然是jdk版本不对

**Comment by sunnylqm** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/615282/bec21962-a1ad-432b-9e8a-403a31c14f55)

**Comment by sunnylqm** [comment]
也请注意区分jre和jdk，你截图中是jre

**Comment by Crane1043778796** [comment]
![image](https://github.com/reactnativecn/react-native-website/assets/63647975/00516683-51dd-4d19-bcad-eb27b61a7e5d)


> 这个报错仍然是jdk版本不对

**Comment by Crane1043778796** [comment]
> 也请注意区分jre和jdk，你截图中是jre
哪一步，是这一步要改成jdk吗
![image](https://github.com/reactnativecn/react-native-website/assets/63647975/7c9590dc-6018-4656-93b9-3a99e9aed800)

**Comment by hdjhdjhdj** [comment]
最后解决了吗
