### ISSUE TITLE
RN0.61.5 & Xcode15.0 Build Project.app not found 

### ISSUE THREAD

**Issue by survivorsfyh** [reactnativecn/react-native-website#837]
RN0.61.5 & Xcode15.0 Build Project.app not found 
ld: warning: ignoring duplicate libraries: '-lc++'
ld: library '/Users/fyhsurvivors/Library/Developer/Xcode/DerivedData/skill_assessment-bhpnftwsdnwmixgaunwfdqjvijse/Build/Products/Debug-iphoneos/skill_assessment.app/skill_assessment' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## 问题的具体描述

Xcode 升级直15.0之前项目 run & build 都 OK
升级后抛出了如上异常
其过程中有尝试重新删除 node_modules 架包和 package-lock 配置文件,也重新对 pod install;
但均无效未果 ...

Build error image:
![20240521181049](https://github.com/reactnativecn/react-native-website/assets/15962850/adb38630-f505-4bac-a4cb-d2c2041cbe54)

Run error image:
![Simulator Screenshot - iPad Pro (12 9-inch) (2nd generation) - 2024-05-20 at 17 31 35](https://github.com/reactnativecn/react-native-website/assets/15962850/8e691208-9811-4dc7-babd-7880e79a363a)

具体版本配置相关如下
info Fetching system and libraries information...
System:
    OS: macOS 14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 221.67 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 12.20.2 - ~/.nvm/versions/node/v12.20.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.20.2/bin/npm
    Watchman: 2023.07.10.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 30.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

Xcode version: 15.0;
ReactNative:
"dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/viewpager": "^4.0.0",
    "@react-navigation/bottom-tabs": "^5.1.1",
    "@react-navigation/drawer": "^5.1.1",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",
    "@types/react-dom": "^16.9.6",
    "@yz1311/react-native-signature-pad": "^0.1.5",
    "decimal.js": "^10.3.1",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-actionsheet": "^2.4.2",
    "react-native-easy-grid": "^0.2.2",
    "react-native-easy-table": "^1.0.2",
    "react-native-elements": "^1.2.7",
    "react-native-fit-image": "^1.5.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-image-picker": "^2.3.3",
    "react-native-keyboard-manager": "^4.0.13-16",
    "react-native-photo-browser": "^0.6.0",
    "react-native-render-html": "^4.2.3",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.2.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-table-component": "^1.2.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^8.1.2",
    "rn-fetch-blob": "^0.12.0",
    "rxjs": "latest",
    "rxjs-hooks": "^0.6.2",
    "teaset": "^0.7.4"
  },
  "devDependencies": {
    "@babel/core": "^7.8.7",
    "@babel/runtime": "^7.8.7",
    "@react-native-community/eslint-config": "^0.0.7",
    "babel-jest": "^25.1.0",
    "babel-plugin-import": "^1.13.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^6.8.0",
    "eslint-plugin-react-hooks": "^1.7.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.56.4",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }

Help ~ thank u !

**Comment by sunnylqm** [comment]
基本上老版本支持都很困难，建议升级rn
