### ISSUE TITLE
按照官方文档搭建开发环境，编译应用的时候一直报错

### ISSUE THREAD

**Issue by YiwenOne** [reactnativecn/react-native-website#838]
## 问题的具体描述

BUILD FAILED in 2s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: A problem occurred configuring root project 'AwesomeProject'. > Could not determine the dependencies of null. > Could not resolve all dependencies for configuration ':classpath'. > The new Java toolchain feature cannot be used at the project level in combination with source and/or target compatibility * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 2s.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sunnylqm** [comment]
jdk版本不对

**Comment by wh-hujinyun** [comment]
请问最后解决了吗?

**Comment by hdjhdjhdj** [comment]
最后怎么解决了啊

**Comment by Jidahan** [comment]
我也是一样的问题

**Comment by Jidahan** [comment]
> 最后怎么解决了啊

解决了吗

**Comment by sunnylqm** [comment]
JDK版本不对，就对着文档弄成文档需要的JDK版本

**Comment by Jidahan** [comment]
> 我也是一样的问题

目前已经解决，使用android studio打开项目，等他自己安装，爆红后点击控制台左边得刷新按钮【reload gradle project】失败了再多点几次，然后就好了

**Comment by Jidahan** [comment]
> > 我也是一样的问题
> 
> 目前已经解决，使用android studio打开项目，等他自己安装，爆红后点击控制台左边得刷新按钮【reload gradle project】失败了再多点几次，然后就好了

![微信截图_20240726144013](https://github.com/user-attachments/assets/e9b19e40-c23e-4883-8e32-44735fa40cec)

**Comment by hdjhdjhdj** [comment]
> > > 我也是一样的问题
> > 
> > 
> > 目前已经解决，使用android studio打开项目，等他自己安装，爆红后点击控制台左边得刷新按钮【reload gradle project】失败了再多点几次，然后就好了
> 
> ![微信截图_20240726144013](https://private-user-images.githubusercontent.com/32761059/352414241-e9b19e40-c23e-4883-8e32-44735fa40cec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNDI1NjYsIm5iZiI6MTcyMjA0MjI2NiwicGF0aCI6Ii8zMjc2MTA1OS8zNTI0MTQyNDEtZTliMTllNDAtYzIzZS00ODgzLThlMzItNDQ3MzVmYTQwY2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDAxMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYmE1NDZhMWE3YjVjNTA2ZWQ4MmE3MDZhYTA2OTI1NGFmMjM4ZWE4MmYyY2UwMmY4MzhiMDYzYjhhODBmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aGpujGPD0jf5jV0x6BzuRyPmSTcER3NbcCFUVRHM_zw)

感谢，我解决了。
原来我用官方文档，直接cmd命令npx react-native run-android打开，可能代理不稳定，容易超时，导致出错
直接用android studio打开项目，这边超时可以重新再安装，会好一点，多重试几次。我装了2个多小时才装好
