### ISSUE TITLE
相机录像问题

### ISSUE THREAD

**Issue by ZemJun** [reactnativecn/react-native-website#842]
利用第三方库添加了一个简单的相机调用功能，可以实现拍照，但在录像的时候，点击结束录制时总会闪退，有没有人遇到过类似的问题，如何解决的？

**Comment by sunnylqm** [comment]
你一不说这个库是啥，二不说具体报错是啥，三没有任何相关环境、版本信息，你打这么多字还不如只打个问号省流量呢？

**Comment by ZemJun** [comment]
不好意思，这里补充一下
库是react-native-image-picker，报错没有任何显示，直接就闪退
rn版本是0.73，利用安卓模拟器运行的
调用handleCamera打开相机
