### ISSUE TITLE
RN 0.70.0版本 需要 Ruby2.7.5，但是总是安装失败。

### ISSUE THREAD

**Issue by GentleCai-CH** [reactnativecn/react-native-website#846]
使用RN 0.70.0版本的 JavaScript模板创建项目，

报错： error Your Ruby version is 3.3.2, but your Gemfile specified 2.7.5 error

安装Ruby2.7.5，但是总是安装失败。
或者安装过程出错，但是会有 2.7.5版本，创建项目还是失败

**Comment by GentleCai-CH** [comment]
折腾了各个方法，还是没用。望求救

**Comment by sunnylqm** [comment]
为啥要指定0.70版本，直接上最新版不行吗

**Comment by GentleCai-CH** [comment]
> 为啥要指定0.70版本，直接上最新版不行吗

因为想使用 JavaScript模板，不想使用最新版typescript模板

**Comment by sunnylqm** [comment]
不影响，模板只有一个文件，直接删掉app.tsx新建个app.js就完事了

**Comment by GentleCai-CH** [comment]
> 不影响，模板只有一个文件，直接删掉app.tsx新建个app.js就完事了

好的，感谢

**Comment by GentleCai-CH** [comment]
> 不影响，模板只有一个文件，直接删掉app.tsx新建个app.js就完事了

1、https://blog.csdn.net/weixin_46449236/article/details/137611646

2、删掉app.tsx，新建app.js，安装、配置react-native-tab-navigator后，报错：
请问是否是  react-native-tab-navigator是typescript版本的原因？

<img width="341" alt="image" src="https://github.com/reactnativecn/react-native-website/assets/38824702/0b82fb5e-8fb8-441c-a8e6-a28789871cd2">

**Comment by sunnylqm** [comment]
ts在语言层面不会有任何影响，rn会直接去掉ts中的任何类型相关特性，当做普通js来执行。所以在任何情况下其实都应该优先选择ts编写的库，哪怕你自己不使用任何ts特性，它也可以帮助你实现更好的自动提示和补完，而并没有任何坏处。更正式的项目其实都应该强制全面使用ts，类型检查是非常非常重要的质量控制手段。

上面的报错是因为这个库太老了，使用了已经废弃的PropTypes，
类似这种老库不兼容的问题，基本是三种选择：
1、查看老库是否有更新的版本
2、是否有其他可以替代使用的库
3、自己分叉原库，自己打补丁
具体到你这个例子，tab导航功能已经整合到目前使用最广泛的react-navigation库中，并不需要单独安装一个已经废弃的库了

**Comment by GentleCai-CH** [comment]
> ts在语言层面不会有任何影响，rn会直接去掉ts中的任何类型相关特性，当做普通js来执行。所以在任何情况下其实都应该优先选择ts编写的库，哪怕你自己不使用任何ts特性，它也可以帮助你实现更好的自动提示和补完，而并没有任何坏处。更正式的项目其实都应该强制全面使用ts，类型检查是非常非常重要的质量控制手段。
> 
> 上面的报错是因为这个库太老了，使用了已经废弃的PropTypes， 类似这种老库不兼容的问题，基本是三种选择： 1、查看老库是否有更新的版本 2、是否有其他可以替代使用的库 3、自己分叉原库，自己打补丁 具体到你这个例子，tab导航功能已经整合到目前使用最广泛的react-navigation库中，并不需要单独安装一个已经废弃的库了

好的，那我就用官方的bottom-tab了。十分感谢。
