### ISSUE TITLE
根据官网安装的环境无法调试应用

### ISSUE THREAD

**Issue by Mrxiaozha** [reactnativecn/react-native-website#850]
RN配置:

PS C:\Users\admin> npm list react-native
admin@ C:\Users\admin
`-- react-native-webview@13.10.4
  `-- react-native@0.74.2
    `-- @react-native/virtualized-lists@0.74.84
      `-- react-native@0.74.2 deduped

PS C:\Users\admin> yarn list react-native
yarn list v1.22.22
warning package.json: No license field
error No lockfile in this directory. Run `yarn install` to generate one.
info Visit https://yarnpkg.com/en/docs/cli/list for documentation about this command.
PS C:\Users\admin>

AS版本2024
node版本20.15.0
根据官网设置了环境变量,但是SDK里面没有 [tools] 目录
但是Debug android 报错:
Launching the application
An error occurred while launching the application. 执行命令 d:\ADMIN\Project\AwesomeProject\node_modules\.bin\react-native.cmd run-android --no-packager 时出错 (error code 101) (error code 303)

环境配置图片:
![SDK](https://github.com/reactnativecn/react-native-website/assets/86549951/aba7542e-7621-412e-9a95-bc5417aaae61)

![调试配置文件以及报错](https://github.com/reactnativecn/react-native-website/assets/86549951/102517a1-e1b1-4528-ae88-70e885910413)

![环境变量与,目录](https://github.com/reactnativecn/react-native-website/assets/86549951/c93035cf-409e-441c-a5e0-6f9daf0ee4af)

**Comment by sunnylqm** [comment]
感谢提醒，最新的sdk中这两个目录已不再需要，已对文档做了更新
至于vscode中调试的问题，应该与这里无关，建议去vscode的插件仓库中讨论，我本人并不使用这种方式，不太清楚具体问题

**Comment by Mrxiaozha** [comment]
好的,谢谢哥
