### ISSUE TITLE
yarn ios报错

### ISSUE THREAD

**Issue by GentleCai-CH** [reactnativecn/react-native-website#855]
yarn iOS时出现以下报错：

The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/xxx/Library/Developer/Xcode/DerivedData/myproject-gaccclzajgvabygqzjlwgoypbadr/Build/Intermediates.noindex/myproject.build/Debug-iphonesimulator/myproject.build/Script-00EEFC60759A1932668264C0.sh (in target 'myproject' from project 'myproject')
(1 failure)

**Comment by sunnylqm** [comment]
![image](https://github.com/user-attachments/assets/964b7b73-f48a-40a2-aa1b-2d8beb5c3f5e)

**Comment by GentleCai-CH** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你所发送的邮件我已收到，待查阅后必要时我会回复。请耐心等待。

**Comment by GentleCai-CH** [comment]
...

**Comment by GentleCai-CH** [comment]
.....

**Comment by icy-goodlike** [comment]
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:5BA57188-7706-4F62-A08E-0AEFDB49ECCD, OS:18.2, name:iPhone 16 Pro }
{ platform:iOS Simulator, id:5BA57188-7706-4F62-A08E-0AEFDB49ECCD, OS:18.2, name:iPhone 16 Pro }
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/icy/Library/Developer/Xcode/DerivedData/qingtianPro-dvpwqfgrrixbkqatigbmmcrcdbsh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperURLSerializer.o /Users/icy/code/qingtianPro/ios/Pods/Flipper/xplat/Flipper/FlipperURLSerializer.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Flipper' from project 'Pods')
        CompileC /Users/icy/Library/Developer/Xcode/DerivedData/qingtianPro-dvpwqfgrrixbkqatigbmmcrcdbsh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperSocketProvider.o /Users/icy/code/qingtianPro/ios/Pods/Flipper/xplat/Flipper/FlipperSocketProvider.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Flipper' from project 'Pods')
        CompileC /Users/icy/Library/Developer/Xcode/DerivedData/qingtianPro-dvpwqfgrrixbkqatigbmmcrcdbsh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperConnectionManagerImpl.o /Users/icy/code/qingtianPro/ios/Pods/Flipper/xplat/Flipper/FlipperConnectionManagerImpl.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Flipper' from project 'Pods')
        CompileC /Users/icy/Library/Developer/Xcode/DerivedData/qingtianPro-dvpwqfgrrixbkqatigbmmcrcdbsh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/FlipperClient.o /Users/icy/code/qingtianPro/ios/Pods/Flipper/xplat/Flipper/FlipperClient.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Flipper' from project 'Pods')
        CompileC /Users/icy/Library/Developer/Xcode/DerivedData/qingtianPro-dvpwqfgrrixbkqatigbmmcrcdbsh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper.build/Objects-normal/x86_64/ConnectionContextStore.o /Users/icy/code/qingtianPro/ios/Pods/Flipper/xplat/Flipper/ConnectionContextStore.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Flipper' from project 'Pods')
        Ld /Users/icy/Library/Developer/Xcode/DerivedData/qingtianPro-dvpwqfgrrixbkqatigbmmcrcdbsh/Build/Products/Debug-iphonesimulator/qingtianPro.app/qingtianPro.debug.dylib normal (in target 'qingtianPro' from project 'qingtianPro')
        Building workspace qingtianPro with scheme qingtianProDev and configuration Debug
(7 failures)

error Command failed with exit code 1.
我依赖都装了，doctor检查也没问题，yarn ios的时候还是会报上面的错，为什么？
