### ISSUE TITLE
我想知道 最新的创建App 推荐哪种方式 是沙盒环境还是原生环境

### ISSUE THREAD

**Issue by wubaibin** [reactnativecn/react-native-website#862]
## 最新的创建App 推荐哪种方式

现在官方文档是这样的了
<img width="2023" alt="image" src="https://github.com/user-attachments/assets/eddb76e4-0634-4e41-aae5-2cb340d22b50">
<img width="2232" alt="image" src="https://github.com/user-attachments/assets/3ef39717-beed-462f-881a-6a5cf3c5c85d">
没有关于原生环境的配置了只有沙盒环境的配置

运行 npx react-native@latest init AwesomeProject 现在是会报错的
需要这样运行了 
npx @react-native-community/cli init AwesomeProject （但是我记得之前react-native-cli 是冲突的）

npx react-native@0.75.1 init AwesomeProject

## 预期结果

我很长时间没有进行RN开发了，现在我想知道哪种方式更好。

**Comment by sunnylqm** [comment]
沙盒环境主要是并不在国内运营，所预装的模块也并不是国内常用的模块，而国内需要用的模块也一概没有，所以你懂的，在国内既不好用，也不实用，任何时候都不推荐
cli是不再用-g方式全局安装，但仍然以npx的方式使用。npx react-native@latest init 或者 npx @react-native-community/cli init 目前都可以（有警告，但仍然可用。如果有报错，就截图具体的报错），目前没有区别，下一步如何演进，官方也还并没有定案
