### ISSUE TITLE
pod install报错

### ISSUE THREAD

**Issue by hottaiger** [reactnativecn/react-native-website#863]
请按以下格式提供问题的相关信息。

## 执行pod install之后
![Snipaste_2024-08-21_16-05-03](https://github.com/user-attachments/assets/c50bacd0-6184-4e8d-a345-5c6ae643b4b3)
### 初始化项目我用的是0.74.5
- npx react-native@0.74.5 init MyNewProjecta --version 0.74.5
![Snipaste_2024-08-21_16-08-19](https://github.com/user-attachments/assets/b580f28c-0307-4edf-ad2b-a5d3a7efeaf2)
 ### 然后按顺序执行
 - bundle install
 - bundle exec pod install，之后会第一张图那样的错误。
-------------------------
### 没用npx react-native@latest init AwesomeProject 创建项目是因为也会报错
![Snipaste_2024-08-21_16-18-52](https://github.com/user-attachments/assets/abc76d94-8914-4b2f-a050-21ef6d72de62)

**Comment by sunnylqm** [comment]
你这个报错我没啥头绪，卸载node和pod都再重装试试？

另外看下系统环境？
`npx react-native info`

**Comment by hottaiger** [comment]
> 你这个报错我没啥头绪，卸载node和pod都再重装试试？
sorry才看到回复。这是npx react-native info 执行的结果。
![WechatIMG89](https://github.com/user-attachments/assets/0ef34827-4620-4456-add9-beae8c81cf0b)
@sunnylqm

**Comment by hottaiger** [comment]
- 我用nvm重新安装了一个node版本，还是报同样的错误。
 ![image](https://github.com/user-attachments/assets/7f0766e3-02a8-432a-b8fd-4d87e2c60afe)
- 我看我安装在全局的包是这样的，需要把react-native也安装到全局么？
![image](https://github.com/user-attachments/assets/9104513a-8316-4794-9966-332ee2727c7c)

**Comment by sunnylqm** [comment]
不装全局

你的项目里有node_modules吗

**Comment by hottaiger** [comment]
> 不装全局
> 
> 你的项目里有node_modules吗

![image](https://github.com/user-attachments/assets/912a9b2b-971b-4f5a-84d1-c3e5fac4e8dd)
没有node_modules

**Comment by sunnylqm** [comment]
npm i

**Comment by hottaiger** [comment]
> npm i

解决了，感谢！👍🏻

**Comment by hottaiger** [comment]
> npm i

补充一下，npm i一直卡住，我用的yarn

**Comment by sunnylqm** [comment]
所以初始化的时候npm i没有完成，但是cli也没有任何相关的报错？

**Comment by hottaiger** [comment]
> 所以初始化的时候npm i没有完成，但是cli也没有任何相关的报错？

好像有提示说什么没安装成功，让运行时候再安装，我记着是个warning类型的提示。

**Comment by sunnylqm** [comment]
截图截完整
