### ISSUE TITLE
文档显示问题

### ISSUE THREAD

**Issue by ytt123** [reactnativecn/react-native-website#864]
## 问题的具体描述

   查看0.74版本的文档，在集成到现有原生应用章节中 ，RCTRootView 调用的是initWithBundleURL 方法但是我看下面描述的是initWithURL方法，如果有错的话，建议更新下。
![image](https://github.com/user-attachments/assets/634134c2-6b92-426d-95ce-8c18e77ce63c)

## 预期结果
      文档更新

**Comment by sunnylqm** [comment]
感谢提醒，已修正，并已向官方文档提交修改
