### ISSUE TITLE
你这个报错我没啥头绪，卸载node和pod都再重装试试？

### ISSUE THREAD

**Issue by hottaiger** [reactnativecn/react-native-website#865]
你这个报错我没啥头绪，卸载node和pod都再重装试试？

另外看下系统环境？
`npx react-native info`

_Originally posted by @sunnylqm in https://github.com/reactnativecn/react-native-website/issues/863#issuecomment-2302069701_

**Comment by hottaiger** [comment]
接上一个issue
https://github.com/reactnativecn/react-native-website/issues/863

**Comment by hottaiger** [comment]
npx react-native info 之后的结果
![WechatIMG89](https://github.com/user-attachments/assets/8e4b9405-6332-4c07-b520-e6dc07f6ddfc)

**Comment by hottaiger** [comment]
- 我用nvm重新安装了一个node版本，还是报同样的错误。
 ![image](https://github.com/user-attachments/assets/7f0766e3-02a8-432a-b8fd-4d87e2c60afe)
- 我看我安装在全局的包是这样的，需要把react-native也安装到全局么？
![image](https://github.com/user-attachments/assets/9104513a-8316-4794-9966-332ee2727c7c)

**Comment by sunnylqm** [comment]
为啥要新开个issue

**Comment by hottaiger** [comment]
> 为啥要新开个issue
我看之前那个close了。
