### ISSUE TITLE
0.75.2版本的react-native跑不起来

### ISSUE THREAD

**Issue by gaoxinxiao** [reactnativecn/react-native-website#867]
AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle-plugin:shared:compileKotlin'.
> Could not resolve all files for configuration ':gradle-plugin:shared:compileClasspath'.
   > Could not resolve com.google.code.gson:gson:2.8.9.
     Required by:
         project :gradle-plugin:shared
      > Could not resolve com.google.code.gson:gson:2.8.9.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. For more on this, please refer to https://docs.gradle.org/8.8/userguide/build_environment.html#sec:gradle_system_properties in the Gradle documentation.
                  > Remote host terminated the handshake
   > Could not resolve com.google.guava:guava:31.0.1-jre.
     Required by:
         project :gradle-plugin:shared
      > Could not resolve com.google.guava:guava:31.0.1-jre.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. For more on this, please refer to https://docs.gradle.org/8.8/userguide/build_environment.html#sec:gradle_system_properties in the Gradle documentation.
                  > Remote host terminated the handshake

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 17s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':gradle-plugin:shared:compileKotlin'.
> Could not resolve all files for configuration ':gradle-plugin:shared:compileClasspath'. > Could not resolve com.google.code.gson:gson:2.8.9. Required by: project :gradle-plugin:shared > Could not resolve com.google.code.gson:gson:2.8.9. > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'. > Could not GET 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'. > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. For more on this, please refer to https://docs.gradle.org/8.8/userguide/build_environment.html#sec:gradle_system_properties in the Gradle documentation. > Remote host terminated the handshake > Could not resolve com.google.guava:guava:31.0.1-jre. Required by: project :gradle-plugin:shared > Could not resolve com.google.guava:guava:31.0.1-jre. > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'. > Could not GET 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'. > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. For more on this, please refer to https://docs.gradle.org/8.8/userguide/build_environment.html#sec:gradle_system_properties in the Gradle documentation. > Remote host terminated the handshake * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 17s.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sunnylqm** [comment]
翻墙问题

**Comment by gaoxinxiao** [comment]
./gradlew generateAutolinkingPackageList
> Task :app:generateAutolinkingPackageList FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateAutolinkingPackageList'.
> RNGP - Autolinking: Could not find project.android.packageName in react-native config output! Could not autolink packages without this field.
目前又有这个错误了

**Comment by sunnylqm** [comment]
官方确认的bug，会在0.75.3中修复（尚未发布）

这里有一个临时解决办法
https://github.com/facebook/react-native/issues/46134#issuecomment-2323674786

创建react-native.config.js文件，里面添加packageName

```
module.exports = {
  project: {
    ios: {},
    android: {
      packageName: 'com.awesomeproject',  // 你的项目的安卓包名
    },
  },
};
```

**Comment by ry-krystal** [comment]
从你提供的错误信息中，可以看到 Gradle 构建失败，主要问题是无法从 Maven 仓库下载依赖的 gson 和 guava 库，并且报错信息提到 TLS 协议问题。

错误原因：
TLS 协议问题：你的项目试图从 https://repo.maven.apache.org/maven2/ 下载依赖，但由于 Gradle 的 TLS 协议配置，服务器与客户端的握手失败。Gradle 8.8 提到了一些与 TLS 协议有关的配置问题。
网络连接问题：如果你在一个代理网络或者防火墙下，这可能会导致网络请求失败。也有可能是 Maven 仓库在本地被阻止访问。

解决方案：
1. 强制使用 TLS 版本
你可以尝试在 gradle.properties 文件中强制设置 Gradle 使用特定的 TLS 版本，例如 TLSv1.2 或 TLSv1.3。
编辑项目的 android/gradle.properties 文件，添加以下配置：
systemProp.javax.net.ssl.trustStoreType=JKS
systemProp.javax.net.ssl.trustStorePassword=changeit
systemProp.javax.net.ssl.keyStoreType=PKCS12
systemProp.javax.net.ssl.trustStore=/path/to/your/java/cacerts
systemProp.javax.net.ssl.keyStorePassword=changeit
systemProp.javax.net.ssl.protocol=TLSv1.2
注意：请确保 trustStore 和 keyStore 的路径与密码是正确的。如果你不确定如何设置，可以省略这些选项，专注于 systemProp.javax.net.ssl.protocol=TLSv1.2 或者 TLSv1.3。

2. 升级或降级 Java 版本
如果你使用的是较新版本的 Java（如 Java 17），尝试降级到 Java 11，因为某些 Gradle 插件可能与较新的 Java 版本不兼容。
检查当前 Java 版本：
java -version
如果使用的是 Java 17，建议安装 Java 11 或 Java 8，并切换到该版本。
安装 Java 11：
brew install --cask adoptopenjdk/openjdk/adoptopenjdk11
切换到 Java 11：
export JAVA_HOME=$(/usr/libexec/java_home -v 11)
然后再次尝试构建项目。

3. 使用本地 Maven 镜像
如果你的网络阻止了对 https://repo.maven.apache.org 的访问，你可以尝试使用本地的 Maven 镜像仓库（例如中国用户可以使用阿里云的 Maven 镜像）。修改 android/build.gradle 文件，将 Maven 仓库源改为阿里云镜像或其他本地镜像。

在 android/build.gradle 中找到 repositories，并添加如下镜像源：
allprojects {
    repositories {
        maven {
            url "https://maven.aliyun.com/repository/public"
        }
        google()
        mavenCentral()
    }
}
你也可以使用其他可用的镜像源。

4. 清理 Gradle 缓存并重新同步
你的 Gradle 缓存可能有问题，导致依赖无法正确下载。可以尝试清理 Gradle 缓存并重新同步依赖：
cd android
./gradlew clean
./gradlew --refresh-dependencies
这将清除缓存并强制重新下载所有依赖项。

5. 增加 Gradle 超时时间
如果网络不稳定，你可以尝试增加 Gradle 的网络超时时间，防止由于网络波动导致下载依赖失败。在 android/build.gradle 文件中添加以下配置：
allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://repo.maven.apache.org/maven2/" }
    }
}

gradle.projectsEvaluated {
    tasks.withType(JavaCompile) {
        options.forkOptions.jvmArgs << "-Dhttp.socketTimeout=60000"
        options.forkOptions.jvmArgs << "-Dhttp.connectionTimeout=60000"
    }
}

6. 检查网络和代理设置
如果你在防火墙后或者通过代理上网，可能需要检查网络配置。确保代理设置正确，并且代理服务器允许访问 https://repo.maven.apache.org。
如果你使用代理，确保在 gradle.properties 中配置了正确的代理信息：
systemProp.http.proxyHost=your.proxy.host
systemProp.http.proxyPort=your.proxy.port
systemProp.https.proxyHost=your.proxy.host
systemProp.https.proxyPort=your.proxy.port
