### ISSUE TITLE
yarn android 运行报错

### ISSUE THREAD

**Issue by yinna1027** [reactnativecn/react-native-website#871]
![b3b2e39e2dace2d0428721a6a6583c5](https://github.com/user-attachments/assets/ebd46add-b776-4da0-b548-c19d3c4edaff)

yarn android 运行报错。已知解决不了

**Comment by sunnylqm** [comment]
任何时候都不要在路径里用中文
![QQ_1725526987301](https://github.com/user-attachments/assets/c1de1117-a13a-4487-af7d-a0a16a9e389a)
