### ISSUE TITLE
yarn android 运行报错

### ISSUE THREAD

**Issue by xiyousha** [reactnativecn/react-native-website#872]
![7d211bb86448e38a9a47f243c84de8e](https://github.com/user-attachments/assets/75f602ba-68f4-4105-8ae1-deed0b4809d2)
![image](https://github.com/user-attachments/assets/fcd4b74b-c5ee-4b9c-9474-e24948021f9c)

**Comment by sunnylqm** [comment]
需要提前配好jdk17

**Comment by xiyousha** [comment]
> 需要提前配好jdk17
![19930767032bc380e17886a551170a2](https://github.com/user-attachments/assets/3ff82bd6-ab5a-4124-a25a-c7c8eae24f95)
大佬，配置了jdk17会报这个是为啥呀

**Comment by sunnylqm** [comment]
置顶问题有提到 https://github.com/reactnativecn/react-native-website/issues/848
