### ISSUE TITLE
npx @react-native-community/clilatest init AwesomeProject 报错

### ISSUE THREAD

**Issue by mengyuntian0** [reactnativecn/react-native-website#873]
![image](https://github.com/user-attachments/assets/740225cf-9888-4f58-9ff3-98e40bdd0f3e)
我自建机场使用 v2rayN 访问，开启了自动配置系统代理，路由绕过大陆，使用浏览器也可以访问 https://registry.npmjs.org/ 网址，但是使用浏览器访问命令行中报错的 https://registry.npmjs.org/@react-native-community%2fclilatest 网址显示 {"error": "Not found"}

**Comment by sunnylqm** [comment]
你少了个 @ 符号啊

**Comment by mengyuntian0** [comment]
> 你少了个 @ 符号啊

![image](https://github.com/user-attachments/assets/d73f13a9-e514-4552-9f89-de72e55dcd02)
那看来是官网文档错了，我直接复制的。。。

**Comment by sunnylqm** [comment]
抱歉是文档里漏了，已补全
应该是
npx @react-native-community/cli@latest init AwesomeProject
