### ISSUE TITLE
使用react-navigation/bottom-tabs后的弹窗问题

### ISSUE THREAD

**Issue by TallNutAlt** [reactnativecn/react-native-website#874]
在使用react-navigation/bottom-tabs后，如何在不使用Modal的情况下遮挡住tab栏？
+
![8896e22c386c6311ba7ef69b1272c201](https://github.com/user-attachments/assets/312135a1-fdb8-453b-b636-c8720bbdb271)
如图使用View `  position: 'absolute',
            width: '100%',
            height: '100%',
            backgroundColor: 'red',`
            使用无法覆盖tab栏
            Modal可以但是Modal层级太高，不可避免的会出现一些问题

**Comment by sunnylqm** [comment]
[用 react-native-root-siblings](https://github.com/magicismight/react-native-root-siblings)

**Comment by TallNutAlt** [comment]
> [用 react-native-root-siblings](https://github.com/magicismight/react-native-root-siblings)

好的 感谢
