### ISSUE TITLE
yarn android报错

### ISSUE THREAD

**Issue by Peter-sss** [reactnativecn/react-native-website#878]
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/ae0515f0-8037-4c85-8715-1910272283d0">

**Comment by sunnylqm** [comment]
rn版本多少？这好像是某个特定rn版本（0.72？0.73？）的bug
把你所用的rn版本升到其最新小版本应该就可以了

**Comment by Peter-sss** [comment]
73版本需yarn start后才可以yarn android

**Comment by sunnylqm** [comment]
升到0.73.9即可直接使用yarn android
