### ISSUE TITLE
react Native 运行的Android时候报错了

### ISSUE THREAD

**Issue by lidashi0317** [reactnativecn/react-native-website#879]
请按以下格式提供问题的相关信息。

## 问题的具体描述

 Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNPermissions' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","SourceCode","Timing","AppState","BlobModule","WebSocketModule","DevSettings","DevToolsSettingsManager","Networking","Appearance","DevLoadingView","HeadlessJsTaskSupport","DeviceInfo","UIManager","ImageLoader","SoundManager","IntentAndroid","DeviceEventManager","NativeAnimatedModule","I18nManager","RNCWebView"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","LinkingManager","RNCSafeAreaContext","NativeReactNativeFeatureFlagsCxx","RNSModule","RNPermissions"]}, js engine: hermes

## 请描述完整的环境/版本信息

System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Memory: 700.76 MB / 7.85 GB
Binaries:
  Node:
    version: 20.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.8.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-241.18034.62.2412.12266719
  Visual Studio: Not Found
Languages:
  Java:
    version: 17.0.12
    path: /c/Program Files/Common Files/Oracle/Java/javapath/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by sunnylqm** [comment]
贴下package.json

**Comment by lidashi0317** [comment]
> 贴下package.json

 "dependencies": {
        "@expo/vector-icons": "^14.0.0",
        "@react-native-async-storage/async-storage": "1.23.1",
        "@react-native-community/geolocation": "^3.2.1",
        "@react-navigation/drawer": "^6.6.6",
        "@react-navigation/native": "^6.0.2",
        "@react-navigation/native-stack": "^6.9.17",
        "@rneui/base": "4.0.0-rc.8",
        "@rneui/layout": "0.0.0-alpha.6",
        "@rneui/themed": "4.0.0-rc.8",
        "@tanstack/react-query": "^5.54.1",
        "axios": "^1.7.7",
        "babel-plugin-inline-import": "^3.0.0",
        "buffer": "^6.0.3",
        "drizzle-orm": "^0.33.0",
        "drizzle-zod": "^0.5.1",
        "expo": "~51.0.8",
        "expo-asset": "~10.0.6",
        "expo-build-properties": "~0.12.1",
        "expo-camera": "~15.0.9",
        "expo-constants": "~16.0.1",
        "expo-file-system": "~17.0.1",
        "expo-font": "~12.0.5",
        "expo-linking": "~6.3.1",
        "expo-router": "~3.5.14",
        "expo-screen-orientation": "~7.0.5",
        "expo-secure-store": "~13.0.2",
        "expo-splash-screen": "~0.27.4",
        "expo-sqlite": "~14.0.6",
        "expo-status-bar": "~1.12.1",
        "expo-system-ui": "~3.0.4",
        "expo-web-browser": "~13.0.3",
        "jszip": "^3.10.1",
        "lodash-es": "^4.17.21",
        "react": "18.2.0",
        "react-native": "0.74.1",
        "react-native-ble-plx": "^3.1.2",
        "react-native-config": "^1.5.1",
        "react-native-device-info": "^11.1.0",
        "react-native-gesture-handler": "~2.16.1",
        "react-native-get-random-values": "^1.11.0",
        "react-native-permissions": "^4.1.5",
        "react-native-reanimated": "~3.10.1",
        "react-native-safe-area-context": "4.10.1",
        "react-native-screens": "3.31.1",
        "react-native-web": "~0.19.10",
        "react-native-webview": "13.10.3",
        "react-native-wifi-reborn": "^4.12.1",
        "react-native-zip-archive": "^7.0.1",
        "reflect-metadata": "^0.2.2",
        "typeorm": "^0.3.20",
        "uuid": "^10.0.0",
        "zod": "^3.23.8",
        "zustand": "^4.5.2"
    },
    "devDependencies": {
        "@babel/core": "^7.24.0",
        "@babel/runtime": "^7.24.4",
        "@tsconfig/react-native": "^3.0.5",
        "@types/jest": "^29.5.12",
        "@types/lodash-es": "^4.17.6",
        "@types/react": "~18.2.45",
        "@types/react-test-renderer": "^18.0.7",
        "babel-plugin-transform-typescript-metadata": "^0.3.2",
        "cross-env": "^7.0.3",
        "dotenv": "^16.4.5",
        "drizzle-kit": "^0.24.2",
        "eslint-plugin-react": "^7.35.0",
        "jest": "^29.2.1",
        "jest-expo": "~50.0.4",
        "react-test-renderer": "18.2.0",
        "typescript": "^5.3.0"
    },
    "overrides": {
        "react-refresh": "~0.14.0"
    },
    "resolutions": {
        "react-refresh": "~0.14.0"
    },
    "private": true

**Comment by sunnylqm** [comment]
是以expo形式运行的，还是expo prebuild

**Comment by lidashi0317** [comment]
expo  运行的

**Comment by sunnylqm** [comment]
expo是一个封装好的沙盒环境，只能用它内置的已有的原生模块，不能自由安装使用第三方的（除非弹出沙盒环境，使用prebuild）
