### ISSUE TITLE
求助，初始化项目运行报错undefined is not an object (evaluating 'warnings.length')

### ISSUE THREAD

**Issue by VickWood** [reactnativecn/react-native-website#88]
这是配置的环境
![image](https://user-images.githubusercontent.com/37318197/77412340-b7220b00-6df8-11ea-8631-b50eb79fe4dc.png)

初始化项目的react native 版本是0.57.8
系统是win10 64

报错截图
![image](https://user-images.githubusercontent.com/37318197/77412431-d6209d00-6df8-11ea-8d1f-1139707d2452.png)
![image](https://user-images.githubusercontent.com/37318197/77412502-edf82100-6df8-11ea-968a-6d5b3e137ba3.png)

根据错误提示找到报错的位置
![image](https://user-images.githubusercontent.com/37318197/77412660-20098300-6df9-11ea-98d5-91b30ee04513.png)

不是很明白为什么报错了，项目是初始化的，没加其他的代码进去，之前在另一台电脑用react native开发也没出现过这个问题，现在新配的环境运行就报错，奇怪的是我初始化最新版的react native 0.61.5又没有报这个错误，想问下有没有人遇到过这个问题。

**Comment by zjy1017** [comment]
同问，请问你这边问题解决了吗？我初始化一个新项目也报这个错误了

**Comment by lvwenbo1111** [comment]
解决了吗,同求方法,上上周还是好的,上周开始就报这个错了,而且只有release模式是这样的,debug模式就是好的

**Comment by lDDii** [comment]
> 解决了吗,同求方法,上上周还是好的,上周开始就报这个错了,而且只有release模式是这样的,debug模式就是好的
请问解决了？？

**Comment by lDDii** [comment]
请问解决了？？升级之后就这样了，YellowBoxListRow这个文件我也没看到有...
