### ISSUE TITLE
0.61版本启动报错

### ISSUE THREAD

**Issue by ZiBo1233** [reactnativecn/react-native-website#89]
报错内容如下：
Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!
Port 8081 already in use, packager is either not running or not running correctly
Command /bin/sh failed with exit code 2

是0.61版本的项目，请问有什么好的解决办法嘛？

**Comment by sunnylqm** [comment]
8081端口被mcaffe占用了
总之这俩中（mcaffe和rn packager）有一个得改端口

**Comment by ZiBo1233** [comment]
是的，后来我发现还真的是被占了。我电脑上装了mcaffe
