### ISSUE TITLE
run-android 后  java.net.ConnectException: Connection refused:

### ISSUE THREAD

**Issue by WhutZml** [reactnativecn/react-native-website#899]
请按以下格式提供问题的相关信息。

## 问题的具体描述

![image](https://github.com/user-attachments/assets/ec1cdbcf-96f9-4e8c-9797-b6ac44df832e)

![image](https://github.com/user-attachments/assets/fab403c4-234d-4abc-8567-6ccefd477ca6)

## 预期结果

- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

**Comment by sunnylqm** [comment]
connection相关报错就是标准的代理问题
