### ISSUE TITLE
 Could not get resource 

### ISSUE THREAD

**Issue by WhutZml** [reactnativecn/react-native-website#900]
请按以下格式提供问题的相关信息。

## 问题的具体描述

![image](https://github.com/user-attachments/assets/5b67de40-e6a8-4f6b-abb0-fa7b926c0fa1)

![image](https://github.com/user-attachments/assets/1fb3929a-93e5-4159-8811-6fa7bb45c245)

挂VPN也不行，按网上方法把maven仓库改成国内镜像源的话，也会报Could not get resource 的错误
<img width="885" alt="5454e383aa9da469535b67616a22315" src="https://github.com/user-attachments/assets/f7ad29ce-575a-4710-950d-d464b10a8359">

**Comment by WhutZml** [comment]
哦对了，试了梯子也不行

**Comment by WhutZml** [comment]
哦对了，试了梯子也不行

**Comment by sunnylqm** [comment]
你的梯子设置有问题，具体什么问题我不清楚

**Comment by WhutZml** [comment]
> 你的梯子设置有问题，具体什么问题我不清楚

谢谢解决了，我是代理设置错了改回来就好了
