### ISSUE TITLE
  java.io.UncheckedIOException : Could not move temporary workspace

### ISSUE THREAD

**Issue by WhutZml** [reactnativecn/react-native-website#907]
请按以下格式提供问题的相关信息。

## 问题的具体描述
运行时出现这样的问题

![image](https://github.com/user-attachments/assets/d7dae1d5-9181-43ab-a9d5-59305294c97a)

## 请描述完整的环境/版本信息

这是我的gradle
![image](https://github.com/user-attachments/assets/5fc569eb-b167-4c1b-a3c1-ab4f8c854292)

## 预期结果

- 请描述你觉得代码正常运行的情况应该是什么样子。
- 如果问题比较模糊，没有具体方案，那么请具体描述你想要实现什么功能。

**Comment by yulittlemoon** [comment]
我也遇到这个问题了

**Comment by zhangqingsong1017** [comment]
请问这个怎么解决的

**Comment by sunnylqm** [comment]
gradle升级到8.11
https://github.com/gradle/gradle/issues/28475#issuecomment-2373630093
