### ISSUE TITLE
我用expo构建了一个项目，但当我想要使用@react-native-community/async-storage模块时报错了

### ISSUE THREAD

**Issue by ryen-intal** [reactnativecn/react-native-website#91]
expo版本为3.15.5
react-native 0.61.4
@react-native-community/async-storage 1.8.1
react 16.9

我查的资料说expo是封闭的，如果要使用expo之外的第三方库，需要执行expo eject命令....我想请教各位的是，执行这个命令对我的项目有什么影响？除了这个还有其他可行方法吗？感谢了！

报错截图:
![image](https://user-images.githubusercontent.com/62331840/77663962-9dc7bd00-6fb8-11ea-8b08-ea6d281be596.png)
ll

**Comment by sunnylqm** [comment]
expo仍然可以用rn自带的asyncstorage，从功能到语法上和社区版都完全一致
https://docs.expo.io/versions/latest/react-native/asyncstorage/

eject弹出的话就脱离沙盒环境，等同于一个用cli创建的rn项目了（所以你得先配好环境），然后也不能再使用expo的app了

**Comment by xdcheng** [comment]
expo 的 [Bare Workflow](https://docs.expo.io/versions/v36.0.0/bare/unimodules-full-list/) 可以用大部分 expo 模块，也可以自己集成第三方，可以尝试一下。

**Comment by ryen-intal** [comment]
@sunnylqm expo自带的react-native0.61.4已经移除了AsyncStorage:
![image](https://user-images.githubusercontent.com/62331840/77738932-a87f6200-704b-11ea-8313-6e4cfeeaba83.png)

本地存储代码：
![image](https://user-images.githubusercontent.com/62331840/77739001-c5b43080-704b-11ea-88dc-b79209da228a.png)

所以现在真是进退两难，如果我要用@react-native-community/async-storage我就得退出沙盒(我用win10开发，希望能能用苹果手机扫expo生成的二维码进行ios端的调试，退出沙盒就就看不到ios端的效果了)

另外如果我退出沙盒，expo的库(如图片、字体库)我还能接着用吗？

**Comment by sunnylqm** [comment]
https://docs.expo.io/versions/v36.0.0/sdk/securestore/

**Comment by ryen-intal** [comment]
@sunnylqm 感谢
