### ISSUE TITLE
react-navigation 5.x 跳转子路由时如何隐藏底下的tabBar

### ISSUE THREAD

**Issue by GWCodeN** [reactnativecn/react-native-website#92]
![69C85840-A632-4191-AAF8-3DB3680E94D0](https://user-images.githubusercontent.com/25916259/77718911-077ab200-701f-11ea-8f87-2a996a42a432.png)

**Comment by sunnylqm** [comment]
应该用stack包含tab，而不是tab包含stack

**Comment by GWCodeN** [comment]
> 应该用stack包含tab，而不是tab包含stack

这样子 会造成 tab下的页面 用的同一个header  给每个页面自定header 造成麻烦

**Comment by sunnylqm** [comment]
@guoyw tab这个页面不用header，自己在各个tab中绘制，其实更方便
否则反过来问题更多，tab包含stack开销更大，隐藏tab麻烦且视觉上会跳动，如果tab还要跳转其他stack的页面也更麻烦了

**Comment by GWCodeN** [comment]
> @guoyw tab这个页面不用header，自己在各个tab中绘制，其实更方便
> 否则反过来问题更多，tab包含stack开销更大，隐藏tab麻烦且视觉上会跳动，如果tab还要跳转其他stack的页面也更麻烦了

明白了谢谢

**Comment by jiyunkeji** [comment]
太棒啦，看到这个问题，我又重新看了一下文档，理解多了，谢谢！
