### ISSUE TITLE
运行ios模拟器XCode报错找不到YogaKit.modulemap,

### ISSUE THREAD

**Issue by aerwacc** [reactnativecn/react-native-website#93]
Showing Recent Issues
Module map file '/Users/dj/Library/Developer/Xcode/DerivedData/AwesomeProject-dpvrawzwepqesyboeiienbjfwzxb/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found

但是我根据路径去找是有看到YogaKit.modulemap，这个问题是出在哪呢

**Comment by dddsswu** [comment]
同问题，楼主解决了嘛

**Comment by gongsy945** [comment]
同问题，楼主解决了嘛

**Comment by zurex** [comment]
Use .xcworkspace instead

**Comment by zurex** [comment]
> Use .xcworkspace instead

@gongsy945 @dddsswu  check this

**Comment by timsky625** [comment]
这问题有没有人解决的，我怎么新建工程。  100%确定打开的是 .xcworkspace 。  一样的
Module map file '/Users/dj/Library/Developer/Xcode/DerivedData/AwesomeProject-dpvrawzwepqesyboeiienbjfwzxb/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found
无解来。 一创建工程用命令行就可以在模拟器上运行。
有没有处理的方法。
无解

**Comment by EliteCRM02** [comment]
> Use .xcworkspace instead

laotie，it's ok！
