### ISSUE TITLE
react native 版本0.62集成react-native-update后程序闪退

### ISSUE THREAD

**Issue by qurbanliwayidin** [reactnativecn/react-native-website#96]
react native 版本0.62集成react-native-update之后程序闪退，没有错误信息，不知道是什么原因。

**Comment by sunnylqm** [comment]
请给出adb logcat日志信息

**Comment by qurbanliwayidin** [comment]
我尝试--variant=release,总是报错:Command failed: gradlew.bat app:installRelease -PreactNativeDevServerPort=8081
Resource and asset merger: Cannot create directory E:\projects\chis_client\node_modules\react-native-update\android\build\intermediates\packaged_res\release\values

**Comment by qurbanliwayidin** [comment]
当前热更新版本的Hash也获取不到。

**Comment by sunnylqm** [comment]
没有报错的具体信息（报错的具体截图，日志等等）我无法进一步分析

**Comment by qurbanliwayidin** [comment]
rn版本降到0.61.2就没问题。谢谢你。

**Comment by sunnylqm** [comment]
这并没有解决问题，希望有空能汇报具体错误信息
