### ISSUE TITLE
有没有人用0.59以前的版本上架过google play？

### ISSUE THREAD

**Issue by bolan9999** [reactnativecn/react-native-website#98]
官方是0.59才开始支持安卓64位，之前的版本能否有一些方法上线呢？ 升级RN版本太痛苦了。

**Comment by sunnylqm** [comment]
0.58就支持64位了，主要是需要升级jsc，之前的版本也可以升级  https://github.com/react-native-community/jsc-android-buildscripts
升级rn有问题也可以找我付费咨询

**Comment by bolan9999** [comment]
没有，一个别人的项目，用的0.55的，太多依赖库了，升级太麻烦了。算了
