### ISSUE TITLE
使用fetch访问http网页报TypeError: Network request failed错误

### ISSUE THREAD

**Issue by ACDC5** [reactnativecn/react-native-website#99]
我使用expo构建项目，
android虚拟机版本10，
文档中提到了
**默认情况下，iOS 会阻止所有 http 的请求，以督促开发者使用 https。如果你仍然需要使用 http 协议，那么首先需要添加一个 App Transport Security 的例外，详细可参考这篇帖子。

从 Android9 开始，也会默认阻止 http 请求，请参考相关配置**
我根据官方提供的文档[https://blog.csdn.net/qq_40347548/article/details/86766932](url)想对android进行配置，但在expo的目录下没发现相关的文件夹(如下图)
![image](https://user-images.githubusercontent.com/43377515/78094825-1a6af900-7408-11ea-8e9e-ab97b6d4ed59.png)请问我该如何配置android端。

这是我的代码:
![image](https://user-images.githubusercontent.com/43377515/78095020-8baaac00-7408-11ea-89b5-61d491de3f78.png)

报错信息：
![image](https://user-images.githubusercontent.com/43377515/78095097-b137b580-7408-11ea-86b5-46554e159641.png)

**Comment by sunnylqm** [comment]
expo的麻烦就在于你不能更改原生配置，只能等官方发布新版本
看起来官方是在sdk33中修复了 https://github.com/expo/expo/commit/fdc6a3a2447284b8946dac9e3def6a2412ee3bf4

**Comment by ACDC5** [comment]
鱼和熊掌不可兼得？看来expo还不是很完美,还是用react-native init吧

**Comment by ACDC5** [comment]
记录一下，新建一个reactNative项目后将参数格式改为:
![image](https://user-images.githubusercontent.com/43377515/78342003-2eab2380-75cb-11ea-8033-9d54d2f4b4c3.png)
即key=value的形式后请求成功。没有对android目录内容进行任何配置。

网上解决这个问题的其他方向有:
1、虚拟机的dns要和本机的dns保持一致；
2、需要配置相应平台的网络设置，如ios对http的限制，android也存在类似的问题

**Comment by sunnylqm** [comment]
1. content-type任何形式，与http协议、系统本身对http协议的限制没有任何关系，不可能解决其相关的问题。好比你打电话的音量大小，不可能影响你的话费多少。
2. content-type具体用什么格式，由服务器决定，它要json格式要xml格式要kv格式，你都得听它的。

**Comment by ACDC5** [comment]
我认为问题出在传参上，Content-Type: application/x-www-form-urlencoded这种格式要求参数以key=value的方式传入；我一开始用的FormData也是k-v格式，正常来说我这样传参是没问题的，但还是出错了。我找到的解释是：FormData.append方法只能在Web Workers 中使用:
![image](https://user-images.githubusercontent.com/43377515/78421154-1b11c280-7688-11ea-947f-2e10c4811ac4.png)
就是因为这个出现了TypeError: Network request failed错误。

**Comment by sunnylqm** [comment]
你的理解还是错误的，
1、form data对应的是multipart/form-data，而不是application/x-www-form-urlencoded
2、form data在web workers中可用，当然不是“只能”。如果是这样，谁还用form data？

**Comment by ACDC5** [comment]
明白了 谢谢
